### ISSUE TITLE
Android 8.1运行报错

### ISSUE THREAD

**Issue by Shyky** [Tencent/tinker#1013]
在8.1系统上运行Tinker直接crash：
service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE internalType=0 internalPriority=0 internalGroupPriority=0 internalFlag=0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
 E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE internalType=0 internalPriority=0 internalGroupPriority=0 internalFlag=0)
 E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE internalType=0 internalPriority=0 internalGroupPriority=0 internalFlag=0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)

**Comment by tomystang** [comment]
虽然问题有些久远了，不过还有问题的话请提供一下tinker版本，或者直接升级到1.9.9版本，这个问题应该就解决了。
