### ISSUE TITLE
华为Mate20热更新应用失败报错

### ISSUE THREAD

**Issue by github-of-daibing** [Tencent/tinker#1029]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：华为mate20

手机系统版本：Android 9.0

tinker版本：1.9.6

gradle版本：4.6

是否使用热更新SDK： Bugly SDK（Tinker-support 1.1.2）

堆栈/日志：
W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
E/Tinker.ResourceLoader: resource hook check failed.
        
java.lang.NoSuchFieldException: Field mStringBlocks not found in class android.content.res.AssetManager
at com.tencent.tinker.loader.shareutil.ShareReflectUtil.findField(ShareReflectUtil.java:55)
at com.tencent.tinker.loader.TinkerResourcePatcher.isResourceCanPatch(TinkerResourcePatcher.java:101)
at com.tencent.tinker.loader.TinkerResourceLoader.checkComplete(TinkerResourceLoader.java:122)
at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:216)
at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
at java.lang.reflect.Method.invoke(Native Method)
at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:163)
at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
at android.app.Application.attach(Application.java:224)
at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
at android.app.LoadedApk.makeApplication(LoadedApk.java:1156)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6529)
at android.app.ActivityThread.access$1900(ActivityThread.java:267)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
at android.os.Handler.dispatchMessage(Handler.java:109)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:7470)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
        
W/Tinker.TinkerLoader: tryLoadPatchFiles:resource check fail
D/Tinker.DefaultAppLike: onBaseContextAttached:
I/Tinker.TinkerPatchListener: application maxMemory:384
W/Tinker.Tinker: tinker patch directory: /data/user/0/.../tinker
I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.6
I/Tinker.TinkerLoadResult: parseTink main process:true, systemOTA:false, fingerPrint:HUAWEI/HMA-AL00/HWHMA:9/HUAWEIHMA-AL00/195C00R1:user/release-keys, oatDir:odex, useInterpretMode:false
I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:02d34b7f13fe64fece8e88d76608a7c3, current:02d34b7f13fe64fece8e88d76608a7c3
I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-23
I/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: patch load resource exception: java.lang.NoSuchFieldException: Field mStringBlocks not found in class android.content.res.AssetManager
I/Tinker.DefaultLoadReporter: res exception disable tinker forever with sp
E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
        
E/Tinker.DefaultLoadReporter: tinker load exception  java.lang.NoSuchFieldException: Field mStringBlocks not found in class android.content.res.AssetManager
at com.tencent.tinker.loader.shareutil.ShareReflectUtil.findField(ShareReflectUtil.java:55)
at com.tencent.tinker.loader.TinkerResourcePatcher.isResourceCanPatch(TinkerResourcePatcher.java:101)
at com.tencent.tinker.loader.TinkerResourceLoader.checkComplete(TinkerResourceLoader.java:122)
at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:216)
at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
at java.lang.reflect.Method.invoke(Native Method)
at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:163)
at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
at android.app.Application.attach(Application.java:224)
at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
at android.app.LoadedApk.makeApplication(LoadedApk.java:1156)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6529)
at android.app.ActivityThread.access$1900(ActivityThread.java:267)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
at android.os.Handler.dispatchMessage(Handler.java:109)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:7470)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
        
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/info.lock
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/patch-02d34b7f.apk
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/dex/changed_classes.dex.jar
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/dex/oat/arm/changed_classes.dex.vdex
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/dex/oat/arm/changed_classes.dex.odex
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/dex/oat/arm/tinker_classN.vdex
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/dex/oat/arm/tinker_classN.odex
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/dex/oat/arm
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/dex/oat
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/dex/tinker_classN.apk
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/dex
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/odex
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/res/resources.apk
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f/res
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-02d34b7f
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch.info
I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker
I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/.../tinker, code: -23, cost: 91ms
W/Tinker.Tinker: tinker load fail!

**Comment by sendoh93** [comment]
@github-of-daibing   你好请问后面如何解决的呢

**Comment by wangpengfei1992** [comment]
遇到了同样的问题，请问解决了吗？
