### ISSUE TITLE
android9.0手机上报错

### ISSUE THREAD

**Issue by liusar** [Tencent/tinker#1070]
tinker load exception  java.lang.NoSuchMethodException: ensureStringBlocks []
                                                                   at java.lang.Class.getMethod(Class.java:2068)
                                                                   at java.lang.Class.getDeclaredMethod(Class.java:2047)
                                                                   at com.tencent.tinker.loader.TinkerResourcePatcher.isResourceCanPatch(SourceFile:111)
                                                                   at com.tencent.tinker.loader.TinkerResourceLoader.checkComplete(SourceFile:122)
                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(SourceFile:215)
                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoad(SourceFile:58)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(SourceFile:163)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:132)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:148)
                                                                   at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(SourceFile:57)
                                                                   at android.app.Application.attach(Application.java:240)
                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:1125)
                                                                   at android.app.LoadedApk.makeApplication(LoadedApk.java:1087)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6010)
                                                                   at android.app.ActivityThread.access$1300(ActivityThread.java:207)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                   at android.os.Looper.loop(Looper.java:193)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6863)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

![image](https://user-images.githubusercontent.com/14871778/56133052-1f982380-5fbe-11e9-8cef-6b51e3fc128a.png)

**Comment by yanweimin7** [comment]
没回应？？

**Comment by xu-duqing** [comment]
`ensureStringBlocks` 貌似是被黑名单了, https://github.com/tiann/FreeReflection/issues/4

**Comment by tomystang** [comment]
是的，ensureStringBlocks是被黑名单了，但是Android 5.0之后其实也不需要调用了。可能你用的tinker版本比较旧，试试升级到1.9.9版本，或者等这周五的1.9.13版本也行。

**Comment by zysidea** [comment]
1.9.13在锤子T1 4.4 上 也提示应用成功，但是补丁不起作用 @tomystang

**Comment by liangchaojie** [comment]
@tomystang 使用的是1.9.9  在8.0机器上是可以看到补丁效果的但是9.0手机上不可以，请问咱们tinker支持9.0么

**Comment by checkming** [comment]
2019-09-16 16:55:04.130 15431-15431/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
2019-09-16 16:55:04.156 1486-1541/? I/ActivityManager: Start proc 15464:gt.com.zf:patch/u0a215 for service gt.com.zf/com.tencent.tinker.lib.service.TinkerPatchService caller=gt.com.zf
2019-09-16 16:55:04.235 15464-15464/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
2019-09-16 16:55:04.236 15464-15464/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-09-16 16:55:04.238 15464-15464/? W/Tinker.Tinker: tinker patch directory: /data/user/0/gt.com.zf/tinker
2019-09-16 16:55:04.239 15464-15464/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
2019-09-16 16:55:04.239 15464-15464/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:gt.com.zf:patch, main process:false, systemOTA:false, fingerPrint:Xiaomi/sirius/sirius:9/PKQ1.181121.001/V10.3.1.0.PEBCNXM:user/release-keys, oatDir:null, useInterpretMode:false
2019-09-16 16:55:04.239 15464-15464/? W/Tinker.TinkerLoadResult: tinker is disable, just return
2019-09-16 16:55:04.239 15464-15464/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/gt.com.zf/tinker, code: -1, cost: 5ms
2019-09-16 16:55:04.239 15464-15464/? W/Tinker.Tinker: tinker load fail!
2019-09-16 16:55:04.242 15464-15464/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-09-16 16:55:04.242 15464-15464/? D/Tinker.DefaultAppLike: onCreate
2019-09-16 16:55:04.245 15464-15482/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
2019-09-16 16:55:04.247 15464-15482/? W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/tinker_patch.apk to /data/user/0/gt.com.zf/tinker_temp/temp.apk
2019-09-16 16:55:04.252 15464-15482/? I/Tinker.TinkerPatchService: try to increase patch process priority
2019-09-16 16:55:04.254 1486-1539/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{gt.com.zf/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
2019-09-16 16:55:04.257 1486-1539/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{gt.com.zf/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
2019-09-16 16:55:04.285 15464-15482/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:6b5f9b57d446acb9db988a76c31fc531
2019-09-16 16:55:04.287 15464-15482/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/gt.com.zf/tinker/patch.info (No such file or directory)
2019-09-16 16:55:04.287 15464-15482/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/gt.com.zf/tinker/patch.info (No such file or directory)
2019-09-16 16:55:04.287 15464-15482/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/gt.com.zf/tinker/patch-6b5f9b57
2019-09-16 16:55:04.288 15464-15482/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/tinker_patch.apk size: 5207, dest file: /data/user/0/gt.com.zf/tinker/patch-6b5f9b57/patch-6b5f9b57.apk size:5207
2019-09-16 16:55:04.288 15464-15482/? W/Tinker.DexDiffPatchInternal: patch recover, dex is not contained
2019-09-16 16:55:04.288 15464-15482/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
2019-09-16 16:55:04.289 15464-15482/? I/Tinker.ResDiffPatchInternal: res dir: /data/user/0/gt.com.zf/tinker/patch-6b5f9b57/res/, meta: resArscMd5:788b442b2d377c2fbc5b8b794baae27d
    arscBaseCrc:4218116511
    pattern:assets/.*
    pattern:resources\.arsc
    pattern:res/.*
    addedSet:assets/only_use_to_test_tinker_resource.txt
    modifiedSet:res/layout/activity_index.xml
2019-09-16 16:55:04.290 15464-15482/? I/Tinker.ResDiffPatchInternal: no large modify or store resources, just return
2019-09-16 16:55:04.563 15464-15482/? I/Tinker.ResDiffPatchInternal: final new resource file:/data/user/0/gt.com.zf/tinker/patch-6b5f9b57/res/resources.apk, entry count:938, size:3390269
2019-09-16 16:55:04.563 15464-15482/? I/Tinker.ResDiffPatchInternal: recover resource result:true, cost:275
2019-09-16 16:55:04.563 15464-15482/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/gt.com.zf/tinker/patch.info , oldVer:, newVer:6b5f9b57d446acb9db988a76c31fc531, fingerprint:Xiaomi/sirius/sirius:9/PKQ1.181121.001/V10.3.1.0.PEBCNXM:user/release-keys, oatDir:odex
2019-09-16 16:55:04.564 15464-15482/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
2019-09-16 16:55:04.564 15464-15482/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/emulated/0/tinker_patch.apk, success: true, cost: 312
2019-09-16 16:55:04.565 15464-15482/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/gt.com.zf/tinker_temp/temp.apk
2019-09-16 16:55:04.595 15431-15497/? I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
    PatchResult: 
    isSuccess:true
    rawPatchFilePath:/storage/emulated/0/tinker_patch.apk
    costTime:312
    patchVersion:6b5f9b57d446acb9db988a76c31fc531
     
2019-09-16 16:55:04.600 15431-15497/? W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /storage/emulated/0/tinker_patch.apk
2019-09-16 16:55:04.600 15431-15497/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/tinker_patch.apk
2019-09-16 16:55:11.929 15506-15506/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2019-09-16 16:55:11.932 15506-15506/? E/Tinker.ResourceLoader: resource hook check failed.
    java.lang.NoSuchMethodException: ensureStringBlocks []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at com.tencent.tinker.loader.TinkerResourcePatcher.isResourceCanPatch(TinkerResourcePatcher.java:18)
        at com.tencent.tinker.loader.TinkerResourceLoader.checkComplete(TinkerResourceLoader.java:13)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:62)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:3)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:6)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:3)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:3)
        at android.app.Application.attach(Application.java:215)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6815)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

tinker版本为1.9.1 在Android9.0的小米9上也是日志上显示修复成功但提示 NoSuchMethodException: ensureStringBlocks [] 错误

**Comment by qianshengta** [comment]
我的也是  小米8 SE  Android9.0  提示修复成功的弹窗都出来了  但是就是没起作用

**Comment by checkming** [comment]
> 我的也是 小米8 SE Android9.0 提示修复成功的弹窗都出来了 但是就是没起作用
或许你可以从 #1114 里找到解决方法
