### ISSUE TITLE
com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null

### ISSUE THREAD

**Issue by BryceCui** [Tencent/tinker#1073]
this is my log
```
2019-04-17 11:21:12.861 17566-17566/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hmbl.hm:pushcore, PID: 17566
    java.lang.RuntimeException: Unable to create application com.hmbl.hm.OtherApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6637)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:184)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:180)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619) 
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
     Caused by: com.getkeepsafe.relinker.MissingLibraryException: librealm-jni.so
        at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:123)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
        at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
        at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
        at io.realm.Realm.initializeRealm(Realm.java:322)
        at io.realm.Realm.init(Realm.java:265)
        at com.hmbl.hm.common.HMApplication.onCreate(HMApplication.java:163)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:180) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619) 
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
```
Tinker is used in the project and inherits DefaultApplicationLike. It is used in the oncreate method as follows.
```
  Realm.init(mContext);
  RealmConfiguration config = new 
  RealmConfiguration.Builder().name("HeMa.realm").schemaVersion(0).build();
  Realm.setDefaultConfiguration(config);
```
I want to know what is the cause of this problem，Please inform thank you！

**Comment by scuzoutao** [comment]
the same issue

**Comment by Damocs0921** [comment]
hi, how did you solve this problem? we have the same issue
