### ISSUE TITLE
App debug 运行会Crash，关闭了TinkerEnable 也一样。 Release正常，补丁也可以正常生效

### ISSUE THREAD

**Issue by elviswong-cn** [Tencent/tinker#1076]
```
异常类型：app启动闪退

手机型号：如:Nexus 5(如是编译异常，则可以不填)

手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)

tinker版本：如:1.9.9

gradle版本：3.1.2

是否使用热更新SDK： Tinker

系统：Windows

堆栈/日志：
2019-04-22 18:26:02.125 9029-9029/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: and.utoo.haomen, PID: 9029
    java.lang.RuntimeException: Unable to instantiate application and.utoo.haomen.tinkerApp: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1170)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6607)
        at android.app.ActivityThread.access$2000(ActivityThread.java:268)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:115)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:121)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:152)
        at android.app.Application.attach(Application.java:224)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1162)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6607) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:268) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
     Caused by: java.lang.ClassNotFoundException: and.utoo.haomen.App
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:121) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:152) 
        at android.app.Application.attach(Application.java:224) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1162) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6607) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:268) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "and.utoo.haomen.App" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/and.utoo.haomen-N0fZLL44rjc89S_OaZ3h0g==/base.apk"],nativeLibraryDirectories=[/data/app/and.utoo.haomen-N0fZLL44rjc89S_OaZ3h0g==/lib/arm, /system/fake-libs, /data/app/and.utoo.haomen-N0fZLL44rjc89S_OaZ3h0g==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:121) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:152) 
        at android.app.Application.attach(Application.java:224) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1162) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6607) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:268) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1995) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
```

**Comment by elviswong-cn** [comment]
debug 环境的 混淆关掉就可以了。 但是还是不知道原因是什么

**Comment by tomystang** [comment]
and.utoo.haomen.App
可以看下这个类在混淆的时候有没有被移除或者改名。

**Comment by qq837890739** [comment]
请问解决了吗？我也是开了混淆就不可以，关掉混淆就可以了
