### ISSUE TITLE
Android9.0补丁应用失败，之后App一直Crash闪退

### ISSUE THREAD

**Issue by 110117ab** [Tencent/tinker#1079]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：XiaoMI 

手机系统版本：Android 9.0

tinker版本：如:1.9.9

gradle版本：如:2.10

是否使用热更新SDK： 是

系统：Window

堆栈/日志：
1. 2019-04-23 14:44:00.900 21612-21612/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
2019-04-23 14:44:04.560 21716-21716/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
2019-04-23 14:44:04.680 21716-21744/? A/o.ygzj:process: runtime.cc:558]   at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.onCreate(SourceFile:189)
2019-04-23 14:44:05.108 21612-21612/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:View with id 2131757262: com.dongbaosoft.ygzj.widget.dragview.DragGridViewNew#onMeasure() did not set the measured dimension by calling setMeasuredDimension()
2019-04-23 14:44:05.110 21612-21612/? E/Tinker.TinkerUncaughtExceptionHandler: tinker has fast crash 1 times
2019-04-23 14:44:05.110 21612-21612/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.IllegalStateException: View with id 2131757262: com.dongbaosoft.ygzj.widget.dragview.DragGridViewNew#onMeasure() did not set the measured dimension by calling setMeasuredDimension()
        at android.view.View.measure(View.java:23236)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:23223)
        at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(SourceFile:8636)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(SourceFile:1577)
        at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1511)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(SourceFile:595)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(SourceFile:3583)
        at android.support.v7.widget.RecyclerView.dispatchLayout(SourceFile:3312)
        at android.support.v7.widget.RecyclerView.onLayout(SourceFile:3844)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SourceFile:636)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.dongbaosoft.ygzj.widget.MoveView.MyCoordinatorLayout.onLayout(SourceFile:35)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20726)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    	at android.widget.FrameLayout.onLayout(Frame

```

没有下载补丁应用前，是不会报DragGridViewNew onMeasure这种错的，只会显示
2019-04-23 14:44:04.560 21716-21716/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike

XiaoMI6 Android8.0手机应用补丁正常，无闪退

**Comment by tomystang** [comment]
DragGridViewNew这个view是通过补丁新增的吗？
我看系统源码和这个DragGridView的源码好像本来就有问题，DragGridViewNew在它的onMeasure里确实没调setMeasuredDimension方法。

**Comment by 110117ab** [comment]
我看其他issue也有提到小米8补丁应用失败，是存在这个Bug嘛？

**Comment by tomystang** [comment]
只要crash的堆栈一样应该就是同一个问题了，要具体看下才知道哇。
