### ISSUE TITLE
启动闪退java.lang.ClassNotFoundException: com.tencent.bugly.beta.tinker.TinkerApplicationLike

### ISSUE THREAD

**Issue by DijinDiandian** [Tencent/tinker#1083]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app启动闪退


手机型号：Nexus 5x api 28

手机系统版本：api 28

tinker版本：1.9.6

gradle版本：4.10.1

是否使用热更新SDK：Bugly SDK

系统:Mac

堆栈/日志：

2019-04-28 16:36:02.283 2248-2248/com.dw.project.dianming E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dw.project.dianming, PID: 2248
    java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1069)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:114)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57)
        at android.app.Application.attach(Application.java:212)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.ClassNotFoundException: com.tencent.bugly.beta.tinker.TinkerApplicationLike
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
        at android.app.Application.attach(Application.java:212) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.ClassNotFoundException: com.tencent.bugly.beta.tinker.TinkerApplicationLike
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
        at android.app.Application.attach(Application.java:212) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tinker/entry/DefaultApplicationLike;
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
        at android.app.Application.attach(Application.java:212) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.DefaultApplicationLike" on path: DexPathList[[zip file "/data/app/com.dw.project.dianming-XnKeKcV9Wjq7RnI7Z73jzg==/base.apk"],nativeLibraryDirectories=[/data/app/com.dw.project.dianming-XnKeKcV9Wjq7RnI7Z73jzg==/lib/x86, /data/app/com.dw.project.dianming-XnKeKcV9Wjq7RnI7Z73jzg==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
        at android.app.Application.attach(Application.java:212) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-04-28 16:36:02.291 2248-2248/com.dw.project.dianming E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1069)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:114)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57)
        at android.app.Application.attach(Application.java:212)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.ClassNotFoundException: com.tencent.bugly.beta.tinker.TinkerApplicationLike
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
        at android.app.Application.attach(Application.java:212) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.ClassNotFoundException: com.tencent.bugly.beta.tinker.TinkerApplicationLike
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
        at android.app.Application.attach(Application.java:212) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tinker/entry/DefaultApplicationLike;
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
        at android.app.Application.attach(Application.java:212) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.DefaultApplicationLike" on path: DexPathList[[zip file "/data/app/com.dw.project.dianming-XnKeKcV9Wjq7RnI7Z73jzg==/base.apk"],nativeLibraryDirectories=[/data/app/com.dw.project.dianming-XnKeKcV9Wjq7RnI7Z73jzg==/lib/x86, /data/app/com.dw.project.dianming-XnKeKcV9Wjq7RnI7Z73jzg==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
        at android.app.Application.attach(Application.java:212) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    
    
    --------- beginning of system
2019-04-28 16:36:02.330 1617-1617/? E/lowmemorykiller: Error writing /proc/2248/oom_score_adj; errno=22
2019-04-28 16:36:02.566 23833-23846/? E/memtrack: Couldn't load memtrack module

**Comment by tomystang** [comment]
看现象应该是你的tinker lib版本和对应的bugly sdk版本对不上导致的，你的bugly sdk看起来比tinker lib要新，所以bugly sdk尝试去找1.9.9版本开始才有的tinker的入口类会找不到。

**Comment by aibingbing** [comment]
// 指定tinker依赖版本（注：应用升级1.3.5版本起，不再内置tinker）
  compile 'com.tencent.tinker:tinker-android-lib:1.9.6'

遇到这个问题，发现bugly1.3.5后需要手动制定tinker，并且是对应的版本
