### ISSUE TITLE
gradle 5.5.1 打开 keepDexApply = true  编译失败

### ISSUE THREAD

**Issue by wangxiaxin** [Tencent/tinker#1105]
异常类型：编译异常

手机型号：

手机系统版本：

tinker版本：1.9.13

gradle版本：5.1.1

是否使用热更新SDK： TinkerPatch SDK

系统：windows/Linux

堆栈/日志：
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com/android/build/gradle/internal/transforms/DexTransform
   > can't find tinkerProcessReleaseManifest, you must init tinker plugin first!

11:11:18.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/internal/transforms/Dex
Transform
11:11:18.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.tencent.tinker.build.gradle.TinkerPatchPlugin$_apply_closure1$_closure2.doCall(Tin
kerPatchPlugin.groovy:217)
11:11:18.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
11:11:18.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
11:11:18.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
11:11:18.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
11:11:18.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollectio
n.java:158)
11:11:18.848 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollectio
n.java:186)

**Comment by tomystang** [comment]
Tinker目前还不支持Gradle 5.x，可以降级到Gradle 4.7和AGP 3.2.1，就能正常编译了。

**Comment by duanxifeng** [comment]
> Tinker目前还不支持Gradle 5.x，可以降级到Gradle 4.7和AGP 3.2.1，就能正常编译了。

请问有计划什么时候支持吗

**Comment by duanxifeng** [comment]
下个版本什么时候发呢

**Comment by zhouguanyi** [comment]
预计什么事实支持Gradle 5.x呢？

**Comment by pumatus** [comment]
plus one!!!!

**Comment by alfredzhang0728** [comment]
现在还不支持吗？求告知 谢谢

**Comment by Primer1889** [comment]
目前还不支持吗
