### ISSUE TITLE
新增资源文件合成失败，报非法字符创

### ISSUE THREAD

**Issue by marssong123** [Tencent/tinker#1132]
## Issue/提问须知
*`
异常类型：app运行时异常/编译异常

手机型号：如:oppo R9

手机系统版本：如:Android 5.0

tinker版本：如:1.9.9

gradle版本：如:3.3.2

是否使用热更新SDK： 否

系统：如:Mac

堆栈/日志：
06-20 02:06:30.730 24412-24412/com.tencent.qqpim W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.tencent.qqpim/tinker
06-20 02:06:30.733 24412-24412/com.tencent.qqpim D/Tinker.DefaultAppLike: onBaseContextAttached:
06-20 02:06:30.739 24412-24412/com.tencent.qqpim I/Tinker.QQPimPatchListener: application maxMemory:256
06-20 02:06:30.743 24412-24412/com.tencent.qqpim W/Tinker.Tinker: tinker patch directory: /data/data/com.tencent.qqpim/tinker
06-20 02:06:30.744 24412-24412/com.tencent.qqpim I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
06-20 02:06:30.745 24412-24412/com.tencent.qqpim I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.tencent.qqpim, main process:true, systemOTA:false, fingerPrint:OPPO/R7Plus/R7Plus:5.0/LRX21M/1431939987:user/release-keys, oatDir:null, useInterpretMode:false
06-20 02:06:30.745 24412-24412/com.tencent.qqpim W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
06-20 02:06:30.745 24412-24412/com.tencent.qqpim I/Tinker.LoadReporter: onLoadResult: loadCode-2 cost:6
06-20 02:06:30.746 24412-24412/com.tencent.qqpim I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.tencent.qqpim/tinker, code: -2, cost: 6ms
06-20 02:06:30.746 24412-24412/com.tencent.qqpim W/Tinker.Tinker: tinker load fail!
06-20 02:06:30.746 24412-24412/com.tencent.qqpim I/Tinker.LoadLibrary: tinker is not loaded, just return
06-20 02:06:30.753 24412-24412/com.tencent.qqpim I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
06-20 02:06:30.753 24412-24412/com.tencent.qqpim D/Tinker.DefaultAppLike: onCreate
06-20 02:06:33.528 24412-24412/com.tencent.qqpim W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
06-20 02:06:35.661 24412-24684/com.tencent.qqpim I/CloudCmdTinkerEnable: parse:6009
06-20 02:06:35.662 24412-24684/com.tencent.qqpim I/CloudCmdTinkerEnable: handleResult cmd receive success ! cloudId:6009
06-20 02:06:35.662 24412-24684/com.tencent.qqpim I/CloudCmdTinkerEnable: handleResult retCode:0
06-20 02:06:35.665 24412-24684/com.tencent.qqpim I/CloudCmdTinkerEnable: handleInfo mTinkerId:6.9.13.239900
06-20 02:06:35.665 24412-24684/com.tencent.qqpim I/CloudCmdTinkerEnable: handleInfo mVersion:1
06-20 02:06:35.665 24412-24684/com.tencent.qqpim I/CloudCmdTinkerEnable: handleInfo mURL:http://mmgr.myapp.com/myapp/gjbig/dpsw/cdn/WiFiManager_Tinker_Patch_1_6.9.13.239901_20190620020428.jar
06-20 02:06:35.665 24412-24684/com.tencent.qqpim I/CloudCmdTinkerEnable: handleInfo startDownload:
06-20 02:06:35.667 24412-24692/com.tencent.qqpim I/TinkerPatchDownloader: tryPatch:start
06-20 02:06:35.667 24412-24692/com.tencent.qqpim I/TinkerPatchDownloader: getReadyFile error3: 
06-20 02:06:35.668 24412-24692/com.tencent.qqpim I/TinkerPatchDownloader: downloadImple:Download Begin
06-20 02:06:36.921 24412-24692/com.tencent.qqpim I/TinkerPatchDownloader: downloadImple Download success:
06-20 02:06:36.923 24412-24692/com.tencent.qqpim I/TinkerPatchDownloader: tryPatch:start
06-20 02:06:36.923 24412-24692/com.tencent.qqpim I/TinkerPatchDownloader: getReadyFile error1: 
06-20 02:06:36.931 24412-24692/com.tencent.qqpim I/TinkerPatchDownloader: tryPatch:Download Ok
06-20 02:06:36.931 24412-24692/com.tencent.qqpim I/TinkerPatchDownloader: tryPatch:Merge Begin
06-20 02:06:36.938 24412-24692/com.tencent.qqpim I/Tinker.QQPimPatchListener: receive a patch file: /data/data/com.tencent.qqpim/tinker/patch.info, file size:967646
06-20 02:06:36.941 24412-24692/com.tencent.qqpim W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
06-20 02:06:36.944 24412-24692/com.tencent.qqpim I/Tinker.QQPimPatchListener: get platform:all
06-20 02:06:36.945 24412-24692/com.tencent.qqpim I/Tinker.TinkerPatchService: run patch service by intent service.
06-20 02:06:36.966 1011-2127/? I/ActivityManager: Start proc com.tencent.qqpim:patch for service com.tencent.qqpim/com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner: pid=24717 uid=11695 gids={51695, 9997, 1028, 1015, 3003, 3002, 3001} abi=armeabi
06-20 02:06:36.968 24412-24692/com.tencent.qqpim I/TinkerPatchDownloader: tryPatch success: 
06-20 02:06:37.025 24717-24717/com.tencent.qqpim:patch W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
06-20 02:06:37.027 24717-24717/com.tencent.qqpim:patch D/Tinker.DefaultAppLike: onBaseContextAttached:
06-20 02:06:37.032 24717-24717/com.tencent.qqpim:patch I/Tinker.QQPimPatchListener: application maxMemory:256
06-20 02:06:37.035 24717-24717/com.tencent.qqpim:patch W/Tinker.Tinker: tinker patch directory: /data/data/com.tencent.qqpim/tinker
06-20 02:06:37.036 24717-24717/com.tencent.qqpim:patch I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
06-20 02:06:37.036 24717-24717/com.tencent.qqpim:patch I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.tencent.qqpim:patch, main process:false, systemOTA:false, fingerPrint:OPPO/R7Plus/R7Plus:5.0/LRX21M/1431939987:user/release-keys, oatDir:null, useInterpretMode:false
06-20 02:06:37.036 24717-24717/com.tencent.qqpim:patch W/Tinker.TinkerLoadResult: tinker is disable, just return
06-20 02:06:37.036 24717-24717/com.tencent.qqpim:patch I/Tinker.LoadReporter: onLoadResult: loadCode-1 cost:5
06-20 02:06:37.036 24717-24717/com.tencent.qqpim:patch I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.tencent.qqpim/tinker, code: -1, cost: 5ms
06-20 02:06:37.037 24717-24717/com.tencent.qqpim:patch W/Tinker.Tinker: tinker load fail!
06-20 02:06:37.037 24717-24717/com.tencent.qqpim:patch I/Tinker.LoadLibrary: tinker is not loaded, just return
06-20 02:06:37.038 24717-24717/com.tencent.qqpim:patch I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
06-20 02:06:37.038 24717-24717/com.tencent.qqpim:patch D/Tinker.DefaultAppLike: onCreate
06-20 02:06:37.372 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@4de1e24 className=com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner packageName=com.tencent.qqpim intent=null}
06-20 02:06:37.375 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@4de1e24 className=com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner packageName=com.tencent.qqpim intent=null}
06-20 02:06:37.377 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner@be01b42, flags=0, startId=1
06-20 02:06:37.378 24717-24768/com.tencent.qqpim:patch I/Tinker.TinkerPatchService: try to increase patch process priority
06-20 02:06:37.380 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@4de1e24 startId=1 args=Intent { cmp=com.tencent.qqpim/com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner (has extras) }}
06-20 02:06:37.385 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@2dc5e753 className=com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner$InnerService packageName=com.tencent.qqpim intent=null}
06-20 02:06:37.386 24717-24768/com.tencent.qqpim:patch I/Tinker.PatchReporter: onPatchServiceStart: 
06-20 02:06:37.386 24717-24768/com.tencent.qqpim:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
06-20 02:06:37.393 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@2dc5e753 className=com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner$InnerService packageName=com.tencent.qqpim intent=null}
06-20 02:06:37.393 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner$InnerService@2fb5e589, flags=0, startId=1
06-20 02:06:37.394 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@2dc5e753 startId=1 args=Intent { cmp=com.tencent.qqpim/com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner$InnerService }}
06-20 02:06:37.394 24717-24717/com.tencent.qqpim:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
06-20 02:06:37.401 24717-24768/com.tencent.qqpim:patch W/Tinker.UpgradePatchRetry: try copy file: /data/data/com.tencent.qqpim/tinker/patch.info to /data/data/com.tencent.qqpim/tinker_temp/temp.apk
06-20 02:06:37.401 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner$InnerService@2fb5e589
06-20 02:06:37.462 24717-24768/com.tencent.qqpim:patch I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:6f8ca3690297a16458f3254005305286
06-20 02:06:37.467 24717-24768/com.tencent.qqpim:patch I/Tinker.PatchReporter: onPatchException: 
06-20 02:06:37.467 24717-24768/com.tencent.qqpim:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchException: patch exception path: /data/data/com.tencent.qqpim/tinker/patch.info, throwable: Tinker Exception:readAndCheckPropertyWithLock fail
06-20 02:06:37.467 24717-24768/com.tencent.qqpim:patch E/Tinker.DefaultPatchReporter: tinker patch exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
06-20 02:06:37.468 24717-24768/com.tencent.qqpim:patch E/Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:readAndCheckPropertyWithLock fail
        at com.tencent.tinker.loader.shareutil.SharePatchInfo.readAndCheckPropertyWithLock(SharePatchInfo.java:70)
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:83)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(TinkerPatchService.java:200)
        at com.tencent.tinker.lib.service.TinkerPatchService.access$100(TinkerPatchService.java:55)
        at com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner.onHandleIntent(TinkerPatchService.java:230)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalArgumentException: Invalid Unicode sequence: illegal character
        at java.util.Properties.load(Properties.java:308)
        at java.util.Properties.load(Properties.java:248)
        at com.tencent.tinker.loader.shareutil.SharePatchInfo.readAndCheckProperty(SharePatchInfo.java:126)
        at com.tencent.tinker.loader.shareutil.SharePatchInfo.readAndCheckPropertyWithLock(SharePatchInfo.java:68)
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:83) 
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(TinkerPatchService.java:200) 
        at com.tencent.tinker.lib.service.TinkerPatchService.access$100(TinkerPatchService.java:55) 
        at com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner.onHandleIntent(TinkerPatchService.java:230) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
06-20 02:06:37.475 24717-24768/com.tencent.qqpim:patch I/Tinker.PatchReporter: onPatchResult: 
06-20 02:06:37.476 24717-24768/com.tencent.qqpim:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /data/data/com.tencent.qqpim/tinker/patch.info, success: false, cost: 64
06-20 02:06:37.479 24717-24768/com.tencent.qqpim:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tencent.qqpim/tinker_temp/temp.apk
06-20 02:06:37.513 24717-24717/com.tencent.qqpim:patch D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner@be01b42
06-20 02:06:38.116 24412-24688/com.tencent.qqpim I/CloudCmdTinkerEnable: parse:6009
06-20 02:06:38.116 24412-24688/com.tencent.qqpim I/CloudCmdTinkerEnable: handleResult cmd receive success ! cloudId:6009
06-20 02:06:38.116 24412-24688/com.tencent.qqpim I/CloudCmdTinkerEnable: handleResult retCode:0
06-20 02:06:38.116 24412-24688/com.tencent.qqpim I/CloudCmdTinkerEnable: handleInfo error old: 
06-20 02:06:41.441 24412-24803/com.tencent.qqpim I/Tinker.QQPimResultService: QQPimResultService receive result: 
    PatchResult: 
    isSuccess:false
    rawPatchFilePath:/data/data/com.tencent.qqpim/tinker/patch.info
    costTime:64
    patchVersion:6f8ca3690297a16458f3254005305286
    Throwable:Tinker Exception:readAndCheckPropertyWithLock fail
06-20 02:06:41.442 24412-24803/com.tencent.qqpim I/Tinker: QQPimResultService! 
    PatchResult: 
    isSuccess:false
    rawPatchFilePath:/data/data/com.tencent.qqpim/tinker/patch.info
    costTime:64
    patchVersion:6f8ca3690297a16458f3254005305286
    Throwable:Tinker Exception:readAndCheckPropertyWithLock fail
06-20 02:06:41.445 24412-24803/com.tencent.qqpim I/Tinker.QQPimResultService: [补丁合成]onHandleIntent正常
.

**Comment by marssong123** [comment]
主要是合成的时候报非法字符串
06-20 02:06:37.468 24717-24768/com.tencent.qqpim:patch E/Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:readAndCheckPropertyWithLock fail
        at com.tencent.tinker.loader.shareutil.SharePatchInfo.readAndCheckPropertyWithLock(SharePatchInfo.java:70)
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:83)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(TinkerPatchService.java:200)
        at com.tencent.tinker.lib.service.TinkerPatchService.access$100(TinkerPatchService.java:55)
        at com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner.onHandleIntent(TinkerPatchService.java:230)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalArgumentException: Invalid Unicode sequence: illegal character
        at java.util.Properties.load(Properties.java:308)
        at java.util.Properties.load(Properties.java:248)
        at com.tencent.tinker.loader.shareutil.SharePatchInfo.readAndCheckProperty(SharePatchInfo.java:126)
        at com.tencent.tinker.loader.shareutil.SharePatchInfo.readAndCheckPropertyWithLock(SharePatchInfo.java:68)
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:83) 
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(TinkerPatchService.java:200) 
        at com.tencent.tinker.lib.service.TinkerPatchService.access$100(TinkerPatchService.java:55) 
        at com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner.onHandleIntent(TinkerPatchService.java:230) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.os.HandlerThread.run(HandlerThread.java:61)
