### ISSUE TITLE
Could not create new AssetManager

### ISSUE THREAD

**Issue by coutliuxing** [Tencent/tinker#1134]
异常类型：app运行时异常

手机型号：小米4

手机系统版本：Android 6.0 

tinker版本：如1.9.13

gradle版本：如:4.10.1

是否使用热更新SDK： 否

系统：win

```06-20 18:46:45.246 13599-13599/com.hardy.hotfix E/Tinker.DefaultLoadReporter: tinker load exception  java.lang.IllegalStateException: Could not create new AssetManager
        at com.tencent.tinker.loader.TinkerResourcePatcher.monkeyPatchExistingResources(TinkerResourcePatcher.java:199)
        at com.tencent.tinker.loader.TinkerResourceLoader.loadTinkerResources(TinkerResourceLoader.java:65)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:305)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:56)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:173)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:146)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:164)
        at com.hardy.hotfix.patch.TinkerPatchReflectApplication.attachBaseContext(TinkerPatchReflectApplication.java:46)
        at android.app.Application.attach(Application.java:191)
        at android.app.Instrumentation.newApplication(Instrumentation.java:998)
        at android.app.Instrumentation.newApplication(Instrumentation.java:982)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:579)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4798)
        at android.app.ActivityThread.access$1700(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)```
patch已经成功了，但load的时候出现的问题，麻烦看一下

**Comment by tomystang** [comment]
光看这个堆栈暂时无法判断问题原因哇，如果能复现的话留意一下系统log里有没有打关于AssetManager或者Resources的内容？

**Comment by coutliuxing** [comment]
@tomystang 
![image](https://user-images.githubusercontent.com/8907930/59893695-55b7b080-9410-11e9-93df-690de8d71d4b.png)

**Comment by tomystang** [comment]
额，你是想一个patch给多个base包用吗？这样可能得大改哇。因为资源文件是靠bsdiff-bspatch来生成的，base变了，bspatch就不保证能生成正确的文件了。而且resoure.apk打出重复的entry估计也跟你去掉了校验逻辑有关，可以debug一下看看。

**Comment by coutliuxing** [comment]
@tomystang 重复的问题还好，应该可以在checkAndExtractResourceLargeFile里边加上文件名称+crc的检验过滤。现在最大的问题是合并生成的resource.arsc完全是不能用的，不知道什么原因
![image](https://user-images.githubusercontent.com/8907930/60000912-cb817d80-9697-11e9-85b8-348d9df818e9.png)，希望能给点建议，谢谢~

**Comment by tomystang** [comment]
正常的，base变了，bspatch生成的产物肯定会有问题的。Tinker目前的机制不彻底换掉bsdiff机制的话应该是不支持一个patch对多个base的。
