### ISSUE TITLE
HUAWEI/JKM-AL00b/HWJKM-HM:8.1.0   Tinker Exception:checkSafeModeCount fail

### ISSUE THREAD

**Issue by jerry9433** [Tencent/tinker#1151]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型: 补丁合并成功后，开屏重启失败，手动重启后并没有效果，报错。

手机型号：HUAWEI/JKM-AL00b/

手机系统版本：如:Android 8.1.0

tinker版本：如:1.9.6

gradle版本：如:3.1.3
是否使用热更新SDK： 使用 Bugly SDK

系统：MacBook pro

堆栈/日志：


2019-07-09 17:22:53.855 com.demo.app E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2019-07-09 17:22:53.856 com.demo.app E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:251)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:163)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57)
        at android.app.Application.attach(Application.java:201)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1106)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1090)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1070)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6602)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)



```

提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没给出任何代码截图报错的，将绝对不会有任何反馈。这种issue也是一律直接关闭的,大家可以参阅[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。

Tinker是一个开源项目，希望大家遇到问题时要学会先思考，看看sample与Tinker的源码，更鼓励大家给我们提pr.

**Comment by jerry9433** [comment]
另外，在Samsung s8 9.0系统上也会重启后失败，报错为
``
2019-07-09 17:34:59.212 com.demo.app E/Tinker.DefaultLoadReporter: tinker load exception  java.lang.NoSuchFieldException: Field mStringBlocks not found in class android.content.res.AssetManager
        at com.tencent.tinker.loader.shareutil.ShareReflectUtil.findField(ShareReflectUtil.java:55)
        at com.tencent.tinker.loader.TinkerResourcePatcher.isResourceCanPatch(TinkerResourcePatcher.java:101)
        at com.tencent.tinker.loader.TinkerResourceLoader.checkComplete(TinkerResourceLoader.java:122)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:216)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:163)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57)
        at android.app.Application.attach(Application.java:237)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1128)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6188)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
``

**Comment by jerry9433** [comment]
经测，tinker 1.9.9版本已经解决此问题
