### ISSUE TITLE
在assembleDebug时候出现无法生成对应的apk

### ISSUE THREAD

**Issue by SmallBenClock** [Tencent/tinker#116]
Exception in thread "png-cruncher_29" java.lang.RuntimeException: Timed out while waiting for slave aapt process, make sure the aapt execute at C:\Users\Administrator\AppData\Local\Android\Sdk\build-tools\23.0.2\aapt.exe can run successfully (some anti-virus may block it) or try setting environment variable SLAVE_AAPT_TIMEOUT to a value bigger than 5 seconds
	at com.android.builder.png.AaptProcess.waitForReady(AaptProcess.java:108)
	at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:120)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "png-cruncher_28" java.lang.RuntimeException: Timed out while waiting for slave aapt process, make sure the aapt execute at C:\Users\Administrator\AppData\Local\Android\Sdk\build-tools\23.0.2\aapt.exe can run successfully (some anti-virus may block it) or try setting environment variable SLAVE_AAPT_TIMEOUT to a value bigger than 5 seconds
	at com.android.builder.png.AaptProcess.waitForReady(AaptProcess.java:108)
	at com.android.builder.png.QueuedCruncher$1.creation(QueuedCruncher.java:120)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:203)
	at java.lang.Thread.run(Thread.java:745)
:app:mergeProdDebugResources
:app:processProdArmeabiDebugManifest
Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

:app:processProdArmeabiDebugResources
:app:processProdUniversalDebugManifest
tinker add b495583 to your AndroidManifest.xml F:\androidStudioWorkSpace\copy1\jxb_android_v3\app\build\intermediates\manifests\full\prod\debug\AndroidManifest.xml
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml
:app:tinkerProcessProdDebugManifest
apply resource mapping file F:\androidStudioWorkSpace\copy1\jxb_android_v3\app\build\bakApk/app-release-1010-15-57-14-R.txt is illegal, just ignore
tinker gen resource public.xml in build/intermediates/tinker_intermediates/public.xml
tinker gen resource idx.xml in build/intermediates/tinker_intermediates/idx.xml
:app:tinkerProcessProdDebugResourceId
Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

**Comment by shwenzhang** [comment]
Exception in thread "png-cruncher_29" java.lang.RuntimeException: Timed out while waiting for slave aapt process, make sure the aapt execute at C:\Users\Administrator\AppData\Local\Android\Sdk\build-tools\23.0.2\aapt.exe can run successfully (some anti-virus may block it) or try setting environment variable SLAVE_AAPT_TIMEOUT to a value bigger than 5 seconds
