### ISSUE TITLE
Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14

### ISSUE THREAD

**Issue by CodeMAI** [Tencent/tinker#1173]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：如:小米6、小米8、华为mete9、华为p20

手机系统版本：Android 9.0、Android 8.0、Android 6.0 
tinker版本：如:1.9.13.1

gradle版本：如:3.1.4

是否使用热更新SDK：Bugly SDK

系统：Mac

堆栈/日志：
08-01 13:55:11.200 25701-26191/com.shanghaigm.mychevy I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
    PatchResult: 
    isSuccess:true
    rawPatchFilePath:/storage/emulated/0/Load.apk
    costTime:9056
    patchVersion:d767c3ae837dbd422eae5d979d5aba93
     
08-01 13:55:11.205 25701-26191/com.shanghaigm.mychevy W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /storage/emulated/0/Load.apk
08-01 13:55:11.205 25701-26191/com.shanghaigm.mychevy I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/Load.apk
08-01 13:55:11.338 1195-4534/? W/ActivityManager: Scheduling restart of crashed service com.shanghaigm.mychevy/com.tencent.tinker.lib.service.DefaultTinkerResultService in 1000ms
    Scheduling restart of crashed service com.shanghaigm.mychevy/.listener.SecurityService in 1000ms
    Scheduling restart of crashed service com.shanghaigm.mychevy/cn.jpush.android.service.PushService in 1000ms
08-01 13:55:12.548 26200-26200/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm
08-01 13:55:12.548 26200-26200/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
08-01 13:55:12.550 26200-26200/? D/Tinker.TinkerInternals: same fingerprint:HUAWEI/MHA-AL00/HWMHA:8.0.0/HUAWEIMHA-AL00/375(C00):user/release-keys
08-01 13:55:12.552 26200-26200/? W/Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_com.shanghaigm.mychevy count:0
08-01 13:55:12.554 26200-26200/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.shanghaigm.mychevy count:1
08-01 13:55:12.555 26200-26200/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shanghaigm.mychevy-Lj_rPhkSOG8JsztBIZbcaA==/base.apk"],nativeLibraryDirectories=[/data/app/com.shanghaigm.mychevy-Lj_rPhkSOG8JsztBIZbcaA==/lib/arm, /data/app/com.shanghaigm.mychevy-Lj_rPhkSOG8JsztBIZbcaA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]]
    verify dex file:/data/user/0/com.shanghaigm.mychevy/tinker/patch-d767c3ae/dex/tinker_classN.apk md5, use time: 0
08-01 13:55:12.555 26200-26200/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.shanghaigm.mychevy/tinker/patch-d767c3ae/odex, dex size:1
08-01 13:55:12.562 26200-26200/? I/Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/com.shanghaigm.mychevy/tinker/patch-d767c3ae/dex/tinker_classN.apk", zip file "/data/app/com.shanghaigm.mychevy-Lj_rPhkSOG8JsztBIZbcaA==/base.apk"],nativeLibraryDirectories=[/data/app/com.shanghaigm.mychevy-Lj_rPhkSOG8JsztBIZbcaA==/lib/arm, /data/app/com.shanghaigm.mychevy-Lj_rPhkSOG8JsztBIZbcaA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]], dex size:1
08-01 13:55:12.563 26200-26200/? W/Tinker.ClassLoaderAdder: checkDexInstall result:false
08-01 13:55:12.563 26200-26200/? E/Tinker.TinkerDexLoader: install dexes failed
08-01 13:55:12.563 26200-26200/? W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
08-01 13:55:12.564 26200-26200/? D/Tinker.DefaultAppLike: onBaseContextAttached:
08-01 13:55:12.568 26200-26200/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.shanghaigm.mychevy/tinker
08-01 13:55:12.569 26200-26200/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.13.1
08-01 13:55:12.570 26200-26200/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14, process name:com.shanghaigm.mychevy, main process:true, systemOTA:false, fingerPrint:HUAWEI/MHA-AL00/HWMHA:8.0.0/HUAWEIMHA-AL00/375(C00):user/release-keys, oatDir:odex, useInterpretMode:false
08-01 13:55:12.571 26200-26200/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:d767c3ae837dbd422eae5d979d5aba93, current:d767c3ae837dbd422eae5d979d5aba93
    Tinker load have exception loadCode:-14
08-01 13:55:12.571 26200-26200/? E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
08-01 13:55:12.574 26200-26200/? I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
08-01 13:55:12.574 26200-26200/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
08-01 13:55:12.575 26200-26200/? E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:85)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:194)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:280)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:56)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:173)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:146)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:164)
        at android.app.Application.attach(Application.java:195)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1105)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1089)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1036)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6491)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
08-01 13:55:12.576 26200-26200/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.shanghaigm.mychevy/tinker/patch.info , oldVer:, newVer:d767c3ae837dbd422eae5d979d5aba93, isProtectedApp:0, isRemoveNewVersion:1, fingerprint:HUAWEI/MHA-AL00/HWMHA:8.0.0/HUAWEIMHA-AL00/375(C00):user/release-keys, oatDir:odex
08-01 13:55:12.579 26200-26200/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.shanghaigm.mychevy/tinker, code: -14, cost: 89ms
08-01 13:55:12.579 26200-26200/? W/Tinker.Tinker: tinker load fail!
08-01 13:55:12.583 26200-26200/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.shanghaigm.mychevy count:0

合成补丁后，加载失败。

**Comment by AimersCat** [comment]
我也遇到了这个问题 请问解决了吗

**Comment by luoyincheng** [comment]
这个问题怎么解决啊

**Comment by CoderNo89757** [comment]
有解决办法吗？？

**Comment by CoderNo89757** [comment]
> 我也遇到了这个问题 请问解决了吗

兄弟你解决了吗？

**Comment by CoderNo89757** [comment]
> 这个问题怎么解决啊

你解决了没
