### ISSUE TITLE
所有静态的方法和常量都无法被合并

### ISSUE THREAD

**Issue by manitozhang** [Tencent/tinker#1192]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：华为p30

手机系统版本：Android9.0

tinker版本：1.9.13.2

gradle版本：4.4

是否使用热更新SDK： TinkerPatch SDK

系统：Mac

修复之后,静态方法和静态变量都会报找不到异常,提出没有该方法
可忽略以下的方法名和常量名,用的是自己服务器下载的

Caused by: java.lang.NoSuchMethodError: No static method saveUserInfo
java.lang.NoSuchFieldError: No static field IMAGE_CAMERA_PATH

**Comment by manitozhang** [comment]
用的是组件化,配置在app的build.gradle,添加的静态成员方法和成员变量是在common的lib中

**Comment by manitozhang** [comment]
7.0一下手机可以,华为p30, 9.0手机不行

**Comment by victorfan336** [comment]
我也遇到了类型的问题，热更后崩溃一大片。要被骂死了。
异常类型：app运行时异常

手机型号：vivo X9，小米 4C等

手机系统版本：Android7.0

tinker版本：1.9.11

gradle版本：4.10.1

是否使用热更新SDK： no
以下是日志：
java.lang.NoSuchMethodError: No static method o(Lcom/xx/xx/xiaoshuo/read/ui/read/ReadActivity;)V in class Lcom/xx/xx/xiaoshuo/read/ui/read/ReadActivity; or its super classes (declaration of 'com.xx.xx.xiaoshuo.read.ui.read.ReadActivity' appears in base.apk)
    at com.xx.xx.xiaoshuo.read.ui.read.ReadActivity$26.a(ReadActivity.java:528)
    at com.xx.xx.xiaoshuo.read.ui.read.ReadActivity.y(ReadActivity.java:428)
    at com.xx.xx.xiaoshuo.read.ui.read.ReadActivity.onCreate(ReadActivity.java:306)
    at android.app.Activity.performCreate(Activity.java:6859)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2681)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1513)
    at android.os.Handler.dispatchMessage(Handler.java:102)

@tomystang @manitozhang @simpleton @junyuecao

**Comment by manitozhang** [comment]
@victorfan336 你改为1.9.13.2版本，还有问一下你是不是用的组件化

**Comment by victorfan336** [comment]
> @victorfan336 你改为1.9.13.2版本，还有问一下你是不是用的组件化

有用组件化开发，唉，都不敢用了。
你的问题找到方法了吗？

**Comment by manitozhang** [comment]
@victorfan336 没有，是组件化问题，看来，我activity都能更新的上，你是不是在组件中取组件中的新方法了？

**Comment by manitozhang** [comment]
@victorfan336 我是在common里面这个公共类取公共类的一个静态方法，如果在其他组件中取是没问题的，只是在common中取common的成员有问题，而且我在app主module写一个activity都没事，就是这个会有问题

**Comment by victorfan336** [comment]
问题是这个问题只是在部分机型上才有这个问题，不是必现的，所以以后得非常谨慎，少用为好。

**Comment by manitozhang** [comment]
@victorfan336 是的，我现在都是保留一个基准包，测试下可以再发布，我感觉这种应该是组件化和tinker一起的坑
