### ISSUE TITLE
Patch成功加载后退出重新打开crash(debug版ok，release混淆版有问题)

### ISSUE THREAD

**Issue by torv** [Tencent/tinker#1199]
```
异常类型：app运行时异常

手机型号：Nexus 6P

手机系统版本：Android 8.0

tinker版本：1.9.13.2

gradle版本：5.1.1

是否使用热更新SDK： NO

系统：Windows

堆栈/日志：

2019-09-02 19:12:34.400 17459-17985/? W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /data/user/0/com.qiyi.video.speaker/files/patch1567422651524.zip
2019-09-02 19:12:34.400 17459-17985/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.qiyi.video.speaker/files/patch1567422651524.zip
2019-09-02 19:12:34.401 17459-17985/? I/HotFix:TinkerResultService: tinker wait screen to restart process
2019-09-02 19:13:59.414 18104-18104/? W/Tinker.TinkerLoader: tryLoadPatchFiles:version is blank, wait main process to restart
2019-09-02 19:13:59.493 18104-18104/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-09-02 19:14:07.725 18289-18289/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm
2019-09-02 19:14:07.726 18289-18289/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2019-09-02 19:14:07.729 18289-18289/? D/Tinker.TinkerInternals: same fingerprint:google/angler/angler:8.1.0/OPM1.171019.011/4448085:user/release-keys
2019-09-02 19:14:07.731 18289-18289/? W/Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_com.qiyi.video.speaker count:0
2019-09-02 19:14:07.742 18289-18289/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.qiyi.video.speaker count:1
2019-09-02 19:14:07.742 18289-18289/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.qiyi.video.speaker-_8V4qIuNF-0ASJhtdsApOQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.qiyi.video.speaker-_8V4qIuNF-0ASJhtdsApOQ==/lib/arm, /data/app/com.qiyi.video.speaker-_8V4qIuNF-0ASJhtdsApOQ==/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]]
2019-09-02 19:14:07.742 18289-18289/? I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/com.qiyi.video.speaker/tinker/patch-bde5444b/dex/tinker_classN.apk md5, use time: 0
2019-09-02 19:14:07.742 18289-18289/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.qiyi.video.speaker/tinker/patch-bde5444b/odex, dex size:1
2019-09-02 19:14:07.770 18289-18289/? I/Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/com.qiyi.video.speaker/tinker/patch-bde5444b/dex/tinker_classN.apk", zip file "/data/app/com.qiyi.video.speaker-_8V4qIuNF-0ASJhtdsApOQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.qiyi.video.speaker-_8V4qIuNF-0ASJhtdsApOQ==/lib/arm, /data/app/com.qiyi.video.speaker-_8V4qIuNF-0ASJhtdsApOQ==/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]], dex size:1
2019-09-02 19:14:07.773 18289-18289/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
2019-09-02 19:14:07.794 18289-18289/? W/Tinker.ResourcePatcher: try to clear typedArray cache!
2019-09-02 19:14:07.795 18289-18289/? I/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
2019-09-02 19:14:07.795 18289-18289/? I/Tinker.ResourceLoader: monkeyPatchExistingResources resource file:/data/user/0/com.qiyi.video.speaker/tinker/patch-bde5444b/res/resources.apk, use time: 22
2019-09-02 19:14:07.795 18289-18289/? I/Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
2019-09-02 19:14:07.796 18289-18289/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.qiyi.video.speaker/tinker/patch.info , oldVer:bde5444b7896265e162a6b78e1ec579e, newVer:bde5444b7896265e162a6b78e1ec579e, isProtectedApp:0, isRemoveNewVersion:0, fingerprint:google/angler/angler:8.1.0/OPM1.171019.011/4448085:user/release-keys, oatDir:odex
2019-09-02 19:14:07.832 18289-18289/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
2019-09-02 19:14:07.958 18289-18289/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.qiyi.video.speaker count:0
2019-09-02 19:14:08.045 18289-18289/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-09-02 19:14:08.187 18289-18289/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.qiyi.video.speaker/tinker
2019-09-02 19:14:08.191 18289-18289/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.13.2
2019-09-02 19:14:08.193 18289-18289/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.qiyi.video.speaker, main process:true, systemOTA:false, fingerPrint:google/angler/angler:8.1.0/OPM1.171019.011/4448085:user/release-keys, oatDir:odex, useInterpretMode:false
2019-09-02 19:14:08.193 18289-18289/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:bde5444b7896265e162a6b78e1ec579e, current:bde5444b7896265e162a6b78e1ec579e
2019-09-02 19:14:08.193 18289-18289/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
2019-09-02 19:14:08.193 18289-18289/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchVersionChanged: patch version change from  to bde5444b7896265e162a6b78e1ec579e
2019-09-02 19:14:08.196 18289-18289/? I/Tinker.UpgradePatchRetry: onPatchResetMaxCheck, reset max check to 1
2019-09-02 19:14:08.197 18289-18289/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.qiyi.video.speaker/tinker, code: 0, cost: 325ms
2019-09-02 19:14:08.197 18289-18289/? I/Tinker.LoadReporterEx: Patch version 1 loaded ok!
2019-09-02 19:14:08.335 18289-18325/? E/AndroidRuntime: FATAL EXCEPTION: PbScheduler-0
    Process: com.qiyi.video.speaker, PID: 18289
    java.lang.NoSuchFieldError: No field mDataSourceAvailable of type Z in class Lorg/qiyi/android/pingback/internal/db/PingbackSQLiteDataSource; or its superclasses (declaration of 'org.qiyi.android.pingback.internal.db.PingbackSQLiteDataSource' appears in /data/data/com.qiyi.video.speaker/tinker/patch-bde5444b/dex/tinker_classN.apk!classes4.dex)
        at org.qiyi.android.pingback.internal.db.PingbackSQLiteDataSource.getAllForStart(Unknown Source:16)
        at org.qiyi.android.pingback.internal.db.PingbackRepository.getAllForStart(Unknown Source:2)
        at org.qiyi.android.pingback.PingbackManagerInternal.getPendingPingbacks(Unknown Source:32)
        at org.qiyi.android.pingback.PingbackManagerInternal.preparePingbacks(Unknown Source:0)
        at org.qiyi.android.pingback.PingbackManagerInternal.c(Unknown Source:0)
        at org.qiyi.android.pingback.PingbackManagerInternal$3.run(Unknown Source:96)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-09-02 19:14:08.336 18289-18325/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.NoSuchFieldError: No field mDataSourceAvailable of type Z in class Lorg/qiyi/android/pingback/internal/db/PingbackSQLiteDataSource; or its superclasses (declaration of 'org.qiyi.android.pingback.internal.db.PingbackSQLiteDataSource' appears in /data/data/com.qiyi.video.speaker/tinker/patch-bde5444b/dex/tinker_classN.apk!classes4.dex)
        at org.qiyi.android.pingback.internal.db.PingbackSQLiteDataSource.getAllForStart(Unknown Source:16)
        at org.qiyi.android.pingback.internal.db.PingbackRepository.getAllForStart(Unknown Source:2)
        at org.qiyi.android.pingback.PingbackManagerInternal.getPendingPingbacks(Unknown Source:32)
        at org.qiyi.android.pingback.PingbackManagerInternal.preparePingbacks(Unknown Source:0)
        at org.qiyi.android.pingback.PingbackManagerInternal.c(Unknown Source:0)
        at org.qiyi.android.pingback.PingbackManagerInternal$3.run(Unknown Source:96)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-09-02 19:14:08.490 18289-18332/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.NoSuchFieldError: No field mDataSourceAvailable of type Z in class Lorg/qiyi/android/pingback/internal/db/PingbackSQLiteDataSource; or its superclasses (declaration of 'org.qiyi.android.pingback.internal.db.PingbackSQLiteDataSource' appears in /data/data/com.qiyi.video.speaker/tinker/patch-bde5444b/dex/tinker_classN.apk!classes4.dex)
        at org.qiyi.android.pingback.internal.db.PingbackSQLiteDataSource.getAllForStart(Unknown Source:16)
        at org.qiyi.android.pingback.internal.db.PingbackRepository.getAllForStart(Unknown Source:2)
        at org.qiyi.android.pingback.PingbackManagerInternal.getPendingPingbacks(Unknown Source:32)
        at org.qiyi.android.pingback.PingbackManagerInternal.preparePingbacks(Unknown Source:0)
        at org.qiyi.android.pingback.PingbackManagerInternal.c(Unknown Source:0)
        at org.qiyi.android.pingback.PingbackManagerInternal$3.run(Unknown Source:96)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by torv** [comment]
R8的问题，gradle.properties添加：
gradle.properties

**Comment by SharksLee** [comment]
> R8的问题，gradle.properties添加：
> gradle.properties

是加这个么?android.enableR8 = true
