### ISSUE TITLE
Tinker1.9.14，使用了360加固，补丁加载成功后重启crash

### ISSUE THREAD

**Issue by Honjay** [Tencent/tinker#1207]
异常类型：app运行时异常

手机型号：honor V9

手机系统版本：Android9.0

tinker版本：1.9.14

gradle版本：4.1

是否使用热更新SDK：TinkerPatch SDK

系统：Win10

堆栈/日志：
java.lang.IllegalAccessError: Illegal class access: '包名.view.DecorationMainActivity' attempting to access '包名.view.DecorationMainActivity$1' (declaration of '包名.view.DecorationMainActivity' appears in /data/user/0/包名/tinker/patch-0150c827/dex/changed_classes.dex.jar)
                                                                         at 包名.view.DecorationMainActivity.<init>(DecorationMainActivity.java:112)
                                                                         at java.lang.Class.newInstance(Native Method)
                                                                         at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
                                                                         at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
                                                                         at com.tencent.tinker.loader.hotplug.interceptor.TinkerHackInstrumentation.newActivity(TinkerHackInstrumentation.java:81)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2832)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
                                                                         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                         at android.os.Looper.loop(Looper.java:193)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6680)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Honjay** [comment]
开启了加固，使用360加固的基准包加载补丁会crash，使用未加固的基准包加载补丁没有crash

**Comment by tomystang** [comment]
这个Activity是通过patch新增的吗？

**Comment by Honjay** [comment]
不是新增的，甚至都没有任何修改

**Comment by tomystang** [comment]
神奇了，你用的是360收费版加固吗？我用基础版测试我的demo是正常的。

**Comment by Honjay** [comment]
我也是用的基础版的。。。刚才重新测试了一下，第一次对代码进行少量修改，补丁加载成功重启没有crash。第二次新增了几个activity和fragment以及一些资源文件，增改了二三十个文件，补丁加载成功后重启就crash了，还是报这个异常。

**Comment by tomystang** [comment]
明白了，看来他们的方案有变化，我再看看吧。

**Comment by tomystang** [comment]
view.DecorationMainActivity$1
这个类有在Application里引用过吗？
另外你的项目的Application用的是Tinker自动生成的还是你们手写的呢？

**Comment by Honjay** [comment]
Application是自动生成的，没有引用这个Activity。另外，回退到1.9.9版本后就没有抛这个异常了。

**Comment by tomystang** [comment]
发下你的邮箱吧，我发个加固过的demo给你，看下在你的机器上这个demo会不会crash。

**Comment by Honjay** [comment]
好的，1020313530@qq.com

**Comment by Honjay** [comment]
![image](https://user-images.githubusercontent.com/19324984/64062826-6eb5bc80-cc1e-11e9-919d-6ee343594499.png)
demo是正常的

**Comment by tomystang** [comment]
嗯……你的App除了tinker之外还用了哪些框架呢？

**Comment by Honjay** [comment]
还有arouter、aspectJ、umeng、eventbus、retrofit2、rxjava2、walle、multidex

**Comment by tomystang** [comment]
嗯嗯，我再构造一个包含这些框架的demo验证一下看看。

**Comment by tomystang** [comment]
确认一个问题哇：确定在没有通过patch新增Activity的情况下也会crash？看你一开始发的堆栈里跑到的应该是启用了通过patch新增Activity才会出现的路径。

**Comment by Honjay** [comment]
有新增Activity的呀，但是报异常的view.DecorationMainActivity不是新增的，并且也没有对这个Activity做修改

**Comment by tomystang** [comment]
好的，明白了。
那全局搜一下 view.DecorationMainActivity$1 这个类看看有没有其他地方引用过？

**Comment by Honjay** [comment]
这个Activity是APP的主界面，只有闪屏页引用到了

**Comment by Honjay** [comment]
补丁的下载、合成、重启都是在这个Activity里面完成的

**Comment by zhx00100** [comment]
借楼咨询一下，应对加固，需开启isProtectedApp=true，也就意味着回退到dexElements方案，在ART上不会有方法内联导致crash的问题吗？是怎么解决的 有大佬知道吗  @tys282000
