### ISSUE TITLE
按照demo集成 报错Tinker Exception:you must install tinker before get tinker sInstance

### ISSUE THREAD

**Issue by awpss** [Tencent/tinker#1211]
异常类型：app运行时异常

手机型号：华为P9plus

手机系统版本 ：Android 8.0

tinker版本：1.9.13

gradle版本：3.1.4

TINKERPATCH_VERSION=1.2.13

是否使用热更新SDK： TinkerPatch SDK 

系统：windows

按照easy-sample 集成 ,
   if (BuildConfig.TINKER_ENABLE) {
                //开始检查是否有补丁，这registerActivityLifecycleCallbacks里配置的是每隔访问3小时服务器是否有更新。
                TinkerPatch.init(this)
                        .reflectPatchLibrary()
                        .setPatchRollbackOnScreenOff(true)
                        .setPatchRestartOnSrceenOff(true)
                        .fetchPatchUpdate(true)
                        .setFetchPatchIntervalByHours(1);

                // 获取当前的补丁版本
                LogUtil.e(TAG, "current patch version is " + TinkerPatch.with().getPatchVersion());

                //每隔3个小时去访问后台时候有更新,通过handler实现轮训的效果
//                TinkerPatch.with().fetchPatchUpdateAndPollWithInterval();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
日志: 
    --------- beginning of crash
2019-09-03 09:57:55.660 12663-12691/abc:patch E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: abc:patch, PID: 12663
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:365)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:you must install tinker before get tinker sInstance
        at com.tencent.tinker.lib.tinker.Tinker.with(SourceFile:104)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(SourceFile:108)
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleWork(SourceFile:156)
        at com.tencent.tinker.lib.util.TinkerJobIntentService$CommandProcessor.doInBackground(SourceFile:425)
        at com.tencent.tinker.lib.util.TinkerJobIntentService$CommandProcessor.doInBackground(SourceFile:408)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784) 
2019-09-03 09:57:55.661 12663-12691/abc:patch E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:365)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:you must install tinker before get tinker sInstance
        at com.tencent.tinker.lib.tinker.Tinker.with(SourceFile:104)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(SourceFile:108)
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleWork(SourceFile:156)
        at com.tencent.tinker.lib.util.TinkerJobIntentService$CommandProcessor.doInBackground(SourceFile:425)
        at com.tencent.tinker.lib.util.TinkerJobIntentService$CommandProcessor.doInBackground(SourceFile:408)
        at android.os.AsyncTask$2.call(AsyncTask.java:345)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:784) 
2019-09-03 09:57:55.744 1139-1861/? W/ActivityManager: Scheduling restart of crashed service abc/com.tencent.tinker.lib.service.TinkerPatchService in 1000ms

**Comment by tomystang** [comment]
Tinker的API设计问题……
TinkerPatch.init(this)这句需要在patch进程里也跑一次，如果你是在AppLike里调用的，而且默认没过滤进程的话应该就没问题了。

**Comment by awpss** [comment]
大佬 这段代码在Applike里调用的，没有过滤任何进程,补丁可以下载,合成就挂了上面的异常,现在有什么方案可以规避这个问题。
尝试用hook的方式 修改了Tinker.sInstalled 值为true ,但是后续也会报错。

**Comment by caocao123** [comment]
tinker版本：1.9.14.5     也有这个问题。
