### ISSUE TITLE
360加固之后，一些代码会导致崩溃，另外isProtectedApp=true的情况

### ISSUE THREAD

**Issue by dyfan** [Tencent/tinker#1212]
异常类型：app运行时异常
手机型号：如:小米8se

手机系统版本：如:Android 9.0

tinker版本：如:1.9.13.2

gradle版本：如:5.1

是否使用热更新SDK：  Bugly SDK

系统：Mac

有2个问题，第一个问题，360加固之后的，补丁包下发成功，合成也成功，但是有部分代码会导致应用崩溃，但是我并没有修改这个类，或者是我修改的这个类的其他地方，但是这个地方就报错，跟踪了一下发现大部分都是内部类导致的。
堆栈日志：
 UncaughtException detected: java.lang.IllegalAccessError: Illegal class access: 'com.xx.fyyyyy.fragment.common.FindFragment' attempting to access 'com.xx.fyyyyy.fragment.common.FindFragment$4' (declaration of 'com.xx.fyyyyy.fragment.common.FindFragment' appears in /data/user/0/com.xx.fyyyyy/tinker/patch-1916b28e/dex/changed_classes2.dex.jar)
        at com.xx.fyyyyy.fragment.common.FindFragment.initView(FindFragment.java:272)
        at com.xx.fyyyyy.fragment.common.FindFragment.onViewCreated(FindFragment.java:150)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1393)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1624)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1689)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3104)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3058)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
        at android.app.Activity.performStart(Activity.java:7479)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3454)
第二个问题：
isProtectedApp=true的情况是不是只能针对加固之后的基准包进行补丁包，现在我们加固和未加固都用的一个基准包，isProtectedApp=true的设置。
isProtectedApp=false的情况是不是只能针对未加固的基准包进行补丁包

**Comment by tomystang** [comment]
第一个问题和 #1207 是一样的，正在排查中；
第二个问题，isProtectedApp=true的时候只能作为加固过的包应用补丁，isProtectedApp=false的时候只能作为未加固的包应用补丁，两种情况共用同一个base包几乎必然会出现跑飞或者类访问异常的crash。

**Comment by dyfan** [comment]
> 第一个问题和 #1207 是一样的，正在排查中；
> 第二个问题，isProtectedApp=true的时候只能作为加固过的包应用补丁，isProtectedApp=false的时候只能作为未加固的包应用补丁，两种情况共用同一个base包几乎必然会出现跑飞或者类访问异常的crash。

谢谢解答疑惑。

**Comment by dyfan** [comment]
@tomystang  还有疑惑，isProtectedApp这个属性是针对补丁包的配置还是基准包的配置
未加固的基准包isProtectedApp=false，补丁包也是isProtectedApp=false？
加固的基准包isProtectedApp=true，补丁包也是isProtectedApp=true？

**Comment by GankLun** [comment]
> 第一个问题和 #1207 是一样的，正在排查中；
> 第二个问题，isProtectedApp=true的时候只能作为加固过的包应用补丁，isProtectedApp=false的时候只能作为未加固的包应用补丁，两种情况共用同一个base包几乎必然会出现跑飞或者类访问异常的crash。

tomystang,你好，我这边也出现了类似#1207 #1212的问题，也是报内部类IllegalAccessError,该内部类是私有的，没有外部类引用。另外我出现crash的情况是，基础包和补丁包产生都基于isProtecedApp=true,然后拿基础包去加固，然后运行加固后的基础包，能正常下载和合成补丁，重启进程加载补丁时报错.但是同样是isProtectedApp=true,拿未加固的基础包去运行，加载同一个补丁，能加载补丁成功生效。

**Comment by jay6780** [comment]
public static void installDexes(Application application, ClassLoader loader, File dexOptDir, List<File> files,
                                    boolean isProtectedApp, boolean useDLC) throws Throwable {
        ShareTinkerLog.i(TAG, "installDexes dexOptDir: " + dexOptDir.getAbsolutePath() + ", dex size:" + files.size());

        if (!files.isEmpty()) {
            files = createSortedAdditionalPathEntries(files);
            ClassLoader classLoader = loader;
            if (Build.VERSION.SDK_INT >= 24 && !isProtectedApp) {
                injectDexesInternal(classLoader, files, dexOptDir);
            }
            //install done
            sPatchDexCount = files.size();
            ShareTinkerLog.i(TAG, "after loaded classloader: " + classLoader + ", dex size:" + sPatchDexCount);

            if (!checkDexInstall(classLoader)) {
                //reset patch dex
                SystemClassLoaderAdder.uninstallPatchDex(classLoader);
                throw new TinkerRuntimeException(ShareConstants.CHECK_DEX_INSTALL_FAIL);
            }
        }
    }   

修改 SystemClassLoaderAdder 类中的代码，使其在 false 时工作
