### ISSUE TITLE
patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail： code: -1

### ISSUE THREAD

**Issue by minhelin** [Tencent/tinker#1219]
异常类型：app运行时异常

手机型号：Honor 10

手机系统版本：Android 9.0

tinker版本：1.9.9

gradle版本：4.6

是否使用热更新SDK：Bugly SDK

系统：windows

堆栈/日志：

09-09 09:37:51.056 21333 21333 I Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
09-09 09:37:51.056 21333 21333 I Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.ruicai.rxdj, main process:true, systemOTA:false, fingerPrint:HONOR/HRY-AL00a/HWHRY-HF:9/HONORHRY-AL00a/9.1.0.226C00:user/release-keys, oatDir:null, useInterpretMode:false
09-09 09:37:51.056 21333 21333 W Tinker.TinkerLoadResult: can't find patch file, is ok, just return
09-09 09:37:51.056 21333 21333 I Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.ruicai.rxdj/tinker, code: -2, cost: 2ms
09-09 09:37:51.056 21333 21333 W Tinker.Tinker: tinker load fail!
09-09 09:37:51.074 21333 21333 I Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
09-09 09:37:51.074 21333 21333 D Tinker.DefaultAppLike: onCreate
09-09 09:37:51.084 21333 21333 I CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@2276fd7
09-09 09:37:51.126 21333 21333 I CrashReport: TINKER_ID:base1.2.3_1
09-09 09:37:51.127 21333 21333 I CrashReport: NEW_TINKER_ID:
09-09 09:37:52.432 21333 21333 W Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.ruicai.rxdj/tinker_temp/temp.apk is not exist, just return
09-09 09:37:54.230 21333 21355 D CrashReport: app version is: [1.2.3.4], [deviceId:null|null|2d3c9facae915603], channel: [null], base tinkerId:[base1.2.3_1], patch tinkerId:[], patch version:[]
09-09 09:37:54.714 21333 21333 D Tinker.TinkerManager: onDownloadSuccess.
09-09 09:37:54.719 21333 21333 D Tinker.TinkerManager: check if has new patch.
09-09 09:37:54.731 21333 21333 D Tinker.TinkerManager: has new patch.
09-09 09:37:54.732 21333 21333 D Tinker.TinkerManager: starting patch.
09-09 09:37:54.733 21333 21333 I Tinker.TinkerPatchListener: receive a patch file: /data/user/0/com.ruicai.rxdj/app_tmpPatch/tmpPatch.apk, file size:4231
09-09 09:37:54.736 21333 21333 I Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /data/user/0/com.ruicai.rxdj/app_tmpPatch/tmpPatch.apk, code: -1

在手机上的现象是下载补丁成功，但是不会生效，不知道这个-1是什么原因，看文档也没有相关错误码的解释及解决方案。。谁能解答下吗

**Comment by minhelin** [comment]
同样的环境，同样的步骤在android7.1（oppo）上没问题，是不是对android版本有要求，没人遇到这个问题吗

**Comment by tomystang** [comment]
patch receive fail: /data/user/0/com.ruicai.rxdj/app_tmpPatch/tmpPatch.apk, code: -1
这个错误码表示在那台机器上tinker被出错保护逻辑禁用了，试试清空app数据，然后重试一次，再看下主进程和patch进程的log？

**Comment by minhelin** [comment]
试了下，卸载后重装再打补丁，当时没生效，报一样的错误，然后我再卸载一次，进入后就生效了，这个tinker被出错保护逻辑禁用什么场景下会发生啊，有什么办法可以避免，不可能让用户卸载重装才能生效。。

**Comment by tomystang** [comment]
看下第一次卸载的时候patch进程有没有打log？（patch进程的log打在logcat里，release包如果有编译时移除logcat的操作要先关掉）

**Comment by minhelin** [comment]
patch进程的tag是什么？之前出现过这种问题吗？

**Comment by minhelin** [comment]
不生效时的log:
09-11 11:38:23.945 29042 29042 D Tinker.TinkerInternals: getCurrentInstructionSet:arm
09-11 11:38:23.945 29042 29042 W Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
09-11 11:38:23.945 29042 29042 D Tinker.TinkerInternals: same fingerprint:HONOR/HRY-AL00a/HWHRY-HF:9/HONORHRY-AL00a/9.1.0.226C00:user/release-keys
09-11 11:38:23.947 29042 29042 W Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_com.ruicai.rxdj count:2
09-11 11:38:23.949 29042 29042 W Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.ruicai.rxdj count:0
09-11 11:38:23.950 29042 29042 W Tinker.TinkerLoader: tryLoadPatchFiles:checkSafeModeCount fail
09-11 11:38:23.950 29042 29042 D Tinker.DefaultAppLike: onBaseContextAttached:
09-11 11:38:23.950 29042 29042 I MultiDex: VM with version 2.1.0 has multidex support
09-11 11:38:23.950 29042 29042 I MultiDex: Installing application
09-11 11:38:23.950 29042 29042 I MultiDex: VM has multidex support, MultiDex support library is disabled.
09-11 11:38:23.952 29042 29042 I Tinker.TinkerPatchListener: application maxMemory:384
09-11 11:38:23.955 29042 29042 W Tinker.Tinker: tinker patch directory: /data/user/0/com.ruicai.rxdj/tinker
09-11 11:38:23.955 29042 29042 I Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
09-11 11:38:23.956 29042 29042 I Tinker.TinkerLoadResult: parseTinkerResult loadCode:-25, process name:com.ruicai.rxdj, main process:true, systemOTA:false, fingerPrint:HONOR/HRY-AL00a/HWHRY-HF:9/HONORHRY-AL00a/9.1.0.226C00:user/release-keys, oatDir:odex, useInterpretMode:false
09-11 11:38:23.956 29042 29042 I Tinker.TinkerLoadResult: parseTinkerResult oldVersion:c38877d5ff3c128f773128ff72cb07c7, newVersion:c38877d5ff3c128f773128ff72cb07c7, current:c38877d5ff3c128f773128ff72cb07c7
09-11 11:38:23.956 29042 29042 I Tinker.TinkerLoadResult: Tinker load have exception loadCode:-25
09-11 11:38:23.957 29042 29042 I Tinker.DefaultLoadReporter: patch loadReporter onLoadException: patch load unCatch exception: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
09-11 11:38:23.959 29042 29042 I Tinker.DefaultLoadReporter: unCaught exception disable tinker forever with sp
09-11 11:38:23.959 29042 29042 E Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:255)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at java.lang.reflect.Method.invoke(Native Method)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:161)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:134)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:152)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at android.app.Application.attach(Application.java:224)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1175)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6688)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at android.app.ActivityThread.access$2000(ActivityThread.java:273)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at android.os.Handler.dispatchMessage(Handler.java:112)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at android.os.Looper.loop(Looper.java:216)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at java.lang.reflect.Method.invoke(Native Method)
09-11 11:38:23.961 29042 29042 E Tinker.DefaultLoadReporter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)



生效时的log
09-11 11:40:01.270 30969 30969 D Tinker.TinkerInternals: getCurrentInstructionSet:arm
09-11 11:40:01.270 30969 30969 W Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
09-11 11:40:01.270 30969 30969 D Tinker.TinkerInternals: same fingerprint:HONOR/HRY-AL00a/HWHRY-HF:9/HONORHRY-AL00a/9.1.0.226C00:user/release-keys
09-11 11:40:01.271 30969 30969 I Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.ruicai.rxdj/tinker/patch.info , oldVer:c38877d5ff3c128f773128ff72cb07c7, newVer:c38877d5ff3c128f773128ff72cb07c7, fingerprint:HONOR/HRY-AL00a/HWHRY-HF:9/HONORHRY-AL00a/9.1.0.226C00:user/release-keys, oatDir:odex
09-11 11:40:01.275 30969 30969 I Tinker.TinkerLoader: tryLoadPatchFiles:success to rewrite patch info, kill other process.
09-11 11:40:01.278 30969 30969 W Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_com.ruicai.rxdj count:0
09-11 11:40:01.282 30969 30969 W Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.ruicai.rxdj count:1
09-11 11:40:01.282 30969 30969 I Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.ruicai.rxdj-oHKy80DEaLS6W7iQ_v2o2A==/base.apk"],nativeLibraryDirectories=[/data/app/com.ruicai.rxdj-oHKy80DEaLS6W7iQ_v2o2A==/lib/arm, /data/app/com.ruicai.rxdj-oHKy80DEaLS6W7iQ_v2o2A==/base.apk!/lib/armeabi, /system/lib, /product/lib]]]
09-11 11:40:01.283 30969 30969 I Tinker.TinkerDexLoader: verify dex file:/data/user/0/com.ruicai.rxdj/tinker/patch-c38877d5/dex/tinker_classN.apk md5, use time: 1
09-11 11:40:01.283 30969 30969 I Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.ruicai.rxdj/tinker/patch-c38877d5/odex, dex size:1
09-11 11:40:01.284 30969 30969 W System  : ClassLoader referenced unknown path: 
09-11 11:40:01.285 30969 30969 W com.ruicai.rxd: Unsupported class loader
09-11 11:40:01.287 30969 30969 W com.ruicai.rxd: Skipping duplicate class check due to unsupported classloader
09-11 11:40:01.290 30969 30969 W com.ruicai.rxd: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
09-11 11:40:01.292 30969 30969 W com.ruicai.rxd: Skipping duplicate class check due to unsupported classloader
09-11 11:40:01.293 30969 30969 I Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/com.ruicai.rxdj/tinker/patch-c38877d5/dex/tinker_classN.apk", zip file "/data/app/com.ruicai.rxdj-oHKy80DEaLS6W7iQ_v2o2A==/base.apk"],nativeLibraryDirectories=[/data/app/com.ruicai.rxdj-oHKy80DEaLS6W7iQ_v2o2A==/lib/arm, /data/app/com.ruicai.rxdj-oHKy80DEaLS6W7iQ_v2o2A==/base.apk!/lib/armeabi, /system/lib, /product/lib]]], dex size:1
09-11 11:40:01.293 30969 30969 W Tinker.ClassLoaderAdder: checkDexInstall result:true
09-11 11:40:01.294 30969 30969 I Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
09-11 11:40:01.294 30969 30969 I Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
09-11 11:40:01.297 30969 30969 D Tinker.DefaultAppLike: onBaseContextAttached:
09-11 11:40:01.298 30969 30969 I MultiDex: VM with version 2.1.0 has multidex support
09-11 11:40:01.298 30969 30969 I MultiDex: Installing application
09-11 11:40:01.298 30969 30969 I MultiDex: VM has multidex support, MultiDex support library is disabled.
09-11 11:40:01.306 30969 30969 I Tinker.TinkerPatchListener: application maxMemory:384
09-11 11:40:01.312 30969 30969 W Tinker.Tinker: tinker patch directory: /data/user/0/com.ruicai.rxdj/tinker
09-11 11:40:01.313 30969 30969 I Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
09-11 11:40:01.314 30969 30969 I Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.ruicai.rxdj, main process:true, systemOTA:false, fingerPrint:HONOR/HRY-AL00a/HWHRY-HF:9/HONORHRY-AL00a/9.1.0.226C00:user/release-keys, oatDir:odex, useInterpretMode:false
09-11 11:40:01.315 30969 30969 I Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:c38877d5ff3c128f773128ff72cb07c7, current:c38877d5ff3c128f773128ff72cb07c7
09-11 11:40:01.316 30969 30969 I Tinker.TinkerLoadResult: oh yeah, tinker load all success
09-11 11:40:01.316 30969 30969 I Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchVersionChanged: patch version change from  to c38877d5ff3c128f773128ff72cb07c7
09-11 11:40:01.318 30969 30969 I Tinker.UpgradePatchRetry: onPatchResetMaxCheck, reset max check to 1
09-11 11:40:01.321 30969 30969 I Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.ruicai.rxdj/tinker, code: 0, cost: 48ms
09-11 11:40:01.325 30969 30969 W Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.ruicai.rxdj count:0
09-11 11:40:01.338 30969 30987 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@62850c4
09-11 11:40:01.340 30969 30987 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@35e4bad
09-11 11:40:01.341 30969 30983 I AwareBitmapCacher: init processName:com.ruicai.rxdj pid=30969 uid=10480
09-11 11:40:01.360 30696 30712 I hwid.persisten: Waiting for a blocking GC ProfileSaver
09-11 11:40:01.367 30969 30969 I Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
09-11 11:40:01.367 30969 30969 D Tinker.DefaultAppLike: onCreate

对比了下生效和不生效时的log，不生效时有个错误禁止了tinker，能看下这个错是什么原因造成的吗
09-11 11:38:23.956 29042 29042 I Tinker.TinkerLoadResult: Tinker load have exception loadCode:-25
09-11 11:38:23.957 29042 29042 I Tinker.DefaultLoadReporter: patch loadReporter onLoadException: patch load unCatch exception: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
09-11 11:38:23.959 29042 29042 I Tinker.DefaultLoadReporter: unCaught exception disable tinker forever with sp

**Comment by minhelin** [comment]
@tomystang 有时间帮看下，麻烦了

**Comment by 1136346879** [comment]
哥们 你最后如何解决的？  我这边 补丁包已下载至本地  然后报这个错 和你的一样 -1

**Comment by actor20170211030627** [comment]
我看了代码, 报错位置是:
https://github.com/Tencent/tinker/blob/d96ae9203e440388635898b50d57a63c49d258b3/tinker-sample-android/app/src/main/java/tinker/sample/android/reporter/SampleLoadReporter.java#L42 这句代码的<code>super.onLoadPatchListenerReceiveFail(patchFile, errorCode);</code>

code=-1这个常量的位置是:
https://github.com/Tencent/tinker/blob/d96ae9203e440388635898b50d57a63c49d258b3/tinker-android/tinker-android-loader/src/main/java/com/tencent/tinker/loader/shareutil/ShareConstants.java#L198

头疼, 接入Tinker浪费了我几天时间, 还没解决问题, 感觉好浪费生命啊, 话说腾讯系的sdk, 文档就不能写的稍微详细一点吗? 国内最烂的了(虽然我是个伸手党, 但还是想吐槽一下...).
