### ISSUE TITLE
Tinker Exception:checkSafeModeCount fail!

### ISSUE THREAD

**Issue by checkming** [Tencent/tinker#1226]
```java
异常类型：app运行时异常

手机型号：MI 8 SE

手机系统版本：Android 9.0

tinker版本：1.9.9

gradle版本：3.4.2

是否使用热更新SDK： 否

系统：Win7

描述:以下日志分为四部分截取，整个操作过程为首次安装基准包，第一次启动APP后闪退,然后两次手动去启动App闪退,最后手动启动成功 可正常打开但没有修复成功。
		第一部分：安装基准包之后第一次打开App闪退后得到的日志（这里还未处理删除补丁之后需马上重启的工作）
		第二部分：手动重启但闪退后得到的日志
		第三部分：与第二部分一样的操作，这里通过Beyond Compare去截取得到有差异的日志
        第四部分: 手动重启，这里App才正常启动了，但并未修复成功的日志
```

堆栈/日志：
### 第一步日志：已经打出了tinker修复成功的日志 isSuccess:true，结果：App闪退(注：提交此issues时还未加上删除补丁之后要马上重启的代码) 修复失败
```java
2019-09-17 14:16:24.489 13200-13200/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/gt.com.zf/tinker
2019-09-17 14:16:24.489 13200-13200/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-09-17 14:16:24.490 13200-13200/? W/Tinker.Tinker: tinker patch directory: /data/user/0/gt.com.zf/tinker
2019-09-17 14:16:24.491 13200-13200/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
2019-09-17 14:16:24.491 13200-13200/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:gt.com.zf, main process:true, systemOTA:false, fingerPrint:Xiaomi/sirius/sirius:9/PKQ1.181121.001/V10.3.1.0.PEBCNXM:user/release-keys, oatDir:null, useInterpretMode:false
2019-09-17 14:16:24.491 13200-13200/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2019-09-17 14:16:24.491 13200-13200/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/gt.com.zf/tinker, code: -2, cost: 1ms
2019-09-17 14:16:24.491 13200-13200/? W/Tinker.Tinker: tinker load fail!
2019-09-17 14:16:24.499 13200-13200/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-09-17 14:16:24.499 13200-13200/? D/Tinker.DefaultAppLike: onCreate
2019-09-17 14:16:26.717 13200-13200/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
2019-09-17 14:16:26.717 13200-13200/? I/Tinker.TinkerPatchService: run patch service by job scheduler.
2019-09-17 14:16:26.718 1462-6025/? I/AutoStartManagerService: MIUILOG- Reject service :Intent { cmp=gt.com.zf/com.tencent.tinker.lib.service.TinkerPatchService$JobServiceRunner } userId : 0 uid : 10218
2019-09-17 14:16:26.719 1462-6025/? D/JobScheduler: Error executing JobStatus{37938d8 #u0a218/-252579085 gt.com.zf/com.tencent.tinker.lib.service.TinkerPatchService$JobServiceRunner u=0 s=10218 TIME=none:+4ms READY}
2019-09-17 14:16:31.724 13200-13200/? I/Tinker.TinkerPatchService: check if patch service is running.
2019-09-17 14:16:31.728 13200-13200/? W/Tinker.TinkerPatchService: patch service is not running, retry with IntentService.
2019-09-17 14:16:31.728 13200-13200/? I/Tinker.TinkerPatchService: run patch service by intent service.
2019-09-17 14:16:31.736 13200-13200/? I/Tinker.TinkerPatchService: successfully start patch service with IntentService.
2019-09-17 14:16:31.780 1462-1532/? I/ActivityManager: Start proc 13249:gt.com.zf:patch/u0a218 for service gt.com.zf/com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner caller=gt.com.zf
2019-09-17 14:16:31.854 13249-13249/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
2019-09-17 14:16:31.854 13249-13249/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-09-17 14:16:31.855 13249-13249/? W/Tinker.Tinker: tinker patch directory: /data/user/0/gt.com.zf/tinker
2019-09-17 14:16:31.855 13249-13249/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
2019-09-17 14:16:31.856 13249-13249/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:gt.com.zf:patch, main process:false, systemOTA:false, fingerPrint:Xiaomi/sirius/sirius:9/PKQ1.181121.001/V10.3.1.0.PEBCNXM:user/release-keys, oatDir:null, useInterpretMode:false
2019-09-17 14:16:31.856 13249-13249/? W/Tinker.TinkerLoadResult: tinker is disable, just return
2019-09-17 14:16:31.856 13249-13249/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/gt.com.zf/tinker, code: -1, cost: 1ms
2019-09-17 14:16:31.856 13249-13249/? W/Tinker.Tinker: tinker load fail!
2019-09-17 14:16:31.858 13249-13249/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-09-17 14:16:31.858 13249-13249/? D/Tinker.DefaultAppLike: onCreate
2019-09-17 14:16:31.860 13249-13264/? I/Tinker.TinkerPatchService: for system version >= Android O, we just ignore increasingPriority job to avoid crash or toasts.
2019-09-17 14:16:31.860 13249-13264/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
2019-09-17 14:16:31.869 13249-13264/? W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/tinker_patch.apk to /data/user/0/gt.com.zf/tinker_temp/temp.apk
2019-09-17 14:16:31.907 13249-13264/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:55138c1b5ae7bcac4b01511b46acc0f2
2019-09-17 14:16:31.908 13249-13264/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/gt.com.zf/tinker/patch.info (No such file or directory)
2019-09-17 14:16:31.908 13249-13264/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/gt.com.zf/tinker/patch.info (No such file or directory)
2019-09-17 14:16:31.909 13249-13264/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/gt.com.zf/tinker/patch-55138c1b
2019-09-17 14:16:31.913 13249-13264/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/tinker_patch.apk size: 711736, dest file: /data/user/0/gt.com.zf/tinker/patch-55138c1b/patch-55138c1b.apk size:711736
2019-09-17 14:16:37.368 13249-13264/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/classes.dex.jar, size: 3467782, use time: 5452
2019-09-17 14:16:39.398 13249-13264/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/classes2.dex.jar, size: 1434142, use time: 2028
2019-09-17 14:16:39.398 13249-13264/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/test.dex.jar
2019-09-17 14:16:39.402 13249-13264/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2019-09-17 14:16:39.626 13249-13264/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/classes2.dex.jar
2019-09-17 14:16:39.628 13249-13264/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/test.dex.jar
2019-09-17 14:16:39.629 13249-13264/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/classes.dex.jar
2019-09-17 14:16:39.633 13249-13264/? I/Tinker.DexDiffPatchInternal: merge classN dex file /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/tinker_classN.apk, result: true, size: 4902354, use: 230ms
2019-09-17 14:16:39.634 13249-13264/? I/Tinker.DexDiffPatchInternal: legal files to do dexopt: [/data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/tinker_classN.apk]
2019-09-17 14:16:39.637 13249-13264/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm
2019-09-17 14:16:39.637 13249-13264/? I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:1, optimizeDexDirectory:/data/user/0/gt.com.zf/tinker/patch-55138c1b/odex/
2019-09-17 14:16:39.638 13249-13264/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/tinker_classN.apk, size: 4902354
2019-09-17 14:16:39.753 13268-13268/? I/dex2oat: /system/bin/dex2oat -j6 --dex-file=/data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/tinker_classN.apk --output-vdex-fd=47 --oat-fd=48 --oat-location=/data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/oat/arm/tinker_classN.odex --compiler-filter=quicken --class-loader-context=&
2019-09-17 14:16:48.160 13249-13264/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/tinker_classN.apk, opt file:/data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/oat/arm/tinker_classN.odex, opt file size: 242088, use time 8522
2019-09-17 14:16:48.161 13249-13264/? I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:16247
2019-09-17 14:16:48.162 13249-13264/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
2019-09-17 14:16:48.164 13249-13264/? I/Tinker.ResDiffPatchInternal: res dir: /data/user/0/gt.com.zf/tinker/patch-55138c1b/res/, meta: resArscMd5:567ceb3d2d6a8dbc3ad1865944082d1e
    arscBaseCrc:1229026169
    pattern:assets/.*
    pattern:resources\.arsc
    pattern:res/.*
    addedSet:assets/only_use_to_test_tinker_resource.txt
    modifiedSet:res/layout/activity_hand_write.xml
    modifiedSet:res/layout/activity_index.xml
2019-09-17 14:16:48.167 13249-13264/? I/Tinker.ResDiffPatchInternal: no large modify or store resources, just return
2019-09-17 14:16:48.634 13249-13264/? I/Tinker.ResDiffPatchInternal: final new resource file:/data/user/0/gt.com.zf/tinker/patch-55138c1b/res/resources.apk, entry count:945, size:3402743
2019-09-17 14:16:48.634 13249-13264/? I/Tinker.ResDiffPatchInternal: recover resource result:true, cost:473
2019-09-17 14:16:48.635 13249-13264/? I/Tinker.DexDiffPatchInternal: raw dex count: 3, dex opt dex count: 1, final wait times: 90
2019-09-17 14:16:48.642 13249-13264/? I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: /data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/oat/arm/tinker_classN.odex, size 242088
2019-09-17 14:16:48.642 13249-13264/? I/Tinker.DexDiffPatchInternal: check dex optimizer file format: tinker_classN.odex, size 242088
2019-09-17 14:16:48.645 13249-13264/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/gt.com.zf/tinker/patch.info , oldVer:, newVer:55138c1b5ae7bcac4b01511b46acc0f2, fingerprint:Xiaomi/sirius/sirius:9/PKQ1.181121.001/V10.3.1.0.PEBCNXM:user/release-keys, oatDir:odex
2019-09-17 14:16:48.648 13249-13264/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
2019-09-17 14:16:48.649 13249-13264/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/emulated/0/tinker_patch.apk, success: true, cost: 16765
2019-09-17 14:16:48.649 13249-13264/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/gt.com.zf/tinker_temp/temp.apk
2019-09-17 14:16:48.671 13200-13286/? I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
    PatchResult: 
    isSuccess:true
    rawPatchFilePath:/storage/emulated/0/tinker_patch.apk
    costTime:16765
    patchVersion:55138c1b5ae7bcac4b01511b46acc0f2
     
2019-09-17 14:16:48.678 13200-13286/? W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /storage/emulated/0/tinker_patch.apk
2019-09-17 14:16:48.678 13200-13286/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/tinker_patch.apk

```

### 第二步日志 得到了一些特殊看不懂的日志：fhQCpYfbMcqMihKulUpWcg==/oat/arm/base.odex (offset 60000) (com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached+294)
```java
2019-09-17 14:21:09.045 13388-13388/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm
2019-09-17 14:21:09.045 13388-13388/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2019-09-17 14:21:09.048 13388-13388/? D/Tinker.TinkerInternals: same fingerprint:Xiaomi/sirius/sirius:9/PKQ1.181121.001/V10.3.1.0.PEBCNXM:user/release-keys
2019-09-17 14:21:09.048 13388-13388/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/gt.com.zf/tinker/patch.info , oldVer:55138c1b5ae7bcac4b01511b46acc0f2, newVer:55138c1b5ae7bcac4b01511b46acc0f2, fingerprint:Xiaomi/sirius/sirius:9/PKQ1.181121.001/V10.3.1.0.PEBCNXM:user/release-keys, oatDir:odex
2019-09-17 14:21:09.050 13388-13388/? I/Tinker.TinkerLoader: tryLoadPatchFiles:success to rewrite patch info, kill other process.
2019-09-17 14:21:09.052 13388-13388/? W/Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_gt.com.zf count:0
2019-09-17 14:21:09.056 13388-13388/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_gt.com.zf count:1
2019-09-17 14:21:09.056 13388-13388/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk"],nativeLibraryDirectories=[/data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/lib/arm, /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]]
2019-09-17 14:21:09.056 13388-13388/? I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/tinker_classN.apk md5, use time: 0
2019-09-17 14:21:09.057 13388-13388/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/gt.com.zf/tinker/patch-55138c1b/odex, dex size:1
2019-09-17 14:21:09.066 13388-13388/? I/gt.com.zf: Failed to add image file Failed to flatten class loader hierarchy 'Unknown class loader type com.tencent.tinker.loader.AndroidNClassLoader'
2019-09-17 14:21:09.072 13388-13388/? I/Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/gt.com.zf/tinker/patch-55138c1b/dex/tinker_classN.apk", zip file "/data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk"],nativeLibraryDirectories=[/data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/lib/arm, /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]], dex size:1
2019-09-17 14:21:09.072 13388-13388/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
2019-09-17 14:21:09.074 13388-13388/? W/Tinker.ResourcePatcher: try to clear typedArray cache!
2019-09-17 14:21:09.074 13388-13388/? I/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
2019-09-17 14:21:09.074 13388-13388/? I/Tinker.ResourceLoader: monkeyPatchExistingResources resource file:/data/user/0/gt.com.zf/tinker/patch-55138c1b/res/resources.apk, use time: 2
2019-09-17 14:21:09.074 13388-13388/? I/Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
2019-09-17 14:21:09.075 13388-13388/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
2019-09-17 14:21:09.077 13388-13388/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-09-17 14:21:09.079 13388-13388/? A/gt.com.zf: entrypoint_utils-inl.h:94] Inlined method resolution crossed dex file boundary: from void com.tencent.tinker.lib.tinker.Tinker$Builder.<init>(android.content.Context) in /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk/0xe8324990 to java.io.File com.tencent.tinker.loader.shareutil.SharePatchFileUtil.getPatchDirectory(android.content.Context) in /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk/0xe8323420. This must be due to duplicate classes or playing wrongly with class loaders
2019-09-17 14:21:09.088 13388-13388/? A/gt.com.zf: entrypoint_utils-inl.h:94] Inlined method resolution crossed dex file boundary: from void com.tencent.tinker.lib.tinker.Tinker$Builder.<init>(android.content.Context) in /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk/0xe8324990 to java.io.File com.tencent.tinker.loader.shareutil.SharePatchFileUtil.getPatchDirectory(android.content.Context) in /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk/0xe8323420. This must be due to duplicate classes or playing wrongly with class loaders
2019-09-17 14:21:09.368 13388-13388/? A/gt.com.zf: runtime.cc:562] #19 pc 000c82f5  /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/oat/arm/base.odex (offset 60000) (com.tencent.tinker.lib.tinker.Tinker$Builder.<init>+1756)
2019-09-17 14:21:09.368 13388-13388/? A/gt.com.zf: runtime.cc:562] #20 pc 000c928f  /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/oat/arm/base.odex (offset 60000) (com.tencent.tinker.lib.tinker.TinkerInstaller.install+102)
2019-09-17 14:21:09.369 13388-13388/? A/gt.com.zf: runtime.cc:562] #28 pc 0049a69e  /data/data/gt.com.zf/tinker/patch-55138c1b/dex/oat/arm/tinker_classN.vdex (com.gt.law.tinker.TinkerManager.installedTinker+18)
2019-09-17 14:21:09.369 13388-13388/? A/gt.com.zf: runtime.cc:562] #40 pc 0049a63a  /data/data/gt.com.zf/tinker/patch-55138c1b/dex/oat/arm/tinker_classN.vdex (com.gt.law.tinker.App.onBaseContextAttached+12)
2019-09-17 14:21:09.369 13388-13388/? A/gt.com.zf: runtime.cc:562] #52 pc 000cc6c7  /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/oat/arm/base.odex (offset 60000) (com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached+294)
2019-09-17 14:21:09.369 13388-13388/? A/gt.com.zf: runtime.cc:562] #53 pc 000cc9dd  /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/oat/arm/base.odex (offset 60000) (com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext+428)
2019-09-17 14:21:09.466 13406-13406/? A/DEBUG: Abort message: 'entrypoint_utils-inl.h:94] Inlined method resolution crossed dex file boundary: from void com.tencent.tinker.lib.tinker.Tinker$Builder.<init>(android.content.Context) in /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk/0xe8324990 to java.io.File com.tencent.tinker.loader.shareutil.SharePatchFileUtil.getPatchDirectory(android.content.Context) in /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/base.apk/0xe8323420. This must be due to duplicate classes or playing wrongly with class loaders'
2019-09-17 14:21:09.752 13406-13406/? A/DEBUG:     #19 pc 000c82f5  /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/oat/arm/base.odex (offset 0x60000) (com.tencent.tinker.lib.tinker.Tinker$Builder.<init>+1756)
2019-09-17 14:21:09.752 13406-13406/? A/DEBUG:     #20 pc 000c928f  /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/oat/arm/base.odex (offset 0x60000) (com.tencent.tinker.lib.tinker.TinkerInstaller.install+102)
2019-09-17 14:21:09.752 13406-13406/? A/DEBUG:     #28 pc 0049a69e  /data/data/gt.com.zf/tinker/patch-55138c1b/dex/oat/arm/tinker_classN.vdex (com.gt.law.tinker.TinkerManager.installedTinker+18)
2019-09-17 14:21:09.753 13406-13406/? A/DEBUG:     #40 pc 0049a63a  /data/data/gt.com.zf/tinker/patch-55138c1b/dex/oat/arm/tinker_classN.vdex (com.gt.law.tinker.App.onBaseContextAttached+12)
2019-09-17 14:21:09.753 13406-13406/? A/DEBUG:     #52 pc 000cc6c7  /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/oat/arm/base.odex (offset 0x60000) (com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached+294)
2019-09-17 14:21:09.753 13406-13406/? A/DEBUG:     #53 pc 000cc9dd  /data/app/gt.com.zf-fhQCpYfbMcqMihKulUpWcg==/oat/arm/base.odex (offset 0x60000) (com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext+428)
```

### 第三步日志 与第二部分日志相同，这里不同的部分提示成功重写了补丁信息tryLoadPatchFiles:success to rewrite patch info, kill other process.

```java
2019-09-17 14:21:09.048 13388-13388/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/gt.com.zf/tinker/patch.info , oldVer:55138c1b5ae7bcac4b01511b46acc0f2, newVer:55138c1b5ae7bcac4b01511b46acc0f2, fingerprint:Xiaomi/sirius/sirius:9/PKQ1.181121.001/V10.3.1.0.PEBCNXM:user/release-keys, oatDir:odex
2019-09-17 14:21:09.050 13388-13388/? I/Tinker.TinkerLoader: tryLoadPatchFiles:success to rewrite patch info, kill other process.
```

### 第四步日志 TinkerRuntimeException 提示Tinker Exception:checkSafeModeCount fail
查看了其它类似情况的issues [#1219 ](https://github.com/Tencent/tinker/issues/1219) 
```java
2019-09-17 14:26:19.797 13479-13479/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2019-09-17 14:26:19.798 13479-13479/? E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:79)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:3)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:4)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:3)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:3)
        at android.app.Application.attach(Application.java:215)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6815)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by checkming** [comment]
与[1070]的情况类似，试试后再决定是否关闭此issues(https://github.com/Tencent/tinker/issues/1070)

**Comment by checkming** [comment]
遇到此问题的小伙伴可在[#1114](https://github.com/Tencent/tinker/issues/1114)找到解决方法，竟然是因为不给自启动权限就无法拉起任何后台进程，所以导致修复失败....
