### ISSUE TITLE
使用bugly后台下发补丁出现问题

### ISSUE THREAD

**Issue by CK875430315** [Tencent/tinker#1238]
异常类型：bugly后台拉取补丁异常

手机型号：魅族15

手机系统版本：android7.1.1

tinker版本：1.9.14

gradle版本：4.10.1-all

是否使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK

系统：win7

依赖：

    api 'com.tencent.bugly:crashreport_upgrade:latest.release'
    //其中latest.release指代最新版本号，也可以指定明确的版本号，例如1.2.0
    api 'com.tencent.bugly:nativecrashreport:latest.release'

    annotationProcessor("com.tencent.tinker:tinker-android-anno:1.9.14") { changing = true }
    compileOnly("com.tencent.tinker:tinker-android-anno:1.9.14") { changing = true }
    api("com.tencent.tinker:tinker-android-lib:1.9.14") { changing = true }
    implementation "com.android.support:multidex:1.0.1"

2019-09-23 14:42:40.142 26012-26012/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.xxx.xxx/tinker
2019-09-23 14:42:40.148 26012-26012/? I/Tinker.TinkerPatchListener: application maxMemory:256
2019-09-23 14:42:40.150 26012-26012/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
2019-09-23 14:42:40.151 26012-26012/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14
2019-09-23 14:42:40.151 26012-26012/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.xxx.xxx, main process:true, systemOTA:false, fingerPrint:Meizu/meizu_15_CN/15:7.1.1/NGI77B/1555472313:user/release-keys, oatDir:null, useInterpretMode:false
2019-09-23 14:42:40.151 26012-26012/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2019-09-23 14:42:40.151 26012-26012/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -2, cost: 3ms
2019-09-23 14:42:40.151 26012-26012/? W/Tinker.Tinker: tinker load fail!
2019-09-23 14:42:40.168 26012-26012/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-09-23 14:42:40.203 26012-26012/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@39ab71a
2019-09-23 14:42:40.214 26028-26028/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.xxx.xxx/tinker
2019-09-23 14:42:40.220 26028-26028/? I/Tinker.TinkerPatchListener: application maxMemory:256
2019-09-23 14:42:40.221 26028-26028/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
2019-09-23 14:42:40.221 26028-26028/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14
2019-09-23 14:42:40.222 26028-26028/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.hljt.yrz:pushservice, main process:false, systemOTA:false, fingerPrint:Meizu/meizu_15_CN/15:7.1.1/NGI77B/1555472313:user/release-keys, oatDir:null, useInterpretMode:false
2019-09-23 14:42:40.222 26028-26028/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2019-09-23 14:42:40.222 26028-26028/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -2, cost: 2ms
2019-09-23 14:42:40.222 26028-26028/? W/Tinker.Tinker: tinker load fail!
2019-09-23 14:42:40.232 26028-26028/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-09-23 14:42:40.240 26012-26012/? W/CrashReport: [patch] tinker new id is null ,so patch version is invalid
2019-09-23 14:42:40.241 26012-26012/? I/CrashReport: TINKER_ID:base-1.9
2019-09-23 14:42:40.241 26012-26012/? I/CrashReport: NEW_TINKER_ID:
2019-09-23 14:42:40.243 26012-26012/? W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(TinkerApplicationInlineFence.java:99)
2019-09-23 14:42:40.243 26012-26012/? W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreate(TinkerApplicationInlineFence.java:110)
2019-09-23 14:42:40.243 26012-26012/? W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:153)
2019-09-23 14:42:40.257 26028-26028/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@d84fbd3
2019-09-23 14:42:40.296 26028-26028/? W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(TinkerApplicationInlineFence.java:99)
2019-09-23 14:42:40.296 26028-26028/? W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreate(TinkerApplicationInlineFence.java:110)
2019-09-23 14:42:40.296 26028-26028/? W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:153)
2019-09-23 14:42:40.371 26028-26028/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2019-09-23 14:42:40.419 26077-26077/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.xxx.xxx/tinker
2019-09-23 14:42:40.423 26077-26077/? I/Tinker.TinkerPatchListener: application maxMemory:256
2019-09-23 14:42:40.425 26077-26077/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
2019-09-23 14:42:40.426 26077-26077/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14
2019-09-23 14:42:40.426 26077-26077/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.xxx.xxx:core, main process:false, systemOTA:false, fingerPrint:Meizu/meizu_15_CN/15:7.1.1/NGI77B/1555472313:user/release-keys, oatDir:null, useInterpretMode:false
2019-09-23 14:42:40.426 26077-26077/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2019-09-23 14:42:40.427 26077-26077/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -2, cost: 2ms
2019-09-23 14:42:40.427 26077-26077/? W/Tinker.Tinker: tinker load fail!
2019-09-23 14:42:40.444 26077-26077/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-09-23 14:42:40.468 26077-26077/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@e8bb310
2019-09-23 14:42:40.500 26077-26077/? W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(TinkerApplicationInlineFence.java:99)
2019-09-23 14:42:40.500 26077-26077/? W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreate(TinkerApplicationInlineFence.java:110)
2019-09-23 14:42:40.500 26077-26077/? W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:153)
2019-09-23 14:42:40.628 26077-26077/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2019-09-23 14:42:41.118 26012-26012/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return

**Comment by AndroidFirstDeveloper** [comment]
我遇到这个错误：tinker new id is null ,so patch version is invalid。我的基准包、补丁包生成都是成功的，后来我发现是发布补丁包-下发范围 选择的问题，我开始选择的是"开发设备"，改成"全量设备"就没问题了。
