### ISSUE TITLE
升级1.9.14.3. Android8.1系统打出Release包，启动闪退TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.

### ISSUE THREAD

**Issue by tuke0919** [Tencent/tinker#1258]
**升级1.9.14.3. Android8.1系统打出Release包，启动闪退TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.，但是打出的Debug包无此问题**

```
异常类型：app运行时异常/编译异常

手机型号：Meizu 16

手机系统版本：Android 8.1.0

tinker版本：1.9.14.3

gradle版本：Grade版本5.1.1，AGP版本 3.1.4

是否使用热更新SDK：无其他SDK，直接使用本github接入

系统：Mac

堆栈/日志：
2019-10-18 11:54:11.188 24216-24216/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.netease.vopen.app.VopenApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.
        at android.app.LoadedApk.makeApplication(LoadedApk.java:990)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5919)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6707)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:118)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
        at android.app.Application.attach(Application.java:206)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1105)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1089)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:984)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5919) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6707) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
     Caused by: java.lang.NoSuchMethodException: <init> [int, class java.lang.String, boolean, long, long, class android.content.Intent]
        at java.lang.Class.getConstructor0(Class.java:2320)
        at java.lang.Class.getConstructor(Class.java:1725)
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:111)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146) 
        at android.app.Application.attach(Application.java:206) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1105) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1089) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:984) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5919) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1747) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6707) 
```
问题说明：
1，打出Debug版本包，正常使用热更新
2，使用assameRelease打出Release版本的包，使用adb install 安装到手机上时，启动闪退了，出现“TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.” 异常。看TinkerApplication源码，比之前版本新增
```java
private ITinkerInlineFenceBridge createInlineFence(int tinkerFlags,
                                                       String delegateClassName,
                                                       boolean tinkerLoadVerifyFlag,
                                                       long applicationStartElapsedTime,
                                                       long applicationStartMillisTime,
                                                       Intent resultIntent) {
        try {
            final Class<?> inlineFenceClazz = Class.forName(
                    "com.tencent.tinker.entry.TinkerApplicationInlineFence",
                    true, super.getClassLoader());
            final Constructor<?> ctor = inlineFenceClazz.getConstructor(int.class, String.class,
                    boolean.class, long.class, long.class, Intent.class);
            ctor.setAccessible(true);
            return (ITinkerInlineFenceBridge) ctor.newInstance(tinkerFlags, delegateClassName,
                    tinkerLoadVerifyFlag, applicationStartElapsedTime,
                    applicationStartMillisTime, resultIntent);
        } catch (Throwable thr) {
            throw new TinkerRuntimeException("fail to create inline fence instance.", thr);
        }
    }
```
在打出的Release包里的classes.dex里存在TinkerApplicationInlineFence.class
![image](https://user-images.githubusercontent.com/13417140/67067396-d44b1180-f1a8-11e9-984f-4c70c614c307.png)

在build/intermediates/legacy_multidex_main_dex_list/release下的maindexlist.txt里也有TinkerApplicationInlineFence
![image](https://user-images.githubusercontent.com/13417140/67067484-18d6ad00-f1a9-11e9-9099-4a7e1c321ade.png)

**所以不明白为什么在Android 8.1的系统上，打出的Release包在启动时会load不到TinkerApplicationInlineFence类，但是打出的Debug包却能正常**

**Comment by tuke0919** [comment]
好像是混淆了TinkerApplicationInlineFence的构造函数，构造函数没保存下来，出现的
```java
 Caused by: java.lang.NoSuchMethodException: <init> [int, class java.lang.String, boolean, long, long, class android.content.Intent]
        at java.lang.Class.getConstructor0(Class.java:2320)
```
异常

**Comment by tuke0919** [comment]
问题已解决！在项目的的混淆文件里添加对TinkerApplicationInlineFence的混淆即可：
```java
-keep public class com.tencent.tinker.entry.TinkerApplicationInlineFence {
    <init>(...);
    void attachBaseContext(com.tencent.tinker.loader.app.TinkerApplication, android.content.Context);
}
```
主要原因就是 混淆后TinkerApplicationInlineFence的构造函数没有了，所有在启动时java反射TinkerApplicationInlineFence的构造函数实例化，会出现 
```java
Caused by: java.lang.NoSuchMethodException: <init> [int, class java.lang.String, boolean, long, long, class android.content.Intent]
```
的异常

**Comment by tuke0919** [comment]
但是我觉得这是个普遍问题吧，应该不止我一个人遇到。

**Comment by LiviaGeneral** [comment]
遇到了同样的问题，但是不是在8.1，而是在4.4上面，反射找到不对应的class.有点坑。而且我这儿debug版本都不行.用了楼主相同的混淆方法也不管用

**Comment by LiviaGeneral** [comment]
在6.0 ，8.0,9.0 都没任何问题，却在4.4.2手机上报：Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.TinkerApplicationInlineFence" on path: DexPathList。现在不知道如何下手了，大神有什么好的思路么?

**Comment by tuke0919** [comment]
5.0一下的手机，需要TinkerApplicationInlineFence在maindex里，你看下的apk的classes.dex 是否有这个类

**Comment by tuke0919** [comment]
> 在6.0 ，8.0,9.0 都没发现问题，却在4.4.2手机上报：Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.TinkerApplicationInlineFence" on path: DexPathList。现在不知道如何下手了，大神有什么好的思路么?

5.0以下的手机，需要TinkerApplicationInlineFence在maindex里，你看下的apk的classes.dex 是否有这个类

**Comment by LiviaGeneral** [comment]
已经搞定了，现在补丁包下发不下去，很奇怪，我用的tinker-support:1.1.5，这个有影响不

**Comment by LiviaGeneral** [comment]
> > 在6.0 ，8.0,9.0 都没发现问题，却在4.4.2手机上报：Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.TinkerApplicationInlineFence" on path: DexPathList。现在不知道如何下手了，大神有什么好的思路么?
> 
> 5.0以下的手机，需要TinkerApplicationInlineFence在maindex里，你看下的apk的classes.dex 是否有这个类

添加到maindex中了，运行没问题，现在热更时补丁合并后，5.0以下会crash。错误日志是：
uncaughtException:Class ref in pre-verified class resolved to unexpected implementation
请问这个问题如何解决

**Comment by tuke0919** [comment]
> > > 在6.0 ，8.0,9.0 都没发现问题，却在4.4.2手机上报：Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.TinkerApplicationInlineFence" on path: DexPathList。现在不知道如何下手了，大神有什么好的思路么?
> > 
> > 
> > 5.0以下的手机，需要TinkerApplicationInlineFence在maindex里，你看下的apk的classes.dex 是否有这个类
> 
> 添加到maindex中了，运行没问题，现在热更时补丁合并后，5.0以下会crash。错误日志是：
> uncaughtException:Class ref in pre-verified class resolved to unexpected implementation
> 请问这个问题如何解决

这个应该不是tinker的错，是不是使用了某插件框架
我看网上说的：
https://blog.csdn.net/berber78/article/details/41721877
https://blog.csdn.net/iamcxl369/article/details/78428593
