### ISSUE TITLE
Gradle编译1.7.0过程中类重复：java.util.zip.ZipException: duplicate entry: META-INF/services/javax.annotation.processing.Processor

### ISSUE THREAD

**Issue by iceAnson** [Tencent/tinker#127]
集成完1.6.2到项目后，测试成功；
修改1.6.2.为1.7.0--》gradle clean aR-->build过程中报如下错误：
:app:prepareComGoogleAndroidGmsPlayServicesAppinvite920Library
:app:prepareComGoogleAndroidGmsPlayServicesAuth920Library
:app:prepareComGoogleAndroidGmsPlayServicesAuthBase920Library
:app:prepareComGoogleAndroidGmsPlayServicesBase920Library
:app:prepareComGoogleAndroidGmsPlayServicesBasement920Library
:app:prepareComGoogleAndroidGmsPlayServicesCast920Library
:app:prepareComGoogleAndroidGmsPlayServicesCastFramework920Library
:app:prepareComGoogleAndroidGmsPlayServicesClearcut920Library
:app:prepareComGoogleAndroidGmsPlayServicesContextmanager920Library
:app:prepareComGoogleAndroidGmsPlayServicesDrive920Library
:app:prepareComGoogleAndroidGmsPlayServicesFitness920Library
:app:prepareComGoogleAndroidGmsPlayServicesGames920Library
:app:prepareComGoogleAndroidGmsPlayServicesGass920Library
:app:prepareComGoogleAndroidGmsPlayServicesGcm920Library
:app:prepareComGoogleAndroidGmsPlayServicesIdentity920Library
:app:prepareComGoogleAndroidGmsPlayServicesIid920Library
:app:prepareComGoogleAndroidGmsPlayServicesLocation920Library
:app:prepareComGoogleAndroidGmsPlayServicesMaps920Library
:app:prepareComGoogleAndroidGmsPlayServicesNearby920Library
:app:prepareComGoogleAndroidGmsPlayServicesPanorama920Library
:app:prepareComGoogleAndroidGmsPlayServicesPlaces920Library
:app:prepareComGoogleAndroidGmsPlayServicesPlus920Library
:app:prepareComGoogleAndroidGmsPlayServicesSafetynet920Library
:app:prepareComGoogleAndroidGmsPlayServicesTagmanager920Library
:app:prepareComGoogleAndroidGmsPlayServicesTagmanagerApi920Library
:app:prepareComGoogleAndroidGmsPlayServicesTasks920Library
:app:prepareComGoogleAndroidGmsPlayServicesVision920Library
:app:prepareComGoogleAndroidGmsPlayServicesWallet920Library
:app:prepareComGoogleAndroidGmsPlayServicesWearable920Library
:app:prepareComGoogleFirebaseFirebaseAnalytics920Library
:app:prepareComGoogleFirebaseFirebaseAnalyticsImpl920Library
:app:prepareComGoogleFirebaseFirebaseAuth920Library
:app:prepareComGoogleFirebaseFirebaseAuthCommon920Library
:app:prepareComGoogleFirebaseFirebaseAuthModule920Library
:app:prepareComGoogleFirebaseFirebaseCommon920Library
:app:prepareComGoogleFirebaseFirebaseConfig920Library
:app:prepareComGoogleFirebaseFirebaseCrash920Library
:app:prepareComGoogleFirebaseFirebaseDatabase920Library
:app:prepareComGoogleFirebaseFirebaseDatabaseConnection920Library
:app:prepareComGoogleFirebaseFirebaseIid920Library
:app:prepareComGoogleFirebaseFirebaseMessaging920Library
:app:prepareComGoogleFirebaseFirebaseStorage920Library
:app:prepareComGoogleFirebaseFirebaseStorageCommon920Library
:app:prepareComMakeramenRoundedimageview221Library
:app:prepareComMeiyouAd_sdk202TestSNAPSHOTLibrary
:app:prepareComMeiyouAppCommon202TestSNAPSHOTLibrary
:app:prepareComMeiyouBrand202TestSNAPSHOTLibrary
:app:prepareComMeiyouCalendar202TestSNAPSHOTLibrary
:app:prepareComMeiyouChartview202TestSNAPSHOTLibrary
:app:prepareComMeiyouCommunity202TestSNAPSHOTLibrary
:app:prepareComMeiyouEcolib202TestSNAPSHOTLibrary
:app:prepareComMeiyouEcoucoin202TestSNAPSHOTLibrary
:app:prepareComMeiyouFrameworkBiz202TestSNAPSHOTLibrary
:app:prepareComMeiyouFrameworkCameraLib009SNAPSHOTLibrary
:app:prepareComMeiyouFrameworkDaemon202TestSNAPSHOTLibrary
:app:prepareComMeiyouFrameworkNetworktool202TestSNAPSHOTLibrary
:app:prepareComMeiyouFrameworkShare202TestSNAPSHOTLibrary
:app:prepareComMeiyouFrameworkUi202TestSNAPSHOTLibrary
:app:prepareComMeiyouFrameworkUriProtocol202TestSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoAnimatedBase0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoAnimatedBaseSupport0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoAnimatedGif0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoAnimatedWebp0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoDrawee0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoDraweePipeline0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoFbcore0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoFrescopainter0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoImagepipeline0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoImagepipelineBase0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoImagepipelineOkhttp30022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouFrescoFrescoWebpsupport0022LinhonghongSNAPSHOTLibrary
:app:prepareComMeiyouPregnancyPregnancyCommon202TestSNAPSHOTLibrary
:app:prepareComMeiyouPregnancyPregnancyHome202TestSNAPSHOTLibrary
:app:prepareComMeiyouPregnancyPregnancyTools202TestSNAPSHOTLibrary
:app:prepareComMeiyouSdkBaseUi202TestSNAPSHOTLibrary
:app:prepareComMeiyouSdkCommon202TestSNAPSHOTLibrary
:app:prepareComMeiyouSdkCore202TestSNAPSHOTLibrary
:app:prepareComMeiyouSdkSwipeback202TestSNAPSHOTLibrary
:app:prepareComMeiyouSlidingmenu202TestSNAPSHOTLibrary
:app:prepareComMeiyouSocket202TestSNAPSHOTLibrary
:app:prepareComMeiyouSupportlib202TestSNAPSHOTLibrary
:app:prepareComTencentBuglyCrashreport230Library
:app:prepareComTencentBuglyNativecrashreport30Library
:app:prepareComTencentTinkerTinkerAndroidLib170Library
:app:prepareComTencentTinkerTinkerAndroidLoader170Library
:app:prepareProductReleaseDependencies
:app:compileProductReleaseAidl
:app:compileProductReleaseRenderscript
:app:mergeProductReleaseAssets
:app:generateProductReleaseResources
:app:mergeProductReleaseResources
:app:processProductReleaseManifest
/Users/mu/PeriodProjectTemp/SeeyouClient/app/src/main/AndroidManifest.xml:45:5-68 Warning:
        Element uses-permission#android.permission.BLUETOOTH at AndroidManifest.xml:45:5-68 duplicated with element declared at AndroidManifest.xml:30:5-67
/Users/mu/PeriodProjectTemp/SeeyouClient/app/src/main/AndroidManifest.xml:57:5-816:19 Warning:
        application@android:theme was tagged at AndroidManifest.xml:57 to replace other declarations but no other declaration present
:app:tinkerProcessProductReleaseManifest
tinker add e8ba0d5 to your AndroidManifest.xml /Users/mu/PeriodProjectTemp/SeeyouClient/app/build/intermediates/manifests/full/product/release/AndroidManifest.xml
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml
:app:processProductReleaseResources
:app:generateProductReleaseSources
:app:compileProductReleaseJavaWithJavac
:app:compileProductReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
collectClassInfo forProtocolShadow
find ProtocolShadow size 0
collectClassInfo forProtocol
get Annotation from Class :PregnancyHomeMainImplement
create file for protocol  PregnancyHomeMainStub
collectClassInfo forProtocolShadow
find ProtocolShadow size 0
collectClassInfo forProtocol
find Protocol size 0
collectClassInfo forProtocolShadow
find ProtocolShadow size 0
collectClassInfo forProtocol
find Protocol size 0
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:app:compileProductReleaseSources
:app:lintVitalProductRelease
:app:transformClassesWithAuxiliaryInjectForProductRelease
[AuxiliaryInject] PreGeneratedPatchDex mode is disabled, skip transforming.
:app:transformClassesWithAuxiliaryInjectForProductRelease FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:transformClassesWithAuxiliaryInjectForProductRelease'.
  
  > java.util.zip.ZipException: duplicate entry: META-INF/services/javax.annotation.processing.Processor
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

已在build.gradle里添加：
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/ASL2.0'
        pickFirst 'META-INF/services/javax.annotation.processing.Processor'
    }
依然无法修复。

**Comment by shwenzhang** [comment]
@iceAnson  使用1.7.1再尝试一下

**Comment by iceAnson** [comment]
刚才使用1.7.1还是如此，没有fix~

**Comment by iceAnson** [comment]
collectClassInfo forProtocol
find Protocol size 0
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:app:compileProductReleaseSources
:app:lintVitalProductRelease
:app:transformClassesWithAuxiliaryInjectForProductRelease
[AuxiliaryInject] PreGeneratedPatchDex mode is disabled, skip transforming.
:app:transformClassesWithAuxiliaryInjectForProductRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithAuxiliaryInjectForProductRelease'.
> java.util.zip.ZipException: duplicate entry: META-INF/services/javax.annotation.processing.Processor

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithAuxiliaryInjectForProductRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:47)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: duplicate entry: META-INF/services/javax.annotation.processing.Processor
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:57)
        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
Caused by: java.util.zip.ZipException: duplicate entry: META-INF/services/javax.annotation.processing.Processor
        at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJarHelper(AuxiliaryClassInjector.java:88)
        at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJar(AuxiliaryClassInjector.java:67)
        at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector$processJar.call(Unknown Source)
        at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform$_transform_closure5.doCall(AuxiliaryInjectTransform.groovy:285)
        at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform.transform(AuxiliaryInjectTransform.groovy:262)
        at com.android.build.gradle.internal.pipeline.TransformTask$3.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$3.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
        ... 77 more


BUILD FAILED

Total time: 1 mins 27.68 secs

**Comment by hemf2010** [comment]
我也遇到了这个问题：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithAuxiliaryInjectForWINBONSDebug'.
> java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml




完整Log：
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithAuxiliaryInjectForWINBONSDebug'.
> java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithAuxiliaryInjectForWINBONSDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:158)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
Caused by: java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml
        at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJarHelper(AuxiliaryClassInjector.java:88)
        at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJar(AuxiliaryClassInjector.java:67)
        at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector$processJar.call(Unknown Source)
        at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform$_transform_closure5.doCall(AuxiliaryInjectTransform.groovy:285)
        at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform.transform(AuxiliaryInjectTransform.groovy:262)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        ... 22 more

已经添加 ->
packagingOptions {
        exclude 'META-INF/maven/com.belerweb/pinyin4j/pom.properties'
        exclude 'META-INF/maven/com.belerweb/pinyin4j/pom.xml'
    }

请问现在有没有解决方案？

**Comment by shwenzhang** [comment]
尝试用dev的localmaven，这个问题应该已经解决

**Comment by TracyZhangLei** [comment]
@shwenzhang 有1.7.2的发布计划么？目前使用本地的patch-plugin也不行．

**Comment by JayRichrd** [comment]
> 我也遇到了这个问题：
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:transformClassesWithAuxiliaryInjectForWINBONSDebug'.
>   > java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml
> 
> 完整Log：
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:transformClassesWithAuxiliaryInjectForWINBONSDebug'.
>   > java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml
> * Try:
>   Run with --info or --debug option to get more log output.
> * Exception is:
>   org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithAuxiliaryInjectForWINBONSDebug'.
>   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
>   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
>   at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
>   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
>   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
>   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
>   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
>   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
>   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
>   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
>   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
>   at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
>   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
>   at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
>   Caused by: java.lang.RuntimeException: java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml
>   at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
>   at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:158)
>   at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
>   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
>   at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
>   at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
>   at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
>   at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
>   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
>   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
>   ... 14 more
>   Caused by: java.util.zip.ZipException: duplicate entry: META-INF/maven/com.belerweb/pinyin4j/pom.xml
>   at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJarHelper(AuxiliaryClassInjector.java:88)
>   at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJar(AuxiliaryClassInjector.java:67)
>   at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector$processJar.call(Unknown Source)
>   at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform$_transform_closure5.doCall(AuxiliaryInjectTransform.groovy:285)
>   at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform.transform(AuxiliaryInjectTransform.groovy:262)
>   at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
>   at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
>   at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
>   ... 22 more
> 
> 已经添加 ->
> packagingOptions {
> exclude 'META-INF/maven/com.belerweb/pinyin4j/pom.properties'
> exclude 'META-INF/maven/com.belerweb/pinyin4j/pom.xml'
> }
> 
> 请问现在有没有解决方案？

请问你是项目的app/build.gradle中添加的：
 packagingOptions {
 exclude 'META-INF/maven/com.belerweb/pinyin4j/pom.properties'
 exclude 'META-INF/maven/com.belerweb/pinyin4j/pom.xml'
 }嘛？
