### ISSUE TITLE
补丁包合成成功，但加载失败 checkDexInstall failed

### ISSUE THREAD

**Issue by chrisLeeCreate** [Tencent/tinker#1291]
## Issue/提问须知
已经查看了相关问题，未见明确解决方案。

异常类型：补丁包合成成功，但加载失败

手机型号：如:HUAWEI/ELE-AL00

手机系统版本：如:Android 10.0

tinker版本：如1.9.14.3 

gradle版本：如:3.0.1

是否使用热更新SDK： 没有
系统：Mac

堆栈/日志：
1. 如是编译异常，请在执行gradle命令时，加上--stacktrace;
2. 日志我们需要过滤"Tinker."关键字;
3. 对于合成失败的情况，请给出:patch进程的日志,这里需要将Android Moniter右上角设为No Filter。
2019-11-29 17:06:44.088 24334-24334/com.xes.jazhanghui.activity W/Tinker.TinkerLoader: found clean patch mark and we are in main process, delete patch file now.
2019-11-29 17:06:44.088 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xes.jazhanghui.activity/tinker/patch-4c138d4a/patch-4c138d4a.apk
2019-11-29 17:06:44.089 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xes.jazhanghui.activity/tinker/patch-4c138d4a/dex/oat/tinker_classN.apk.cur.prof
2019-11-29 17:06:44.089 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xes.jazhanghui.activity/tinker/patch-4c138d4a/dex/oat
2019-11-29 17:06:44.089 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xes.jazhanghui.activity/tinker/patch-4c138d4a/dex/tinker_classN.apk
2019-11-29 17:06:44.096 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xes.jazhanghui.activity/tinker/patch-4c138d4a/dex
2019-11-29 17:06:44.097 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xes.jazhanghui.activity/tinker/patch-4c138d4a/odex
2019-11-29 17:06:44.097 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xes.jazhanghui.activity/tinker/patch-4c138d4a/res/resources.apk
2019-11-29 17:06:44.111 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xes.jazhanghui.activity/tinker/patch-4c138d4a/res
2019-11-29 17:06:44.111 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xes.jazhanghui.activity/tinker/patch-4c138d4a
2019-11-29 17:06:44.111 24334-24334/com.xes.jazhanghui.activity I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.xes.jazhanghui.activity/tinker/patch.info , oldVer:, newVer:, isProtectedApp:0, isRemoveNewVersion:0, fingerprint:HUAWEI/ELE-AL00/HWELE:10/HUAWEIELE-AL00/10.0.0.173C00:user/release-keys, oatDir:odex
2019-11-29 17:06:44.116 24334-24334/com.xes.jazhanghui.activity W/Tinker.PatchInfo: path info file  corrupted:/data/user/0/com.xes.jazhanghui.activity/tinker/patch.info
2019-11-29 17:06:44.118 24334-24334/com.xes.jazhanghui.activity W/Tinker.PatchInfo: path info file  corrupted:/data/user/0/com.xes.jazhanghui.activity/tinker/patch.info
2019-11-29 17:06:44.126 24334-24334/com.xes.jazhanghui.activity D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-11-29 17:06:45.143 24374-24374/com.xes.jazhanghui.activity:GuardService D/Tinker.TinkerLoader: tryLoad test test
2019-11-29 17:06:45.145 24374-24374/com.xes.jazhanghui.activity:GuardService W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/com.xes.jazhanghui.activity/tinker/patch.info
2019-11-29 17:06:45.153 24374-24374/com.xes.jazhanghui.activity:GuardService D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-11-29 17:06:45.188 24374-24374/com.xes.jazhanghui.activity:GuardService E/RePlugin.PluginInfoList: load: Load error!
    java.io.FileNotFoundException: File '/data/user/0/com.xes.jazhanghui.activity/app_p_a/p.l' does not exist
        at com.qihoo360.replugin.utils.FileUtils.openInputStream(FileUtils.java:99)
        at com.qihoo360.replugin.utils.FileUtils.readFileToString(FileUtils.java:359)
        at com.qihoo360.replugin.model.PluginInfoList.load(PluginInfoList.java:71)
        at com.qihoo360.replugin.packages.PluginManagerServer.loadLocked(PluginManagerServer.java:100)
        at com.qihoo360.replugin.packages.PluginManagerServer.access$300(PluginManagerServer.java:58)
        at com.qihoo360.replugin.packages.PluginManagerServer$Stub.load(PluginManagerServer.java:623)
        at com.qihoo360.replugin.packages.PluginManagerProxy.load(PluginManagerProxy.java:91)
        at com.qihoo360.loader2.PmBase.initForServer(PmBase.java:321)
        at com.qihoo360.loader2.PmBase.init(PmBase.java:268)
        at com.qihoo360.loader2.PMF.init(PMF.java:72)
        at com.qihoo360.replugin.RePlugin$App.attachBaseContext(RePlugin.java:985)
        at com.xes.jazhanghui.activity.app.XesAPP.onBaseContextAttached(XesAPP.java:257)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.attachBaseContextImpl_$noinline$(TinkerApplicationInlineFence.java:79)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.attachBaseContext(TinkerApplicationInlineFence.java:86)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:130)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
        at com.xes.jazhanghui.activity.app.XesApplication.attachBaseContext(Unknown Source:3)
        at android.app.Application.attach(Application.java:358)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1161)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7142)
        at android.app.ActivityThread.access$2200(ActivityThread.java:292)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2195)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by chrisLeeCreate** [comment]
堆栈填写错误
