### ISSUE TITLE
补丁合成成功，但是没生效，Tinker Exception:checkDexInstall failed

### ISSUE THREAD

**Issue by chrisLeeCreate** [Tencent/tinker#1292]
## Issue/提问须知
已经查看了相关问题，未见明确解决方案。

异常类型：补丁包合成成功，但加载失败

手机型号：如:HUAWEI/ELE-AL00

手机系统版本：如:Android 10.0

tinker版本：如1.9.14.3

gradle版本：如:3.0.1

是否使用热更新SDK： 没有
系统：Mac
堆栈/日志：
1. 如是编译异常，请在执行gradle命令时，加上--stacktrace;
2. 日志我们需要过滤"Tinker."关键字;
3. 对于合成失败的情况，请给出:patch进程的日志,这里需要将Android Moniter右上角设为No Filter。
2019-11-29 17:12:19.240 26545-26545/com.xes.jazhanghui.activity:GuardService I/Tinker.SamplePatchListener: application maxMemory:384
2019-11-29 17:12:19.242 26545-26545/com.xes.jazhanghui.activity:GuardService W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xes.jazhanghui.activity/tinker
2019-11-29 17:12:19.243 26545-26545/com.xes.jazhanghui.activity:GuardService I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2019-11-29 17:12:19.244 26545-26545/com.xes.jazhanghui.activity:GuardService I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-5, process name:com.xes.jazhanghui.activity:GuardService, main process:false, systemOTA:false, fingerPrint:HUAWEI/ELE-AL00/HWELE:10/HUAWEIELE-AL00/10.0.0.173C00:user/release-keys, oatDir:odex, useInterpretMode:false
2019-11-29 17:12:19.244 26545-26545/com.xes.jazhanghui.activity:GuardService I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:4c138d4a904e604e9a18b32d7a1c84c3, current:
2019-11-29 17:12:19.244 26545-26545/com.xes.jazhanghui.activity:GuardService E/Tinker.TinkerLoadResult: path info blank, wait main process to restart
2019-11-29 17:12:19.244 26545-26545/com.xes.jazhanghui.activity:GuardService I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xes.jazhanghui.activity/tinker, code: -5, cost: 3ms
2019-11-29 17:12:19.244 26545-26545/com.xes.jazhanghui.activity:GuardService W/Tinker.Tinker: tinker load fail!
2019-11-29 17:12:19.248 26545-26545/com.xes.jazhanghui.activity:GuardService I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-11-29 17:12:19.248 26545-26545/com.xes.jazhanghui.activity:GuardService D/Tinker.DefaultAppLike: onCreate
2019-11-29 17:12:19.264 26545-26545/com.xes.jazhanghui.activity:GuardService W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2019-11-29 17:12:19.276 26504-26504/com.xes.jazhanghui.activity I/Tinker.SamplePatchListener: application maxMemory:384
2019-11-29 17:12:19.278 26504-26504/com.xes.jazhanghui.activity W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xes.jazhanghui.activity/tinker
2019-11-29 17:12:19.279 26504-26504/com.xes.jazhanghui.activity I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2019-11-29 17:12:19.280 26504-26504/com.xes.jazhanghui.activity I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14, process name:com.xes.jazhanghui.activity, main process:true, systemOTA:false, fingerPrint:HUAWEI/ELE-AL00/HWELE:10/HUAWEIELE-AL00/10.0.0.173C00:user/release-keys, oatDir:odex, useInterpretMode:false
2019-11-29 17:12:19.280 26504-26504/com.xes.jazhanghui.activity I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:4c138d4a904e604e9a18b32d7a1c84c3, current:4c138d4a904e604e9a18b32d7a1c84c3
2019-11-29 17:12:19.280 26504-26504/com.xes.jazhanghui.activity I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
2019-11-29 17:12:19.280 26504-26504/com.xes.jazhanghui.activity E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
2019-11-29 17:12:19.284 26504-26504/com.xes.jazhanghui.activity I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
2019-11-29 17:12:19.284 26504-26504/com.xes.jazhanghui.activity E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2019-11-29 17:12:19.285 26504-26504/com.xes.jazhanghui.activity E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:85)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:194)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:293)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:92)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:126)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
        at com.xes.jazhanghui.activity.app.XesApplication.attachBaseContext(Unknown Source:3)
        at android.app.Application.attach(Application.java:358)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1161)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7142)
        at android.app.ActivityThread.access$2200(ActivityThread.java:292)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2195)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
2019-11-29 17:12:19.285 26504-26504/com.xes.jazhanghui.activity I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.xes.jazhanghui.activity/tinker/patch.info , oldVer:, newVer:4c138d4a904e604e9a18b32d7a1c84c3, isProtectedApp:0, isRemoveNewVersion:1, fingerprint:HUAWEI/ELE-AL00/HWELE:10/HUAWEIELE-AL00/10.0.0.173C00:user/release-keys, oatDir:odex
2019-11-29 17:12:19.291 26504-26504/com.xes.jazhanghui.activity I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xes.jazhanghui.activity/tinker, code: -14, cost: 1571ms
2019-11-29 17:12:19.291 26504-26504/com.xes.jazhanghui.activity W/Tinker.Tinker: tinker load fail!
2019-11-29 17:12:19.293 26504-26504/com.xes.jazhanghui.activity W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.xes.jazhanghui.activity count:0
2019-11-29 17:12:19.326 26504-26504/com.xes.jazhanghui.activity I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-11-29 17:12:19.333 26504-26504/com.xes.jazhanghui.activity D/Tinker.DefaultAppLike: onCreate
2019-11-29 17:12:20.394 26612-26612/com.xes.jazhanghui.activity:core D/Tinker.TinkerLoader: tryLoad test test
2019-11-29 17:12:20.398 26612-26612/com.xes.jazhanghui.activity:core W/Tinker.TinkerLoader: tryLoadPatchFiles:version is blank, wait main process to restart
2019-11-29 17:12:20.406 26612-26612/com.xes.jazhanghui.activity:core D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-11-29 17:12:20.450 26612-26612/com.xes.jazhanghui.activity:core I/Tinker.SamplePatchListener: application maxMemory:384
2019-11-29 17:12:20.452 26612-26612/com.xes.jazhanghui.activity:core W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xes.jazhanghui.activity/tinker
2019-11-29 17:12:20.454 26612-26612/com.xes.jazhanghui.activity:core I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2019-11-29 17:12:20.454 26612-26612/com.xes.jazhanghui.activity:core I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-5, process name:com.xes.jazhanghui.activity:core, main process:false, systemOTA:false, fingerPrint:HUAWEI/ELE-AL00/HWELE:10/HUAWEIELE-AL00/10.0.0.173C00:user/release-keys, oatDir:odex, useInterpretMode:false
2019-11-29 17:12:20.455 26612-26612/com.xes.jazhanghui.activity:core I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:4c138d4a904e604e9a18b32d7a1c84c3, current:
2019-11-29 17:12:20.455 26612-26612/com.xes.jazhanghui.activity:core E/Tinker.TinkerLoadResult: path info blank, wait main process to restart
2019-11-29 17:12:20.455 26612-26612/com.xes.jazhanghui.activity:core I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xes.jazhanghui.activity/tinker, code: -5, cost: 4ms
2019-11-29 17:12:20.455 26612-26612/com.xes.jazhanghui.activity:core W/Tinker.Tinker: tinker load fail!
2019-11-29 17:12:20.458 26612-26612/com.xes.jazhanghui.activity:core I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-11-29 17:12:20.458 26612-26612/com.xes.jazhanghui.activity:core D/Tinker.DefaultAppLike: onCreate
2019-11-29 17:12:20.515 26612-26612/com.xes.jazhanghui.activity:core W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2019-11-29 17:12:22.358 26504-26504/com.xes.jazhanghui.activity W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.xes.jazhanghui.activity/tinker_temp/temp.apk is not exist, just return

**Comment by shitouren1994** [comment]
你好请问解决了吗

**Comment by cyf1161265793** [comment]
> 你好请问解决了吗

我也遇到这个问题了，请问你解决了吗？

**Comment by CoderNo89757** [comment]
同样的问题，请问解决了吗？

**Comment by masu123** [comment]
checkDexInstall failed 同样的问题怎么样解决
