### ISSUE TITLE
Service not registered。Bugly后台收集的问题全部是华为手机遇到的

### ISSUE THREAD

**Issue by zhoupeng2** [Tencent/tinker#1299]
异常类型：app运行时异常

手机型号：华为Mate20，华为Mate30、华为 LND-AL40、华为 DUK-AL20、华为LDN-AL00等各种 华为手机。也仅仅在华为手机上遇到过

手机系统版本：如:Android 8.0、9.0、10.0（10版本也会，自己手机是Android 10）

tinker版本：1.9.14.3

gradle版本：4.1

加固方式：360加固

集成方式： gradle依赖

系统：Windows

堆栈/日志：
 java.lang.IllegalArgumentException: Service not registered: com.jg.ids.h@ef968b5
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1755)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1925)
	at com.jg.ids.g.b(SourceFile:46)
	at com.jg.ids.b.a.a(SourceFile:56)
	at com.jg.ids.h.onServiceConnected(SourceFile:15)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1932)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1964)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

----------------------------------------------------------------
Issue #1239 也是同一个问题，有具体的报错类,如下：
java.lang.IllegalArgumentException: Service not registered: com.tencent.tinker.lib.listener.DefaultPatchListener$1@ac52d76

大佬有空，请查看一下，谢谢

**Comment by zhoupeng2** [comment]
@tomystang 大佬有空看看这个问题吗？

**Comment by sonuan** [comment]
遇到了一模一样的问题。问题是我们根本没有‘ com.jg.ids’这个包名相关的类。你那有吗？

**Comment by andyxialm** [comment]
这个问题已确认为 360 加固的问题，可以联系加固宝团队。另外加固宝应该在本月 7 号下午修复了此问题并上线，可以再次验证下。@zhoupeng2

**Comment by zhoupeng2** [comment]
@andyxialm  谢谢解答。

**Comment by hy2012** [comment]
这个和 Issue #1239 不是同一个问题吧， 没有使用 360 加固同样有这个问题。

**Comment by zhoupeng2** [comment]
@hy2012 我用另外一台安装同事加固打包就没这个问题了。很奇怪

**Comment by zhouchuanping** [comment]
也遇到了，最后怎么解决的呀？@zhoupeng2

**Comment by klop78** [comment]
> 这个问题已确认为 360 加固的问题，可以联系加固宝团队。另外加固宝应该在本月 7 号下午修复了此问题并上线，可以再次验证下。@zhoupeng2

这个问题，怎么解决的？
