### ISSUE TITLE
OPPO补丁只生效一次

### ISSUE THREAD

**Issue by po1arbear** [Tencent/tinker#1307]
异常类型：app运行时异常

手机型号：OPPO Reno 10倍变焦版

手机系统版本：Android 9 (ColorOS V6.0)

tinker版本：1.9.13.2

gradle版本：3.2.0

系统：Windows

堆栈/日志：
2019-12-17 10:33:37.667 29832-29832/com.fcbox.hiveconsumer W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/com.fcbox.hiveconsumer/tinker/patch.info
2019-12-17 10:33:37.667 29832-29832/com.fcbox.hiveconsumer D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-12-17 10:33:37.668 29832-29832/com.fcbox.hiveconsumer I/Tinker.SamplePatchListener: application maxMemory:384
2019-12-17 10:33:37.670 29832-29832/com.fcbox.hiveconsumer W/Tinker.Tinker: tinker patch directory: /data/user/0/com.fcbox.hiveconsumer/tinker
2019-12-17 10:33:37.670 29832-29832/com.fcbox.hiveconsumer I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.13.2
2019-12-17 10:33:37.670 29832-29832/com.fcbox.hiveconsumer I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3, process name:com.fcbox.hiveconsumer, main process:true, systemOTA:false, fingerPrint:OPPO/PCCM00/OP46C3:9/PKQ1.190223.001/1571886656:user/release-keys, oatDir:null, useInterpretMode:false
2019-12-17 10:33:37.670 29832-29832/com.fcbox.hiveconsumer W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2019-12-17 10:33:37.671 29832-29832/com.fcbox.hiveconsumer I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.fcbox.hiveconsumer/tinker, code: -3, cost: 2ms
2019-12-17 10:33:37.671 29832-29832/com.fcbox.hiveconsumer W/Tinker.Tinker: tinker load fail!
2019-12-17 10:33:38.187 29832-29832/com.fcbox.hiveconsumer I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-12-17 10:33:38.187 29832-29832/com.fcbox.hiveconsumer D/Tinker.DefaultAppLike: onCreate
2019-12-17 10:33:38.218 29832-29832/com.fcbox.hiveconsumer I/CrashReport: backup java handler: com.fcbox.lib.tinker.a.a@c5fe7ca
2019-12-17 10:33:38.277 29832-29832/com.fcbox.hiveconsumer W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.invokeAppLikeOnCreate(TinkerApplication.java:189)
2019-12-17 10:33:38.277 29832-29832/com.fcbox.hiveconsumer W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:205)
2019-12-17 10:33:38.322 29860-29860/com.fcbox.hiveconsumer:pushservice W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/com.fcbox.hiveconsumer/tinker/patch.info
2019-12-17 10:33:38.323 29860-29860/com.fcbox.hiveconsumer:pushservice D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-12-17 10:33:38.327 29860-29860/com.fcbox.hiveconsumer:pushservice I/Tinker.SamplePatchListener: application maxMemory:384
2019-12-17 10:33:38.328 29860-29860/com.fcbox.hiveconsumer:pushservice W/Tinker.Tinker: tinker patch directory: /data/user/0/com.fcbox.hiveconsumer/tinker
2019-12-17 10:33:38.329 29860-29860/com.fcbox.hiveconsumer:pushservice I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.13.2
2019-12-17 10:33:38.329 29860-29860/com.fcbox.hiveconsumer:pushservice I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3, process name:com.fcbox.hiveconsumer:pushservice, main process:false, systemOTA:false, fingerPrint:OPPO/PCCM00/OP46C3:9/PKQ1.190223.001/1571886656:user/release-keys, oatDir:null, useInterpretMode:false
2019-12-17 10:33:38.329 29860-29860/com.fcbox.hiveconsumer:pushservice W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2019-12-17 10:33:38.330 29860-29860/com.fcbox.hiveconsumer:pushservice I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.fcbox.hiveconsumer/tinker, code: -3, cost: 2ms
2019-12-17 10:33:38.330 29860-29860/com.fcbox.hiveconsumer:pushservice W/Tinker.Tinker: tinker load fail!
2019-12-17 10:33:38.332 29860-29860/com.fcbox.hiveconsumer:pushservice I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2019-12-17 10:33:38.333 29860-29860/com.fcbox.hiveconsumer:pushservice D/Tinker.DefaultAppLike: onCreate
2019-12-17 10:33:38.340 29860-29860/com.fcbox.hiveconsumer:pushservice D/Tinker.DefaultAppLike: onTrimMemory level:5
2019-12-17 10:33:38.362 29860-29860/com.fcbox.hiveconsumer:pushservice W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2019-12-17 10:33:38.423 29832-29832/com.fcbox.hiveconsumer D/Tinker.DefaultAppLike: onTrimMemory level:5
2019-12-17 10:33:38.825 29832-29832/com.fcbox.hiveconsumer W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.fcbox.hiveconsumer/tinker_temp/temp.apk is not exist, just return

补丁下载后后成正常，第一次重启后生效。之后重启又无法加载补丁了，目前只再OPPO上发现这个问题。其他机型都正常

**Comment by po1arbear** [comment]
后来又试了几款机型，发现ColorOS 6.0以上存在这个问题

**Comment by po1arbear** [comment]
load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:85)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:194)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:280)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:56)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:173)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:146)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:164)
        at android.app.Application.attach(Application.java:216)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1122)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6339)
        at android.app.ActivityThread.access$1400(ActivityThread.java:221)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7278)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:909)

补丁加载异常

**Comment by po1arbear** [comment]
最终定位到的问题原因是：apk包存在多个dex文件时，ColorOS6.0以上系统tinker补丁有成功回调，但是大概率失效

**Comment by littlegrow** [comment]
> 最终定位到的问题原因是：apk包存在多个dex文件时，ColorOS6.0以上系统tinker补丁有成功回调，但是大概率失效

请问怎么解决这个问题

**Comment by po1arbear** [comment]
> > 最终定位到的问题原因是：apk包存在多个dex文件时，ColorOS6.0以上系统tinker补丁有成功回调，但是大概率失效
> 
> 请问怎么解决这个问题

加固的包只存在一个dex，不会出现这个问题
