### ISSUE TITLE
编译补丁包时候报错：java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by feng19960223** [Tencent/tinker#1319]
异常类型：编译异常

tinker版本：1.9.9

gradle版本：3.20

是否使用热更新SDK： bugly 1.3.6

系统：win7

日志：

D:\work\com.hema58.app.join>gradle buildTinkerPatchRelease --stacktrace
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
Parallel execution is an incubating feature.

> Configure project :app 
TinkerSupport Plugin Version: 1.1.4
        Requires:
                Android Plugin for Gradle, Revision 2.0.0 or higher
        Dependencies:
                Gradle 2.10 or higher (Current Gradle Version: 4.6)

apply plugin: 'com.tencent.tinker.patch'
----------------------tinker build warning ------------------------------------
tinker auto operation:
excluding annotation processor and source template from app packaging. Enable dx jumboMode to reduce package size.
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is booting.
disable archive dex mode so far for keeping dex apply.

tinker will change your build configs:
we will add TINKER_ID=null in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and we will help you to put it in the MultiDexKeepProguardFile.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk!
-----------------------------------------------------------------
----------------------tinker-support build warning ------------------------------------
if you not set autoBackupApkDir we will auto backup the build file to D:\work\com.hema58.app.join\app/tinker.

if overrideTinkerPatchConfiguration is true
we will override tinker patch configuration，you must use tinker-support's configuration

you will find the gen proguard rule file at build/intermediates/bugly_intermediates/bugly_proguard.pro
and we will help you to put it in the proguardFiles.

if enableProxyApplication is true
we will replace you real application to TINKER_PATCH_APPLICATION

if autoGenerateTinkerId is true
we will auto set base tinkerId as versionName.versionCode, like 1.0.1
-----------------------------------------------------------------
------ Tinker Support Override tinkerPatch Configuration ------
tinkerPatch {
        tinkerEnable = true
        oldApk = D:\work\com.hema58.app.join\app\build\bakApk/app-1220-22-34-10/phone_com.hema58.app.join_release_v1.8.1_14.apk
        ignoreWarning = false
        useSign = true
        buildConfig {
                applyMapping = D:\work\com.hema58.app.join\app\build\bakApk/app-1220-22-34-10/app-release-mapping.txt
                applyResourceMapping = D:\work\com.hema58.app.join\app\build\bakApk/app-1220-22-34-10/app-release-R.txt
                tinkerId = 1221-16-40-16
                keepDexApply = false
                isProtectedApp = true
                supportHotplugComponent = true
        }
        dex {
                dexMode = jar
                pattern = [classes*.dex, assets/secondary-dex-?.jar]
                loader = [com.tencent.tinker.loader.*]
        }
        lib {
                 pattern = [lib/*/*.so]
        }
        res {
                 pattern = [res/*, r/*, assets/*, resources.arsc, AndroidManifest.xml]
                 ignoreChange = [assets/*_meta.txt]
                 largeModSize = 100
        }
        packageConfig {
        }
        sevenZip {
                 zipArtiface = com.tencent.mm:SevenZip:1.1.10
                 path =
        }
------ End ------
variantName:Debug
outputVariantName:Debug
variantName:Release
outputVariantName:Release

> Task :app:processReleaseManifest 
D:\work\com.hema58.app.join\app\src\main\AndroidManifest.xml:23:9-27:56 Warning:
        activity#com.tencent.bugly.beta.ui.BetaActivity@tools:name was tagged at AndroidManifest.xml:23 to replace other declarations but no other declaration present
D:\work\com.hema58.app.join\app\src\main\AndroidManifest.xml:23:9-27:56 Warning:
        activity#com.tencent.bugly.beta.ui.BetaActivity@tools:configChanges was tagged at AndroidManifest.xml:23 to replace other declarations but no other declaration present
D:\work\com.hema58.app.join\app\src\main\AndroidManifest.xml:23:9-27:56 Warning:
        activity#com.tencent.bugly.beta.ui.BetaActivity@tools:theme was tagged at AndroidManifest.xml:23 to replace other declarations but no other declaration present
D:\work\com.hema58.app.join\app\src\main\AndroidManifest.xml:29:9-39:20 Warning:
        provider#com.tencent.bugly.beta.utils.BuglyFileProvider@tools:name was tagged at AndroidManifest.xml:29 to replace other declarations but no other declaration present
D:\work\com.hema58.app.join\app\src\main\AndroidManifest.xml:29:9-39:20 Warning:
        provider#com.tencent.bugly.beta.utils.BuglyFileProvider@tools:authorities was tagged at AndroidManifest.xml:29 to replace other declarations but no other declaration present
D:\work\com.hema58.app.join\app\src\main\AndroidManifest.xml:29:9-39:20 Warning:
        provider#com.tencent.bugly.beta.utils.BuglyFileProvider@tools:exported was tagged at AndroidManifest.xml:29 to replace other declarations but no other declaration present
D:\work\com.hema58.app.join\app\src\main\AndroidManifest.xml:29:9-39:20 Warning:
        provider#com.tencent.bugly.beta.utils.BuglyFileProvider@tools:grantUriPermissions was tagged at AndroidManifest.xml:29 to replace other declarations but no other declaration present
D:\work\com.hema58.app.join\app\src\main\AndroidManifest.xml Warning:
        meta-data#android.support.FILE_PROVIDER_PATHS@tools:name was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present
D:\work\com.hema58.app.join\app\src\main\AndroidManifest.xml Warning:
        meta-data#android.support.FILE_PROVIDER_PATHS@tools:resource was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present

> Task :app:tinkerProcessReleaseManifest 
tinker add tinker_id_1221-16-40-16 to your AndroidManifest.xml D:\work\com.hema58.app.join\app\build\intermediates\merged_manifests\release\processReleaseManifest\merged\AndroidManifest.xml
tinker add com.hema58.app.join.App to dex loader pattern
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml

> Task :app:tinkerProcessReleaseResourceId 
we build app apk with apply resource mapping file D:\work\com.hema58.app.join\app\build\bakApk/app-1220-22-34-10/app-release-R.txt

> Task :app:tinkerSupportProcessReleaseManifest 
manifestPath: D:\work\com.hema58.app.join\app\build\intermediates\merged_manifests\release\processReleaseManifest\merged\AndroidManifest.xml
app version:1.8.1.14
Remove TINKER_ID tinker_id_1221-16-40-16
append TINKER_ID 1.8.1.14_1221-16-40-20
tinkerSupport add com.hema58.app.join.App to dex loader pattern
tinkerSupport gen AndroidManifest.xml in build/intermediates/bugly_intermediates/AndroidManifest.xml

> Task :app:processReleaseResources 
tinker add additionalParameters --stable-ids D:\work\com.hema58.app.join\app\build\intermediates\tinker_intermediates\public.txt

> Task :app:tinkerProcessReleaseProguard 
try update tinker proguard file with D:\work\com.hema58.app.join\app\build\intermediates\tinker_intermediates\tinker_proguard.pro
try add applymapping D:\work\com.hema58.app.join\app\build\bakApk/app-1220-22-34-10/app-release-mapping.txt to build the package
now proguard files is [D:\work\com.hema58.app.join\build\intermediates\proguard-files\proguard-android.txt-3.2.1, D:\work\com.hema58.app.join\app\proguard-rules.pro, D:\work\com.hema58.app.join\app\build\intermediates\tinker_intermediates\tinker_proguard.pro]

> Task :app:tinkerSupportProcessReleaseProguard 
try update bugly proguard file with D:\work\com.hema58.app.join\app\build\intermediates\bugly_intermediates\bugly_proguard.pro
auto add bugly proguard config:
-dontwarn com.tencent.bugly.**
-keep public class com.tencent.bugly.**{*;}
?-keep class android.support.**{*;}

now proguard files is [D:\work\com.hema58.app.join\build\intermediates\proguard-files\proguard-android.txt-3.2.1, D:\work\com.hema58.app.join\app\proguard-rules.pro, D:\work\com.hema58.app.join\app\build\intermediates\tinker_intermediates\tinker_proguard.pro, D:
\work\com.hema58.app.join\app\build\intermediates\bugly_intermediates\bugly_proguard.pro]

> Task :app:tinkerProcessReleaseMultidexKeep 
try update tinker multidex keep proguard file with D:\work\com.hema58.app.join\app\build\intermediates\tinker_intermediates\tinker_multidexkeep.pro

Removed unused resources: Binary resource data reduced from 2216KB to 2208KB: Removed 0%

> Task :app:assembleRelease 
Copy the output files into backup dir
Target dir: D:\work\com.hema58.app.join\app\build\bakApk\app-1221-16-40-16
Copy app-release.apk to D:\work\com.hema58.app.join\app\build\bakApk\app-1221-16-40-16/app-release.apk
Copy mapping.txt to D:\work\com.hema58.app.join\app\build\bakApk\app-1221-16-40-16/app-release-mapping.txt
Copy R.txt to D:\work\com.hema58.app.join\app\build\bakApk\app-1221-16-40-16/app-release-R.txt

> Task :app:tinkerPatchRelease 
-----------------------Tinker patch begin-----------------------
configuration:
oldApk:D:\work\com.hema58.app.join\app\build\bakApk/app-1220-22-34-10/phone_com.hema58.app.join_release_v1.8.1_14.apk
newApk:D:\work\com.hema58.app.join\app\build\outputs\apk\release\phone_com.hema58.app.join_release_v1.8.1_14.apk
outputFolder:D:\work\com.hema58.app.join\app\build\outputs\apk/tinkerPatch/release
isIgnoreWarning:false
isProtectedApp:true
7-ZipPath:C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.tencent.mm\SevenZip\1.1.10\4786999cf29d8e3b0c39a80359b5127bda36132a\SevenZip-1.1.10-windows-x86_64.exe
useSignAPk:true
package meta fields:
dex configs:
dexMode: jar
dexPattern:classes.*\.dex
dexPattern:assets/secondary-dex-.\.jar
dex loader:com.hema58.app.join.App
dex loader:com.tencent.tinker.loader.*
lib configs:
libPattern:lib/.*/.*\.so
resource configs:
resPattern:assets/.*
resPattern:r/.*
resPattern:resources\.arsc
resPattern:res/.*
resPattern:AndroidManifest\.xml
resIgnore change:assets/.*_meta\.txt
largeModSize:100kb
useApplyResource:true

Analyze old and new apk files:
old apk: phone_com.hema58.app.join_release_v1.8.1_14.apk, size=12057293, md5=ca395c5a28bc089103600fe210c84a8b
new apk: phone_com.hema58.app.join_release_v1.8.1_14.apk, size=12057408, md5=b0f02d244ea7ae892b5b6c24123a8e5e

Manifest was changed, while there's no any new components added. Make sure if such changes were all you expected.

UnZipping apk to D:\work\com.hema58.app.join\app\build\outputs\apk\tinkerPatch\release\phone_com.hema58.app.join_release_v1.8.1_14-old
UnZipping apk to D:\work\com.hema58.app.join\app\build\outputs\apk\tinkerPatch\release\phone_com.hema58.app.join_release_v1.8.1_14-new
found modify resource: AndroidManifest.xml, but it is AndroidManifest.xml, just ignore!
Check for loader classes in dex: classes.dex
Check for loader classes in dex: classes2.dex
Found modify resource: res/layout/bd_ocr_confirm_result.xml
Found modify resource: res/layout/bd_ocr_crop.xml
Found modify resource: res/layout/bd_ocr_take_picture.xml
Found modify resource: res/layout-v17/bd_ocr_confirm_result.xml
Found modify resource: res/layout-v17/bd_ocr_crop.xml
Found modify resource: res/layout-v17/bd_ocr_take_picture.xml
java.lang.IndexOutOfBoundsException: index:-1, length=9539
        at com.tencent.tinker.android.dex.Dex.checkBounds(Dex.java:159)
        at com.tencent.tinker.android.dex.Dex.descriptorIndexFromTypeIndex(Dex.java:531)
        at com.tencent.tinker.android.dex.Dex$TypeIndexToDescriptorTable.get(Dex.java:905)
        at com.tencent.tinker.android.dex.Dex$TypeIndexToDescriptorTable.get(Dex.java:902)
        at com.tencent.tinker.build.util.DexClassesComparator.isSameClassDesc(DexClassesComparator.java:628)
        at com.tencent.tinker.build.util.DexClassesComparator.isSameClass(DexClassesComparator.java:553)
        at com.tencent.tinker.build.util.DexClassesComparator.startCheck(DexClassesComparator.java:257)
        at com.tencent.tinker.build.dexpatcher.util.ChangedClassesDexClassInfoCollector.doCollect(ChangedClassesDexClassInfoCollector.java:81)
        at com.tencent.tinker.build.decoder.DexDiffDecoder.generateChangedClassesDexFile(DexDiffDecoder.java:229)
        at com.tencent.tinker.build.decoder.DexDiffDecoder.onAllPatchesEnd(DexDiffDecoder.java:196)
        at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:123)
        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
        at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
        at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
        at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.tinkerPatch(TinkerPatchSchemaTask.groovy:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:59)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:130)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:46)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:210)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:140)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:115)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:49)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

**Comment by tuzhao** [comment]
我也出现了这样的问题，在以前老版本的android studio上没有出现过，应该跟新版本android studio有关系。

**Comment by xiongjianchang** [comment]
同样问题，手贱点了升级

**Comment by xiongjianchang** [comment]
@feng19960223 @tuzhao 你们是怎么解决这个问题的

**Comment by tuzhao** [comment]
> @feng19960223 @tuzhao 你们是怎么解决这个问题的

把热更新移除了....
