### ISSUE TITLE
 集成Tinker后个别机器 vivo android 5.0.2安装apk包报错

### ISSUE THREAD

**Issue by l114624915** [Tencent/tinker#132]
10-18 13:59:31.875 17741-17741/com.xxx.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.xxx.android, PID: 17741
                                                                       java.lang.RuntimeException: Unable to instantiate application com.xxx.android.base.XxxBaseApplication: java.lang.ClassNotFoundException: Didn't find class "com.xxx.android.base.XxxBaseApplication" on path: DexPathList[[zip file "/mnt/asec/com.xxx.android-1/base.apk"],nativeLibraryDirectories=[/mnt/asec/com.xxx.android-1/lib/arm, /vendor/lib, /system/lib]]
                                                                           at android.app.LoadedApk.makeApplication(LoadedApk.java:566)
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:155)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1392)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5318)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xxx.android.base.XxxBaseApplication" on path: DexPathList[[zip file "/mnt/asec/com.xxx.android-1/base.apk"],nativeLibraryDirectories=[/mnt/asec/com.xxx.android-1/lib/arm, /vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at android.app.Instrumentation.newApplication(Instrumentation.java:981)
                                                                           at android.app.LoadedApk.makeApplication(LoadedApk.java:561)
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588) 
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:155) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1392) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5318) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717) 
                                                                       	Suppressed: java.lang.NoClassDefFoundError: com.xxx.android.base.XxxBaseApplication
                                                                           at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                           at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                           at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                           at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                           		... 14 more
                                                                       	Suppressed: java.lang.ClassNotFoundException: com.xxx.android.base.XxxBaseApplication
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 13 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by dqxxhl** [comment]
这个问题的原因是？

**Comment by ifinver** [comment]
我也遇到了，自己的application无法加载了
