### ISSUE TITLE
app运行崩溃 TinkerRuntimeException: Tinker Exception:near "FROM": syntax error (code 1): , while compiling: SELECT  FROM "GS_DB_ANALYTICS_EVENT" T

### ISSUE THREAD

**Issue by FOnlyJack** [Tencent/tinker#1320]
异常类型：app运行时异常

手机型号：OPPO PADM00

手机系统版本：Android 8.1

tinker版本：1.9.14.3

gradle版本：3.5.3

是否使用热更新SDK： Bugly  1.4.2

系统：Win 10

 java.lang.RuntimeException: Unable to create application com.gstianfu.rice.android.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:near "FROM": syntax error (code 1): , while compiling: SELECT  FROM "GS_DB_ANALYTICS_EVENT" T
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6173)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:187)
        at android.app.ActivityThread.main(ActivityThread.java:7025)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:near "FROM": syntax error (code 1): , while compiling: SELECT  FROM "GS_DB_ANALYTICS_EVENT" T
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(SourceFile:6)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreate(SourceFile:1)
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(SourceFile:3)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6170)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:187) 
        at android.app.ActivityThread.main(ActivityThread.java:7025) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888) 
     Caused by: android.database.sqlite.SQLiteException: near "FROM": syntax error (code 1): , while compiling: SELECT  FROM "GS_DB_ANALYTICS_EVENT" T
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1404)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1336)
        at y21.a(SourceFile:1)
        at q21.b(SourceFile:1)
        at j30.<init>(SourceFile:10)
        at com.gstianfu.rice.android.RiceApp.onCreate(SourceFile:18)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreateImpl_$noinline$(SourceFile:4)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.onCreate(SourceFile:1) 
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(SourceFile:3) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6170) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:187) 
        at android.app.ActivityThread.main(ActivityThread.java:7025) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888) 

项目中用到了GreenDao

**Comment by FOnlyJack** [comment]
额   混淆的问题
