### ISSUE TITLE
TinkerDexLoader: install dexes failed

### ISSUE THREAD

**Issue by xyh976039745** [Tencent/tinker#1324]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常/编译异常

手机型号：如:Nexus 5(如是编译异常，则可以不填)

手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)

tinker版本：如:1.7.7

gradle版本：如:5.2.1

是否使用热更新SDK： 如 TinkerPatch SDK

系统：如:Android

堆栈/日志：
2019-12-31 10:17:42.086 5469-5469/? E/Tinker.TinkerDexLoader: install dexes failed
2019-12-31 10:17:42.087 5469-5469/? W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
2019-12-31 10:17:42.089 5469-5469/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2019-12-31 10:17:42.091 5469-5469/? I/MultiDex: VM with version 2.1.0 has multidex support
2019-12-31 10:17:42.091 5469-5469/? I/MultiDex: Installing application
2019-12-31 10:17:42.091 5469-5469/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2019-12-31 10:17:42.094 5469-5469/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.qlkj.myapplication/tinker
2019-12-31 10:17:42.098 5469-5469/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2019-12-31 10:17:42.099 5469-5469/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14, process name:com.qlkj.myapplication, main process:true, systemOTA:false, fingerPrint:HUAWEI/EML-AL00/HWEML:9/HUAWEIEML-AL00/9.1.0.339C00:user/release-keys, oatDir:odex, useInterpretMode:false
2019-12-31 10:17:42.100 5469-5469/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:5c938ca2774bf31b4bbbaa853fed1b73, current:5c938ca2774bf31b4bbbaa853fed1b73
2019-12-31 10:17:42.100 5469-5469/? I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
2019-12-31 10:17:42.100 5469-5469/? E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
2019-12-31 10:17:42.106 5469-5469/? I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
2019-12-31 10:17:42.106 5469-5469/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2019-12-31 10:17:42.108 5469-5469/? E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:85)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:194)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:293)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:92)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:126)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
        at android.app.Application.attach(Application.java:224)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1175)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6688)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

每次调用TinkerInstaller.onReceiveUpgradePatch时 显示补丁successed，但是当自动退出后，在打开就提示上述错误，安装失败

**Comment by xyh976039745** [comment]
> ## Issue/提问须知
> **在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**
> 
> ```
> 异常类型：app运行时异常/编译异常
> 
> 手机型号：如:Nexus 5(如是编译异常，则可以不填)
> 
> 手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)
> 
> tinker版本：如:1.7.7
> 
> gradle版本：如:5.2.1
> 
> 是否使用热更新SDK： 如 TinkerPatch SDK
> 
> 系统：如:Android
> 
> 堆栈/日志：
> 2019-12-31 10:17:42.086 5469-5469/? E/Tinker.TinkerDexLoader: install dexes failed
> 2019-12-31 10:17:42.087 5469-5469/? W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
> 2019-12-31 10:17:42.089 5469-5469/? D/Tinker.DefaultAppLike: onBaseContextAttached:
> 2019-12-31 10:17:42.091 5469-5469/? I/MultiDex: VM with version 2.1.0 has multidex support
> 2019-12-31 10:17:42.091 5469-5469/? I/MultiDex: Installing application
> 2019-12-31 10:17:42.091 5469-5469/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
> 2019-12-31 10:17:42.094 5469-5469/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.qlkj.myapplication/tinker
> 2019-12-31 10:17:42.098 5469-5469/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
> 2019-12-31 10:17:42.099 5469-5469/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14, process name:com.qlkj.myapplication, main process:true, systemOTA:false, fingerPrint:HUAWEI/EML-AL00/HWEML:9/HUAWEIEML-AL00/9.1.0.339C00:user/release-keys, oatDir:odex, useInterpretMode:false
> 2019-12-31 10:17:42.100 5469-5469/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:5c938ca2774bf31b4bbbaa853fed1b73, current:5c938ca2774bf31b4bbbaa853fed1b73
> 2019-12-31 10:17:42.100 5469-5469/? I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
> 2019-12-31 10:17:42.100 5469-5469/? E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
> 2019-12-31 10:17:42.106 5469-5469/? I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
> 2019-12-31 10:17:42.106 5469-5469/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
> 2019-12-31 10:17:42.108 5469-5469/? E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
>         at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:85)
>         at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:194)
>         at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:293)
>         at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:92)
>         at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:126)
>         at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
>         at android.app.Application.attach(Application.java:224)
>         at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
>         at android.app.LoadedApk.makeApplication(LoadedApk.java:1175)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6688)
>         at android.app.ActivityThread.access$2000(ActivityThread.java:273)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
>         at android.os.Handler.dispatchMessage(Handler.java:112)
>         at android.os.Looper.loop(Looper.java:216)
>         at android.app.ActivityThread.main(ActivityThread.java:7625)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
> 
> 每次调用TinkerInstaller.onReceiveUpgradePatch时 显示补丁successed，但是当自动退出后，在打开就提示上述错误，安装失败
> ```

**Comment by CoderNo89757** [comment]
请问解决了吗？

**Comment by wuzhongyuan** [comment]
请问解决了吗？
