### ISSUE TITLE
跟腾讯Shadow插件化框架一起用的时候应用tinker补丁失败

### ISSUE THREAD

**Issue by hzx0910** [Tencent/tinker#1337]
异常类型：app运行时异常/编译异常

手机型号：如:小米 MIX 2S(如是编译异常，则可以不填)

手机系统版本：如:Android 10(如是编译异常，则可以不填)

tinker版本：如:1.9.14.5

gradle版本：如:3.2.1

是否使用热更新SDK： 使用插件化框架Shadow

系统 Mac

堆栈/日志：
2020-02-07 18:39:56.599 4647-4685/? I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:5468
2020-02-07 18:39:56.599 4647-4685/? I/Tinker.DefaultPatchReporter: patchReporter onPatchException: patch exception path: /storage/emulated/0/patch_signed_7zip.apk, throwable: Attempt to register dex file /data/app/...-k79-FG8IbP0u7z0Czw70HA==/base.apk with multiple class loaders
2020-02-07 18:39:56.599 4647-4685/? E/Tinker.DefaultPatchReporter: tinker patch exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2020-02-07 18:39:56.600 4647-4685/? E/Tinker.DefaultPatchReporter: tinker patch exception java.lang.InternalError: Attempt to register dex file /data/app/...-k79-FG8IbP0u7z0Czw70HA==/base.apk with multiple class loaders
at dalvik.system.DexFile.defineClassNative(Native Method)
at dalvik.system.DexFile.defineClass(DexFile.java:296)
at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:289)
at dalvik.system.DexPathList$Element.findClass(DexPathList.java:806)
at dalvik.system.DexPathList.findClass(DexPathList.java:551)
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:228)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:161)
at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(TinkerPatchService.java:141)
at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:96)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:224)
at android.os.HandlerThread.run(HandlerThread.java:67)

2020-02-07 18:39:56.605 4647-4685/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/.../tinker/patch-3e0036be/patch-3e0036be.apk

**Comment by cheng1128feng** [comment]
我没有集成Shaow框架，但是用爱加密加固后出现了这个问题，加固前是正常的
