### ISSUE TITLE
TinkerRuntimeException: Tinker Exception:createInlineFence failed

### ISSUE THREAD

**Issue by wht3xr** [Tencent/tinker#1348]
Android6.0正常，android9和android10 补丁加载成功，重启后crash
ManagerTinkerLike类是继承DefaultApplicationLike，求指点
release模式

异常类型：app运行时异常

手机型号：小米6

手机系统版本：Android9

tinker版本：1.9.14.5

gradle版本：5.4.1

是否使用热更新SDK： 无

系统：Mac

堆栈/日志：
java.lang.RuntimeException: Unable to instantiate application com.boyce.test.ManagerApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createInlineFence failed
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1073)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5988)
	at android.app.ActivityThread.access$1200(ActivityThread.java:202)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1680)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createInlineFence failed
	at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:127)
	at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:137)
	at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:156)
	at com.daiketong.commonsdk.ManagerApplication.attachBaseContext(ManagerApplication.kt:75)
	at android.app.Application.attach(Application.java:215)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
	… 9 more
Caused by: java.lang.IllegalArgumentException: method com.tencent.tinker.entry.TinkerApplicationInlineFence.<init> argument 1 has type com.tencent.tinker.entry.ApplicationLike, got com.boyce.test.ManagerTinkerLike
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:125)
	… 15 more

**Comment by wht3xr** [comment]
不好意思 我的问题

**Comment by LoquatZ** [comment]
您这是什么原因造成的呢？ 我也遇到了同样的问题，Android 4.0 无法 找个TinkerApplicationInlineFence这个class

**Comment by 1136346879** [comment]
怎么解决的？我这边也一直包这个错误？
ava.lang.RuntimeException: Unable to instantiate application com.boyce.test.ManagerApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createInlineFence failed
求指教
