### ISSUE TITLE
应用补丁失败， patch receive fail: -1

### ISSUE THREAD

**Issue by iotxc** [Tencent/tinker#1352]
异常类型：app运行时异常

手机型号：如:huawei P20pro

手机系统版本：Android 10.0

tinker版本：1.9.9

gradle版本：5.1.1

是否使用热更新SDK：Bugly SDK

系统：Win10

堆栈/日志：
2020-03-06 11:10:19.698 26111-26111/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2020-03-06 11:10:19.699 26111-26111/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:cn.com.qrun.ph25.mobi.qr104.app.PHApplication
2020-03-06 11:10:19.712 26111-26111/? I/Tinker.TinkerPatchListener: application maxMemory:384
2020-03-06 11:10:19.715 26111-26111/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.qrun.lian/tinker
2020-03-06 11:10:19.716 26111-26111/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.9
2020-03-06 11:10:19.716 26111-26111/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-20, process name:com.qrun.lian, main process:true, systemOTA:false, fingerPrint:HUAWEI/CLT-AL01/HWCLT:10/HUAWEICLT-AL01/10.0.0.156C00:user/release-keys, oatDir:null, useInterpretMode:false
2020-03-06 11:10:19.716 26111-26111/? I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-20
2020-03-06 11:10:19.716 26111-26111/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: patch load unknown exception: java.lang.NoSuchMethodException: com.tencent.tinker.loader.e.tryLoad [class com.tencent.tinker.loader.app.TinkerApplication]
2020-03-06 11:10:19.716 26111-26111/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2020-03-06 11:10:19.717 26111-26111/? E/Tinker.DefaultLoadReporter: tinker load exception  java.lang.NoSuchMethodException: com.tencent.tinker.loader.e.tryLoad [class com.tencent.tinker.loader.app.TinkerApplication]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:2)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:3)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:3)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:1)
        at android.app.Application.attach(Application.java:358)
        at java.lang.Runtime.nativeLoad(Native Method)
        at java.lang.Runtime.nativeLoad(Runtime.java:1115)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1069)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.qrun.lian.MyWrapperProxyApplication.initProxyApplication(MyWrapperProxyApplication.java:49)
        at com.wrapper.proxyapplication.WrapperProxyApplication.attachBaseContext(WrapperProxyApplication.java:498)
        at android.app.Application.attach(Application.java:358)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1161)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7164)
        at android.app.ActivityThread.access$2200(ActivityThread.java:296)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8169)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
2020-03-06 11:10:19.717 26111-26111/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.qrun.lian/tinker, code: -20, cost: 0ms
2020-03-06 11:10:19.717 26111-26111/? W/Tinker.Tinker: tinker load fail!
2020-03-06 11:10:19.730 26111-26111/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
2020-03-06 11:10:19.731 26111-26111/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2020-03-06 11:10:19.731 26111-26111/? D/Tinker.DefaultAppLike: onCreate
2020-03-06 11:10:20.288 26111-26111/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
2020-03-06 11:10:23.447 26111-26111/? D/Tinker.TinkerManager: onDownloadSuccess.
2020-03-06 11:10:23.448 26111-26111/? D/Tinker.TinkerManager: check if has new patch.
2020-03-06 11:10:23.460 26111-26111/? D/Tinker.TinkerManager: has new patch.
2020-03-06 11:10:23.462 26111-26111/? D/Tinker.TinkerManager: starting patch.
2020-03-06 11:10:23.464 26111-26111/? I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/com.qrun.lian/app_tmpPatch/tmpPatch.apk, file size:13315
2020-03-06 11:10:23.464 26111-26111/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /data/user/0/com.qrun.lian/app_tmpPatch/tmpPatch.apk, code: -1

**Comment by dede1314** [comment]
你这个在启动时就报错了，是不是配置错了
java.lang.NoSuchMethodException: com.tencent.tinker.loader.e.tryLoad [class com.tencent.tinker.loader.app.TinkerApplication]

**Comment by BaiMingxu1** [comment]
您好我也遇到这个问题了，请问怎么解决呀

**Comment by iotxc** [comment]
@BaiMingxu1 更新到最新版，跟着bugly的文档重新配置一遍，注意混淆

**Comment by ludaxin6** [comment]
异常类型：app运行时异常

手机型号：如:huawei P20pro

手机系统版本：Android 10.0

tinker版本：1.9.18

gradle版本：3.5.3

是否使用热更新SDK：Bugly SDK

系统：mac
同样的问题啊，有解决吗？
