### ISSUE TITLE
集成tinker以后  5.0以下一定会报错

### ISSUE THREAD

**Issue by sjj370216540gmail** [Tencent/tinker#1353]
异常类型：app运行时异常/编译异常

手机型号：华为 MT7

手机系统版本：4.4.2

tinker版本： implementation 'com.tencent.bugly:crashreport_upgrade:1.3.8'
                     implementation 'com.tencent.bugly:crashreport_upgrade:latest.release'
                     implementation 'com.tencent.tinker:tinker-android-lib:1.9.14'

gradle版本：如:3.2.1

是否使用热更新SDK： Bugly SDK

系统：Mac

堆栈/日志：
03-11 11:04:28.321 3341-3341/? E/HwLauncher: Launcher dialog dismiss failed : java.lang.IllegalArgumentException: no dialog with id 1 was ever shown via Activity#showDialog
03-11 11:04:28.346 11282-11282/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.e0575.job.app.BaseTinkerApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.
        at android.app.LoadedApk.makeApplication(LoadedApk.java:537)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586)
        at android.app.ActivityThread.access$1800(ActivityThread.java:139)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5314)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:118)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
        at android.app.Application.attach(Application.java:194)
        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.Instrumentation.newApplication(Instrumentation.java:976)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:532)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5314) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ClassNotFoundException: com.tencent.tinker.entry.TinkerApplicationInlineFence
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:251)
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:108)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146) 
        at android.app.Application.attach(Application.java:194) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:532) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5314) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.NoClassDefFoundError: com/tencent/tinker/entry/TinkerApplicationInlineFence
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:251) 
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146) 
        at android.app.Application.attach(Application.java:194) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:532) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5314) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.TinkerApplicationInlineFence" on path: DexPathList[[zip file "/data/app/com.e0575.job-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.e0575.job-1, /vendor/lib, /system/lib, /data/datalib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:251) 
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146) 
        at android.app.Application.attach(Application.java:194) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:532) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5314) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678) 
        at dalvik.system.NativeStart.main(Native Method) 
03-11 11:04:28.346 11282-11282/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.e0575.job, PID: 11282
    java.lang.RuntimeException: Unable to instantiate application com.e0575.job.app.BaseTinkerApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.
        at android.app.LoadedApk.makeApplication(LoadedApk.java:537)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586)
        at android.app.ActivityThread.access$1800(ActivityThread.java:139)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5314)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:fail to create inline fence instance.
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:118)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
        at android.app.Application.attach(Application.java:194)
        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.Instrumentation.newApplication(Instrumentation.java:976)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:532)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5314) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ClassNotFoundException: com.tencent.tinker.entry.TinkerApplicationInlineFence
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:251)
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:108)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146) 
        at android.app.Application.attach(Application.java:194) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:532) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5314) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.NoClassDefFoundError: com/tencent/tinker/entry/TinkerApplicationInlineFence
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:251) 
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146) 
        at android.app.Application.attach(Application.java:194) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:532) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5314) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.TinkerApplicationInlineFence" on path: DexPathList[[zip file "/data/app/com.e0575.job-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.e0575.job-1, /vendor/lib, /system/lib, /data/datalib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:251) 
        at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:127) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146) 
        at android.app.Application.attach(Application.java:194) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:532) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5314) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678) 
        at dalvik.system.NativeStart.main(Native Method) 
03-11 11:04:28.356 2430-2528/? E/logserver: Object Path:/data/system/dropbox/, mask=0x00000080
03-11 11:04:28.356 2430-2528/? E/logserver: event->len=48, name=data_app_crash@1583895868361.txt
03-11 11:04:28.356 2430-2528/? E/logserver: find_first_match: find match, plogs(type=1, pfile=/data/system/dropbox/, match=app_crash)
03-11 11:04:28.356 2430-2528/? E/logserver: move_dir:src_path=/data/log/dbox/appdbg/logcache
03-11 11:04:28.356 2430-2528/? E/logserver: move_dir:dst_path=/data/log/logcache/21071648/
03-11 11:04:28.356 2430-2528/? E/logserver: is_all_ready, any file is ready in non-keyfile exception.
03-11 11:04:28.356 2430-2528/? E/logserver: extract_appname, forward search, appname=com.e0575.job
03-11 11:04:28.356 2430-2528/? E/logserver: archive_and_send, pos=0, type=crash, output=20200311110428_crash
03-11 11:04:28.356 2430-2528/? E/logserver: ---copy_match_files enter!!--
03-11 11:04:28.356 2430-2528/? E/logserver: [copy_match_files,829]: copy [/data/system/dropbox/data_app_crash@1583895868361.txt] to [/data/log/logcache/21071648/data_app_crash@1583895868361.txt]
03-11 11:04:28.356 2430-2528/? E/logserver: internal_archive, argc=7
03-11 11:04:28.356 2430-2528/? E/logserver: get_fault_appname, appname=com.e0575.job
03-11 11:04:28.356 2430-2528/? E/logserver: handle_archive_exception, argc=7
03-11 11:04:28.356 2430-2528/? E/logserver: get alarm time = 2304 (sec.)!
03-11 11:04:28.356 2430-2528/? E/logserver: log_apr_add_record open file:/data/log/apr/MT7-UL00_V100R001C17B125SP01_V6V7N14910008559_20180510140910_statistics
03-11 11:04:28.356 2430-2528/? E/logserver: move_input_files, create dir [/data/log/unzip/MT7-UL00_V100R001C17B125SP01_V6V7N14910008559_20200311110428_crash]
03-11 11:04:28.361 2430-2528/? E/logserver: copy_file_to_dir, /data/log/logcache/21071648/data_app_crash@1583895864425.txt -> /data/log/unzip/MT7-UL00_V100R001C17B125SP01_V6V7N14910008559_20200311110428_crash
03-11 11:04:28.361 2430-2528/? E/logserver: copy_file_to_dir, /data/log/logcache/21071648/data_app_crash@1583895868361.txt -> /data/log/unzip/MT7-UL00_V100R001C17B125SP01_V6V7N14910008559_20200311110428_crash
03-11 11:04:28.361 2430-2528/? E/logserver: copy_file_to_dir, /data/log/logcache/21071648/finger.txt -> /data/log/unzip/MT7-UL00_V100R001C17B125SP01_V6V7N14910008559_20200311110428_crash

**Comment by oncealong** [comment]
https://github.com/Tencent/tinker/blob/1224805c7d4f0731bf328478943c642d2aae92b3/tinker-sample-android/app/build.gradle

参考这个，加上multiDexKeepProguard file("tinker_multidexkeep.pro")选项。tinker_multidexkeep.pro的值如下
https://raw.githubusercontent.com/Tencent/tinker/1224805c7d4f0731bf328478943c642d2aae92b3/tinker-sample-android/app/tinker_multidexkeep.pro
