### ISSUE TITLE
基准包ApplicationLike.onCreate()执行业务初始化报java.lang.VerifyError: Verifier rejected class

### ISSUE THREAD

**Issue by xpleemoon** [Tencent/tinker#1360]
异常类型：app运行时异常

手机型号：OPPO R17

手机系统版本：Android 8.1.0

tinker版本：1.9.14.5

gradle版本：3.3.2

是否使用热更新SDK： 否

系统：Mac

症状：基准包安装后运行，ApplicationLike.onCreate()执行业务代码的初始化报java.lang.VerifyError: Verifier rejected class

堆栈/日志：
```
TinkerUncaughtHandler catch exception:java.lang.VerifyError: Verifier rejected class com.xxxx.android.yyyy.location.LocationComponent: void com.xxxx.android.yyyy.location.LocationComponent.initBasicsConfig(com.xxxx.android.yyyy.publicbundle.application.BaseApplication, java.lang.String, boolean) failed to verify: void com.xxxx.android.yyyy.location.LocationComponent.initBasicsConfig(com.xxxx.android.yyyy.publicbundle.application.BaseApplication, java.lang.String, boolean): [0x5] register v6 has type Reference: com.xxxx.android.yyyy.publicbundle.application.BaseApplication but expected Reference: android.content.Context (declaration of 'com.xxxx.android.yyyy.location.LocationComponent' appears in /data/app/com.xxxx.yyyy-VvnoeBzwOG6P2AWaIRc50Q==/base.apk!classes8.dex)
        at com.xxxx.android.yyyy.location.LocationComponent.getInstance(Unknown Source:0)
        at com.xxxx.android.yyyy.location.LocationAutoInit.initialize(LocationAutoInit.java:21)
        at com.xxxx.yyyy.HelloServiceManager.resortInitialize(HelloServiceManager.java:31)
        at com.xxxx.yyyy.HelloServiceManager.initialize(HelloServiceManager.java:22)
        at com.xxxx.yyyy.application.yyyyApp.initFetch(yyyyApp.java:286)
        at com.xxxx.yyyy.application.yyyyApp.init(yyyyApp.java:82)
        at com.xxxx.android.yyyy.publicbundle.application.BaseApplication.onCreate(BaseApplication.java:28)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(TinkerApplicationInlineFence.java:70)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(TinkerApplicationInlineFence.java:59)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(TinkerApplicationInlineFence.java:52)
        at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnCreate(TinkerInlineFenceAction.java:49)
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:165)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6152)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1834)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:7015)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
```

**Comment by 98Degree** [comment]
这个问题是怎么解决的？

**Comment by 767954322** [comment]
同问，怎么解决的啊
