### ISSUE TITLE
Dex version '037'无法编译出补丁

### ISSUE THREAD

**Issue by yikeng** [Tencent/tinker#1364]
```
异常类型：编译异常

tinker版本：1.9.14.6

gradle版本：5.1.1

androidMinSdkVersion=24

androidTargetSdkVersion=28

androidCompileSdkVersion=28

androidBuildToolsVersion=28.0.3

堆栈/日志：
Caused by: com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
        at com.tencent.tinker.android.dex.TableOfContents.readHeader(TableOfContents.java:159)
        at com.tencent.tinker.android.dex.TableOfContents.readFrom(TableOfContents.java:145)
        at com.tencent.tinker.android.dex.Dex.loadFrom(Dex.java:171)
        at com.tencent.tinker.android.dex.Dex.<init>(Dex.java:140)
        ... 94 more

```

**Comment by fengguangbo** [comment]
![image](https://user-images.githubusercontent.com/12950349/119757477-94e1bc80-bed7-11eb-94fd-14e8bbaedcd4.png)
运行包的时候buildtype选择release
