### ISSUE TITLE
360加固包：修改内容：动态设置TextView内容  异常：下载补丁成功，合成失败

### ISSUE THREAD

**Issue by zhengzhuoxing** [Tencent/tinker#1385]
异常类型：app运行时异常

手机型号：HUAWEI PRA-ALOOX

手机系统版本：Android 8.0 

tinker版本： 1.9.14.6

gradle版本：3.4.1

是否使用热更新SDK： TinkerPatch SDK 
系统：Mac

2020-04-24 17:45:14.076 18556-18556/? D/Tinker.TinkerLoader: tryLoad test test
2020-04-24 17:45:14.103 18556-18556/? I/Tinker.TinkerInternals: class not found exception
2020-04-24 17:45:14.106 18556-18556/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2020-04-24 17:45:14.107 18556-18556/? D/Tinker.TinkerInternals: same fingerprint:HONOR/PRA-AL00X/HWPRA-H:8.0.0/HONORPRA-AL00X/348(C00):user/release-keys
2020-04-24 17:45:14.109 18556-18556/? W/Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_com.haotang.pet count:0
2020-04-24 17:45:14.120 18556-18556/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.haotang.pet count:1
2020-04-24 17:45:14.120 18556-18556/? W/Tinker.TinkerDexLoader: there is no dex to load
2020-04-24 17:45:14.125 18556-18556/? I/Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
2020-04-24 17:45:14.126 18556-18556/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
2020-04-24 17:45:14.128 18556-18556/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2020-04-24 17:45:14.131 18556-18556/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.haotang.pet count:0
2020-04-24 17:45:14.132 18556-18556/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.haotang.pet.MApplication
2020-04-24 17:45:14.138 18556-18556/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
2020-04-24 17:45:14.178 18556-18556/? D/Tinker.DefaultAppLike: onCreate
2020-04-24 17:45:14.630 18556-18556/? I/Tinker.ServerUtils: with app key from manifest appKey:835c9a286b05645c
2020-04-24 17:45:14.631 18556-18556/? I/Tinker.ServerUtils: with app version from manifest appVersion:5.3.31
2020-04-24 17:45:14.634 18556-18556/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.haotang.pet/tinker_server/835c9a286b05645c_version.info, appVersion: 5.3.31, uuid:010cf284-8a31-4a18-8ea4-a9026104aee7, abi:arm64-v8a, patchVersion:14, patchMd5:bf7b5117ccb5322bd46cc760d55e6886, grayValue:6, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
2020-04-24 17:45:14.651 18556-18556/? I/Tinker.Debugger: debugger attached
2020-04-24 17:45:14.653 18556-18556/? D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
2020-04-24 17:45:14.653 18556-18556/? I/Tinker.ServerClient: installTinkerServer, debug value: true, appVersion: 5.3.31, appKey: 835c9a286b05645c
2020-04-24 17:45:14.660 18556-18556/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.haotang.pet/tinker
2020-04-24 17:45:14.664 18556-18556/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.6
2020-04-24 17:45:14.666 18556-18556/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.haotang.pet, main process:true, systemOTA:false, fingerPrint:HONOR/PRA-AL00X/HWPRA-H:8.0.0/HONORPRA-AL00X/348(C00):user/release-keys, oatDir:odex, useInterpretMode:false
2020-04-24 17:45:14.666 18556-18556/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:5be0ba32a4fcee3bfa6a5734eaebd3b9, newVersion:5be0ba32a4fcee3bfa6a5734eaebd3b9, current:5be0ba32a4fcee3bfa6a5734eaebd3b9
2020-04-24 17:45:14.666 18556-18556/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
2020-04-24 17:45:14.666 18556-18556/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.haotang.pet/tinker, code: 0, cost: 51ms
2020-04-24 17:45:14.667 18556-18556/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.14.6
2020-04-24 17:45:14.669 18556-18556/? I/Tinker666666  版本信息: Current patch version is 14
2020-04-24 17:45:14.669 18556-18556/? I/Tinker666666: 99999999
2020-04-24 17:45:14.973 18600-18600/? D/Tinker.TinkerLoader: tryLoad test test
2020-04-24 17:45:15.004 18600-18600/? I/Tinker.TinkerInternals: class not found exception
2020-04-24 17:45:15.008 18600-18600/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2020-04-24 17:45:15.011 18600-18600/? D/Tinker.TinkerInternals: same fingerprint:HONOR/PRA-AL00X/HWPRA-H:8.0.0/HONORPRA-AL00X/348(C00):user/release-keys
2020-04-24 17:45:15.013 18600-18600/? W/Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_com.haotang.pet:pushcore count:0
2020-04-24 17:45:15.024 18600-18600/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.haotang.pet:pushcore count:1
2020-04-24 17:45:15.024 18600-18600/? W/Tinker.TinkerDexLoader: there is no dex to load
2020-04-24 17:45:15.031 18600-18600/? I/Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
2020-04-24 17:45:15.032 18600-18600/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
2020-04-24 17:45:15.035 18600-18600/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2020-04-24 17:45:15.038 18600-18600/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.haotang.pet:pushcore count:0
2020-04-24 17:45:15.039 18600-18600/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.haotang.pet.MApplication
2020-04-24 17:45:15.048 18600-18600/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
2020-04-24 17:45:15.060 18600-18600/? D/Tinker.DefaultAppLike: onCreate
2020-04-24 17:45:15.617 18600-18600/? I/Tinker.ServerUtils: with app key from manifest appKey:835c9a286b05645c
2020-04-24 17:45:15.618 18600-18600/? I/Tinker.ServerUtils: with app version from manifest appVersion:5.3.31
2020-04-24 17:45:15.621 18600-18600/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.haotang.pet/tinker_server/835c9a286b05645c_version.info, appVersion: 5.3.31, uuid:010cf284-8a31-4a18-8ea4-a9026104aee7, abi:arm64-v8a, patchVersion:14, patchMd5:bf7b5117ccb5322bd46cc760d55e6886, grayValue:6, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
2020-04-24 17:45:15.634 18600-18600/? I/Tinker.Debugger: debugger attached
2020-04-24 17:45:15.638 18600-18600/? D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
2020-04-24 17:45:15.638 18600-18600/? I/Tinker.ServerClient: installTinkerServer, debug value: true, appVersion: 5.3.31, appKey: 835c9a286b05645c
2020-04-24 17:45:15.646 18600-18600/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.haotang.pet/tinker
2020-04-24 17:45:15.650 18600-18600/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.6
2020-04-24 17:45:15.652 18600-18600/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.haotang.pet:pushcore, main process:false, systemOTA:false, fingerPrint:HONOR/PRA-AL00X/HWPRA-H:8.0.0/HONORPRA-AL00X/348(C00):user/release-keys, oatDir:odex, useInterpretMode:false
2020-04-24 17:45:15.652 18600-18600/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:5be0ba32a4fcee3bfa6a5734eaebd3b9, newVersion:5be0ba32a4fcee3bfa6a5734eaebd3b9, current:5be0ba32a4fcee3bfa6a5734eaebd3b9
2020-04-24 17:45:15.653 18600-18600/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
2020-04-24 17:45:15.653 18600-18600/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.haotang.pet/tinker, code: 0, cost: 59ms
2020-04-24 17:45:15.654 18600-18600/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.14.6
2020-04-24 17:45:15.657 18600-18600/? I/Tinker666666  版本信息: Current patch version is 14
2020-04-24 17:45:15.657 18600-18600/? I/Tinker666666: 99999999
2020-04-24 17:45:15.675 18600-18600/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
2020-04-24 17:45:15.682 18600-18600/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2020-04-24 17:45:16.489 18556-18556/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
2020-04-24 17:45:16.582 18556-18556/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.haotang.pet/tinker_temp/temp.apk is exist, retry to patch
2020-04-24 17:45:16.584 18556-18556/? I/Tinker.TinkerServerPatchListener: receive a patch file: /data/user/0/com.haotang.pet/tinker_temp/temp.apk, file size:13725
2020-04-24 17:45:16.607 1148-1424/? I/ActivityManager: Start proc 18738:com.haotang.pet:patch/u0a308 for service com.haotang.pet/com.tencent.tinker.lib.service.TinkerPatchForeService
2020-04-24 17:45:16.608 18556-18556/? I/Tinker.TinkerPatchService: run patch service...
2020-04-24 17:45:16.617 18556-18556/? E/Tinker.ReportUtil: checkTinkerApplySuccess, current patch md5:bf7b5117ccb5322bd46cc760d55e6886 is not equal with tinker version 5be0ba32a4fcee3bfa6a5734eaebd3b9
2020-04-24 17:45:16.618 18556-18556/? W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
2020-04-24 17:45:16.646 18556-18556/? I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/dev/835c9a286b05645c/5.3.31?d=010cf284-8a31-4a18-8ea4-a9026104aee7&v=1587721516639, method:GET, body:null
2020-04-24 17:45:16.908 18556-18753/? I/Tinker.UrlConnectionFetcher: response code 200 msg: OK
2020-04-24 17:45:16.909 18556-18753/? I/Tinker.ClientImpl: tinker server sync respond:{"v":14}
2020-04-24 17:45:16.909 18556-18753/? I/Tinker.VersionInfo: VersionCheck: target version 14 is not latest. current version is 14
2020-04-24 17:45:16.911 18556-18753/? D/Tinker.PatchRequestCallback: [beforePatchRequest] have pending patch to install, version: 14, patch:/data/user/0/com.haotang.pet/tinker_server/5.3.31_14.apk
2020-04-24 17:45:16.911 18556-18753/? I/Tinker.VersionInfo: updateVersionInfo file path:/data/user/0/com.haotang.pet/tinker_server/835c9a286b05645c_version.info, appVersion: 5.3.31, uuid:010cf284-8a31-4a18-8ea4-a9026104aee7, abi:arm64-v8a, patchVersion:14, patchMd5:bf7b5117ccb5322bd46cc760d55e6886, grayValue:6, crashTimes:0, retryTimes:1, applySuccess:0, patchSuccess:0
2020-04-24 17:45:16.913 18556-18753/? I/Tinker.TinkerServerPatchListener: receive a patch file: /data/user/0/com.haotang.pet/tinker_server/5.3.31_14.apk, file size:13725
2020-04-24 17:45:16.918 18556-18753/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /data/user/0/com.haotang.pet/tinker_server/5.3.31_14.apk, code: -3
2020-04-24 17:45:16.918 18556-18753/? I/Tinker.ClientImpl: Fetch result: needn't update, gray: 6
2020-04-24 17:45:17.199 18738-18738/? D/Tinker.TinkerLoader: tryLoad test test
2020-04-24 17:45:17.204 18738-18738/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
2020-04-24 17:45:17.208 18738-18738/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2020-04-24 17:45:17.209 18738-18738/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.haotang.pet.MApplication
2020-04-24 17:45:17.216 18738-18738/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
2020-04-24 17:45:17.227 18738-18738/? D/Tinker.DefaultAppLike: onCreate
2020-04-24 17:45:17.699 18738-18738/? I/Tinker.ServerUtils: with app key from manifest appKey:835c9a286b05645c
2020-04-24 17:45:17.700 18738-18738/? I/Tinker.ServerUtils: with app version from manifest appVersion:5.3.31
2020-04-24 17:45:17.704 18738-18738/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.haotang.pet/tinker_server/835c9a286b05645c_version.info, appVersion: 5.3.31, uuid:010cf284-8a31-4a18-8ea4-a9026104aee7, abi:arm64-v8a, patchVersion:14, patchMd5:bf7b5117ccb5322bd46cc760d55e6886, grayValue:6, crashTimes:0, retryTimes:1, applySuccess:0, patchSuccess:0
2020-04-24 17:45:17.720 18738-18738/? I/Tinker.Debugger: debugger attached
2020-04-24 17:45:17.723 18738-18738/? D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
2020-04-24 17:45:17.723 18738-18738/? I/Tinker.ServerClient: installTinkerServer, debug value: true, appVersion: 5.3.31, appKey: 835c9a286b05645c
2020-04-24 17:45:17.733 18738-18738/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.haotang.pet/tinker
2020-04-24 17:45:17.736 18738-18738/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.6
2020-04-24 17:45:17.738 18738-18738/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.haotang.pet:patch, main process:false, systemOTA:false, fingerPrint:HONOR/PRA-AL00X/HWPRA-H:8.0.0/HONORPRA-AL00X/348(C00):user/release-keys, oatDir:null, useInterpretMode:false
2020-04-24 17:45:17.738 18738-18738/? W/Tinker.TinkerLoadResult: tinker is disable, just return
2020-04-24 17:45:17.738 18738-18738/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.haotang.pet/tinker, code: -1, cost: 7ms
2020-04-24 17:45:17.739 18738-18738/? W/Tinker.Tinker: tinker load fail!
2020-04-24 17:45:17.739 18738-18738/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.14.6
2020-04-24 17:45:17.741 18738-18738/? I/Tinker666666  版本信息: Current patch version is 14
2020-04-24 17:45:17.741 18738-18738/? I/Tinker666666: 99999999
2020-04-24 17:45:17.753 18738-18787/? I/Tinker.TinkerPatchService: for system version >= Android O, we just ignore increasingPriority job to avoid crash or toasts.
2020-04-24 17:45:17.753 18738-18787/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
2020-04-24 17:45:17.771 18738-18738/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
2020-04-24 17:45:17.778 18738-18738/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2020-04-24 17:45:17.784 18738-18787/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:bf7b5117ccb5322bd46cc760d55e6886
2020-04-24 17:45:17.787 18738-18787/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.haotang.pet/tinker/patch-bf7b5117
2020-04-24 17:45:17.801 18738-18787/? W/Tinker.DexDiffPatchInternal: class n dex file tinker_classN.apk is already exist, and md5 match, just continue
2020-04-24 17:45:17.802 18738-18787/? I/Tinker.DexDiffPatchInternal: legal files to do dexopt: [/data/user/0/com.haotang.pet/tinker/patch-bf7b5117/dex/tinker_classN.apk]
2020-04-24 17:45:17.803 18738-18787/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm64
2020-04-24 17:45:17.803 18738-18787/? I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:1, optimizeDexDirectory:/data/user/0/com.haotang.pet/tinker/patch-bf7b5117/odex/
2020-04-24 17:45:17.806 18738-18787/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.haotang.pet/tinker/patch-bf7b5117/dex/tinker_classN.apk, size: 22871
2020-04-24 17:45:17.806 18738-18787/? I/Tinker.TinkerInternals: class not found exception
2020-04-24 17:45:18.015 18738-18787/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.haotang.pet/tinker/patch-bf7b5117/dex/tinker_classN.apk, opt file:/data/user/0/com.haotang.pet/tinker/patch-bf7b5117/dex/oat/arm64/tinker_classN.odex, opt file size: 0, use time 209
2020-04-24 17:45:18.016 18738-18787/? I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:222
2020-04-24 17:45:18.021 18738-18787/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
2020-04-24 17:45:18.030 18738-18787/? W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
2020-04-24 17:45:18.030 18738-18787/? I/Tinker.DexDiffPatchInternal: raw dex count: 3, dex opt dex count: 1, final wait times: 90
2020-04-24 17:45:18.031 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 1 times
2020-04-24 17:45:21.913 18805-18805/? D/Tinker.TinkerLoader: tryLoad test test
2020-04-24 17:45:21.972 18805-18805/? I/Tinker.TinkerInternals: class not found exception
2020-04-24 17:45:21.976 18805-18805/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2020-04-24 17:45:21.980 18805-18805/? D/Tinker.TinkerInternals: same fingerprint:HONOR/PRA-AL00X/HWPRA-H:8.0.0/HONORPRA-AL00X/348(C00):user/release-keys
2020-04-24 17:45:21.982 18805-18805/? W/Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_com.haotang.pet:remote count:0
2020-04-24 17:45:21.986 18805-18805/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.haotang.pet:remote count:1
2020-04-24 17:45:21.986 18805-18805/? W/Tinker.TinkerDexLoader: there is no dex to load
2020-04-24 17:45:21.992 18805-18805/? I/Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
2020-04-24 17:45:21.992 18805-18805/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
2020-04-24 17:45:21.995 18805-18805/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2020-04-24 17:45:21.998 18805-18805/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.haotang.pet:remote count:0
2020-04-24 17:45:21.999 18805-18805/? I/Tinker.ReflectApp: with app application from manifest applicationName:com.haotang.pet.MApplication
2020-04-24 17:45:22.006 18805-18805/? I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
2020-04-24 17:45:22.017 18805-18805/? D/Tinker.DefaultAppLike: onCreate
2020-04-24 17:45:22.438 18805-18805/? I/Tinker.ServerUtils: with app key from manifest appKey:835c9a286b05645c
2020-04-24 17:45:22.439 18805-18805/? I/Tinker.ServerUtils: with app version from manifest appVersion:5.3.31
2020-04-24 17:45:22.442 18805-18805/? I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/com.haotang.pet/tinker_server/835c9a286b05645c_version.info, appVersion: 5.3.31, uuid:010cf284-8a31-4a18-8ea4-a9026104aee7, abi:arm64-v8a, patchVersion:14, patchMd5:bf7b5117ccb5322bd46cc760d55e6886, grayValue:6, crashTimes:0, retryTimes:1, applySuccess:0, patchSuccess:0
2020-04-24 17:45:22.455 18805-18805/? I/Tinker.Debugger: debugger attached
2020-04-24 17:45:22.457 18805-18805/? D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
2020-04-24 17:45:22.458 18805-18805/? I/Tinker.ServerClient: installTinkerServer, debug value: true, appVersion: 5.3.31, appKey: 835c9a286b05645c
2020-04-24 17:45:22.464 18805-18805/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.haotang.pet/tinker
2020-04-24 17:45:22.468 18805-18805/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.6
2020-04-24 17:45:22.469 18805-18805/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.haotang.pet:remote, main process:false, systemOTA:false, fingerPrint:HONOR/PRA-AL00X/HWPRA-H:8.0.0/HONORPRA-AL00X/348(C00):user/release-keys, oatDir:odex, useInterpretMode:false
2020-04-24 17:45:22.470 18805-18805/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:5be0ba32a4fcee3bfa6a5734eaebd3b9, newVersion:5be0ba32a4fcee3bfa6a5734eaebd3b9, current:5be0ba32a4fcee3bfa6a5734eaebd3b9
2020-04-24 17:45:22.470 18805-18805/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
2020-04-24 17:45:22.470 18805-18805/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.haotang.pet/tinker, code: 0, cost: 79ms
2020-04-24 17:45:22.470 18805-18805/? I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.14.6
2020-04-24 17:45:22.472 18805-18805/? I/Tinker666666  版本信息: Current patch version is 14
2020-04-24 17:45:22.472 18805-18805/? I/Tinker666666: 99999999
2020-04-24 17:45:22.500 18805-18805/? I/Tinker.FetchPatchHandler: try to fetch patch update with FetchPatchHandler with interval 10800000
2020-04-24 17:45:22.507 18805-18805/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2020-04-24 17:45:28.032 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 2 times
2020-04-24 17:45:38.034 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 3 times
2020-04-24 17:45:48.035 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 4 times
2020-04-24 17:45:58.037 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 5 times
2020-04-24 17:46:08.041 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 6 times
2020-04-24 17:46:18.042 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 7 times
2020-04-24 17:46:28.044 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 8 times
2020-04-24 17:46:38.045 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 9 times
2020-04-24 17:46:48.046 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 10 times
2020-04-24 17:46:58.047 18738-18787/? E/Tinker.DexDiffPatchInternal: parallel dex optimizer file tinker_classN.odex is not exist, just wait 11 times

**Comment by zhengzhuoxing** [comment]
修改xml内容可以合成补丁成功

**Comment by zhengzhuoxing** [comment]
04-24 19:27:11.468 17012-17051/? E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  java.io.IOException: Failed to open dex files from /data/user/0/com.haotang.pet/tinker/patch-6550254e/dex/tinker_classN.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:295)
        at dalvik.system.DexFile.<init>(DexFile.java:111)
        at dalvik.system.DexFile.loadDex(DexFile.java:151)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:134)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:82)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:59)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:371)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:194)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85)
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:157)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(TinkerPatchService.java:141)
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:96)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by 84wangmou** [comment]
请问修改了什么合并成功了？
