### ISSUE TITLE
1.7.1 Nexus 6P  android.content.res.Resources$NotFoundException: Resource ID #0x7f040152

### ISSUE THREAD

**Issue by kongnanlive** [Tencent/tinker#139]
`E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.android.debug, PID: 17169
                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.huika.o2o.android.xmdd.debug/com.huika.o2o.android.ui.tinker.A}: android.content.res.Resources$NotFoundException: Resource ID #0x7f040152
                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                      Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f040152
                                         at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
                                         at android.content.res.Resources.loadXmlResourceParser(Resources.java:2094)
                                         at android.content.res.Resources.getLayout(Resources.java:1111)
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                         at com.android.ui.tinker.A.onCreate(A.java:39)
                                         at android.app.Activity.performCreate(Activity.java:6664)
                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                         at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                         at android.os.Looper.loop(Looper.java:154) 
                                         at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                         at java.lang.reflect.Method.invoke(Native Method) 
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) `

![qq20161021-0](https://cloud.githubusercontent.com/assets/2374686/19594197/9e1c948e-97b6-11e6-8c45-ba636b566f2c.png)

经过测试得出，如果Activity布局文件中含有WebView会导致原本已经替换成功的Resources又被换回去了。

**Comment by kongnanlive** [comment]
用法没错，预埋的Activity，新增的layout布局文件。

**Comment by shwenzhang** [comment]
@kongnanlive try with dev localMaven

**Comment by kongnanlive** [comment]
在dev localMaven下测试通过。
