### ISSUE TITLE
关于新版本1.9.14.6 加固 dex version 为 039 导致9.0以下无法修复的问题及疑惑。

### ISSUE THREAD

**Issue by YummyLau** [Tencent/tinker#1391]
异常类型：app运行时异常

手机型号：vivo Y91 8.0系统

手机系统版本：8.0系统

tinker版本：1.9.14.6

gradle版本：3.4.1

是否使用热更新SDK：false

系统：Mac

堆栈/日志：
```

2020-05-06 13:36:28.875 23690-23690/<包名> D/Tinker.TinkerLoader: tryLoad test test
2020-05-06 13:36:29.036 23690-23690/<包名> I/Tinker.TinkerInternals: class not found exception
2020-05-06 13:36:29.043 23690-23690/<包名> D/Tinker.TinkerInternals: getCurrentInstructionSet:arm
2020-05-06 13:36:29.045 23690-23690/<包名> W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2020-05-06 13:36:29.052 23690-23690/<包名> D/Tinker.TinkerInternals: same fingerprint:vivo/PD1818E/PD1818E:8.1.0/O11019/1559233420:user/release-keys
2020-05-06 13:36:29.055 23690-23690/<包名> W/Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_<包名> count:0
2020-05-06 13:36:29.064 23690-23690/<包名> W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_<包名> count:1
2020-05-06 13:36:29.065 23690-23690/<包名> I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk", dex file "/system/framework/org.simalliance.openmobileapi.jar"],nativeLibraryDirectories=[/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/lib/arm, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]]
2020-05-06 13:36:29.065 23690-23690/<包名> I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk md5, use time: 0
2020-05-06 13:36:29.068 23690-23690/<包名> I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/<包名>/tinker/patch-a1a36e29/odex, dex size:1
2020-05-06 13:36:29.073 23690-23690/<包名> W/zygote: Unrecognized version number in /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk: 0 3 9 
2020-05-06 13:36:29.077 23690-23690/<包名> W/Tinker.ClassLoaderAdder: Exception in makePathElement
    java.io.IOException: Failed to open dex files from /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk because: Unrecognized version number in /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk: 0 3 9 
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:142)
        at dalvik.system.DexFile.loadDex(DexFile.java:201)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:377)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.makePathElements(DexPathList.java:423)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.SystemClassLoaderAdder$V23.makePathElements(SystemClassLoaderAdder.java:268)
        at com.tencent.tinker.loader.SystemClassLoaderAdder$V23.install(SystemClassLoaderAdder.java:227)
        at com.tencent.tinker.loader.SystemClassLoaderAdder$V23.access$000(SystemClassLoaderAdder.java:213)
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:67)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:189)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:300)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:95)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:156)
        at android.app.Application.attach(Application.java:189)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.stub.StubApp.attachBaseContext(SourceFile:197)
        at android.app.Application.attach(Application.java:189)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1108)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1092)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1001)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6132)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6959)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
2020-05-06 13:36:29.078 23690-23690/<包名> E/Tinker.TinkerDexLoader: install dexes failed
2020-05-06 13:36:29.079 23690-23690/<包名> W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
2020-05-06 13:36:29.102 23690-23690/<包名> I/Tinker.PatchStatusListener: application maxMemory:256
2020-05-06 13:36:29.109 23690-23690/<包名> W/Tinker.Tinker: tinker patch directory: /data/user/0/<包名>/tinker
2020-05-06 13:36:29.113 23690-23690/<包名> I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.6
2020-05-06 13:36:29.117 23690-23690/<包名> I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14, process name:<包名>, main process:true, systemOTA:false, fingerPrint:vivo/PD1818E/PD1818E:8.1.0/O11019/1559233420:user/release-keys, oatDir:odex, useInterpretMode:false
2020-05-06 13:36:29.119 23690-23690/<包名> I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:a1a36e29275c60ead5d72e5f9b6d32eb, current:a1a36e29275c60ead5d72e5f9b6d32eb
2020-05-06 13:36:29.120 23690-23690/<包名> I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
2020-05-06 13:36:29.121 23690-23690/<包名> I/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: patch load dex exception: java.io.IOException: Failed to open dex files from /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk because: Unrecognized version number in /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk: 0 3 9 
2020-05-06 13:36:29.130 23690-23690/<包名> I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
2020-05-06 13:36:29.130 23690-23690/<包名> E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2020-05-06 13:36:29.133 23690-23690/<包名> E/Tinker.DefaultLoadReporter: tinker load exception  java.io.IOException: Failed to open dex files from /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk because: Unrecognized version number in /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk: 0 3 9 
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:142)
        at dalvik.system.DexFile.loadDex(DexFile.java:201)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:377)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.makePathElements(DexPathList.java:423)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.SystemClassLoaderAdder$V23.makePathElements(SystemClassLoaderAdder.java:268)
        at com.tencent.tinker.loader.SystemClassLoaderAdder$V23.install(SystemClassLoaderAdder.java:227)
        at com.tencent.tinker.loader.SystemClassLoaderAdder$V23.access$000(SystemClassLoaderAdder.java:213)
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:67)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:189)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:300)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:95)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:156)
        at android.app.Application.attach(Application.java:189)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.stub.StubApp.attachBaseContext(SourceFile:197)
        at android.app.Application.attach(Application.java:189)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1108)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1092)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1001)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6132)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6959)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
2020-05-06 13:36:29.138 23690-23690/<包名> I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/<包名>/tinker/patch.info , oldVer:, newVer:a1a36e29275c60ead5d72e5f9b6d32eb, isProtectedApp:1, isRemoveNewVersion:1, fingerprint:vivo/PD1818E/PD1818E:8.1.0/O11019/1559233420:user/release-keys, oatDir:odex
2020-05-06 13:36:29.212 23690-23690/<包名> D/HotFix: TinkerReport key : 252
2020-05-06 13:36:29.213 23690-23690/<包名> E/Tinker.TinkerReport: tinker dex reflect fail:Failed to open dex files from /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk because: Unrecognized version number in /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk: 0 3 9 
2020-05-06 13:36:29.228 23690-23690/<包名> D/HotFix: TinkerReport message : Tinker Exception:load tinker occur exception java.io.IOException: Failed to open dex files from /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk because: Unrecognized version number in /data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk: 0 3 9 
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:142)
        at dalvik.system.DexFile.loadDex(DexFile.java:201)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:377)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.makePathElements(DexPathList.java:423)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.SystemClassLoaderAdder$V23.makePathElements(SystemClassLoaderAdder.java:268)
        at com.tencent.tinker.loader.SystemClassLoaderAdder$V23.install(SystemClassLoaderAdder.java:227)
        at com.tencent.tinker.loader.SystemClassLoaderAdder$V23.access$000(SystemClassLoaderAdder.java:213)
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:67)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:189)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:300)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:95)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:156)
        at android.app.Application.attach(Application.java:189)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.stub.StubApp.attachBaseContext(SourceFile:197)
        at android.app.Application.attach(Application.java:189)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1108)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1092)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1001)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6132)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6959)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
2020-05-06 13:36:29.230 23690-23690/<包名> I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/<包名>/tinker, code: -14, cost: 205ms
2020-05-06 13:36:29.231 23690-23690/<包名> W/Tinker.Tinker: tinker load fail!
2020-05-06 13:36:29.301 23690-23690/<包名> W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_<包名> count:0
2020-05-06 13:36:29.692 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(TinkerApplicationInlineFence.java:70)
2020-05-06 13:36:29.692 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(TinkerApplicationInlineFence.java:59)
2020-05-06 13:36:29.692 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(TinkerApplicationInlineFence.java:52)
2020-05-06 13:36:29.692 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnCreate(TinkerInlineFenceAction.java:49)
2020-05-06 13:36:29.692 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:165)
2020-05-06 13:36:29.695 23690-23690/<包名> W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.netease.ntunisdk.base.SdkMgr" on path: DexPathList[[zip file "/data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk", dex file "/system/framework/org.simalliance.openmobileapi.jar"],nativeLibraryDirectories=[/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/lib/arm, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
2020-05-06 13:36:29.698 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(TinkerApplicationInlineFence.java:70)
2020-05-06 13:36:29.698 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(TinkerApplicationInlineFence.java:59)
2020-05-06 13:36:29.698 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(TinkerApplicationInlineFence.java:52)
2020-05-06 13:36:29.699 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnCreate(TinkerInlineFenceAction.java:49)
2020-05-06 13:36:29.699 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:165)
2020-05-06 13:36:29.726 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(TinkerApplicationInlineFence.java:70)
2020-05-06 13:36:29.726 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(TinkerApplicationInlineFence.java:59)
2020-05-06 13:36:29.726 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(TinkerApplicationInlineFence.java:52)
2020-05-06 13:36:29.727 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnCreate(TinkerInlineFenceAction.java:49)
2020-05-06 13:36:29.727 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:165)
2020-05-06 13:36:29.729 23690-23690/<包名> W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.netease.ntunisdk.base.UniSdkUtils" on path: DexPathList[[zip file "/data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk", dex file "/system/framework/org.simalliance.openmobileapi.jar"],nativeLibraryDirectories=[/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/lib/arm, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
2020-05-06 13:36:29.835 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(TinkerApplicationInlineFence.java:70)
2020-05-06 13:36:29.835 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(TinkerApplicationInlineFence.java:59)
2020-05-06 13:36:29.835 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(TinkerApplicationInlineFence.java:52)
2020-05-06 13:36:29.835 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnCreate(TinkerInlineFenceAction.java:49)
2020-05-06 13:36:29.835 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:165)
2020-05-06 13:36:30.075 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(TinkerApplicationInlineFence.java:70)
2020-05-06 13:36:30.075 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(TinkerApplicationInlineFence.java:59)
2020-05-06 13:36:30.075 23690-23690/<包名> W/System.err:     at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(TinkerApplicationInlineFence.java:52)
2020-05-06 13:36:30.075 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnCreate(TinkerInlineFenceAction.java:49)
2020-05-06 13:36:30.075 23690-23690/<包名> W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:165)
2020-05-06 13:36:31.704 23690-23690/<包名> I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk", dex file "/system/framework/org.simalliance.openmobileapi.jar"],nativeLibraryDirectories=[/data/user/0/<包名>/app_unity_libs, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/lib/arm, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
2020-05-06 13:36:31.706 23690-23690/<包名> I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk", dex file "/system/framework/org.simalliance.openmobileapi.jar"],nativeLibraryDirectories=[/data/user/0/<包名>/app_unity_libs, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/lib/arm, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
2020-05-06 13:36:31.707 23690-23690/<包名> I/zygote: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk", dex file "/system/framework/org.simalliance.openmobileapi.jar"],nativeLibraryDirectories=[/data/user/0/<包名>/app_unity_libs, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/lib/arm, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
2020-05-06 13:36:32.429 23690-23825/<包名> W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.identifier.AdvertisingIdClient" on path: DexPathList[[zip file "/data/user/0/<包名>/tinker/patch-a1a36e29/dex/tinker_classN.apk", zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk", dex file "/system/framework/org.simalliance.openmobileapi.jar"],nativeLibraryDirectories=[/data/user/0/<包名>/app_unity_libs, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/lib/arm, /data/app/<包名>-HT1Yg7QigE_XvP2jv6ju5A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
2020-05-06 13:36:38.338 23690-23690/<包名> W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/<包名>/tinker_temp/temp.apk is not exist, just return
```

目前存在其他机型。
@tomystang

**Comment by YummyLau** [comment]
补充下目前的解决方案及对高版本1.9.14.6的一些疑惑。
我的场景是：使用加固之后，发现补丁输出的dex version 全部是039，在9.0以下的手机，基本全军覆没。

`DexDiffDecoder.java` 在1.9.14.6 更新了有关 DexBuilder 指定 api 的操作。 [commit变动](https://github.com/Tencent/tinker/commit/6c8759e6cc77f6444453157d9350f52167422cc5)
运营|技术|梁海滨  5月6日 19:25:09
改用1.9.14.6后，变成了039.

目前，选了回退了最新版本使用1.9.14.5版本。

@tomystang  后续会怎么处理呢？

**Comment by zyz001** [comment]
我遇到和你一模一样的问题，用的也是1.9.14.6版本，在6.0.1，7.1.1合成均失败，在android高版本系统均没有问题，用的梆梆加固，不加固的话，都没有问题，加固在低版本系统就不行，已经设了isProtectApp=true，请问下大神怎么解决的？

**Comment by YummyLau** [comment]
@zyz001 z升级最新，或者回退。

**Comment by zyz001** [comment]
> @zyz001 z升级最新，或者回退。

1.9.14.7 可以解决这个低系统版本加固包修复失败的问题是吗？？

**Comment by YummyLau** [comment]
@zyz001 错误的原因是1.9.14.6版本里面处理dex的逻辑有误，新版版应该更新了，这个是bug，你升级。

**Comment by zyz001** [comment]
> @zyz001 错误的原因是1.9.14.6版本里面处理dex的逻辑有误，新版版应该更新了，这个是bug，你升级。

多谢！ 升级1.9.14.7 问题已解决。
