### ISSUE TITLE
使用1.9.14.7编译报错

### ISSUE THREAD

**Issue by YuYongzhi** [Tencent/tinker#1394]
先是遇到 support 库的问题 #1393 ，后clone源码，单独编译support库后，最终项目还是编译失败，错误日志如下：
```
Caused by: java.util.ServiceConfigurationError: javax.annotation.processing.Processor: Provider com.tencent.tinker.anno.AnnotationProcessor not found
        at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1206)
        at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1239)
        at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1230)
        at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.doLoadProcessors(ProcessorLoader.kt:80)
        at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.loadProcessors(ProcessorLoader.kt:45)
        at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:42)
        ... 25 more
```
请问如何解决？

**Comment by starchen84** [comment]
你好,遇到同样问题,请问有解决方案吗?
