### ISSUE TITLE
vivo X3t补丁加载后重新启动会造成程序崩溃

### ISSUE THREAD

**Issue by maofan4041** [Tencent/tinker#144]
有一台vivo X3t  百度云OS系统  公测版60 Android [4.2.1，加载补丁后，重新启动会造成程序崩溃。而测试其他的手机不会有任何问题。在补丁包中我有对一张db_ic_guide1_b.png图片资源进行替换，图片名没有进行改变。同时也修改了string.xml下name为db_recharge_tip的的内容，在原来的内容上添加了几个字。
报出的错误如下所示：

``` java
0-27 10:01:55.705 7753-7753/? E/dalvikvm: Could not find class 'android.util.ArrayMap', referenced from method com.tencent.tinker.loader.TinkerResourcePatcher.isResourceCanPatch
10-27 10:01:55.816 7753-7753/? E/dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.internal.zzrt.zzg
10-27 10:01:56.112 7753-7753/? E/com.umeng.message.UmengRegistrar: isRegisteredToUmeng: empty registration id
10-27 10:01:56.145 7753-7753/? E/com.umeng.message.UTrack: RegistrationId is empty
10-27 10:01:56.198 7753-7753/? E/Tinker.SampleUncaughtExHandler: uncaughtException:Unable to start activity ComponentInfo{com.yyxx.new/com.cry.test.ui.SplashActivity_}: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
10-27 10:01:56.217 7753-7753/? E/Tinker.SampleUncaughtExHandler: tinker has fast crash 2 times
10-27 10:01:56.221 7753-7753/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yyxx.new/com.cry.test.ui.SplashActivity_}: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2308)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:156)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:153)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5338)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:357)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:278)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.initWindowDecorActionBar(AppCompatDelegateImplV7.java:171)
                                                     at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:87)
                                                     at android.support.v7.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:79)
                                                     at com.cry.test.ui.base.BaseActivity.initTitle(BaseActivity.java:33)
                                                     at com.cry.test.ui.base.BaseActivity.onCreate(BaseActivity.java:25)
                                                     at com.cry.test.ui.SplashActivity.onCreate(SplashActivity.java:60)
                                                     at com.cry.test.ui.SplashActivity_.onCreate(SplashActivity_.java:41)
                                                     at android.app.Activity.performCreate(Activity.java:5232)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2272)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)?
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:156)?
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)?
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)?
                                                     at android.os.Looper.loop(Looper.java:153)?
                                                     at android.app.ActivityThread.main(ActivityThread.java:5338)?
                                                     at java.lang.reflect.Method.invokeNative(Native Method)?
                                                     at java.lang.reflect.Method.invoke(Method.java:511)?
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)?
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)?
                                                     at dalvik.system.NativeStart.main(Native Method)?
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)?
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)?
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)?
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)?
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)?
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)?
                                                     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:357)?
                                                     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:278)?
                                                     at android.support.v7.app.AppCompatDelegateImplV7.initWindowDecorActionBar(AppCompatDelegateImplV7.java:171)?
                                                     at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:87)?
                                                     at android.support.v7.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:79)?
                                                     at com.cry.test.ui.base.BaseActivity.initTitle(BaseActivity.java:33)?
                                                     at com.cry.test.ui.base.BaseActivity.onCreate(BaseActivity.java:25)?
                                                     at com.cry.test.ui.SplashActivity.onCreate(SplashActivity.java:60)?
                                                     at com.cry.test.ui.SplashActivity_.onCreate(SplashActivity_.java:41)?
                                                     at android.app.Activity.performCreate(Activity.java:5232)?
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)?
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2272)?
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)?
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:156)?
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)?
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)?
                                                     at android.os.Looper.loop(Looper.java:153)?
                                                     at android.app.ActivityThread.main(ActivityThread.java:5338)?
                                                     at java.lang.reflect.Method.invokeNative(Native Method)?
                                                     at java.lang.reflect.Method.invoke(Method.java:511)?
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)?
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)?
                                                     at dalvik.system.NativeStart.main(Native Method)?
                                                  Caused by: android.content.res.Resources$NotFoundException: File res/mipmap-xhdpi-v4/db_actionbar_ic_top_back.png from drawable resource ID #0x7f030013
                                                     at android.content.res.BaiduResources.loadDrawableBaidu(BaiduResources.java:180)
                                                     at android.content.res.BaiduResources.loadDrawable(BaiduResources.java:103)
                                                     at android.content.res.Resources.getDrawable(Resources.java:673)
                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)
                                                     at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:174)
                                                     at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:167)
                                                     at android.support.v7.internal.widget.TintTypedArray.getDrawable(TintTypedArray.java:62)
                                                     at android.support.v7.widget.Toolbar.<init>(Toolbar.java:265)
                                                     at android.support.v7.widget.Toolbar.<init>(Toolbar.java:207)
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)?
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)?
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587)?
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)?
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)?
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)?
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)?
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)?
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)?
                                                     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:357)?
                                                     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:278)?
                                                     at android.support.v7.app.AppCompatDelegateImplV7.initWindowDecorActionBar(AppCompatDelegateImplV7.java:171)?
                                                     at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:87)?
                                                     at android.support.v7.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:79)?
                                                     at com.cry.test.ui.base.BaseActivity.initTitle(BaseActivity.java:33)?
                                                     at com.cry.test.ui.base.BaseActivity.onCreate(BaseActivity.java:25)?
                                                     at com.cry.test.ui.SplashActivity.onCreate(SplashActivity.java:60)?
                                                     at com.cry.test.ui.SplashActivity_.onCreate(SplashActivity_.java:41)?
                                                     at android.app.Activity.performCreate(Activity.java:5232)?
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)?
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2272)?
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)?
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:156)?
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)?
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)?
                                                     at android.os.Looper.loop(Looper.java:153)?
                                                     at android.app.ActivityThread.main(ActivityThread.java:5338)?
                                                     at java.lang.reflect.Method.invokeNative(Native Method)?
                                                     at java.lang.reflect.Method.invoke(Method.java:511)?
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)?
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)?
                                                     at dalvik.system.NativeStart.main(Native Method)?
                                                  Caused by: java.lang.ClassCastException: android.content.res.AssetManager cannot be cast to android.content.res.BaiduAssetManager
                                                     at android.content.res.BaiduResources.loadDrawableBaidu(BaiduResources.java:168)
                                                     at android.content.res.BaiduResources.loadDrawable(BaiduResources.java:103)?
                                                     at android.content.res.Resources.getDrawable(Resources.java:673)?
                                                     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:323)?
                                                     at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:174)?
                                                     at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:167)?
                                                     at android.support.v7.internal.widget.TintTypedArray.getDrawable(TintTypedArray.java:62)?
                                                     at android.support.v7.widget.Toolbar.<init>(Toolbar.java:265)?
                                                     at android.support.v7.widget.Toolbar.<init>(Toolbar.java:207)?
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)?
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)?
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587)?
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)?
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)?
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)?
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)?
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)?
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)?
                                                     at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:357)?
                                                     at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:278)?
                                                     at android.support.v7.app.AppCompatDelegateImplV7.initWindowDecorActionBar(AppCompatDelegateImplV7.java:171)?
                                                     at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:87)?
                                                     at android.support.v7.app.AppCompatActivity.getSupportActionBar(AppCompatActivity.java:79)?
                                                     at com.cry.test.ui.base.BaseActivity.initTitle(BaseActivity.java:33)?
                                                     at com.cry.test.ui.base.BaseActivity.onCreate(BaseActivity.java:25)?
                                                     at com.cry.test.ui.SplashActivity.onCreate(SplashActivity.java:60)?
                                                     at com.cry.test.ui.SplashActivity_.onCreate(SplashActivity_.java:41)?
                                                     at android.app.Activity.performCreate(Activity.java:5232)?
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)?
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2272)?
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)?
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:156)?
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)?
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)?
                                                     at android.os.Looper.loop(Looper.java:153)?
                                                     at android.app.ActivityThread.main(ActivityThread.java:5338)?
                                                     at java.lang.reflect.Method.invokeNative(Native Method)?
                                                     at java.lang.reflect.Method.invoke(Method.java:511)?
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)?
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)?
                                                     at dalvik.system.NativeStart.main(Native Method)?
```

**Comment by shwenzhang** [comment]
使用最新的Dev代码， localmaven try一下
