### ISSUE TITLE
集成tinker后导致白屏

### ISSUE THREAD

**Issue by XuZhiFan** [Tencent/tinker#1465]
Describe the bug
E/weex: [WXBridgeManager] invokeInitFramework java.lang.ClassCastException: com.tencent.tinker.loader.TinkerClassLoader cannot be cast to dalvik.system.PathClassLoader
at org.apache.weex.WXEnvironment.findSoPath(WXEnvironment.java:566)
at org.apache.weex.WXEnvironment.getLibJssRealPath(WXEnvironment.java:614)
at org.apache.weex.bridge.WXBridgeManager.assembleDefaultOptions(WXBridgeManager.java:2272)
at org.apache.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:2166)
at org.apache.weex.bridge.WXBridgeManager.access$300(WXBridgeManager.java:147)
at org.apache.weex.bridge.WXBridgeManager$17.run(WXBridgeManager.java:1558)
at org.apache.weex.common.WXThread$SafeRunnable.run(WXThread.java:70)
at android.os.Handler.handleCallback(Handler.java:794)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:176)
at android.os.HandlerThread.run(HandlerThread.java:65)

To Reproduce
集成weex 0.28.0，集成tinker1.9.14.7,运行在android8以上手机

Environment
Device: 小米5x
OS: android
Version 8.0

**Comment by android-huolailai** [comment]
遇到同样的问题，是weex sdk版本的问题吗
