### ISSUE TITLE
最新的tinker-android-lib 1.9.14.8   和crashreport_upgrade:1.4.5  不匹配

### ISSUE THREAD

**Issue by ldmgithub** [Tencent/tinker#1472]
异常类型：app运行时异常/编译异常

手机型号：都会出现

手机系统版本：都会出现

tinker版本：tinker-support:1.2.1 tinker-android-lib 1.9.14.8   和crashreport_upgrade:1.4.5

gradle版本：gradle-4.7-all

是否使用热更新SDK： TinkerPatch SDK

系统：如:window10

堆栈/日志：
tinker-support:1.2.1 tinker-android-lib 1.9.14.7   和crashreport_upgrade:1.4.2  这样搭配没问题
打包运行到手机，点开应用直接崩溃，日志如下:
10-14 16:06:13.803 10441-10441/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cwgj.park.oldfee, PID: 10441
    java.lang.NoSuchMethodError: com.tencent.tinker.loader.app.TinkerApplication.<init>
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.<init>(BUGLY:44)
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1208)
        at android.app.Instrumentation.newApplication(Instrumentation.java:990)
        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:512)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)
        at android.app.ActivityThread.access$1800(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5333)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by liangdong9676** [comment]
哈哈哈，我也发现了这个问题，所以现在用着
tinker-support  1.2.1
tinker-android  1.9.14.7 
crashreport_upgrade:1.3.8

**Comment by liangdong9676** [comment]
官方说得好清楚了。。是不能用自己的Application了。
enableProxyApplication=为true就是无需改造Application，但官方不再维护，bugly只能用到 1.4.5 + 3.7.500 + 1.9.14.7版本。

1.9.14.8和以后的版本，需集成SampleApplicationLike。

目前最新是
api 'com.tencent.bugly:crashreport_upgrade:1.5.0'
api 'com.tencent.bugly:nativecrashreport:3.7.700'
api 'com.tencent.tinker:tinker-android-lib:1.9.14.10'

**Comment by jin123d** [comment]
> 官方说得好清楚了。。是不能用自己的Application了。
> enableProxyApplication=为true就是无需改造Application，但官方不再维护，bugly只能用到 1.4.5 + 3.7.500 + 1.9.14.7版本。
> 
> 1.9.14.8和以后的版本，需集成SampleApplicationLike。
> 
> 目前最新是
> api 'com.tencent.bugly:crashreport_upgrade:1.5.0'
> api 'com.tencent.bugly:nativecrashreport:3.7.700'
> api 'com.tencent.tinker:tinker-android-lib:1.9.14.10'

那com.tencent.bugly:tinker-support:1.2.1 也依然无法在APG3.6+使用啊，请问您是怎么解决的。
