### ISSUE TITLE
没有构造方法： AppApplication extends DefaultApplicationLike

### ISSUE THREAD

**Issue by Lsdjack** [Tencent/tinker#148]
提示没有InstantiationException: class com.phone580.cn.ZhongyuYun.common.AppApplication has no zero argument constructor，
启动报错

                                                                             Caused by: java.lang.InstantiationException: class com.phone580.cn.ZhongyuYun.common.AppApplication has no zero argument constructor
                                                                                at java.lang.Class.newInstance(Class.java:1597)
                                                                                at android.app.Instrumentation.newApplication(Instrumentation.java:995)
                                                                                at android.app.Instrumentation.newApplication(Instrumentation.java:980)
                                                                                at android.app.LoadedApk.makeApplication(LoadedApk.java:560)
                                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556) 
                                                                                at android.app.ActivityThread.access$1500(ActivityThread.java:154) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:135) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
                                                                             Caused by: java.lang.NoSuchMethodException: <init> []
                                                                                at java.lang.Class.getConstructor(Class.java:531)
                                                                                at java.lang.Class.getDeclaredConstructor(Class.java:510)
                                                                                at java.lang.Class.newInstance(Class.java:1595)
                                                                                at android.app.Instrumentation.newApplication(Instrumentation.java:995) 
                                                                                at android.app.Instrumentation.newApplication(Instrumentation.java:980) 
                                                                                at android.app.LoadedApk.makeApplication(LoadedApk.java:560) 
                                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556) 
                                                                                at android.app.ActivityThread.access$1500(ActivityThread.java:154) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:135) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by shwenzhang** [comment]
看文档把，这个是接入不当造成的

**Comment by SuXiGithub** [comment]
现在也碰到这个问题，想问下是怎么解决的吗

**Comment by fengchao1261** [comment]
我也遇到了，已解决。
是因为manifest文件中application的name不能写自己创建的，要写成自动生成的，哈哈
