### ISSUE TITLE
在小米3上运行demo，点击load library发生crash

### ISSUE THREAD

**Issue by liudave** [Tencent/tinker#150]
11-03 14:55:35.449 12638-12638/tinker.sample.android D/AndroidRuntime: Shutting down VM
11-03 14:55:35.451 12638-12638/tinker.sample.android E/Tinker.SampleUncaughtExHandler: uncaughtException:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tinker.sample.android-1/base.apk"],nativeLibraryDirectories=[/data/app/tinker.sample.android-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libstlport_shared.so"
11-03 14:55:35.457 12638-12638/tinker.sample.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: tinker.sample.android, PID: 12638
                                                                       java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tinker.sample.android-1/base.apk"],nativeLibraryDirectories=[/data/app/tinker.sample.android-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libstlport_shared.so"
                                                                           at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                           at java.lang.System.loadLibrary(System.java:1076)
                                                                           at com.tencent.tinker.lib.tinker.TinkerInstaller.loadArmLibrary(TinkerInstaller.java:181)
                                                                           at tinker.sample.android.app.MainActivity$2.onClick(MainActivity.java:68)
                                                                           at android.view.View.performClick(View.java:5207)
                                                                           at android.view.View$PerformClick.run(View.java:21177)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
11-03 14:55:35.476 12638-12638/tinker.sample.android I/Process: Sending signal. PID: 12638 SIG: 9

**Comment by shwenzhang** [comment]
本该如此，这个只是留的接口。好好看文档，看代码

**Comment by deankostomaj** [comment]
Can you please provide an English explanation of this issue.

**Comment by Gh0u1L5** [comment]
@deankostomaj That "libstlport_shared.so" is just a placeholder string to illustrate how to use the API, it's not guaranteed to exist on all the platforms.
