### ISSUE TITLE
在三星GT-N7102，Android：4.1.2出现报错，Tinker Exception:onBaseContextAttached method not found

### ISSUE THREAD

**Issue by taoweiji** [Tencent/tinker#154]
在三星GT-N7102，Android：4.1.2出现报错

java.lang.RuntimeException: Unable to instantiate application co.runner.app.MyApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:501)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4224)
                                                       at android.app.ActivityThread.access$1400(ActivityThread.java:140)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:4921)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
                                                       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:140)
                                                       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154)
                                                       at android.app.Application.attach(Application.java:155)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:998)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:496)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4224) 
                                                       at android.app.ActivityThread.access$1400(ActivityThread.java:140) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:4921) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:138)
                                                       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154) 
                                                       at android.app.Application.attach(Application.java:155) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:998) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:496) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4224) 
                                                       at android.app.ActivityThread.access$1400(ActivityThread.java:140) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:4921) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                       at co.runner.app.SampleApplicationLike.onBaseContextAttached(SampleApplicationLike.java:84)
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:138) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154) 
                                                       at android.app.Application.attach(Application.java:155) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:998) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:496) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4224) 
                                                       at android.app.ActivityThread.access$1400(ActivityThread.java:140) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:137) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:4921) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by taoweiji** [comment]
public class SampleApplicationLike extends DefaultApplicationLike {

    @TargetApi(Build.VERSION_CODES.ICE_CREAM_SANDWICH)
    @Override
    public void onBaseContextAttached(Context base) {
        super.onBaseContextAttached(base);

我已经写了，不知道为什么不行，在5.0没有这个问题

**Comment by taoweiji** [comment]
public class SampleApplicationLike extends DefaultApplicationLike {

    @TargetApi(Build.VERSION_CODES.ICE_CREAM_SANDWICH)
    @Override
    public void onBaseContextAttached(Context base) {
        super.onBaseContextAttached(base);

我已经写了，不知道为什么不行，在5.0没有这个问题

**Comment by taoweiji** [comment]
public class SampleApplicationLike extends DefaultApplicationLike {

    @TargetApi(Build.VERSION_CODES.ICE_CREAM_SANDWICH)
    @Override
    public void onBaseContextAttached(Context base) {
        super.onBaseContextAttached(base);

我已经写了，不知道为什么不行，在5.0没有这个问题

**Comment by taoweiji** [comment]
Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                       at co.runner.app.SampleApplicationLike.onBaseContextAttached(SampleApplicationLike.java:84)
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 

根源好像是这里报错，为什么呢？

**Comment by laobie** [comment]
@taoweiji 哥们你这个问题最后怎么解决的。
