### ISSUE TITLE
红米10X补丁合成成功，但是重启没有效果，同样环境下onePlus 8手机是正常有效的

### ISSUE THREAD

**Issue by liuchunboVampire** [Tencent/tinker#1555]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：红米10X   onApplySuccess()回调方法弹出补丁合成成功，但是重启没有效果，同样环境下onePlus 8手机是正常有效的

手机型号：红米10X

手机系统版本：如:Android 10

tinker版本：1.9.14.7

gradle版本：  /**
     * tinker-support 1.2.1
     * tinker-android 1.9.14.7
     * crashreport_upgrade:1.4.5
     */

是否使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK

系统：如:Windows10

堆栈/日志：
2021-04-27 09:55:50.384 11423-11423/? D/Tinker.TinkerLoader: tryLoad test test
2021-04-27 09:55:50.388 11423-11423/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.example.buglydemo/tinker
2021-04-27 09:55:50.388 11423-11423/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2021-04-27 09:55:50.392 11423-11423/? I/Tinker.TinkerPatchListener: application maxMemory:256
2021-04-27 09:55:50.393 11423-11423/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.example.buglydemo/tinker
2021-04-27 09:55:50.393 11423-11423/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.7
2021-04-27 09:55:50.393 11423-11423/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.example.buglydemo, main process:true, systemOTA:false, fingerPrint:Redmi/atom/atom:10/QP1A.190711.020/V12.0.5.0.QJHCNXM:user/release-keys, oatDir:null, useInterpretMode:false
2021-04-27 09:55:50.393 11423-11423/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2021-04-27 09:55:50.393 11423-11423/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.example.buglydemo/tinker, code: -2, cost: 5ms
2021-04-27 09:55:50.393 11423-11423/? W/Tinker.Tinker: tinker load fail!
2021-04-27 09:55:50.400 11423-11423/? D/Tinker.DefaultAppLike: onCreate
2021-04-27 09:55:50.404 11423-11423/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@f742014
2021-04-27 09:55:50.546 11423-11423/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
2021-04-27 09:55:59.089 11423-11423/? D/Tinker.TinkerManager: onDownloadSuccess.
2021-04-27 09:55:59.124 11423-11423/? D/Tinker.TinkerManager: check if has new patch.
2021-04-27 09:55:59.128 11423-11423/? D/Tinker.TinkerManager: has new patch.
2021-04-27 09:55:59.128 11423-11423/? D/Tinker.TinkerManager: starting patch.
2021-04-27 09:55:59.129 11423-11423/? I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/com.example.buglydemo/app_tmpPatch/tmpPatch.apk, file size:4894
2021-04-27 09:55:59.132 11423-11423/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.example.buglydemo/tinker/patch.info: open failed: ENOENT (No such file or directory)
2021-04-27 09:55:59.132 11423-11423/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.example.buglydemo/tinker/patch.info: open failed: ENOENT (No such file or directory)
2021-04-27 09:55:59.132 11423-11423/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
2021-04-27 09:55:59.133 11423-11423/? I/Tinker.TinkerPatchListener: get platform:null
2021-04-27 09:55:59.135 11423-11423/? I/Tinker.TinkerPatchService: run patch service...
2021-04-27 09:55:59.180 1301-1342/? D/Boost: hostingType=service, hostingName={com.example.buglydemo/com.tencent.tinker.lib.service.TinkerPatchForeService}, callerPackage=com.example.buglydemo, isSystem=false, isBoostNeeded=false.
2021-04-27 09:55:59.181 1301-1342/? I/ActivityManager: Start proc 11750:com.example.buglydemo:patch/u0a277 for service {com.example.buglydemo/com.tencent.tinker.lib.service.TinkerPatchForeService} caller=com.example.buglydemo
2021-04-27 09:55:59.238 11750-11750/? D/Tinker.TinkerLoader: tryLoad test test
2021-04-27 09:55:59.239 11750-11750/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
2021-04-27 09:55:59.239 11750-11750/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2021-04-27 09:55:59.244 11750-11750/? I/Tinker.TinkerPatchListener: application maxMemory:256
2021-04-27 09:55:59.245 11750-11750/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.example.buglydemo/tinker
2021-04-27 09:55:59.245 11750-11750/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.7
2021-04-27 09:55:59.245 11750-11750/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.example.buglydemo:patch, main process:false, systemOTA:false, fingerPrint:Redmi/atom/atom:10/QP1A.190711.020/V12.0.5.0.QJHCNXM:user/release-keys, oatDir:null, useInterpretMode:false
2021-04-27 09:55:59.245 11750-11750/? W/Tinker.TinkerLoadResult: tinker is disable, just return
2021-04-27 09:55:59.245 11750-11750/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.example.buglydemo/tinker, code: -1, cost: 0ms
2021-04-27 09:55:59.245 11750-11750/? W/Tinker.Tinker: tinker load fail!
2021-04-27 09:55:59.249 11750-11750/? D/Tinker.DefaultAppLike: onCreate
2021-04-27 09:55:59.254 11750-11750/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@4bc6e26
2021-04-27 09:55:59.268 11750-11784/? I/Tinker.TinkerPatchService: for system version >= Android O, we just ignore increasingPriority job to avoid crash or toasts.
2021-04-27 09:55:59.268 11750-11784/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
2021-04-27 09:55:59.269 11750-11784/? W/Tinker.UpgradePatchRetry: try copy file: /data/user/0/com.example.buglydemo/app_tmpPatch/tmpPatch.apk to /data/user/0/com.example.buglydemo/tinker_temp/temp.apk
2021-04-27 09:55:59.269 11750-11750/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2021-04-27 09:55:59.286 11750-11784/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:0b21a641701a180af12c7143b45c46fe
2021-04-27 09:55:59.287 11750-11784/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.example.buglydemo/tinker/patch.info: open failed: ENOENT (No such file or directory)
2021-04-27 09:55:59.287 11750-11784/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.example.buglydemo/tinker/patch.info: open failed: ENOENT (No such file or directory)
2021-04-27 09:55:59.287 11750-11784/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.example.buglydemo/tinker/patch-0b21a641
2021-04-27 09:55:59.289 11750-11784/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.example.buglydemo/app_tmpPatch/tmpPatch.apk size: 4894, dest file: /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/patch-0b21a641.apk size:4894
2021-04-27 09:55:59.291 11750-11784/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/classes.dex.jar
2021-04-27 09:55:59.293 11750-11784/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2021-04-27 09:55:59.294 11750-11784/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/test.dex.jar
2021-04-27 09:55:59.296 11750-11784/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2021-04-27 09:55:59.298 11750-11784/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/test.dex.jar
2021-04-27 09:55:59.298 11750-11784/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/classes.dex.jar
2021-04-27 09:55:59.298 11750-11784/? I/Tinker.DexDiffPatchInternal: merge classN dex file /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/tinker_classN.apk, result: true, size: 3413, use: 2ms
2021-04-27 09:55:59.299 11750-11784/? I/Tinker.DexDiffPatchInternal: legal files to do dexopt: [/data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/tinker_classN.apk]
2021-04-27 09:55:59.300 11750-11784/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm64
2021-04-27 09:55:59.300 11750-11784/? I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:1, optimizeDexDirectory:/data/user/0/com.example.buglydemo/tinker/patch-0b21a641/odex/
2021-04-27 09:55:59.300 11750-11784/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/tinker_classN.apk, size: 3413
2021-04-27 09:55:59.300 11750-11784/? I/Tinker.TinkerInternals: class not found exception
2021-04-27 09:55:59.302 11750-11784/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/tinker_classN.apk, opt file:/data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/oat/arm64/tinker_classN.odex, opt file size: 0, use time 2
2021-04-27 09:55:59.302 11750-11784/? I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:14
2021-04-27 09:55:59.302 11750-11784/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
2021-04-27 09:55:59.302 11750-11784/? W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
2021-04-27 09:55:59.303 11750-11784/? I/Tinker.DexDiffPatchInternal: raw dex count: 2, dex opt dex count: 1, final wait times: 60
2021-04-27 09:55:59.308 11750-11784/? I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/oat/arm64/tinker_classN.odex, size 0
2021-04-27 09:55:59.309 11750-11784/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.example.buglydemo/tinker/patch.info , oldVer:, newVer:0b21a641701a180af12c7143b45c46fe, isProtectedApp:1, isRemoveNewVersion:0, fingerprint:Redmi/atom/atom:10/QP1A.190711.020/V12.0.5.0.QJHCNXM:user/release-keys, oatDir:odex, isRemoveInterpretOATDir:0
2021-04-27 09:55:59.310 11750-11784/? I/Tinker.UpgradePatchRetry: onPatchResetMaxCheck, reset max check to 1
2021-04-27 09:55:59.310 11750-11784/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
2021-04-27 09:55:59.311 11750-11784/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /data/user/0/com.example.buglydemo/app_tmpPatch/tmpPatch.apk, success: true, cost: 39
2021-04-27 09:55:59.311 11750-11784/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.example.buglydemo/tinker_temp/temp.apk
2021-04-27 09:55:59.317 11423-11795/? I/Tinker.TinkerResultService: TinkerResultService receive result: 
    PatchResult: 
    isSuccess:true
    rawPatchFilePath:/data/user/0/com.example.buglydemo/app_tmpPatch/tmpPatch.apk
    costTime:39
    patchVersion:0b21a641701a180af12c7143b45c46fe
2021-04-27 09:55:59.319 11423-11795/? W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /data/user/0/com.example.buglydemo/app_tmpPatch/tmpPatch.apk
2021-04-27 09:55:59.319 11423-11423/? I/CrashReport: Tinker patch success, result: 
    PatchResult: 
    isSuccess:true
    rawPatchFilePath:/data/user/0/com.example.buglydemo/app_tmpPatch/tmpPatch.apk
    costTime:39
    patchVersion:0b21a641701a180af12c7143b45c46fe
2021-04-27 09:55:59.319 11423-11795/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.example.buglydemo/app_tmpPatch/tmpPatch.apk
2021-04-27 09:55:59.319 11423-11795/? I/Tinker.TinkerResultService: tinker wait screen to restart process
2021-04-27 09:55:59.358 1301-2124/? W/ActivityManager: Exception when unbinding service com.example.buglydemo/com.tencent.tinker.lib.service.TinkerPatchForeService
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:511)
        at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1663)
        at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:3235)
        at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:1960)
        at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:14536)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2382)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2834)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2021-04-27 09:56:09.880 11893-11893/? D/Tinker.TinkerLoader: tryLoad test test
2021-04-27 09:56:09.891 11893-11893/? I/Tinker.TinkerInternals: class not found exception
2021-04-27 09:56:09.892 11893-11893/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm64
2021-04-27 09:56:09.892 11893-11893/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2021-04-27 09:56:09.892 11893-11893/? D/Tinker.TinkerInternals: same fingerprint:Redmi/atom/atom:10/QP1A.190711.020/V12.0.5.0.QJHCNXM:user/release-keys
2021-04-27 09:56:09.893 11893-11893/? W/Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_com.example.buglydemo count:0
2021-04-27 09:56:09.895 11893-11893/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.example.buglydemo count:1
2021-04-27 09:56:09.896 11893-11893/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.buglydemo-qwK1pQE4uGAVPpLF51fOTg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.buglydemo-qwK1pQE4uGAVPpLF51fOTg==/lib/arm64, /data/app/com.example.buglydemo-qwK1pQE4uGAVPpLF51fOTg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]]
2021-04-27 09:56:09.896 11893-11893/? I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/tinker_classN.apk md5, use time: 0
2021-04-27 09:56:09.896 11893-11893/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.example.buglydemo/tinker/patch-0b21a641/odex, dex size:1
2021-04-27 09:56:09.898 11893-11893/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/com.example.buglydemo/tinker/patch-0b21a641/dex/tinker_classN.apk", zip file "/data/app/com.example.buglydemo-qwK1pQE4uGAVPpLF51fOTg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.buglydemo-qwK1pQE4uGAVPpLF51fOTg==/lib/arm64, /data/app/com.example.buglydemo-qwK1pQE4uGAVPpLF51fOTg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]], dex size:1
2021-04-27 09:56:09.898 11893-11893/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
2021-04-27 09:56:09.898 11893-11893/? I/Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
2021-04-27 09:56:09.898 11893-11893/? I/Tinker.AppInfoChangedBlocker: tryStart called.
2021-04-27 09:56:09.899 11893-11893/? I/Tinker.AppInfoChangedBlocker: tryStart done.
2021-04-27 09:56:09.899 11893-11893/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.example.buglydemo/tinker/patch.info , oldVer:0b21a641701a180af12c7143b45c46fe, newVer:0b21a641701a180af12c7143b45c46fe, isProtectedApp:1, isRemoveNewVersion:0, fingerprint:Redmi/atom/atom:10/QP1A.190711.020/V12.0.5.0.QJHCNXM:user/release-keys, oatDir:odex, isRemoveInterpretOATDir:0
2021-04-27 09:56:09.900 11893-11893/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
2021-04-27 09:56:09.901 11893-11893/? D/Tinker.DefaultAppLike: onBaseContextAttached:
2021-04-27 09:56:09.905 11893-11893/? I/Tinker.TinkerPatchListener: application maxMemory:256
2021-04-27 09:56:09.906 11893-11893/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.example.buglydemo/tinker
2021-04-27 09:56:09.906 11893-11893/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.7
2021-04-27 09:56:09.906 11893-11893/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.example.buglydemo, main process:true, systemOTA:false, fingerPrint:Redmi/atom/atom:10/QP1A.190711.020/V12.0.5.0.QJHCNXM:user/release-keys, oatDir:odex, useInterpretMode:false
2021-04-27 09:56:09.906 11893-11893/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:0b21a641701a180af12c7143b45c46fe, current:0b21a641701a180af12c7143b45c46fe
2021-04-27 09:56:09.906 11893-11893/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
2021-04-27 09:56:09.906 11893-11893/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchVersionChanged: patch version change from  to 0b21a641701a180af12c7143b45c46fe
2021-04-27 09:56:09.906 11893-11893/? I/Tinker.UpgradePatchRetry: onPatchResetMaxCheck, reset max check to 1
2021-04-27 09:56:09.907 11893-11893/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.example.buglydemo/tinker, code: 0, cost: 21ms
2021-04-27 09:56:09.908 11893-11893/? W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.example.buglydemo count:0
2021-04-27 09:56:09.933 11893-11893/? I/Tinker.AppInfoChangedBlocker: tryStart called.
2021-04-27 09:56:09.933 11893-11893/? W/Tinker.AppInfoChangedBlocker: Already intercepted, skip rest logic.
2021-04-27 09:56:09.933 11893-11893/? I/Tinker.AppInfoChangedBlocker: tryStart done.
2021-04-27 09:56:09.933 11893-11893/? D/Tinker.DefaultAppLike: onCreate
2021-04-27 09:56:09.938 11893-11893/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@3b789dc
2021-04-27 09:56:10.100 11893-11893/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.example.buglydemo/tinker_temp/temp.apk is not exist, just return

**Comment by zhangwanggit** [comment]
我的问题是打开了isProtectedApp开关，但是修复的是未加固的包导致的问题，如果修复的是加固后的，就没有问题。https://www.jianshu.com/p/b4df056c02cf
