### ISSUE TITLE
补丁只生效1次再次重启APP补丁失效

### ISSUE THREAD

**Issue by srxffcc1** [Tencent/tinker#1566]
异常类型：app运行时异常

手机型号：如:OnePlus

手机系统版本：如:Android 5.0 (如是编译异常，则可以不填)

tinker版本：如:1.9.14.16

gradle版本：如:3.6.1

是否使用热更新SDK： Bugly SDK

系统：如:Windows

堆栈/日志：

问题描述  第一次应用补丁成功之后 提示重启 重启ok之后 ok补丁生效了 然后手动杀死进程再进APP 补丁不生效了 多次重启也没用

**Comment by srxffcc1** [comment]
2021-05-22 17:55:48.230 16208-16208/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3, process name:com.health.client:pushcore, main process:false, systemOTA:false, fingerPrint:OnePlus/OnePlus7_CH/OnePlus7:11/RKQ1.201022.002/2104052322:user/release-keys, oatDir:null, useInterpretMode:false

**Comment by srxffcc1** [comment]
杀死进程之后重新加载报这个错

**Comment by srxffcc1** [comment]
2021-05-22 17:59:33.372 12456-12456/? E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:73)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:191)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:325)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:119)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:157)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:180)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:1)
        at android.app.Application.attach(Application.java:371)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1165)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6957)
        at android.app.ActivityThread.access$1700(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by srxffcc1** [comment]
但是这时候是生效的 然后再杀死进程 再进入APP就 不生效了

**Comment by srxffcc1** [comment]
tryLoadPatchFiles:patch info not exist:/data/user/0/com.health.client/tinker/patch.info

**Comment by srxffcc1** [comment]
2021-05-23 10:16:34.016 10531-10531/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.health.client/tinker/patch-65691640/odex, dex size:1
2021-05-23 10:16:34.166 10531-10531/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.DelegateLastClassLoader[DexPathList[[zip file "/data/user/0/com.health.client/tinker/patch-65691640/dex/tinker_classN.apk"],nativeLibraryDirectories=[/data/app/~~AzGMwxHK7E9foFF_6z4pJw==/com.health.client-z05_e-KGoG5rlcQbdSGssg==/lib/arm, /data/app/~~AzGMwxHK7E9foFF_6z4pJw==/com.health.client-z05_e-KGoG5rlcQbdSGssg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/system_ext/lib]]], dex size:1
2021-05-23 10:16:34.166 10531-10531/? W/Tinker.ClassLoaderAdder: checkDexInstall result:false

**Comment by srxffcc1** [comment]
2021-05-23 10:16:34.193 10531-10531/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2021-05-23 10:16:34.194 10531-10531/? E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:73)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:191)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:325)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:119)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:157)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:180)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:1)
        at android.app.Application.attach(Application.java:371)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1165)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6957)
        at android.app.ActivityThread.access$1700(ActivityThread.java:274)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by srxffcc1** [comment]
看起来是成功之后有个地方报错了 导致的回退

**Comment by srxffcc1** [comment]
![image](https://user-images.githubusercontent.com/14032777/119246726-7e292600-bbb6-11eb-99f9-02a875e82f74.png)
应该是此处做了二次验证导致的

**Comment by srxffcc1** [comment]
因为上面已经加载了 所以会展示一个假象的打上补丁 然后下面又卸载掉了 然后 下次重启就导致了 这块补丁没了

**Comment by srxffcc1** [comment]
暂时使用这种办法修复了 这个问题 
![image](https://user-images.githubusercontent.com/14032777/119247586-5be6d680-bbbd-11eb-9140-81a80d0fa532.png)
然后
![image](https://user-images.githubusercontent.com/14032777/119247596-74ef8780-bbbd-11eb-99ca-9666ce16944e.png)
只能先注释掉了 后续有了更好的方法再看看怎么解决吧

**Comment by cyf1161265793** [comment]
我也遇到这个问题了，你是下载了loader的源码吗？


> 暂时使用这种办法修复了 这个问题
> ![image](https://user-images.githubusercontent.com/14032777/119247586-5be6d680-bbbd-11eb-9140-81a80d0fa532.png)
> 然后
> ![image](https://user-images.githubusercontent.com/14032777/119247596-74ef8780-bbbd-11eb-99ca-9666ce16944e.png)
> 只能先注释掉了 后续有了更好的方法再看看怎么解决吧



> ![image](https://user-images.githubusercontent.com/14032777/119246726-7e292600-bbb6-11eb-99f9-02a875e82f74.png)
> 应该是此处做了二次验证导致的

请问你是怎么做的呢？

**Comment by srxffcc1** [comment]
> 我也遇到这个问题了，你是下载了loader的源码吗？
> 
> > 暂时使用这种办法修复了 这个问题
> > ![image](https://user-images.githubusercontent.com/14032777/119247586-5be6d680-bbbd-11eb-9140-81a80d0fa532.png)
> > 然后
> > ![image](https://user-images.githubusercontent.com/14032777/119247596-74ef8780-bbbd-11eb-99ca-9666ce16944e.png)
> > 只能先注释掉了 后续有了更好的方法再看看怎么解决吧
> 
> > ![image](https://user-images.githubusercontent.com/14032777/119246726-7e292600-bbb6-11eb-99f9-02a875e82f74.png)
> > 应该是此处做了二次验证导致的
> 
> 请问你是怎么做的呢？

我们不是已经微信私聊过了吗

**Comment by linzhongshu** [comment]
> 暂时使用这种办法修复了 这个问题
> ![image](https://user-images.githubusercontent.com/14032777/119247586-5be6d680-bbbd-11eb-9140-81a80d0fa532.png)
> 然后
> ![image](https://user-images.githubusercontent.com/14032777/119247596-74ef8780-bbbd-11eb-99ca-9666ce16944e.png)
> 只能先注释掉了 后续有了更好的方法再看看怎么解决吧

我也遇到了这样的情况，请问这个怎么做的啊？

**Comment by srxffcc1** [comment]
> > 暂时使用这种办法修复了 这个问题
> > ![image](https://user-images.githubusercontent.com/14032777/119247586-5be6d680-bbbd-11eb-9140-81a80d0fa532.png)
> > 然后
> > ![image](https://user-images.githubusercontent.com/14032777/119247596-74ef8780-bbbd-11eb-99ca-9666ce16944e.png)
> > 只能先注释掉了 后续有了更好的方法再看看怎么解决吧
> 
> 我也遇到了这样的情况，请问这个怎么做的啊？

哦 拷贝源码 直接替换掉这个库不就行了吗 
![image](https://user-images.githubusercontent.com/14032777/132298301-2fb166f4-056c-43b9-bde2-87c9fd4710db.png)

**Comment by linzhongshu** [comment]
> > > 暂时使用这种办法修复了 这个问题
> > > ![image](https://user-images.githubusercontent.com/14032777/119247586-5be6d680-bbbd-11eb-9140-81a80d0fa532.png)
> > > 然后
> > > ![image](https://user-images.githubusercontent.com/14032777/119247596-74ef8780-bbbd-11eb-99ca-9666ce16944e.png)
> > > 只能先注释掉了 后续有了更好的方法再看看怎么解决吧
> > 
> > 
> > 我也遇到了这样的情况，请问这个怎么做的啊？
> 
> 哦 拷贝源码 直接替换掉这个库不就行了吗
> ![image](https://user-images.githubusercontent.com/14032777/132298301-2fb166f4-056c-43b9-bde2-87c9fd4710db.png)
我试试，3q

**Comment by linzhongshu** [comment]
te

> 异常类型：app运行时异常
> 
> 手机型号:OnePlus
> 
> 手机系统版本:Android 11
> 
> tinker版本:1.9.14.16
> 
> gradle版本:3.6.1
> 
> 是否使用热更新SDK： Bugly SDK
> 
> 系统:Windows
> 
> 堆栈/日志：
> 
> 问题描述 第一次应用补丁成功之后 提示重启 重启ok之后 ok补丁生效了 然后手动杀死进程再进APP 补丁不生效了 多次重启也没用

tinker-support:1.2.3 么？

**Comment by linzhongshu** [comment]
![QQ截图20210907165358](https://user-images.githubusercontent.com/10766636/132315633-d970f1bd-17ae-42f4-ac22-3abff31741b7.png)
打补丁包有出现这情况么？

**Comment by srxffcc1** [comment]
> ![QQ截图20210907165358](https://user-images.githubusercontent.com/10766636/132315633-d970f1bd-17ae-42f4-ac22-3abff31741b7.png)
> 打补丁包有出现这情况么？

因为源码是最新的 所以只能用最新的补丁版本 进行拦截替换掉这个库

**Comment by linzhongshu** [comment]
> 因为源码是最新的 所以只能用最新的补丁版本 进行拦截替换掉这个库

用你的方法解决了，感谢。也不知道具体造成这个问题的原因，我看以前的库也是这样子的。会不会是>=21 分包的问题？

**Comment by qianqianyixia** [comment]
请问现在这个问题好了么 我用最新版本1.9.14.24的sdk 也遇到这个问题了

**Comment by pengyongshun** [comment]
我用最新版本1.9.14.25的sdk 也遇到这个问题了,按照上面的方式修改后还是不行
