### ISSUE TITLE
编译打包后运行就闪退

### ISSUE THREAD

**Issue by AtenzaZoom** [Tencent/tinker#1574]
异常类型：app运行时异常

手机型号：索尼 xperia xz premium

手机系统版本：Android 9.0 

tinker版本：1.9.14.11

gradle版本：4.0.1

系统：Windows

堆栈/日志：
java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/String;Ljava/lang/String;Z)V in class Lcom/tencent/tinker/loader/app/TinkerApplication; or its super classes (declaration of 'com.tencent.tinker.loader.app.TinkerApplication' appears in base.apk!classes3.dex)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.<init>(BUGLY:2)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:1)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1066)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5870)
        at android.app.ActivityThread.access$1100(ActivityThread.java:205)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6706)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

采用的是enableProxyApplication  = false的形式接入，即继承TinkerApplication并新建SampleApplicationLike

**Comment by srxffcc1** [comment]
建议查看下 bugly报什么错 然后检查下 基准包打包时的依赖版本是不是都是有明确版本号的 排查 latest这种问题 导致基准包和补丁包 某种so依赖不一致没替换等问题

**Comment by shixiangyu** [comment]
是release包吗，如果是，是否开启R8,如果以上都满足，关闭R8试试
