### ISSUE TITLE
华为Android 10设备执行oat时出现 java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by noproxy** [Tencent/tinker#1591]
异常类型：app运行时异常
手机型号：线上数据均为，各种华为手机, 排行多的机型为： STK-AL00, JSN-AL00A, GLK-AL00, HRY-AL00A, MAR-AL00
手机系统版本：Android 10.0， SDK 29
tinker版本：如: 1.9.14.17
是否使用热更新SDK：只使用Tinker

堆栈：

```

java.lang.AbstractMethodError

abstract method "void android.content.pm.PackageManager$DexModuleRegisterCallback.onDexModuleRegistered(java.lang.String, boolean, java.lang.String)"
android.app.ApplicationPackageManager$DexModuleRegisterCallbackDelegate.handleMessage(ApplicationPackageManager.java:3067)
android.os.Handler.dispatchMessage(Handler.java:103)
android.os.Looper.loop(Looper.java:213)
android.app.ActivityThread.main(ActivityThread.java:8178)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
```

日志
```
789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ksad_bottom_ad_tag_icon.png, file size:380, use time:4
--
108-03 10:50:46.793 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xhdpi-v4/tt_shadow_lefterback_titlebar_press_withoutnight.png
208-03 10:50:46.795 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
308-03 10:50:46.795 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xhdpi-v4/tt_shadow_lefterback_titlebar_press_withoutnight.png, file size:262, use time:2
408-03 10:50:46.796 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/card_wechat.png
508-03 10:50:46.799 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
608-03 10:50:46.799 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/card_wechat.png, file size:67, use time:3
708-03 10:50:46.800 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/report_page_back_icon.png
808-03 10:50:46.801 1403 1403 I IActivityTaskManager: invoke: activitySlept()
908-03 10:50:46.802 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
1008-03 10:50:46.802 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/report_page_back_icon.png, file size:597, use time:2
1108-03 10:50:46.803 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/era_morning_bag.png
1208-03 10:50:46.811 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
1308-03 10:50:46.812 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/era_morning_bag.png, file size:153762, use time:8
1408-03 10:50:46.812 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/vip_head_img_ad_launcher.png
1508-03 10:50:46.814 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
1608-03 10:50:46.815 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/vip_head_img_ad_launcher.png, file size:14475, use time:3
1708-03 10:50:46.815 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ksad_photo_more_button_2_bg.png
1808-03 10:50:46.817 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
1908-03 10:50:46.818 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ksad_photo_more_button_2_bg.png, file size:2410, use time:3
2008-03 10:50:46.818 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable/ssp_guide_icon_normal.png
2108-03 10:50:46.820 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
2208-03 10:50:46.822 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable/ssp_guide_icon_normal.png, file size:1247, use time:3
2308-03 10:50:46.822 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/abc_text_select_handle_middle_mtrl.png
2408-03 10:50:46.825 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
2508-03 10:50:46.826 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/abc_text_select_handle_middle_mtrl.png, file size:753, use time:3
2608-03 10:50:46.826 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/mipmap-mdpi-v4/test.png
2708-03 10:50:46.828 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
2808-03 10:50:46.829 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/mipmap-mdpi-v4/test.png, file size:4054, use time:3
2908-03 10:50:46.830 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ttdp_report_radio_select.png
3008-03 10:50:46.832 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
3108-03 10:50:46.832 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ttdp_report_radio_select.png, file size:908, use time:2
3208-03 10:50:46.833 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ttdp_report_radio.png
3308-03 10:50:46.835 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
3408-03 10:50:46.835 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ttdp_report_radio.png, file size:641, use time:3
3508-03 10:50:46.836 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-hdpi-v4/gdt_ic_express_play.png
3608-03 10:50:46.838 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
3708-03 10:50:46.839 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-hdpi-v4/gdt_ic_express_play.png, file size:67, use time:3
3808-03 10:50:46.839 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ic_func_wallpaper.png
3908-03 10:50:46.841 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
4008-03 10:50:46.842 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ic_func_wallpaper.png, file size:67, use time:3
4108-03 10:50:46.843 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ksad_photo_hot_enter_label.webp
4208-03 10:50:46.845 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
4308-03 10:50:46.846 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ksad_photo_hot_enter_label.webp, file size:1098, use time:4
4408-03 10:50:46.846 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxxhdpi-v4/outline_close_black_24.png
4508-03 10:50:46.848 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
4608-03 10:50:46.849 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxxhdpi-v4/outline_close_black_24.png, file size:328, use time:3
4708-03 10:50:46.850 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xhdpi-v4/picker_close.png
4808-03 10:50:46.852 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
4908-03 10:50:46.853 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xhdpi-v4/picker_close.png, file size:67, use time:4
5008-03 10:50:46.854 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/gdt_ic_volume_on.png
5108-03 10:50:46.856 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
5208-03 10:50:46.860 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/gdt_ic_volume_on.png, file size:67, use time:5
5308-03 10:50:46.860 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/icon_ice.png
5408-03 10:50:46.862 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
5508-03 10:50:46.863 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/icon_ice.png, file size:5223, use time:3
5608-03 10:50:46.863 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xhdpi-v4/icon_wifi_connect_light1.png
5708-03 10:50:46.865 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
5808-03 10:50:46.866 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xhdpi-v4/icon_wifi_connect_light1.png, file size:2233, use time:2
5908-03 10:50:46.866 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ksad_func_button_media_share.webp
6008-03 10:50:46.868 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
6108-03 10:50:46.869 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ksad_func_button_media_share.webp, file size:6980, use time:3
6208-03 10:50:46.871 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/home_guide_av.png
6308-03 10:50:46.874 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
6408-03 10:50:46.874 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/home_guide_av.png, file size:13908, use time:4
6508-03 10:50:46.875 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ttdp_report_btn.png
6608-03 10:50:46.878 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
6708-03 10:50:46.878 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ttdp_report_btn.png, file size:2111, use time:4
6808-03 10:50:46.879 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ares_app_more.png
6908-03 10:50:46.882 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
7008-03 10:50:46.883 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ares_app_more.png, file size:317, use time:3
7108-03 10:50:46.884 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ksad_content_feed_item_video_play_img.webp
7208-03 10:50:46.888 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
7308-03 10:50:46.889 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ksad_content_feed_item_video_play_img.webp, file size:2024, use time:4
7408-03 10:50:46.889 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
7508-03 10:50:46.892 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
7608-03 10:50:46.893 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png, file size:186, use time:4
7708-03 10:50:46.893 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ttdp_video_fullscreen_no.png
7808-03 10:50:46.896 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
7908-03 10:50:46.897 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-xxhdpi-v4/ttdp_video_fullscreen_no.png, file size:226, use time:3
8008-03 10:50:46.898 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: try Extracting /data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-hdpi-v4/notification_bg_normal.9.png
8108-03 10:50:46.900 18339 19789 E Tinker.BasePatchInternal: !! NO_LOG_IMPL !! Original Log: isExtractionSuccessful: true
8208-03 10:50:46.901 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover store file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/res/drawable-hdpi-v4/notification_bg_normal.9.png, file size:212, use time:3
8308-03 10:50:46.914 18339 19789 I ton.clean:patc: IncrementDisableThreadFlip blocked for 7.020ms
8408-03 10:50:47.094 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover large modify file:/data/user/0/dr.newton.clean/tinker/patch-8c9c5d3a/res/res_temp/resources.arsc, file size:2020744, use time:193
8508-03 10:50:47.095 18339 19789 E Tinker.ResDiffPatchInternal: !! NO_LOG_IMPL !! Original Log: success recover all large modify and store resources use time:10668
8608-03 10:50:48.225 1403 1403 I IActivityTaskManager: invoke: activitySlept()
8708-03 10:50:48.617 1403 1403 I IActivityTaskManager: invoke: activitySlept()
88--------- beginning of crash
8908-03 10:50:49.367 18339 18339 E AndroidRuntime: FATAL EXCEPTION: main
9008-03 10:50:49.367 18339 18339 E AndroidRuntime: Process: dr.newton.clean:patch, PID: 18339
9108-03 10:50:49.367 18339 18339 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void android.content.pm.PackageManager$DexModuleRegisterCallback.onDexModuleRegistered(java.lang.String, boolean, java.lang.String)"
9208-03 10:50:49.367 18339 18339 E AndroidRuntime: at android.app.ApplicationPackageManager$DexModuleRegisterCallbackDelegate.handleMessage(ApplicationPackageManager.java:3067)
9308-03 10:50:49.367 18339 18339 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
9408-03 10:50:49.367 18339 18339 E AndroidRuntime: at android.os.Looper.loop(Looper.java:213)
9508-03 10:50:49.367 18339 18339 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8178)
9608-03 10:50:49.367 18339 18339 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
9708-03 10:50:49.367 18339 18339 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
9808-03 10:50:49.367 18339 18339 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
9908-03 10:50:49.373 18339 18339 W hera.see: evaluate: MyExceptionInfo{message='abstract method "void android.content.pm.PackageManager$DexModuleRegisterCallback.onDexModuleRegistered(java.lang.String, boolean, java.lang.String)"', classname='java.lang.AbstractMethodError', stackTrace='java.lang.AbstractMethodError: abstract method "void android.content.pm.PackageManager$DexModuleRegisterCallback.onDexModuleRegistered(java.lang.String, boolean, java.lang.String)"
10008-03 10:50:49.373 18339 18339 W hera.see: at android.app.ApplicationPackageManager$DexModuleRegisterCallbackDelegate.handleMessage(ApplicationPackageManager.java:3067)
10108-03 10:50:49.373 18339 18339 W hera.see: at android.os.Handler.dispatchMessage(Handler.java:103)
10208-03 10:50:49.373 18339 18339 W hera.see: at android.os.Looper.loop(Looper.java:213)
10308-03 10:50:49.373 18339 18339 W hera.see: at android.app.ActivityThread.main(ActivityThread.java:8178)
10408-03 10:50:49.373 18339 18339 W hera.see: at java.lang.reflect.Method.invoke(Native Method)
10508-03 10:50:49.373 18339 18339 W hera.see: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10608-03 10:50:49.373 18339 18339 W hera.see: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
10708-03 10:50:49.373 18339 18339 W hera.see: ', threadName='main', isMainThread=true, causesMessages=[abstract method "void android.content.pm.PackageManager$DexModuleRegisterCallback.onDexModuleRegistered(java.lang.String, boolean, java.lang.String)"], causesClassNames=[java.lang.AbstractMethodError]}
10808-03 10:50:49.374 18339 18339 V hera.cueh: not capture exception java.lang.AbstractMethodError: abstract method "void android.content.pm.PackageManager$DexModuleRegisterCallback.onDexModuleRegistered(java.lang.String, boolean, java.lang.String)"
10908-03 10:50:51.210 1403 1403 I IActivityTaskManager: invoke: activitySlept()
11008-03 10:50:51.429 18339 11473 E BasicInfoCollector: process=dr.newton.clean:patch;channelId=255068;vn=1.2.4.1101;vc=16;sigHashMd5=2d58a74329e4ea598b0cb83fdd56e116
```

这个问题是这里引起的：
https://github.com/Tencent/tinker/blob/612aa2820fc297bec751064c390fdbfd0466c88d/tinker-android/tinker-android-loader/src/main/java/com/tencent/tinker/loader/TinkerDexOptimizer.java#L200-L204

这个崩溃在我的测试设备上必现，在注释掉这里对华为Android SDK 29的设备的特殊处理之后，崩溃消失，并且仍然能够正常安装补丁，并且生效。华为设备还没有找到有Android SDK 30的机型，未能测试。

想问下这里的这块特殊处理是为了解决什么问题？如果这里不能注释掉的话，是否有别的修复方式？

**Comment by AriaLyy** [comment]
+1 遇到了同样的问题

**Comment by AriaLyy** [comment]
貌似是混淆问题 https://github.com/Tencent/tinker/issues/1591
