### ISSUE TITLE
android11运行时合成补丁报错

### ISSUE THREAD

**Issue by igottime** [Tencent/tinker#1597]
异常类型：app运行时异常

手机型号：小米11

手机系统版本：Android 11

tinker版本：1.9.14.17

gradle版本：4.1.1

是否使用热更新SDK： 否

系统：Win

（在华为P10 Android9上没问题）

2021-08-27 15:33:46.980 30469-30469/? W/Tinker.MyLogImp: new log level: 3
2021-08-27 15:33:46.983 30469-30469/? W/Tinker.Tinker: tinker patch directory: /data/user/0/*****/tinker
2021-08-27 15:33:46.983 30469-30469/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2021-08-27 15:33:46.983 30469-30469/? W/Tinker.Tinker: tinker load fail!
2021-08-27 15:33:47.164 30469-30469/? W/Tinker.TinkerLoader: [PendingLog @ 2021-08-27 15:33:46.972] tryLoadPatchFiles:patch dir not exist:/data/user/0/*****/tinker
2021-08-27 15:33:47.445 30469-30469/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
2021-08-27 15:33:48.755 30543-30543/? D/Tinker.TinkerLoader: tryLoad test test
2021-08-27 15:33:48.756 30543-30543/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/*****/tinker
2021-08-27 15:33:48.757 30543-30543/? W/Tinker.MyLogImp: new log level: 3
2021-08-27 15:33:48.759 30543-30543/? W/Tinker.Tinker: tinker patch directory: /data/user/0/*****/tinker
2021-08-27 15:33:48.760 30543-30543/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
2021-08-27 15:33:48.760 30543-30543/? W/Tinker.Tinker: tinker load fail!
2021-08-27 15:33:48.840 30543-30543/? W/Tinker.TinkerLoader: [PendingLog @ 2021-08-27 15:33:48.756] tryLoadPatchFiles:patch dir not exist:/data/user/0/*****/tinker
2021-08-27 15:33:48.841 30543-30543/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2021-08-27 15:33:49.076 30469-30469/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/*****/tinker/patch.info: open failed: ENOENT (No such file or directory)
2021-08-27 15:33:49.076 30469-30469/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/*****/tinker/patch.info: open failed: ENOENT (No such file or directory)
2021-08-27 15:33:49.076 30469-30469/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
2021-08-27 15:33:49.087 1666-1824/? I/ActivityManager: Start proc 30694:*****:patch/u0a508 for service {*****/com.tencent.tinker.lib.service.TinkerPatchForeService} caller=*****
2021-08-27 15:33:49.127 30694-30694/? D/Tinker.TinkerLoader: tryLoad test test
2021-08-27 15:33:49.128 30694-30694/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
2021-08-27 15:33:49.128 30694-30694/? W/Tinker.MyLogImp: new log level: 3
2021-08-27 15:33:49.130 30694-30694/? W/Tinker.Tinker: tinker patch directory: /data/user/0/*****/tinker
2021-08-27 15:33:49.130 30694-30694/? W/Tinker.TinkerLoadResult: tinker is disable, just return
2021-08-27 15:33:49.130 30694-30694/? W/Tinker.Tinker: tinker load fail!
2021-08-27 15:33:49.200 30694-30694/? W/Tinker.TinkerLoader: [PendingLog @ 2021-08-27 15:33:49.128] tryLoadPatchFiles: we don't load patch with :patch process itself, just return
2021-08-27 15:33:49.200 30694-30769/? W/Tinker.UpgradePatchRetry: try copy file: /data/user/0/*****/tinker/75da778213999ac6dcf2d5c925513009.apk to /data/user/0/*****/tinker_temp/temp.apk
2021-08-27 15:33:49.201 30694-30694/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2021-08-27 15:33:49.228 30694-30769/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/*****/tinker/patch.info: open failed: ENOENT (No such file or directory)
2021-08-27 15:33:49.228 30694-30769/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/*****/tinker/patch.info: open failed: ENOENT (No such file or directory)
2021-08-27 15:33:49.228 30694-30769/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/*****/tinker/75da778213999ac6dcf2d5c925513009.apk size: 8004, dest file: /data/user/0/*****/tinker/patch-ce3ba748/patch-ce3ba748.apk size:8004
2021-08-27 15:33:49.240 30694-30769/? E/Tinker.ParallelDex: [-] Fail to call performDexOptSecondary.  java.lang.IllegalStateException: Failure on triggering secondary dexopt
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.performDexOptSecondary(SourceFile:254)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.triggerPMDexOptOnDemand(SourceFile:192)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(SourceFile:157)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:100)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:75)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(SourceFile:380)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(SourceFile:196)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(SourceFile:87)
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(SourceFile:157)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(SourceFile:142)
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(SourceFile:97)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.UnsupportedOperationException: Cannot query transaction code of performDexOptSecondary.
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.queryPerformDexOptSecondaryTransactionCode(SourceFile:267)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.performDexOptSecondary(SourceFile:218)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.triggerPMDexOptOnDemand(SourceFile:192) 
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(SourceFile:157) 
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:100) 
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:75) 
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(SourceFile:380) 
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(SourceFile:196) 
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(SourceFile:87) 
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(SourceFile:157) 
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(SourceFile:142) 
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(SourceFile:97) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.queryPerformDexOptSecondaryTransactionCode(SourceFile:262)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.performDexOptSecondary(SourceFile:218) 
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.triggerPMDexOptOnDemand(SourceFile:192) 
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(SourceFile:157) 
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:100) 
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:75) 
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(SourceFile:380) 
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(SourceFile:196) 
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(SourceFile:87) 
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(SourceFile:157) 
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(SourceFile:142) 
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(SourceFile:97) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.NoSuchFieldException: No field TRANSACTION_performDexOptSecondary in class Landroid/content/pm/IPackageManager$Stub; (declaration of 'android.content.pm.IPackageManager$Stub' appears in /system/framework/framework.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.queryPerformDexOptSecondaryTransactionCode(SourceFile:262) 
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.performDexOptSecondary(SourceFile:218) 
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.triggerPMDexOptOnDemand(SourceFile:192) 
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(SourceFile:157) 
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:100) 
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:75) 
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(SourceFile:380) 
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(SourceFile:196) 
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(SourceFile:87) 
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(SourceFile:157) 
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(SourceFile:142) 
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(SourceFile:97) 
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-08-27 15:33:50.241 30694-30769/? E/Tinker.ParallelDex: [-] Fail to call triggerPMDexOptAsyncOnDemand.  java.lang.IllegalStateException: Bg-dexopt was triggered, but no odex file was generated.
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.triggerPMDexOptOnDemand(SourceFile:207)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(SourceFile:157)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:100)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(SourceFile:75)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(SourceFile:380)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(SourceFile:196)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(SourceFile:87)
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(SourceFile:157)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(SourceFile:142)
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(SourceFile:97)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-08-27 15:33:50.242 30694-30769/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
2021-08-27 15:33:50.242 30694-30769/? W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
2021-08-27 15:33:50.250 30694-30769/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
2021-08-27 15:33:50.270 30469-30838/? W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /data/user/0/*****/tinker/75da778213999ac6dcf2d5c925513009.apk
2021-08-27 15:34:50.245 31048-31048/? D/Tinker.TinkerLoader: tryLoad test test
2021-08-27 15:34:50.255 31048-31048/? I/Tinker.TinkerInternals: class not found exception
2021-08-27 15:34:50.256 31048-31048/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm
2021-08-27 15:34:50.257 31048-31048/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2021-08-27 15:34:50.257 31048-31048/? D/Tinker.TinkerInternals: same fingerprint:Xiaomi/venus/venus:11/RKQ1.200928.002/V12.5.9.0.RKBCNXM:user/release-keys
2021-08-27 15:34:50.257 31048-31048/? W/Tinker.TinkerInternals: getSafeModeCount: recFileName:safemode_count_rec_***** failed, return 0 instead.
2021-08-27 15:34:50.258 31048-31048/? I/Tinker.TinkerInternals: setSafeModeCount: count: 1
2021-08-27 15:34:50.258 31048-31048/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/base.apk"],nativeLibraryDirectories=[/data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/lib/arm, /data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]]
2021-08-27 15:34:50.258 31048-31048/? I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/*****/tinker/patch-ce3ba748/dex/tinker_classN.apk md5, use time: 0
2021-08-27 15:34:50.258 31048-31048/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/*****/tinker/patch-ce3ba748/odex, dex size:1
2021-08-27 15:34:50.259 31048-31048/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/*****/tinker/patch-ce3ba748/dex/tinker_classN.apk", zip file "/data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/base.apk"],nativeLibraryDirectories=[/data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/lib/arm, /data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]], dex size:1
2021-08-27 15:34:50.259 31048-31048/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
2021-08-27 15:34:50.260 31048-31048/? I/Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
2021-08-27 15:34:50.260 31048-31048/? I/Tinker.AppInfoChangedBlocker: tryStart called.
2021-08-27 15:34:50.260 31048-31048/? I/Tinker.AppInfoChangedBlocker: tryStart done.
2021-08-27 15:34:50.261 31048-31048/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/*****/tinker/patch.info , oldVer:ce3ba74899f2bae86b09a375d6037684, newVer:ce3ba74899f2bae86b09a375d6037684, isProtectedApp:1, isRemoveNewVersion:0, fingerprint:Xiaomi/venus/venus:11/RKQ1.200928.002/V12.5.9.0.RKBCNXM:user/release-keys, oatDir:odex, isRemoveInterpretOATDir:0
2021-08-27 15:34:50.264 31048-31048/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
2021-08-27 15:34:50.266 31048-31048/? W/Tinker.MyLogImp: new log level: 3
2021-08-27 15:34:50.268 31048-31048/? W/Tinker.Tinker: tinker patch directory: /data/user/0/*****/tinker
2021-08-27 15:34:50.411 31105-31105/? D/Tinker.TinkerLoader: tryLoad test test
2021-08-27 15:34:50.419 31105-31105/? I/Tinker.TinkerInternals: class not found exception
2021-08-27 15:34:50.420 31105-31105/? D/Tinker.TinkerInternals: getCurrentInstructionSet:arm
2021-08-27 15:34:50.420 31105-31105/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2021-08-27 15:34:50.421 31105-31105/? D/Tinker.TinkerInternals: same fingerprint:Xiaomi/venus/venus:11/RKQ1.200928.002/V12.5.9.0.RKBCNXM:user/release-keys
2021-08-27 15:34:50.421 31105-31105/? W/Tinker.TinkerInternals: getSafeModeCount: recFileName:safemode_count_rec_*****:pushservice failed, return 0 instead.
2021-08-27 15:34:50.421 31105-31105/? I/Tinker.TinkerInternals: setSafeModeCount: count: 1
2021-08-27 15:34:50.421 31105-31105/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/base.apk"],nativeLibraryDirectories=[/data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/lib/arm, /data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]]
2021-08-27 15:34:50.421 31105-31105/? I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/*****/tinker/patch-ce3ba748/dex/tinker_classN.apk md5, use time: 0
2021-08-27 15:34:50.422 31105-31105/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/*****/tinker/patch-ce3ba748/odex, dex size:1
2021-08-27 15:34:50.422 31105-31105/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/*****/tinker/patch-ce3ba748/dex/tinker_classN.apk", zip file "/data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/base.apk"],nativeLibraryDirectories=[/data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/lib/arm, /data/app/~~eR9yKFpA33DxJbaSL9TRoQ==/*****-elLncqt_omazMkayfPq_gg==/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]], dex size:1
2021-08-27 15:34:50.423 31105-31105/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
2021-08-27 15:34:50.423 31105-31105/? I/Tinker.IncrementCompMgr: package has no incremental component meta, skip init.
2021-08-27 15:34:50.423 31105-31105/? I/Tinker.AppInfoChangedBlocker: tryStart called.
2021-08-27 15:34:50.423 31105-31105/? I/Tinker.AppInfoChangedBlocker: tryStart done.
2021-08-27 15:34:50.423 31105-31105/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
2021-08-27 15:34:50.424 31105-31105/? W/Tinker.MyLogImp: new log level: 3
2021-08-27 15:34:50.426 31105-31105/? W/Tinker.Tinker: tinker patch directory: /data/user/0/*****/tinker
2021-08-27 15:34:50.508 31105-31105/? W/Tinker.TinkerLoader: [PendingLog @ 2021-08-27 15:34:50.420] tryLoadPatchFiles:isEnabledForResource:true
2021-08-27 15:34:50.508 31105-31105/? W/Tinker.TinkerInternals: [PendingLog @ 2021-08-27 15:34:50.421] getSafeModeCount: recFileName:safemode_count_rec_*****:pushservice failed, return 0 instead.
2021-08-27 15:34:50.510 31105-31105/? W/Tinker.ClassLoaderAdder: [PendingLog @ 2021-08-27 15:34:50.423] checkDexInstall result:true
2021-08-27 15:34:50.512 31105-31105/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
2021-08-27 15:34:50.649 31048-31048/? W/Tinker.TinkerLoader: [PendingLog @ 2021-08-27 15:34:50.257] tryLoadPatchFiles:isEnabledForResource:true
2021-08-27 15:34:50.649 31048-31048/? W/Tinker.TinkerInternals: [PendingLog @ 2021-08-27 15:34:50.257] getSafeModeCount: recFileName:safemode_count_rec_***** failed, return 0 instead.

**Comment by chengxushi** [comment]
老哥请问解决了吗

**Comment by ssyijiu** [comment]
老哥，请问问题解决了吗，我把 Bugly 的接入方式改成 AppLike 也这样了，难受。

**Comment by lovejhf** [comment]
1.9.14.21版本无该情况 ，测试正常   最新版本有此问题

**Comment by lovejhf** [comment]
@ssyijiu gradle：7.5  tinker ：1.9.14.21 正常 
1.9.14.25.2有此问题，而且会一直走大概60s后会修复正常 vivo 12手机
