### ISSUE TITLE
补丁包首次修复成功，杀进程重启后，又失效了。

### ISSUE THREAD

**Issue by linzhongshu** [Tencent/tinker#1601]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常 

手机型号： 所有

手机系统版本：5.0以上 

tinker版本： 1.9.14.16

gradle版本：6.5

是否使用热更新SDK：   Bugly SDK  crashreport_upgrade:1.4.2 tinker-support:1.2.3  tinker-android-lib:1.9.14.16

系统：如:Windows 10

堆栈/日志：
1. 如是编译异常，请在执行gradle命令时，加上--stacktrace;
2. 日志我们需要过滤"Tinker."关键字;
3. 对于合成失败的情况，请给出:patch进程的日志,这里需要将Android Moniter右上角设为No Filter。
```
补丁包下发成功，合成也提示成功，重启后，出现异常log:

2021-09-07 14:17:44.788 8009-8009/com.sumiao123.fastkitty I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
2021-09-07 14:17:44.788 8009-8009/com.sumiao123.fastkitty E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
2021-09-07 14:17:44.794 8009-8009/com.sumiao123.fastkitty I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
2021-09-07 14:17:44.794 8009-8009/com.sumiao123.fastkitty E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2021-09-07 14:17:44.795 8009-8009/com.sumiao123.fastkitty E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:73)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:191)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:325)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:119)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:157)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:180)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57)
        at android.app.Application.attach(Application.java:200)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1105)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1089)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1053)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6590)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
2021-09-07 14:17:44.797 8009-8009/com.sumiao123.fastkitty I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.sumiao123.fastkitty/tinker/patch.info , oldVer:, newVer:d40f162a4ee0839df57eb75f3cb4f7b2, isProtectedApp:0, isRemoveNewVersion:1, fingerprint:HUAWEI/NXT-AL10/HWNXT:8.0.0/HUAWEINXT-AL10/850(C00):user/release-keys, oatDir:odex, isRemoveInterpretOATDir:0
2021-09-07 14:17:44.800 8009-8009/com.sumiao123.fastkitty I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.sumiao123.fastkitty/tinker, code: -14, cost: 90ms
2021-09-07 14:17:44.800 8009-8009/com.sumiao123.fastkitty W/Tinker.Tinker: tinker load fail!
2021-09-07 14:17:44.852 8009-8009/com.sumiao123.fastkitty E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
2021-09-07 14:17:44.852 8009-8009/com.sumiao123.fastkitty D/Tinker.DefaultAppLike: onCreate
2021-09-07 14:17:44.904 8009-8009/com.sumiao123.fastkitty I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@e07e1e1
这次bug是查看是修复的，获取不到NewTinkerId。但是两次杀进程重启后，就出现
2021-09-07 14:25:06.903 8575-8620/com.sumiao123.fastkitty I/CrashReport: [Upload] Success: 804
2021-09-07 14:25:06.917 8575-8620/com.sumiao123.fastkitty D/CrashReport: [UploadManager] Local network consume: 3 KB
2021-09-07 14:25:06.926 8575-8620/com.sumiao123.fastkitty D/CrashReport: [Database] deleted t_lr data 1
2021-09-07 14:25:06.931 8575-8620/com.sumiao123.fastkitty D/CrashReport: [Database] insert t_lr success.
2021-09-07 14:25:06.931 8575-8620/com.sumiao123.fastkitty D/CrashReport: [UploadManager] Network total consume: 3 KB
2021-09-07 14:25:06.932 8575-8620/com.sumiao123.fastkitty I/CrashReport: upload succ:[804] [sended 825] [recevied 129]
2021-09-07 14:25:06.939 8575-8620/com.sumiao123.fastkitty I/CrashReport: patch has downloaded!
bug就没有修复，失效了。

**Comment by srxffcc1** [comment]
checkDexInstall failed 去看看这个是啥时候调用的

**Comment by linzhongshu** [comment]
参照 #1566 这个方法已暂时解决，再次感谢大佬。

> checkDexInstall failed 去看看这个是啥时候调用的
