### ISSUE TITLE
经常编译补丁失败，Warning:ignoreWarning is false, but we found some loader class has been changed in new primary dex

### ISSUE THREAD

**Issue by liangdong9676** [Tencent/tinker#1607]
如题，就改了几个java类，没增删四大组件，打补丁经常都会这样。。最近一段时间才频繁出现。搞得我只能发布完整版apk，后面就继续可以打补丁了。。但后面一样会遇到这问题。。。好想知道问题出在哪里，求赐教。

异常类型：编译异常

手机型号：
手机系统版本：
tinker版本：如:1.9.14.10

gradle版本：如:4.6

是否使用热更新SDK： Bugly SDK

系统：Windows10

堆栈/日志：
Warning:ignoreWarning is false, but we found some loader class has been changed in new primary dex. Such these changes will not take effect!! related classes: {Lcom/tencent/tinker/loader/shareutil/SharePatchFileUtil;,Lcom/tencent/tinker/loader/shareutil/ShareTinkerInternals;,Lcom/tencent/tinker/loader/TinkerDexLoader;,Lcom/tencent/tinker/loader/hotplug/handler/MHMessageHandler;}
java.lang.RuntimeException: com.tencent.tinker.build.util.TinkerPatchException: some loader class has been changed in new primary dex. Such these changes will not take effect!! related classes: {Lcom/tencent/tinker/loader/shareutil/SharePatchFileUtil;,Lcom/tencent/tinker/loader/shareutil/ShareTinkerInternals;,Lcom/tencent/tinker/loader/TinkerDexLoader;,Lcom/tencent/tinker/loader/hotplug/handler/MHMessageHandler;}
	at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:184)
	at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:144)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:116)
	at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
	at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
	at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
	at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)

**Comment by xFJournet** [comment]
我也遇到了，不知道是什么问题
