### ISSUE TITLE
Bg-dexopt was triggered, but no odex file was generated. / tinker_classN.odex does not exist.

### ISSUE THREAD

**Issue by ssyijiu** [Tencent/tinker#1632]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：补丁合成成功，启动的时候 Load 异常

手机型号：如:所有手机

手机系统版本：如:Android  10

tinker版本：如:1.9.14.18

gradle版本：如:3.6.0

是否使用热更新SDK： Bugly SDK

系统：如:Mac

堆栈/日志：
2022-02-06 10:59:10.507 27580-27683/? E/Tinker.ParallelDex: [-] Fail to call performDexOptSecondary.  java.lang.IllegalStateException: Expected oat file: /data/user/0/com.tianyancha.skyeye/tinker/patch-6422886b/dex/oat/arm/tinker_classN.odex does not exist.
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.performDexOptSecondary(TinkerDexOptimizer.java:247)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.triggerPMDexOptOnDemand(TinkerDexOptimizer.java:193)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:157)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:100)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:75)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:380)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:196)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:87)
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:157)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(TinkerPatchService.java:223)
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:101)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:230)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-02-06 10:59:11.510 27580-27683/? E/Tinker.ParallelDex: [-] Fail to call triggerPMDexOptAsyncOnDemand.  java.lang.IllegalStateException: Bg-dexopt was triggered, but no odex file was generated.
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.triggerPMDexOptOnDemand(TinkerDexOptimizer.java:208)
        at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:157)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:100)
        at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:75)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:380)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:196)
        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:87)
        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:157)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(TinkerPatchService.java:223)
        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:101)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:230)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by ssyijiu** [comment]
已经发现问题：
之前按照 Bugly 文档写的
`
public class BaseApplication extends TinkerApplication {

    public BaseApplication() {
        super(ShareConstants.TINKER_ENABLE_ALL, "com.xxx.xxx");
    }
}
`

修改为：
`
public class BaseApplication extends TinkerApplication {

    public BaseApplication() {
        super(ShareConstants.TINKER_ENABLE_ALL, "com.xxx.xxx",
                "com.tencent.tinker.loader.TinkerLoader", false, true);
    }
}
`

**Comment by nsacer** [comment]
你好，可以咨询下关于Tinker接入的问题么。我的QQ：1250855973
