### ISSUE TITLE
生成path文件时编译失败 报can't found string:only use for test tinker resource: a in the resources.arsc file's string pool!的错误

### ISSUE THREAD

**Issue by 4XV** [Tencent/tinker#165]
ava.lang.RuntimeException: can't found string:only use for test tinker resource: a in the resources.arsc file's string pool!
	at com.tencent.tinker.build.apkparser.AndroidParser.editResourceTableString(AndroidParser.java:123)
	at com.tencent.tinker.build.decoder.ResDiffDecoder.modArscFileForTestResource(ResDiffDecoder.java:226)
	at com.tencent.tinker.build.decoder.ResDiffDecoder.onAllPatchesEnd(ResDiffDecoder.java:245)
	at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:125)
	at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
	at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
	at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
	at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.tinkerPatch(TinkerPatchSchemaTask.groovy:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)

**Comment by shwenzhang** [comment]
使用1.7.3
