### ISSUE TITLE
Tinker Exception:checkDexInstall failed

### ISSUE THREAD

**Issue by limrw** [Tencent/tinker#1667]
#
异常类型：tinker异常

手机型号：onePlus 9

手机系统版本：Android 12

tinker版本：1.9.14.24

gradle版本：4.1.2

是否使用热更新SDK：  Bugly SDK

系统：window 11

堆栈/日志：

08:12:44.842 26767-26767/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.24
2022-08-11 08:12:44.843 26767-26767/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14, process name:com.yadea.dms, main process:true, systemOTA:false, fingerPrint:OnePlus/OnePlus9_CH/OnePlus9:12/RKQ1.211119.001/R.202206271449:user/release-keys, oatDir:odex, useInterpretMode:false
2022-08-11 08:12:44.843 26767-26767/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:0129ea3d532ea615376708507fbe62c8, current:0129ea3d532ea615376708507fbe62c8
2022-08-11 08:12:44.843 26767-26767/? I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
2022-08-11 08:12:44.843 26767-26767/? E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
2022-08-11 08:12:44.845 26767-26767/? I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
2022-08-11 08:12:44.845 26767-26767/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2022-08-11 08:12:44.845 26767-26767/? E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:73)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:191)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:346)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:119)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:157)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:180)
        at android.app.Application.attach(Application.java:340)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1193)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1393)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7001)
        at android.app.ActivityThread.access$1800(ActivityThread.java:254)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2184)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8210)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

什么原因会导致安装失败   安装失败后自动删除补丁包
只有启动第一次生效
杀死进程在进入时候， 恢复基线包原来样子

**Comment by liangdong9676** [comment]
可以看看 https://github.com/Tencent/tinker/issues/1566
