### ISSUE TITLE
Android 10上新增非export组件应用crash

### ISSUE THREAD

**Issue by SweetSalts** [Tencent/tinker#1677]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：Android 10 所有型号

手机系统版本：Android 10

tinker版本：v1.9.14.24

gradle版本：4.1.3

是否使用热更新SDK： 无

系统：Mac

堆栈/日志：
08-31 17:03:15.778  5418  5418 W Tinker.Instrumentation: oldComponent was null, start ComponentInfo{com.DefaultCompany.Unity2018Empty/com.DefaultCompany.Unity2018Empty.UnityPlayerActivity} next.
08-31 17:03:15.778  5418  5418 E Instrumentation: Uninitialized ActivityThread, likely app-created Instrumentation, disabling AppComponentFactory
08-31 17:03:15.778  5418  5418 E Instrumentation: java.lang.Throwable
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.app.Instrumentation.getFactory(Instrumentation.java:1296)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1287)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at com.tencent.tinker.loader.hotplug.interceptor.TinkerHackInstrumentation.newActivity(Unknown Source:19)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4148)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4463)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2665)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.os.Handler.dispatchMessage(Handler.java:109)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.os.Looper.loopOnce(Looper.java:206)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.os.Looper.loop(Looper.java:296)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at android.app.ActivityThread.main(ActivityThread.java:8912)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at java.lang.reflect.Method.invoke(Native Method)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
08-31 17:03:15.778  5418  5418 E Instrumentation: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)
08-31 17:03:15.789  5418  5418 V ActivityThread: callActivityOnCreate
```

**Comment by awdvhil9** [comment]
你打包的时候，安装会提示不能创建application的错吗？

**Comment by SweetSalts** [comment]
不会的

**Comment by Primer1889** [comment]
我也遇到了这个问题，不知道为啥 Instrumentation 字段 mTread 为空

**Comment by jacklongway** [comment]
您好！很高兴收到您的邮件，稍后查看。

**Comment by canlan818** [comment]
这是来自QQ邮箱的自动回复邮件。您好，来信已收到，谢谢您，我会及时回复您的！O(∩_∩)O~
