### ISSUE TITLE
混淆以后不能创建application实例

### ISSUE THREAD

**Issue by awdvhil9** [Tencent/tinker#1679]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常/编译异常

手机型号：定制平板

手机系统版本：定制平板

tinker版本：1.9.14.24

gradle版本：4.1.1

是否使用热更新SDK： 否

系统：windows

堆栈/日志：
java.lang.RuntimeException: Unable to instantiate application ***App: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:impossible
        at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:impossible
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(:4)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext()
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:996)
        at android.app.Instrumentation.newApplication(Instrumentation.java:980)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
     Caused by: java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:45)
        at java.lang.Enum$1.create(Enum.java:35)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
        at java.lang.Enum.getSharedConstants(Enum.java:211)
        at java.util.EnumMap.initialization(EnumMap.java:758)
        at java.util.EnumMap.<init>(EnumMap.java:404)
        at com.tencent.mmkv.MMKV.<clinit>()
        at com.szx.carload.CarLoadAppLike.onBaseContextAttached()
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl()
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$()
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage()
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(:1)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext() 
        at android.app.Application.attach(Application.java:181) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:996) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:980) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:558) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
     Caused by: java.lang.NoSuchMethodException: values []
        at java.lang.Class.getMethod(Class.java:664)
        at java.lang.Class.getDeclaredMethod(Class.java:626)
        at java.lang.Enum$1.create(Enum.java:41)
        at java.lang.Enum$1.create(Enum.java:35) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:54) 
        at java.lang.Enum.getSharedConstants(Enum.java:211) 
        at java.util.EnumMap.initialization(EnumMap.java:758) 
        at java.util.EnumMap.<init>(EnumMap.java:404) 
        at com.tencent.mmkv.MMKV.<clinit>() 
        at com.szx.carload.CarLoadAppLike.onBaseContextAttached() 
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl() 
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$() 
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage() 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(:1) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext() 
        at android.app.Application.attach(Application.java:181) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:996) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:980) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:558) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 

build.gradle是照着demo里配置的，改了一块：

try {
       from new File(packageAndroidArtifact.outputDirectory.getAsFile().get(), variant.outputs.first().variantOutput.outputFileName.get())
} catch (Exception e) {
      from new File(packageAndroidArtifact.outputDirectory, variant.outputs.first().variantOutput.outputFileName.get())
}
这里原来是：
try {
        from new File(packageAndroidArtifact.outputDirectory.getAsFile().get(), variant.outputs.first().apkData.outputFileName)
} catch (Exception e) {
        from new File(packageAndroidArtifact.outputDirectory, variant.outputs.first().apkData.outputFileName)
 }
不改编译不通过，报找不到apkData。改完以后可以打包，但是运行的时候报上面的错误，去掉混淆后就不报错了，混淆也是照着demo里配置的，请问是哪里的混淆没配置好？

**Comment by awdvhil9** [comment]
用的是java8

**Comment by awdvhil9** [comment]
是其它地方混淆的问题，只是错误提示有误导
