### ISSUE TITLE
Unable to instantiate application，运行闪退

### ISSUE THREAD

**Issue by lixiangkai1987** [Tencent/tinker#1692]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：XiAOMI

手机系统版本：Android 12

tinker版本：1.9.14.25

gradle版本：4.1.0

依赖
implementation("com.tencent.tinker:tinker-android-lib:${TINKER_VERSION}") { changing = true }
implementation("com.tencent.tinker:tinker-android-loader:${TINKER_VERSION}") { changing = true }
compileOnly("com.tencent.tinker:tinker-android-anno:${TINKER_VERSION}") { changing = true }
annotationProcessor("com.tencent.tinker:tinker-android-anno:${TINKER_VERSION}") { changing = true }

自定义Application：
@DefaultLifeCycle(application = ".SimpleApplication", flags = ShareConstants.TINKER_ENABLE_ALL, loadVerifyFlag = false)
public class MyApp extends ApplicationLike {
    public MyApp(Application application, int tinkerFlags, boolean tinkerLoadVerifyFlag, long applicationStartElapsedTime, long applicationStartMillisTime,
                 Intent tinkerResultIntent
    ) {
        super(application, tinkerFlags, tinkerLoadVerifyFlag, applicationStartElapsedTime, applicationStartMillisTime, tinkerResultIntent);
    }

堆栈/日志：
Process: com.xjj.cloud.hotfix, PID: 19890
                                                                                                    java.lang.RuntimeException: Unable to instantiate application com.xjj.cloud.hotfix.SimpleApplication package com.xjj.cloud.hotfix: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createInlineFence failed
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1377)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6904)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:264)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8103)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
                                                                                                    Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createInlineFence failed
                                                                                                    	at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:157)
                                                                                                    	at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:165)
                                                                                                    	at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:186)
                                                                                                    	at android.app.Application.attach(Application.java:333)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6904) 
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:264) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8103) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
                                                                                                    Caused by: java.lang.NoSuchMethodException: com.xjj.cloud.hotfix.MyApp.<init> [class android.app.Application, int, boolean, long, long, class android.content.Intent]
                                                                                                    	at java.lang.Class.getConstructor0(Class.java:2363)
                                                                                                    	at java.lang.Class.getConstructor(Class.java:1759)
                                                                                                    	at com.tencent.tinker.loader.app.TinkerApplication.createInlineFence(TinkerApplication.java:145)
                                                                                                    	at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:165) 
                                                                                                    	at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:186) 
                                                                                                    	at android.app.Application.attach(Application.java:333) 
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1178) 
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1369) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6904) 
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:264) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8103) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by lixiangkai1987** [comment]
1.9.2版本可以正常运行

**Comment by spysoos** [comment]
> 1.9.2版本可以正常运行

哪来的1.9.2?

**Comment by weimingjue** [comment]
> > 1.9.2版本可以正常运行
> 
> 哪来的1.9.2?

1.9.14都有了，文档是2017年的
