### ISSUE TITLE
补丁只生效一次，杀进程再次进入补丁失效

### ISSUE THREAD

**Issue by isanwenyu** [Tencent/tinker#1716]
异常类型：app运行时异常 `tinker load exception java.lang.NoSuchMethodError: No static method checkDexInstall(Ljava/lang/ClassLoader;)`

手机型号：Pixel 7(如是编译异常，则可以不填)

手机系统版本：Android 13.0 (如是编译异常，则可以不填)

tinker版本：1.9.14.3

gradle版本：5.1.1

是否使用热更新SDK： TinkerPatch SDK 

系统：Mac

堆栈/日志：
2023-06-26 18:31:11.646 21967-22720/ W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.xxx.xxx/tinker/patch.info: open failed: ENOENT (No such file or directory)
2023-06-26 18:31:11.647 21967-22720/com.xxx.xxx W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.xxx.xxx/tinker/patch.info: open failed: ENOENT (No such file or directory)
2023-06-26 18:31:11.647 21967-22720/com.xxx.xxx W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
2023-06-26 18:31:11.650 21967-22720/com.xxx.xxx I/Tinker.TinkerPatchService: run patch service...
2023-06-26 18:31:12.404 23161-23161/com.xxx.xxx D/Tinker.TinkerLoader: tryLoad test test
2023-06-26 18:31:12.404 23161-23161/com.xxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
2023-06-26 18:31:13.198 23161-23161/com.xxx.xxx D/Tinker.DefaultAppLike: onBaseContextAttached:
2023-06-26 18:31:13.217 23161-23161/com.xxx.xxx W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
2023-06-26 18:31:13.217 23161-23161/com.xxx.xxx I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2023-06-26 18:31:13.218 23161-23161/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.xxx.xxx:patch, main process:false, systemOTA:false, fingerPrint:google/panther/panther:13/TD1A.220804.031/9071314:user/release-keys, oatDir:null, useInterpretMode:false
2023-06-26 18:31:13.218 23161-23161/com.xxx.xxx W/Tinker.TinkerLoadResult: tinker is disable, just return
2023-06-26 18:31:13.218 23161-23161/com.xxx.xxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -1, cost: 1ms
2023-06-26 18:31:13.222 23161-23161/com.xxx.xxx W/Tinker.Tinker: tinker load fail!
2023-06-26 18:31:13.224 23161-23161/com.xxx.xxx I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2023-06-26 18:31:13.224 23161-23161/com.xxx.xxx D/Tinker.DefaultAppLike: onCreate
2023-06-26 18:31:13.468 23161-23224/com.xxx.xxx I/Tinker.TinkerPatchService: for system version >= Android O, we just ignore increasingPriority job to avoid crash or toasts.
2023-06-26 18:31:13.469 23161-23224/com.xxx.xxx I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
2023-06-26 18:31:13.471 23161-23224/com.xxx.xxx W/Tinker.UpgradePatchRetry: try copy file: /data/user/0/com.xxx.xxx/cache/download/340a0609fd9309a6abe17448bc2cf3d3 to /data/user/0/com.xxx.xxx/tinker_temp/temp.apk
2023-06-26 18:31:13.498 23161-23224/com.xxx.xxx I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:dec422c530cd0b5ef0ac48f09693a060
2023-06-26 18:31:13.500 23161-23224/com.xxx.xxx W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.xxx.xxx/tinker/patch.info: open failed: ENOENT (No such file or directory)
2023-06-26 18:31:13.500 23161-23224/com.xxx.xxx W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.xxx.xxx/tinker/patch.info: open failed: ENOENT (No such file or directory)
2023-06-26 18:31:13.500 23161-23224/com.xxx.xxx I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.xxx.xxx/tinker/patch-dec422c5
2023-06-26 18:31:13.501 23161-23224/com.xxx.xxx W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.xxx.xxx/cache/download/340a0609fd9309a6abe17448bc2cf3d3 size: 92051, dest file: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/patch-dec422c5.apk size:92051
2023-06-26 18:31:13.506 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes.dex.jar
2023-06-26 18:31:13.512 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2023-06-26 18:31:13.512 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes2.dex.jar
2023-06-26 18:31:13.513 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2023-06-26 18:31:13.514 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes3.dex.jar
2023-06-26 18:31:13.516 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2023-06-26 18:31:13.516 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes4.dex.jar
2023-06-26 18:31:13.520 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2023-06-26 18:31:13.520 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes5.dex.jar
2023-06-26 18:31:13.522 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2023-06-26 18:31:13.522 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes6.dex.jar
2023-06-26 18:31:13.525 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2023-06-26 18:31:13.525 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes7.dex.jar
2023-06-26 18:31:13.526 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2023-06-26 18:31:13.526 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes8.dex.jar
2023-06-26 18:31:13.529 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2023-06-26 18:31:13.529 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/test.dex.jar
2023-06-26 18:31:13.530 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
2023-06-26 18:31:13.538 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes2.dex.jar
2023-06-26 18:31:13.538 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes6.dex.jar
2023-06-26 18:31:13.538 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes7.dex.jar
2023-06-26 18:31:13.538 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes5.dex.jar
2023-06-26 18:31:13.538 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes.dex.jar
2023-06-26 18:31:13.538 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes3.dex.jar
2023-06-26 18:31:13.538 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/test.dex.jar
2023-06-26 18:31:13.539 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes4.dex.jar
2023-06-26 18:31:13.539 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/classes8.dex.jar
2023-06-26 18:31:13.539 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: merge classN dex file /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/tinker_classN.apk, result: true, size: 208171, use: 9ms
2023-06-26 18:31:13.539 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: legal files to do dexopt: [/data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/tinker_classN.apk]
2023-06-26 18:31:13.539 23161-23224/com.xxx.xxx D/Tinker.TinkerInternals: getCurrentInstructionSet:arm64
2023-06-26 18:31:13.539 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:1, optimizeDexDirectory:/data/user/0/com.xxx.xxx/tinker/patch-dec422c5/odex/
2023-06-26 18:31:13.540 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/tinker_classN.apk, size: 208171
2023-06-26 18:31:13.543 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/tinker_classN.apk, opt file:/data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/oat/arm64/tinker_classN.odex, opt file size: 0, use time 2
2023-06-26 18:31:13.543 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:38
2023-06-26 18:31:13.543 23161-23224/com.xxx.xxx W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
2023-06-26 18:31:13.545 23161-23224/com.xxx.xxx I/Tinker.ResDiffPatchInternal: res dir: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/res/, meta: resArscMd5:22e5f4033eb6af2e92288d7ae38ea4d4
    arscBaseCrc:1683613064
    pattern:resources\.arsc
    pattern:res/.*
    pattern:assets/.*
    addedSet:assets/only_use_to_test_tinker_resource.txt
    modifiedSet:assets/config.properties
2023-06-26 18:31:13.545 23161-23224/com.xxx.xxx I/Tinker.ResDiffPatchInternal: no large modify or store resources, just return
2023-06-26 18:31:14.087 23161-23224/com.xxx.xxx I/Tinker.ResDiffPatchInternal: final new resource file:/data/user/0/com.xxx.xxx/tinker/patch-dec422c5/res/resources.apk, entry count:4229, size:52165749
2023-06-26 18:31:14.087 23161-23224/com.xxx.xxx I/Tinker.ResDiffPatchInternal: recover resource result:true, cost:542
2023-06-26 18:31:14.087 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: raw dex count: 9, dex opt dex count: 1, final wait times: 120
2023-06-26 18:31:14.090 23161-23224/com.xxx.xxx I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/oat/arm64/tinker_classN.odex, size 0
2023-06-26 18:31:14.090 23161-23224/com.xxx.xxx I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.xxx.xxx/tinker/patch.info , oldVer:, newVer:dec422c530cd0b5ef0ac48f09693a060, isProtectedApp:1, isRemoveNewVersion:0, fingerprint:google/panther/panther:13/TD1A.220804.031/9071314:user/release-keys, oatDir:odex
2023-06-26 18:31:14.091 23161-23224/com.xxx.xxx I/Tinker.UpgradePatchRetry: onPatchResetMaxCheck, reset max check to 1
2023-06-26 18:31:14.091 23161-23224/com.xxx.xxx W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
2023-06-26 18:31:14.092 23161-23224/com.xxx.xxx I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /data/user/0/com.xxx.xxx/cache/download/340a0609fd9309a6abe17448bc2cf3d3, success: true, cost: 615
2023-06-26 18:31:14.092 23161-23224/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker_temp/temp.apk
2023-06-26 18:31:14.106 21967-23232/com.xxx.xxx W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /data/user/0/com.xxx.xxx/cache/download/340a0609fd9309a6abe17448bc2cf3d3
2023-06-26 18:31:14.106 21967-23232/com.xxx.xxx I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/cache/download/340a0609fd9309a6abe17448bc2cf3d3
2023-06-26 18:31:58.075 23264-23264/com.xxx.xxx D/Tinker.TinkerLoader: tryLoad test test
2023-06-26 18:31:58.080 23264-23264/com.xxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:version is blank, wait main process to restart
2023-06-26 18:32:00.184 21967-21967/com.xxx.xxx D/Tinker.DefaultAppLike: onTrimMemory level:20
2023-06-26 18:32:00.414 23264-23264/com.xxx.xxx D/Tinker.DefaultAppLike: onBaseContextAttached:
2023-06-26 18:32:00.428 23264-23264/com.xxx.xxx W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
2023-06-26 18:32:00.430 23264-23264/com.xxx.xxx I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2023-06-26 18:32:00.431 23264-23264/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-5, process name:com.xxx.xxx:remote, main process:false, systemOTA:false, fingerPrint:google/panther/panther:13/TD1A.220804.031/9071314:user/release-keys, oatDir:odex, useInterpretMode:false
2023-06-26 18:32:00.431 23264-23264/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:dec422c530cd0b5ef0ac48f09693a060, current:
2023-06-26 18:32:00.431 23264-23264/com.xxx.xxx E/Tinker.TinkerLoadResult: path info blank, wait main process to restart
2023-06-26 18:32:00.431 23264-23264/com.xxx.xxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -5, cost: 7ms
2023-06-26 18:32:00.446 23264-23264/com.xxx.xxx W/Tinker.Tinker: tinker load fail!
2023-06-26 18:32:00.451 23264-23264/com.xxx.xxx I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2023-06-26 18:32:00.452 23264-23264/com.xxx.xxx D/Tinker.DefaultAppLike: onCreate
2023-06-26 18:32:12.631 23350-23350/com.xxx.xxx D/Tinker.TinkerLoader: tryLoad test test
2023-06-26 18:32:12.646 23350-23350/com.xxx.xxx D/Tinker.TinkerInternals: getCurrentInstructionSet:arm64
2023-06-26 18:32:12.646 23350-23350/com.xxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
2023-06-26 18:32:12.647 23350-23350/com.xxx.xxx D/Tinker.TinkerInternals: same fingerprint:google/panther/panther:13/TD1A.220804.031/9071314:user/release-keys
2023-06-26 18:32:12.648 23350-23350/com.xxx.xxx W/Tinker.TinkerInternals: getSafeModeCount: preferName:tinker_own_config_com.xxx.xxx count:0
2023-06-26 18:32:12.651 23350-23350/com.xxx.xxx W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.xxx.xxx count:1
2023-06-26 18:32:12.651 23350-23350/com.xxx.xxx I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~Ywspe0IzRdraqQThYlhkuQ==/com.xxx.xxx-g7WVtn6-U2GWaCd0F6ULGA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Ywspe0IzRdraqQThYlhkuQ==/com.xxx.xxx-g7WVtn6-U2GWaCd0F6ULGA==/lib/arm64, /data/app/~~Ywspe0IzRdraqQThYlhkuQ==/com.xxx.xxx-g7WVtn6-U2GWaCd0F6ULGA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]
2023-06-26 18:32:12.651 23350-23350/com.xxx.xxx I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/tinker_classN.apk md5, use time: 0
2023-06-26 18:32:12.652 23350-23350/com.xxx.xxx I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.xxx.xxx/tinker/patch-dec422c5/odex, dex size:1
2023-06-26 18:32:12.653 23350-23350/com.xxx.xxx I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/com.xxx.xxx/tinker/patch-dec422c5/dex/tinker_classN.apk", zip file "/data/app/~~Ywspe0IzRdraqQThYlhkuQ==/com.xxx.xxx-g7WVtn6-U2GWaCd0F6ULGA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Ywspe0IzRdraqQThYlhkuQ==/com.xxx.xxx-g7WVtn6-U2GWaCd0F6ULGA==/lib/arm64, /data/app/~~Ywspe0IzRdraqQThYlhkuQ==/com.xxx.xxx-g7WVtn6-U2GWaCd0F6ULGA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]], dex size:1
2023-06-26 18:32:12.653 23350-23350/com.xxx.xxx E/Tinker.TinkerDexLoader: install dexes failed
2023-06-26 18:32:12.653 23350-23350/com.xxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
2023-06-26 18:32:13.259 23350-23350/com.xxx.xxx D/Tinker.DefaultAppLike: onBaseContextAttached:
2023-06-26 18:32:13.274 23350-23350/com.xxx.xxx W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
2023-06-26 18:32:13.275 23350-23350/com.xxx.xxx I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2023-06-26 18:32:13.275 23350-23350/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14, process name:com.xxx.xxx, main process:true, systemOTA:false, fingerPrint:google/panther/panther:13/TD1A.220804.031/9071314:user/release-keys, oatDir:odex, useInterpretMode:false
2023-06-26 18:32:13.275 23350-23350/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:dec422c530cd0b5ef0ac48f09693a060, current:dec422c530cd0b5ef0ac48f09693a060
2023-06-26 18:32:13.275 23350-23350/com.xxx.xxx I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
2023-06-26 18:32:13.275 23350-23350/com.xxx.xxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: patch load dex exception: java.lang.NoSuchMethodError: No static method checkDexInstall(Ljava/lang/ClassLoader;)Z in class Lcom/tencent/tinker/loader/SystemClassLoaderAdder; or its super classes (declaration of 'com.tencent.tinker.loader.SystemClassLoaderAdder' appears in /data/app/~~Ywspe0IzRdraqQThYlhkuQ==/com.xxx.xxx-g7WVtn6-U2GWaCd0F6ULGA==/base.apk!classes129.dex)
2023-06-26 18:32:13.277 23350-23350/com.xxx.xxx I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
2023-06-26 18:32:13.277 23350-23350/com.xxx.xxx E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
2023-06-26 18:32:13.278 23350-23350/com.xxx.xxx E/Tinker.DefaultLoadReporter: tinker load exception  java.lang.NoSuchMethodError: No static method checkDexInstall(Ljava/lang/ClassLoader;)Z in class Lcom/tencent/tinker/loader/SystemClassLoaderAdder; or its super classes (declaration of 'com.tencent.tinker.loader.SystemClassLoaderAdder' appears in /data/app/~~Ywspe0IzRdraqQThYlhkuQ==/com.xxx.xxx-g7WVtn6-U2GWaCd0F6ULGA==/base.apk!classes129.dex)
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:82)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:194)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:293)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
        at com.xxx.xxx.myapp.YqbTinkerLoader.tryLoad(CustomTinkerLoader.kt:31)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:92)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:126)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
        at com.xxx.xxx.tool.MyApp.attachBaseContext(Unknown Source:0)
        at android.app.Application.attach(Application.java:346)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1233)
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6746)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-06-26 18:32:13.278 23350-23350/com.xxx.xxx I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.xxx.xxx/tinker/patch.info , oldVer:, newVer:dec422c530cd0b5ef0ac48f09693a060, isProtectedApp:1, isRemoveNewVersion:1, fingerprint:google/panther/panther:13/TD1A.220804.031/9071314:user/release-keys, oatDir:odex
2023-06-26 18:32:13.283 23350-23350/com.xxx.xxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -14, cost: 22ms
2023-06-26 18:32:13.284 23350-23350/com.xxx.xxx W/Tinker.Tinker: tinker load fail!
2023-06-26 18:32:13.285 23350-23350/com.xxx.xxx W/Tinker.TinkerInternals: setSafeModeCount: preferName:tinker_own_config_com.xxx.xxx count:0
2023-06-26 18:32:13.336 23350-23350/com.xxx.xxx I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2023-06-26 18:32:13.336 23350-23350/com.xxx.xxx D/Tinker.DefaultAppLike: onCreate
2023-06-26 18:32:14.678 23487-23487/com.xxx.xxx D/Tinker.TinkerLoader: tryLoad test test
2023-06-26 18:32:14.685 23487-23487/com.xxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:version is blank, wait main process to restart
2023-06-26 18:32:14.712 23533-23533/com.xxx.xxx D/Tinker.TinkerLoader: tryLoad test test
2023-06-26 18:32:14.714 23533-23533/com.xxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:version is blank, wait main process to restart
2023-06-26 18:32:15.761 23487-23487/com.xxx.xxx D/Tinker.DefaultAppLike: onBaseContextAttached:
2023-06-26 18:32:15.779 23487-23487/com.xxx.xxx W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
2023-06-26 18:32:15.782 23487-23487/com.xxx.xxx I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2023-06-26 18:32:15.783 23487-23487/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-5, process name:com.xxx.xxx:update, main process:false, systemOTA:false, fingerPrint:google/panther/panther:13/TD1A.220804.031/9071314:user/release-keys, oatDir:odex, useInterpretMode:false
2023-06-26 18:32:15.784 23487-23487/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:dec422c530cd0b5ef0ac48f09693a060, current:
2023-06-26 18:32:15.784 23487-23487/com.xxx.xxx E/Tinker.TinkerLoadResult: path info blank, wait main process to restart
2023-06-26 18:32:15.784 23487-23487/com.xxx.xxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -5, cost: 8ms
2023-06-26 18:32:15.794 23487-23487/com.xxx.xxx W/Tinker.Tinker: tinker load fail!
2023-06-26 18:32:15.796 23487-23487/com.xxx.xxx I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2023-06-26 18:32:15.796 23487-23487/com.xxx.xxx D/Tinker.DefaultAppLike: onCreate
2023-06-26 18:32:15.845 23533-23533/com.xxx.xxx D/Tinker.DefaultAppLike: onBaseContextAttached:
2023-06-26 18:32:15.865 23533-23533/com.xxx.xxx W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
2023-06-26 18:32:15.868 23533-23533/com.xxx.xxx I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2023-06-26 18:32:15.870 23533-23533/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-5, process name:com.xxx.xxx:remote, main process:false, systemOTA:false, fingerPrint:google/panther/panther:13/TD1A.220804.031/9071314:user/release-keys, oatDir:odex, useInterpretMode:false
2023-06-26 18:32:15.870 23533-23533/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:dec422c530cd0b5ef0ac48f09693a060, current:
2023-06-26 18:32:15.870 23533-23533/com.xxx.xxx E/Tinker.TinkerLoadResult: path info blank, wait main process to restart
2023-06-26 18:32:15.871 23533-23533/com.xxx.xxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -5, cost: 1ms
2023-06-26 18:32:15.884 23533-23533/com.xxx.xxx W/Tinker.Tinker: tinker load fail!
2023-06-26 18:32:15.886 23533-23533/com.xxx.xxx I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2023-06-26 18:32:15.886 23533-23533/com.xxx.xxx D/Tinker.DefaultAppLike: onCreate
2023-06-26 18:32:17.935 23792-23792/com.xxx.xxx D/Tinker.TinkerLoader: tryLoad test test
2023-06-26 18:32:17.940 23792-23792/com.xxx.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:version is blank, wait main process to restart
2023-06-26 18:32:20.319 23792-23792/com.xxx.xxx D/Tinker.DefaultAppLike: onBaseContextAttached:
2023-06-26 18:32:20.379 23792-23792/com.xxx.xxx W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
2023-06-26 18:32:20.380 23792-23792/com.xxx.xxx I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.14.3
2023-06-26 18:32:20.381 23792-23792/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-5, process name:com.xxx.xxx:pgmini1, main process:false, systemOTA:false, fingerPrint:google/panther/panther:13/TD1A.220804.031/9071314:user/release-keys, oatDir:odex, useInterpretMode:false
2023-06-26 18:32:20.382 23792-23792/com.xxx.xxx I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:dec422c530cd0b5ef0ac48f09693a060, current:
2023-06-26 18:32:20.382 23792-23792/com.xxx.xxx E/Tinker.TinkerLoadResult: path info blank, wait main process to restart
2023-06-26 18:32:20.382 23792-23792/com.xxx.xxx I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code: -5, cost: 20ms
2023-06-26 18:32:20.394 23792-23792/com.xxx.xxx W/Tinker.Tinker: tinker load fail!
2023-06-26 18:32:20.398 23792-23792/com.xxx.xxx I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
2023-06-26 18:32:20.398 23792-23792/com.xxx.xxx D/Tinker.DefaultAppLike: onCreate

```

**Comment by isanwenyu** [comment]
问题已解决，为插桩代码导致。
