### ISSUE TITLE
Android12-debug环境补丁加载正常，release加载成功，但重启app会连续崩溃3次并自动清理补丁

### ISSUE THREAD

**Issue by yanjunhui2014** [Tencent/tinker#1734]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：release环境补丁加载成功，但app启动异常

手机型号：任意手机

手机系统版本：Android12

tinker版本：如:1.9.14.25.3

gradle版本：如:4.1.3

是否使用热更新SDK： 使用，接入方式借鉴于tinker-sample-android

系统：如:Mac

堆栈/日志：
Process Name: 'com.ishowedu.aitalk'
Thread Name: 'main'
Back traces starts.
java.lang.NoSuchMethodError: No virtual method b()V in class Landroidx/recyclerview/widget/RecyclerView; or its super classes (declaration of 'androidx.recyclerview.widget.RecyclerView' appears in /data/app/~~ekKbhVjuldpSsqG5by7Nlg==/com.ishowedu.aitalk-htJL5mfnAuWeNHBHjIw1Zg==/base.apk)
	at androidx.recyclerview.widget.ChildHelper.a(ChildHelper.java:10)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.c(RecyclerView.java:23)
	at androidx.recyclerview.widget.LinearLayoutManager.y1(LinearLayoutManager.java:6)
	at androidx.recyclerview.widget.LinearLayoutManager.l1(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.z0(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.RecyclerView.s(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.q(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:8)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:870)
	at android.view.View.layout(View.java:23847)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4134)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3510)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2476)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9331)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1390)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1398)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1040)
	at android.view.Choreographer.doFrame(Choreographer.java:954)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1370)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8116)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Back traces ends.
```

提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没给出任何代码截图报错的，将绝对不会有任何反馈。这种issue也是一律直接关闭的,大家可以参阅[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。

Tinker是一个开源项目，希望大家遇到问题时要学会先思考，看看sample与Tinker的源码，更鼓励大家给我们提pr.

**Comment by yanjunhui2014** [comment]
确定了，系混淆开关导致。目前release混淆关闭，补丁就能正常加载。ext.tinkerApplyMappingPath 确认配置无误。请问这种情况和android.enableR8的修改有关吗？

**Comment by yanjunhui2014** [comment]
解决了，我解决的办法是在proguard-rules.pro中加入 -dontoptimize
(根目录gradle.properties中android.enableR8被注释之后，需要添加-dontoptimize，否则开启混淆后补丁即使加载成功，app也会奔溃)

**Comment by yanjunhui2014** [comment]
目前tinker补丁已经可以正常使用了，总结一下吧。
如果希望tinker可以正常使用，且修复率保持在99%+的水准，需要保证android.enableR8=false
```
projectDir/gradle.properties

android.enableR8.libraries=false
android.enableR8=false
```

如果你的工程在开启混淆后提示你

```
Please correct the above warnings first.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:minifyDebugWithProguard'.
......
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: Please correct the above warnings
......
Caused by: java.io.IOException: Please correct the above warnings first.
	at proguard.InputReader.execute(InputReader.java:149)
	at proguard.ProGuard.readInput(ProGuard.java:255)
	at proguard.ProGuard.execute(ProGuard.java:96)
......
```

那么你只需要在你的混淆文件projectDir/proguard-rules.pro中加入
```
-dontoptimize
-ignorewarnings
```

然后就可以通过编译了，而且打出来的补丁修复率极高。


当然，如果你不得不注释
```
android.enableR8.libraries=false
android.enableR8=false
```
那么混淆文件中配置
```
-dontoptimize
```
也可以保证你补丁正常生成，只不过补丁的成功率智能维持在95%左右。

PS
-dontoptimize
作用：忽略字节码优化

**Comment by KevonGeng** [comment]
👍
