### ISSUE TITLE
修改资源文件以后不能成功编译patch文件 报can't found string:only use for test tinker resource: a in the resources.arsc file's string pool!错误

### ISSUE THREAD

**Issue by 4XV** [Tencent/tinker#174]
## 崩溃详情       
Tinker的版本是1.7.3，android studio的版本是2.2，测试机型的系统版本是5.0，生成base.apk后在mainactivity中增加了一行toast，可以正常的生成new.apk和patch文件，也可以顺利的加载补丁文件并且生效，但是当我再在mainactivity的xml文件中增加了一个textview后便不能生成patch文件了，每次编译执行到tinkerPatchDebug这一项的时候都会崩溃并且报这个错误，tinkerApplyResourcePath的路径也正确配置了，把新添加的TextView删除后就又能正常编译patch文件。希望您能在百忙之中解答我的问题 谢谢。

## 下面是完整的崩溃日志

```
java.lang.RuntimeException: can't found string:only use for test tinker resource: a in the resources.arsc file's string pool!
	at com.tencent.tinker.build.apkparser.AndroidParser.editResourceTableString(AndroidParser.java:123)
	at com.tencent.tinker.build.decoder.ResDiffDecoder.modArscFileForTestResource(ResDiffDecoder.java:226)
	at com.tencent.tinker.build.decoder.ResDiffDecoder.onAllPatchesEnd(ResDiffDecoder.java:245)
	at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:125)
	at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
	at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
	at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
	at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.tinkerPatch(TinkerPatchSchemaTask.groovy:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:133)

```
## 下面是我的gradle配置

```
def bakPath = file("${buildDir}/bakApk/")
ext {
    tinkerEnabled = true
    tinkerOldApkPath = "${bakPath}/studentapp-debug-1115-12-09-53.apk"
    tinkerApplyMappingPath = "${bakPath}/"
    tinkerApplyResourcePath = "${bakPath}/studentapp-debug-1115-12-09-53-R.txt"
}

def getOldApkPath() {
    return hasProperty("OLD_APK") ? OLD_APK : ext.tinkerOldApkPath
}

def getApplyMappingPath() {
    return hasProperty("APPLY_MAPPING") ? APPLY_MAPPING : ext.tinkerApplyMappingPath
}

def getApplyResourceMappingPath() {
    return hasProperty("APPLY_RESOURCE") ? APPLY_RESOURCE : ext.tinkerApplyResourcePath
}

def getTinkerIdValue() {
    return hasProperty("TINKER_ID") ? TINKER_ID : getVersionName()
}

def buildWithTinker() {
    return hasProperty("TINKER_ENABLE") ? TINKER_ENABLE : ext.tinkerEnabled
}

if (buildWithTinker()) {
    apply plugin: 'com.tencent.tinker.patch'
    tinkerPatch {
        oldApk = getOldApkPath()
        ignoreWarning = false
        useSign = true
        buildConfig {
            applyMapping = getApplyMappingPath()
            applyResourceMapping = getApplyResourceMappingPath()
            tinkerId = getTinkerIdValue()
        }

        dex {
            dexMode = "jar"
            pattern = ["classes*.dex",
                       "assets/secondary-dex-?.jar"]
            loader = ["com.tencent.tinker.loader.*",
                      "org.zuicool.studentapp.EventHandler.AppApplication"
            ]
        }

        lib {
            pattern = ["lib/armeabi/*.so"]
        }

        res {
            pattern = ["res/*", "assets/*", "resources.arsc", "AndroidManifest.xml"]
            ignoreChange = ["assets/sample_meta.txt"]
            largeModSize = 100
        }

        packageConfig {
            configField("patchMessage", "tinker is sample to use")
            configField("platform", "all")
        }
        sevenZip {
            zipArtifact = "com.tencent.mm:SevenZip:1.1.10"
        }
    }

    android.applicationVariants.all { variant ->

        def taskName = variant.name

        tasks.all {
            if ("assemble${taskName.capitalize()}".equalsIgnoreCase(it.name)) {
                it.doLast {
                    copy {
                        def date = new Date().format("MMdd-HH-mm-ss")
                        from "${buildDir}/outputs/apk/${project.getName()}-${taskName}.apk"
                        into bakPath
                        rename { String fileName ->
                            fileName.replace("${project.getName()}-${taskName}.apk", "${project.getName()}-${taskName}-${date}.apk")
                        }
                        from "${buildDir}/outputs/mapping/${taskName}/mapping.txt"
                        into bakPath
                        rename { String fileName ->
                            fileName.replace("mapping.txt", "${project.getName()}-${taskName}-${date}-mapping.txt")
                        }
                        from "${buildDir}/intermediates/symbols/${taskName}/R.txt"
                        into bakPath
                        rename { String fileName ->
                            fileName.replace("R.txt", "${project.getName()}-${taskName}-${date}-R.txt")
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by shwenzhang** [comment]
你用的应该不是1.7.3，或者基准包引用的不是。

**Comment by 4XV** [comment]
compile('com.tencent.tinker:tinker-android-anno:1.7.3')
compile('com.tencent.tinker:tinker-android-lib:1.7.3')
compile 'com.android.support:multidex:1.0.1'
这是我的依赖脚本，版本应该是1.7.3没错

基准包引用的也是这个，但是我把tinker的依赖项配置到了一个公共类库里面，然后app依赖这个公共类库，也就是说我的app的build.gradle里面没有直接依赖tinker， 而是通过这个公共类库间接依赖的tinker，是因为这个原因吗。

**Comment by shwenzhang** [comment]
这个代码是tinker-gradle-plugin的版本问题，看一下你根目录的build.gradle文件

**Comment by 4XV** [comment]
恩恩 的确是tinker-gradle-plugin的版本问题 非常感谢
