### ISSUE TITLE
tinker patch exception  java.lang.NoSuchMethodError: No direct method  <init>(Ljava/lang/String;Ljava/lang/String;ZZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V in class

### ISSUE THREAD

**Issue by taofaqi** [Tencent/tinker#1744]
合并补丁包失败。

手机型号：Huawei Mate50Pro
手机系统版本：HarmonyOS 4.0.0
tinker版本：1.9.14.26.3
gradle版本：7.1.1
是否使用热更新SDK：  TinkerPatch SDK 

系统：如:Macbookpro-m2

tinker patch exception  java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;ZZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V in class Lcom/tencent/tinker/loader/shareutil/SharePatchInfo; or its super classes (declaration of 'com.tencent.tinker.loader.shareutil.SharePatchInfo' appears in /data/app/com.ttpc.bidding_hall-_R8nO2amA2YIBqjq5ByV8g==/base.apk!classes2.dex)
                                                                                                    	at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:402)
                                                                                                    	at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(TinkerPatchService.java:88)
                                                                                                    	at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:4)
                                                                                                    	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by jacklongway** [comment]
您好！很高兴收到您的邮件，稍后查看。

**Comment by canlan818** [comment]
这是来自QQ邮箱的自动回复邮件。您好，来信已收到，谢谢您，我会及时回复您的！O(∩_∩)O~

**Comment by mrzbn** [comment]
@taofaqi did you find the cause or solution?
