### ISSUE TITLE
删除sample项目的BaseBuildInfo类后报错

### ISSUE THREAD

**Issue by jp1017** [Tencent/tinker#198]
```
java.lang.RuntimeException: com.tencent.tinker.build.util.TinkerPatchException: loader classes in old primary dex are mismatched to those in new primary dex, 
if deleted classes is not empty, check if your dex division strategy is fine. 
added classes: {}
deleted classes: {Ltinker/sample/android/app/BaseBuildInfo;}
	at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:179)
	at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:138)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:113)
	at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
	at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
	at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
```

同时删除的还有 `BuildInfo`, 什么样的类不能删除？

**Comment by jp1017** [comment]
gradle 看到了这个:

```
            loader = ["com.tencent.tinker.loader.*",
                      //todo, you must change it with your application
                      "tinker.sample.android.app.SampleApplication",
                      //use sample, let BaseBuildInfo unchangeable with tinker
                      "tinker.sample.android.app.BaseBuildInfo"
            ]
```

`BaseBuildInfo` 有哪些作用呢，我都删了,,, :disappointed:

**Comment by shwenzhang** [comment]
如果你删除它，就也要在loader pattern同时删除！

**Comment by jp1017** [comment]
懂了，谢谢！
