### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by ruanlei** [Tencent/tinker#210]
Tinker Version: 1.7.5
Crash User: 66
Crash Count: 66
Devices: Meitu M4, Meitu M4s, OPPO R7, OPPO R7s, R8107, 
OS: 4.4.4 (86%), 4.4.2 (12%), 4.2.2 (2%)

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx/xxxActivity}: android.content.res.Resources$NotFoundException: failed to add asset path /data/user/0/xxx/tinker/patch-e8eea126/res/resources.apk
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by android.content.res.Resources$NotFoundException: failed to add asset path /data/user/0/xxx/tinker/patch-e8eea126/res/resources.apk
       at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:275)
       at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:332)
       at android.app.ResourcesManager.getOrCreateResources(ResourcesManager.java:612)
       at android.app.ResourcesManager.createBaseActivityResources(ResourcesManager.java:540)
       at android.app.ContextImpl.(ContextImpl.java:2237)
       at android.app.ContextImpl.createActivityContext(ContextImpl.java:2167)
       at android.app.ActivityThread.createBaseContextForActivity(ActivityThread.java:2810)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2710)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by shwenzhang** [comment]
link https://code.google.com/p/android/issues/detail?id=228618

**Comment by shwenzhang** [comment]
原因是因为删除了补丁，但是没有去重启进程，是应用自己处理的问题

**Comment by richzjc** [comment]
为什么 这个问题只发生在华为7.0的手机上面？  针对华为7.0的手机出现这样的问题  如何才能解决呢？
