### ISSUE TITLE
TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found

### ISSUE THREAD

**Issue by ruanlei** [Tencent/tinker#213]
100%
Android 7.0

Fatal Exception: java.lang.RuntimeException: Unable to create service com.baidu.location.f: java.lang.RuntimeException: Unable to instantiate application xxx.xxx.xxx.GenApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3345)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by java.lang.RuntimeException: Unable to instantiate application xxx.xxx.xxx.GenApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
       at android.app.LoadedApk.makeApplication(LoadedApk.java:855)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3325)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:140)
       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154)
       at android.app.Application.attach(Application.java:189)
       at android.app.Instrumentation.newApplication(Instrumentation.java:1011)
       at android.app.Instrumentation.newApplication(Instrumentation.java:995)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3325)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:138)
       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154)
       at android.app.Application.attach(Application.java:189)
       at android.app.Instrumentation.newApplication(Instrumentation.java:1011)
       at android.app.Instrumentation.newApplication(Instrumentation.java:995)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3325)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by java.lang.IllegalAccessError: Field 'xxx.xxx.xxx.hotfix.ApplicationDelegator.myApplication' is inaccessible to class 'xxx.xxx.xxx.hotfix.ApplicationDelegator' (declaration of 'xxx.xxx.xxx.hotfix.ApplicationDelegator' appears in /data/user/0/xxx.xxx.xxx/tinker/patch-ac02970d/dex/classes.dex)
       at xxx.xxx.xxx.hotfix.ApplicationDelegator.onBaseContextAttached(ApplicationDelegator.java:91)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:138)
       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154)
       at android.app.Application.attach(Application.java:189)
       at android.app.Instrumentation.newApplication(Instrumentation.java:1011)
       at android.app.Instrumentation.newApplication(Instrumentation.java:995)
       at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3325)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by helloJude** [comment]
嗯 我之前用米4  android6.0系统， 跑通了sample，然后今天再想着运行一下就报错了， 然后用 联想 android 4.4 的 却可以运行。。。。。

**Comment by shwenzhang** [comment]
原因是因为删除了补丁，但是没有去重启进程，是应用自己处理的问题
