### ISSUE TITLE
1.7.5版本，app在加载补丁时报错

### ISSUE THREAD

**Issue by 1987jin** [Tencent/tinker#219]
tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:patch dex_art extract failed (/data/data/com.vehicles.activities/tinker/patch-5002e91a/patch-5002e91a.apk: open failed: ENOENT (No such file or directory)).
                                                                                              at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(DexDiffPatchInternal.java:274)
                                                                                              at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:76)
                                                                                              at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:66)
                                                                                              at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:128)
                                                                                              at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:139)
                                                                                              at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                           Caused by: java.io.FileNotFoundException: /data/data/com.vehicles.activities/tinker/patch-5002e91a/patch-5002e91a.apk: open failed: ENOENT (No such file or directory)
                                                                                              at libcore.io.IoBridge.open(IoBridge.java:456)
                                                                                              at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
                                                                                              at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
                                                                                              at java.util.zip.ZipFile.<init>(ZipFile.java:158)
                                                                                              at java.util.zip.ZipFile.<init>(ZipFile.java:119)
                                                                                              at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(DexDiffPatchInternal.java:144)
                                                                                              at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:76) 
                                                                                              at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:66) 
                                                                                              at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:128) 
                                                                                              at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:139) 
                                                                                              at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                           Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                              at libcore.io.Posix.open(Native Method)
                                                                                              at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                                              at libcore.io.IoBridge.open(IoBridge.java:442)
                                                                                              at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117) 
                                                                                              at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149) 
                                                                                              at java.util.zip.ZipFile.<init>(ZipFile.java:158) 
                                                                                              at java.util.zip.ZipFile.<init>(ZipFile.java:119) 
                                                                                              at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(DexDiffPatchInternal.java:144) 
                                                                                              at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:76) 
                                                                                              at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:66) 
                                                                                              at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:128) 
                                                                                              at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:139) 
                                                                                              at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by shwenzhang** [comment]
日志已经很清晰了
