### ISSUE TITLE
java.util.zip.ZipException: attempt to write past end of STORED entry

### ISSUE THREAD

**Issue by AllenCoder** [Tencent/tinker#236]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithAuxiliaryInjectForWattDebug'.
> java.util.zip.ZipException: attempt to write past end of STORED entry

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithAuxiliaryInjectForWattDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: attempt to write past end of STORED entry
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:158)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:158)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:118)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
Caused by: java.util.zip.ZipException: attempt to write past end of STORED entry
	at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processClass(AuxiliaryClassInjector.java:120)
	at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJarHelper(AuxiliaryClassInjector.java:97)
	at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJar(AuxiliaryClassInjector.java:69)
	at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector$processJar$0.call(Unknown Source)
	at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform$_transform_closure5.doCall(AuxiliaryInjectTransform.groovy:287)
	at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform.transform(AuxiliaryInjectTransform.groovy:264)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	... 21 more


BUILD FAILED

```

**Comment by shwenzhang** [comment]
使用 dev 分支的localmaven测试
