### ISSUE TITLE
某些机型 加载补丁后闪退

### ISSUE THREAD

**Issue by shingohu** [Tencent/tinker#244]
设备,日志如下 
![image](https://cloud.githubusercontent.com/assets/4944887/21044179/994a2bce-be35-11e6-9ded-37c4b81482ae.png)

java.lang.NoClassDefFoundError: android/os/PersistableBundle
	at java.lang.Class.getDeclaredMethods(Native Method)
	at java.lang.Class.getDeclaredMethods(Class.java:656)
	at de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:75)
	at de.greenrobot.event.EventBus.register(EventBus.java:163)
	at de.greenrobot.event.EventBus.register(EventBus.java:133)
	at com.naodong.xgs.domain.b.f.b(EventManager.java:28)
	at com.naodong.xgs.presentation.base.BaseActivity.y(BaseActivity.java:316)
	at com.naodong.xgs.googker.ui.GoogkerTaskDetailActivity.j(GoogkerTaskDetailActivity.java:152)
	at com.naodong.xgs.presentation.base.BaseActivity.onCreate(BaseActivity.java:68)
	at android.app.Activity.performCreate(Activity.java:5285)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2345)
	at android.app.ActivityThread.access$1100(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5314)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.PersistableBundle" on path: DexPathList[[zip file "/data/data/com.naodong.xgs/tinker/patch-4439d283/dex/classes.dex.jar", zip file "/data/data/com.naodong.xgs/tinker/patch-4439d283/dex/test.dex.jar", zip file "/data/app/com.naodong.xgs-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.naodong.xgs-2, /vendor/lib, /system/lib, /data/datalib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 23 more

**Comment by shwenzhang** [comment]
1. tinker版本 2.人数，基础版本是否会出现

**Comment by shingohu** [comment]
@shwenzhang
1. 1.7.5 
2.人数不多 基本集中在华为手机和vivo上
3.直接打包出来的版本也会

**Comment by shingohu** [comment]
@shwenzhang  不好意思 可能是这个的问题 http://blog.csdn.net/lovejjfg/article/details/49796665
