### ISSUE TITLE
Didn't find class "com.tencent.tinker.commons.dexpatcher.DexPatchApplier" on path: DexPathList[[zip file "/data/app/tinker.sample.android-1/base.apk"]

### ISSUE THREAD

**Issue by weiyf** [Tencent/tinker#248]
```
tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:patch dex_art extract failed (Failed resolution of: Lcom/tencent/tinker/commons/dexpatcher/DexPatchApplier;).
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(DexDiffPatchInternal.java:274)
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:76)
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:66)
at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:128)
at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:139)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:150)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tinker/commons/dexpatcher/DexPatchApplier;
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexFile(DexDiffPatchInternal.java:409)
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(DexDiffPatchInternal.java:260)
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:76) 
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:66) 
at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:128) 
at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:139) 
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:150) 
at android.os.HandlerThread.run(HandlerThread.java:61) 
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.commons.dexpatcher.DexPatchApplier" on path: DexPathList[[zip file "/data/app/tinker.sample.android-1/base.apk"],nativeLibraryDirectories=[/data/app/tinker.sample.android-1/lib/arm64, /vendor/lib64, /system/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexFile(DexDiffPatchInternal.java:409) 
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(DexDiffPatchInternal.java:260) 
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:76) 
at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:66) 
at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:128) 
at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:139) 
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:150) 
at android.os.HandlerThread.run(HandlerThread.java:61) 
Suppressed: java.lang.ClassNotFoundException: com.tencent.tinker.commons.dexpatcher.DexPatchApplier
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 11 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by shwenzhang** [comment]
将Tinker版本这些信息都应该列出来

**Comment by weiyf** [comment]
跑的是github上刚clone下来的sample，测试机手机是荣耀7，电脑是ubuntu系统
```
12-13 14:10:04.055 405-405/tinker.sample.android I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, isUpgrade:true, file size:4271
12-13 14:10:04.063 405-405/tinker.sample.android I/Tinker.SamplePatchListener: get platform:all
12-13 14:10:04.340 405-3879/tinker.sample.android I/Tinker.SampleResultService: SampleResultService receive result: 
PatchResult: 
isUpgradePatch:true
isSuccess:false
rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
costTime:51
patchVersion:bb40b5a84563fe0603275f468cc3fc23
Throwable:Tinker Exception:patch dex_art extract failed (Failed resolution of: Lcom/tencent/tinker/commons/dexpatcher/DexPatchApplier;).
```

**Comment by weiyf** [comment]
@shwenzhang 我在Windows跑了一次， 发现是没有问题的，暂时没发现是什么问题！

**Comment by weiyf** [comment]
@shwenzhang 为什么在ubuntu系统 生成的补丁是会出错的呢？

**Comment by weiyf** [comment]
@shwenzhang 为什么在ubuntu系统 生成的补丁是会出错的呢？

**Comment by shwenzhang** [comment]
跟系统没有关系的把，你自己clean再试试。我这边也有ubuntu的机器，也没有问题
