### ISSUE TITLE
完全相同的配置，对同一个release包打包，不同电脑打补丁失败

### ISSUE THREAD

**Issue by OoadaioO** [Tencent/tinker#254]
混淆去掉了-keep class com.tencent.tinker.loader.** {
    *;
}
本地proguard 版本 4.7
release包和混淆文件git 提交以后，对release包打补丁
同样配置下有些电脑打补丁是提示异常
com.tencent.tinker.build.util.TinkerPatchException: some loader class has been changed in new dex. Such these changes will not take effect!! related classes: {Lcom/tencent/tinker/loader/R;}
	at com.tencent.tinker.build.util.ExcludedClassModifiedChecker.checkIfExcludedClassWasModifiedInNewDex(ExcludedClassModifiedChecker.java:190)
	at com.tencent.tinker.build.decoder.DexDiffDecoder.patch(DexDiffDecoder.java:133)
	at com.tencent.tinker.build.decoder.UniqueDexDiffDecoder.patch(UniqueDexDiffDecoder.java:39)
	at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:176)

确认过基准包tinkerid 是同一个
打release包的电脑打补丁必定成功，其他电脑有些能成功有些不能成功，请问是什么原因导致的

**Comment by tomystang** [comment]
先手动对比一下Lcom/tencent/tinker/loader/R这个类在新旧两个包之间究竟多了哪些内容，然后把结果贴上来吧。

**Comment by OoadaioO** [comment]
老版的release包打补丁失败，1.7.5打的的release包不会出现该问题了，老版打包会生成动态生成一个com.tencent.tinker.loader.R文件，新版打包不会生成所以就没问题了

**Comment by shwenzhang** [comment]
因为人力问题，旧版本不会再维护，这种情况你可以把ignoreWarning打卡，这个文件的改变不会有问题的。但是要仔细看最终的编译日志
