### ISSUE TITLE
4.4 设备 Tinker Exception:onBaseContextAttached method not found

### ISSUE THREAD

**Issue by laobie** [Tencent/tinker#263]
报错信息如下：

```
 com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:136)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                               at dalvik.system.NativeStart.main(Native Method)
                                                            Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:140)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:154)
                                                               at android.app.Application.attach(Application.java:181)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:136) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:138)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:154) 
                                                               at android.app.Application.attach(Application.java:181) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:136) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: java.lang.NoClassDefFoundError: android.support.multidex.MultiDex
                                                               at com.mingdao.app.common.AppLike.onBaseContextAttached(AppLike.java:99)
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:138) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:154) 
                                                               at android.app.Application.attach(Application.java:181) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:136) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
```

我 debug 了一下，是找不到  MultiDex 类原因，但是我查看 apk ，主 dex 中是有 MultiDex 类的，截图如下。

![image](https://cloud.githubusercontent.com/assets/7184320/21255658/39315e74-c3a8-11e6-8627-ff69b18f2cb7.png)

![image](https://cloud.githubusercontent.com/assets/7184320/21255687/7493f95e-c3a8-11e6-9285-6c5125ca04f7.png)

在 AppLike 中重写了  `onBaseContextAttached`  方法

``` java
    @Override
    public void onBaseContextAttached(Context base) {
        super.onBaseContextAttached(base);
        //you must install multiDex whatever tinker is installed!
        MultiDex.install(base);
        initTinker();
    }
```

**Comment by laobie** [comment]
在 5.0 以上的机器是上正常运行的，补丁应用也是成功的。

**Comment by shwenzhang** [comment]
4.X就是分包问题

**Comment by gaoxuefeng** [comment]
这个问题怎么解决

**Comment by laobie** [comment]
@gaoxuefeng 我们这边使用了分包插件，目前还没解决，还在解决中

**Comment by gaoxuefeng** [comment]
4.4及以下的问题解决了吗?

**Comment by laobie** [comment]
@gaoxuefeng 手动将 AppLike 中的相关类加到 keep 中，保证在主 dex 中
