### ISSUE TITLE
NoSuchMethodException

### ISSUE THREAD

**Issue by zhangpingV5** [Tencent/tinker#268]
打包安装到手机上后，启动闪退。文档中Application相关的部分均有排查，没有找到问题。请大神指点一二。

12-19 15:46:45.710 3376-3376/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: android.upedu.meeting, PID: 3376
                                                 java.lang.RuntimeException: Unable to instantiate application android.upedu.meeting.MeetingApp: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:537)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586)
                                                     at android.app.ActivityThread.access$1800(ActivityThread.java:139)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5314)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                     at com.tencent.tinker.loader.app.TinkerApplication.a(Unknown Source)
                                                     at com.tencent.tinker.loader.app.TinkerApplication.b(Unknown Source)
                                                     at com.tencent.tinker.loader.app.TinkerApplication.c(Unknown Source)
                                                     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source)
                                                     at android.app.Application.attach(Application.java:200)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:992)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:976)
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:532)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
                                                     at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5314) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.NoSuchMethodException: <init> [class android.app.Application, int, boolean, long, long, class android.content.Intent, class [Landroid.content.res.Resources;, class [Ljava.lang.ClassLoader;, class [Landroid.content.res.AssetManager;]
                                                     at java.lang.Class.getConstructorOrMethod(Class.java:472)
                                                     at java.lang.Class.getConstructor(Class.java:446)
                                                     at com.tencent.tinker.loader.app.TinkerApplication.a(Unknown Source) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.b(Unknown Source) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.c(Unknown Source) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source) 
                                                     at android.app.Application.attach(Application.java:200) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:532) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586) 
                                                     at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5314) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by shwenzhang** [comment]
1. maindex pattern问题
