### ISSUE TITLE
tinker 集成到项目加載闪退，锁屏关闭后打开app闪退，app运行一会也闪退，这是为何？

### ISSUE THREAD

**Issue by yangxp108** [Tencent/tinker#283]
tinker 集成到项目加载闪退，锁屏关闭后打开app闪退，app运行一会也闪退，这是为何？ app是加载成功内容修改成功。

**Comment by zzwwws** [comment]
闪退的日志贴一下啊

**Comment by yangxp108** [comment]
12-25 17:57:24.585 2447-2447/? E/Thermal-daemon: [pa_0] temp_new :29  temp_old :30
12-25 17:57:26.490 6012-6012/? E/qiso: 2adapter
12-25 17:57:26.735 6012-6012/? E/qiso: 2adapter
12-25 17:57:27.190 6012-6012/? E/JPush: [e] JPushInterface.onResume() must be called after called JPushInterface.onPause() and JPushInterface.onResume should not be called more time in last Activity or Fragment  
12-25 17:57:27.190 6012-6012/? E/qisos: ShowViewPager  hometime
12-25 17:57:27.645 6012-6012/? E/qiso: onDestroy 0
12-25 17:57:29.590 2447-2447/? E/Thermal-daemon: [ap] temp_new :33  temp_old :34
12-25 17:57:31.380 3297-3413/? E/WifiService: wifiservice ACTION_SCREEN_ON -> ctrlSocket sretVal :1
12-25 17:57:31.400 2439-3100/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:57:31.785 6012-6012/? E/qisos: ShowViewPager  hometime___stoppp
12-25 17:57:31.820 3435-3435/? E/KeyguardHostView: KeyguardHostView()
12-25 17:57:31.820 2439-3031/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:57:31.825 2439-3031/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:57:31.825 2439-3031/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:57:31.885 3297-3542/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
12-25 17:57:31.915 2439-2439/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:57:31.925 3297-3308/? E/ActivityManager: check pkg = ComponentInfo{com.ali.money.shield/com.ali.money.shield.service.ForeService}, isNotAllowedRestart = false, allowRestart = true
12-25 17:57:32.120 3435-3435/? E/AuthenticationManager: AuthenticationManager open failed: the AuthenticationService is null
12-25 17:57:32.140 3435-3435/? E/AbsClockView: In setFactory...
12-25 17:57:32.140 3435-3435/? E/HwClockView: In HwClockView...
12-25 17:57:32.215 3435-3435/? E/AbsClockView: In setFactory...
12-25 17:57:32.215 3435-3435/? E/HwClockView: In HwClockView...
12-25 17:57:32.240 8376-9031/? E/UGCHttpClient: HCDN_LOG: [2016/12/25-17:57:32:245]:GetHostByName(pdata.video.iqiyi.com) takes 1 ms.
12-25 17:57:32.255 8376-9031/? E/UGCHttpClient: HCDN_LOG: [2016/12/25-17:57:32:262]:connect(pdata.video.iqiyi.com) takes 16 ms.
12-25 17:57:32.295 3435-3435/? E/AbsClockView: In setFactory...
12-25 17:57:32.295 3435-3435/? E/HwClockView: In HwClockView...
12-25 17:57:33.245 6012-6012/? E/JPush: [e] JPushInterface.onResume() must be called after called JPushInterface.onPause() and JPushInterface.onResume should not be called more time in last Activity or Fragment  
12-25 17:57:33.250 6012-6012/? E/qisos: ShowViewPager  hometime
12-25 17:57:33.320 3297-3413/? E/WifiService: wifiservice ACTION_SCREEN_ON -> ctrlSocket sretVal :1
12-25 17:57:33.375 3900-3900/? E/HwLauncher: Launcher dialog dismiss failed : java.lang.IllegalArgumentException: no dialog with id 1 was ever shown via Activity#showDialog
12-25 17:57:33.385 2439-3100/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:57:35.080 3435-3435/? E/AbsKeyguardPatternView: In setFactory...
12-25 17:57:35.080 3435-3435/? E/HwKeyguardPatternView: In HwKeyguardPatternView...
12-25 17:57:35.320 2432-3266/? E/CommandListener: readDefRoute call readDefRoute
12-25 17:57:35.320 2432-3266/? E/SecondaryTablController: isWifiDefaultRouteExisted /system/bin/ip route
12-25 17:57:36.325 2432-3266/? E/CommandListener: readDefRoute Rsp ok
12-25 17:57:36.325 3297-3297/? E/NetdConnector: NDC Command {57 interface route readDefRoute} took too long (1007ms)
12-25 17:57:36.425 2439-3031/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:57:36.425 2439-3031/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:57:36.425 2439-3031/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:57:36.480 3946-10944/? E/HwMtpServerExJNI: void android_mtp_MtpServerEx_add_storage(JNIEnv*, jobject, jobject), line 138: descriptionStr = 内存设备
12-25 17:57:36.525 8639-8639/? E/Utils: lockCreate
12-25 17:57:36.585 8639-8639/? E/Utils: release: release wake and wifi lock!
12-25 17:57:36.925 6012-10950/? E/Bugout: ****************************************
12-25 17:57:36.925 6012-10950/? E/Bugout: A Java crash caught by Bugout, pkg=com.chuizhicai 
12-25 17:57:36.925 6012-10950/? E/Bugout: ----------------------------------------
12-25 17:57:36.925 6012-10950/? E/Bugout: reason: java.lang.NoClassDefFoundError: cn/jpush/android/service/PushProtocol 
12-25 17:57:36.925 6012-10950/? E/Bugout: ----------------------------------------
12-25 17:57:36.925 6012-10950/? E/Bugout: stacktrace: 
                                          
                                              at cn.jpush.android.b.a(Unknown Source)
                                              at cn.jpush.android.b.a(Unknown Source)
                                              at cn.jpush.android.service.PushReceiver.onReceive(Unknown Source)
                                              at android.app.ActivityThread.handleReceiver(ActivityThread.java:2533)
                                              at android.app.ActivityThread.access$2000(ActivityThread.java:139)
                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                              at android.os.Looper.loop(Looper.java:136)
                                              at android.app.ActivityThread.main(ActivityThread.java:5315)
                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                              at dalvik.system.NativeStart.main(Native Method)
12-25 17:57:36.925 6012-10950/? E/Bugout: ----------------------------------------
12-25 17:57:36.925 6012-10950/? E/Bugout: deviceinfo: 
                                          	Device: Huawei/PE-UL00
                                          	OS: 4.4.2
                                          	AppVersion: 3.2(45)
                                          	PackageName: com.chuizhicai
                                          	Activity: CZC_MainActivity
                                          	Total Disk Space: 11849 MB ; Free Disk Space: 5333 MB 
                                          	Total SD Space: 11829 MB ; Free SD Space: 5313 MB 
                                          	CPU Usage: 2.21 % 
                                          	Memory Usage: 98 MB
                                          	Userinfo: 18720970820 
12-25 17:57:36.925 6012-10950/? E/Bugout: ****************************************
12-25 17:57:37.195 6012-6012/? E/Tinker.SampleUncaughtExHandler: uncaughtException:cn/jpush/android/service/PushProtocol
12-25 17:57:37.195 6012-6012/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.chuizhicai, PID: 6012
                                                 java.lang.NoClassDefFoundError: cn/jpush/android/service/PushProtocol
                                                     at cn.jpush.android.b.a(Unknown Source)
                                                     at cn.jpush.android.b.a(Unknown Source)
                                                     at cn.jpush.android.service.PushReceiver.onReceive(Unknown Source)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2533)
                                                     at android.app.ActivityThread.access$2000(ActivityThread.java:139)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                     at dalvik.system.NativeStart.main(Native Method)
12-25 17:57:37.225 4672-4857/? E/SubmitMessage: Submit string: submit:trigger=0,bugtype=2,modulename=com.chuizhicai,level=1,testtype=NORMAL,path=/data/log/unzip/PE-UL00_V100R001CHNC00B200_M3LDU15A06009631_20161225175737_crash
12-25 17:57:38.080 4672-4841/? E/PackageLogInfoManager: checkPackageLogState, cr: android.app.ContextImpl$ApplicationContentResolver@43251328, packageNames: null
12-25 17:57:38.480 3946-3946/? E/HwMtpServerExJNI: void android_mtp_MtpServerEx_add_storage(JNIEnv*, jobject, jobject), line 138: descriptionStr = 内存设备
12-25 17:57:39.600 2447-2447/? E/Thermal-daemon: [ap] temp_new :34  temp_old :33

**Comment by yangxp108** [comment]
12-25 17:59:11.270 3297-3413/? E/WifiService: wifiservice ACTION_SCREEN_ON -> ctrlSocket sretVal :1
12-25 17:59:11.305 3297-3321/? E/UsbDeviceManager:  mCurrentFunctions  = mtp,adb
12-25 17:59:11.305 3297-3321/? E/UsbDeviceManager:  functions  = mtp,adb
12-25 17:59:11.305 3297-3321/? E/UsbDeviceManager:  mDefaultFunctions  = mtp,adb
12-25 17:59:11.355 3297-7214/? E/UsbDebuggingManager: got -1 reading
12-25 17:59:11.365 2439-3100/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:59:12.425 3435-3435/? E/AbsKeyguardPatternView: In setFactory...
12-25 17:59:12.425 3435-3435/? E/HwKeyguardPatternView: In HwKeyguardPatternView...
12-25 17:59:13.280 2432-3266/? E/CommandListener: readDefRoute call readDefRoute
12-25 17:59:13.280 2432-3266/? E/SecondaryTablController: isWifiDefaultRouteExisted /system/bin/ip route
12-25 17:59:13.655 2439-3031/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:59:13.660 2439-3031/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:59:13.665 2439-3031/? E/AudioFlinger: setLppDtsGeq():invalid keyValue of dts geq.
12-25 17:59:13.705 3946-11479/? E/HwMtpServerExJNI: void android_mtp_MtpServerEx_add_storage(JNIEnv*, jobject, jobject), line 138: descriptionStr = 内存设备
12-25 17:59:13.760 8639-8639/? E/Utils: lockCreate
12-25 17:59:13.810 8639-8639/? E/Utils: release: release wake and wifi lock!
12-25 17:59:13.830 11195-11195/? E/JPush: [e] JPushInterface.onResume() must be called after called JPushInterface.onPause() and JPushInterface.onResume should not be called more time in last Activity or Fragment  
12-25 17:59:13.835 11195-11195/? E/qisos: ShowViewPager  hometime
12-25 17:59:14.085 11195-11484/? E/Bugout: ****************************************
12-25 17:59:14.085 11195-11484/? E/Bugout: A Java crash caught by Bugout, pkg=com.chuizhicai 
12-25 17:59:14.085 11195-11484/? E/Bugout: ----------------------------------------
12-25 17:59:14.085 11195-11484/? E/Bugout: reason: java.lang.NoClassDefFoundError: cn/jpush/android/service/PushProtocol 
12-25 17:59:14.085 11195-11484/? E/Bugout: ----------------------------------------
12-25 17:59:14.085 11195-11484/? E/Bugout: stacktrace: 
                                           
                                               at cn.jpush.android.b.a(Unknown Source)
                                               at cn.jpush.android.b.a(Unknown Source)
                                               at cn.jpush.android.service.PushReceiver.onReceive(Unknown Source)
                                               at android.app.ActivityThread.handleReceiver(ActivityThread.java:2533)
                                               at android.app.ActivityThread.access$2000(ActivityThread.java:139)
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                               at android.os.Looper.loop(Looper.java:136)
                                               at android.app.ActivityThread.main(ActivityThread.java:5315)
                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                               at dalvik.system.NativeStart.main(Native Method)
12-25 17:59:14.085 11195-11484/? E/Bugout: ----------------------------------------
12-25 17:59:14.085 11195-11484/? E/Bugout: deviceinfo: 
                                           	Device: Huawei/PE-UL00
                                           	OS: 4.4.2
                                           	AppVersion: 3.2(45)
                                           	PackageName: com.chuizhicai
                                           	Activity: CZC_MainActivity
                                           	Total Disk Space: 11849 MB ; Free Disk Space: 5330 MB 
                                           	Total SD Space: 11829 MB ; Free SD Space: 5310 MB 
                                           	CPU Usage: 6.287 % 
                                           	Memory Usage: 107 MB
                                           	Userinfo: 18720970820 
12-25 17:59:14.085 11195-11484/? E/Bugout: ****************************************
12-25 17:59:14.285 2432-3266/? E/CommandListener: readDefRoute Rsp ok
12-25 17:59:14.285 3297-3297/? E/NetdConnector: NDC Command {64 interface route readDefRoute} took too long (1007ms)
12-25 17:59:14.300 3297-3539/? E/NetdConnector: NDC Command {65 bandwidth gettetherstats} took too long (574ms)
12-25 17:59:14.495 11195-11195/? E/Tinker.SampleUncaughtExHandler: uncaughtException:cn/jpush/android/service/PushProtocol
12-25 17:59:14.500 11195-11195/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.chuizhicai, PID: 11195
                                                   java.lang.NoClassDefFoundError: cn/jpush/android/service/PushProtocol
                                                       at cn.jpush.android.b.a(Unknown Source)
                                                       at cn.jpush.android.b.a(Unknown Source)
                                                       at cn.jpush.android.service.PushReceiver.onReceive(Unknown Source)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2533)
                                                       at android.app.ActivityThread.access$2000(ActivityThread.java:139)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5315)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                       at dalvik.system.NativeStart.main(Native Method)
12-25 17:59:14.545 4672-4857/? E/SubmitMessage: Submit string: submit:trigger=0,bugtype=2,modulename=com.chuizhicai,level=1,testtype=NORMAL,path=/data/log/unzip/PE-UL00_V100R001CHNC00B200_M3LDU15A06009631_20161225175914_crash
12-25 17:59:14.675 2447-2447/? E/Thermal-daemon: [flash_led] temp_new :28  temp_old :27
12-25 17:59:14.675 2447-2447/? E/Thermal-daemon: [ap] temp_new :33  temp_old :32
12-25 17:59:15.135 4672-4841/? E/PackageLogInfoManager: checkPackageLogState, cr: android.app.ContextImpl$ApplicationContentResolver@43251328, packageNames: null

**Comment by shwenzhang** [comment]
see wiki

**Comment by yangxp108** [comment]
是35分前闪退
