### ISSUE TITLE
Tinker Exception:checkSafeModeCount fail

### ISSUE THREAD

**Issue by KgdFnYpeu** [Tencent/tinker#300]
在华为上能正常修复问题，但是在小米 HM2上，加载补丁过程中，会出现如下异常:
我看了checkSafeModeCount 代码，TINKER_SAFE_MODE_COUNT这个标识应该是每个进程只会为赋一次值1才对，实在不知道为什么还会超过3，也不知道这里 checkModeCount 的意义何在，希望能够回应帮助，谢谢
tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
                                                                              at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TbsSdkJava:220)
                                                                              at com.tencent.tinker.loader.TinkerLoader.tryLoad(TbsSdkJava:56)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TbsSdkJava:171)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TbsSdkJava:135)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TbsSdkJava:156)
                                                                              at android.app.Application.attach(Application.java:184)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4413)
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:141)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                              at dalvik.system.NativeStart.main(Native Method)
11-21 16:20:12.343 14309-14309/? E/fxtv_tinkerTinker.SampleLoadReporter: tinker uncaught real exception:process:com.fxtv.threebears
                                                                         java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                                             at com.fxtv.threebears.tinker.SampleApplicationLike.onBaseContextAttached(TbsSdkJava:90)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TbsSdkJava:139)
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TbsSdkJava:156)
                                                                             at android.app.Application.attach(Application.java:184)
                                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4413)
                                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:141)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:136)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by shwenzhang** [comment]
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
，查看文档
