### ISSUE TITLE
Caused by: java.lang.NumberFormatException: For input string: " 0x7f0e0081"

### ISSUE THREAD

**Issue by LaughingAndroid** [Tencent/tinker#303]
Caused by: java.lang.NumberFormatException: For input string: " 0x7f0e0081"
        at com.tencent.tinker.build.aapt.AaptResourceCollector.<init>(AaptResourceCollector.java:73)
        at com.tencent.tinker.build.aapt.AaptUtil.collectResource(AaptUtil.java:82)
        at com.tencent.tinker.build.aapt.AaptUtil$collectResource.call(Unknown Source)
        at com.tencent.tinker.build.gradle.task.TinkerResourceIdTask.applyResourceId(TinkerResourceIdTask.groovy:63)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)

**Comment by LaughingAndroid** [comment]
有些id莫名其妙有空格，代码可以加固一下

**Comment by shwenzhang** [comment]
tinker的版本？

**Comment by LaughingAndroid** [comment]
TINKER_VERSION=1.7.6

**Comment by shwenzhang** [comment]
dev已经加了代码
