### ISSUE TITLE
IOException writing serializable object

### ISSUE THREAD

**Issue by huzhenjie** [Tencent/tinker#314]
加上之后就出现这个异常了，Activity间传递 serializable obj出现的

```
E/Tinker.SampleUncaughtExHandler: uncaughtException:Parcelable encountered IOException writing serializable object (name = com.scrat.data.model.AuthAccount)
E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.scrat.data.model.AuthAccount)
                              at android.os.Parcel.writeSerializable(Parcel.java:1388)
                              at android.os.Parcel.writeValue(Parcel.java:1335)
                              at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                              at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                              at android.os.Bundle.writeToParcel(Bundle.java:1096)
                              at android.os.Parcel.writeBundle(Parcel.java:663)
                              at android.content.Intent.writeToParcel(Intent.java:7192)
                              at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2396)
                              at android.app.Instrumentation.execStartActivity(Instrumentation.java:1480)
                              at android.app.Activity.startActivityForResult(Activity.java:3742)
                              at android.app.Activity.startActivityForResult(Activity.java:3703)
                              at android.support.v4.b.m.startActivityForResult(Unknown Source)
                              at com.scrat.module.account.edit.AccountEditActivity.a(Unknown Source)
                              at com.scrat.module.account.list.AccountListActivity$a$1.onClick(Unknown Source)
                              at android.view.View.performClick(View.java:4760)
                              at android.view.View$PerformClick.run(View.java:19779)
                              at android.os.Handler.handleCallback(Handler.java:739)
                              at android.os.Handler.dispatchMessage(Handler.java:95)
                              at android.os.Looper.loop(Looper.java:135)
                              at android.app.ActivityThread.main(ActivityThread.java:5238)
                              at java.lang.reflect.Method.invoke(Native Method)
                              at java.lang.reflect.Method.invoke(Method.java:372)
                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
                           Caused by: java.io.NotSerializableException: com.b.a.b.g$1
                              at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                              at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                              at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                              at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                              at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                              at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                              at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                              at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                              at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                              at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                              at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                              at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                              at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                              at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                              at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                              at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                              at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                              at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                              at android.os.Parcel.writeSerializable(Parcel.java:1383)
                              at android.os.Parcel.writeValue(Parcel.java:1335) 
                              at android.os.Parcel.writeArrayMapInternal(Parcel.java:638) 
                              at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
                              at android.os.Bundle.writeToParcel(Bundle.java:1096) 
                              at android.os.Parcel.writeBundle(Parcel.java:663) 
                              at android.content.Intent.writeToParcel(Intent.java:7192) 
                              at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2396) 
                              at android.app.Instrumentation.execStartActivity(Instrumentation.java:1480) 
                              at android.app.Activity.startActivityForResult(Activity.java:3742) 
                              at android.app.Activity.startActivityForResult(Activity.java:3703) 
                              at android.support.v4.b.m.startActivityForResult(Unknown Source) 
                              at com.scrat.module.account.edit.AccountEditActivity.a(Unknown Source) 
                              at com.scrat.module.account.list.AccountListActivity$a$1.onClick(Unknown Source) 
                              at android.view.View.performClick(View.java:4760) 
                              at android.view.View$PerformClick.run(View.java:19779) 
                              at android.os.Handler.handleCallback(Handler.java:739) 
                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                              at android.os.Looper.loop(Looper.java:135) 
                              at android.app.ActivityThread.main(ActivityThread.java:5238) 
                              at java.lang.reflect.Method.invoke(Native Method) 
                              at java.lang.reflect.Method.invoke(Method.java:372) 
                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909) 
                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704) 
```

**Comment by shwenzhang** [comment]
这个跟tinker不应该有关系吧
