### ISSUE TITLE
SM-G900P Android 5.0 patch fail on tinker version 1.7.6

### ISSUE THREAD

**Issue by fenghebaiyang** [Tencent/tinker#318]
tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
                                                                   at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SourceFile:80)
                                                                   at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(SourceFile:147)
                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(SourceFile:227)
                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoad(SourceFile:56)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(SourceFile:171)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:135)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:156)
                                                                   at android.app.Application.attach(Application.java:205)
                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:988)
                                                                   at android.app.LoadedApk.makeApplication(LoadedApk.java:620)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4985)
                                                                   at android.app.ActivityThread.access$1600(ActivityThread.java:172)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5837)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by shwenzhang** [comment]
Known issue

**Comment by blueb0ne** [comment]
https://github.com/Tencent/tinker/issues/318

@shwenzhang 为何三星的部分机型不能热修复呢，是rom比较特殊吗？
