### ISSUE TITLE
加载补丁包成功以后，在app应用信息里面清除数据，补丁失效，然后再重新添加补丁包，重新加载提示加载失败

### ISSUE THREAD

**Issue by shanyaodan** [Tencent/tinker#334]
我的小米3手机是这样，不知道别的手机是不是。不知道应该怎么解决，求正解.是不是应该把状态数据保存在sharedpreference里面呢，而不是保存在assert中。或者每次加载补丁包的时候判断补丁包是否存在，不存在的时候改变一下状态。
        TinkerInstaller.install(this, new DefaultLoadReporter(mContext), new DefaultPatchReporter(mContext), new DefaultPatchListener(mContext), SampleResultService.class, new UpgradePatch());
我是这样初始化的

**Comment by shwenzhang** [comment]
给后面重新加载失败的日志

**Comment by shanyaodan** [comment]
1-20 17:10:53.495 27822-27837/com.dyc.testtinker:patch E/Tinker.DefaultPatchReporter: tinker patch exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
01-20 17:10:53.496 27822-27837/com.dyc.testtinker:patch E/Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:ShareSecurityCheck file /storage/emulated/0/patch_signed_7zip.apk, size 5208 verifyPatchMetaSignature fail
                                                                                           at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:139)
                                                                                           at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(ShareTinkerInternals.java:106)
                                                                                           at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(ShareTinkerInternals.java:91)
                                                                                           at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:60)
                                                                                           at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                        Caused by: java.io.FileNotFoundException: /storage/emulated/0/patch_signed_7zip.apk: open failed: EACCES (Permission denied)
                                                                                           at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                                           at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
                                                                                           at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
                                                                                           at java.util.zip.ZipFile.<init>(ZipFile.java:170)
                                                                                           at java.util.jar.JarFile.<init>(JarFile.java:199)
                                                                                           at java.util.jar.JarFile.<init>(JarFile.java:182)
                                                                                           at java.util.jar.JarFile.<init>(JarFile.java:168)
                                                                                           at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:110)
                                                                                           at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(ShareTinkerInternals.java:106) 
                                                                                           at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(ShareTinkerInternals.java:91) 
                                                                                           at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:60) 
                                                                                           at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                        Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                                                           at libcore.io.Posix.open(Native Method)
                                                                                           at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                                           at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                                           at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117) 
                                                                                           at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149) 
                                                                                           at java.util.zip.ZipFile.<init>(ZipFile.java:170) 
                                                                                           at java.util.jar.JarFile.<init>(JarFile.java:199) 
                                                                                           at java.util.jar.JarFile.<init>(JarFile.java:182) 
                                                                                           at java.util.jar.JarFile.<init>(JarFile.java:168) 
                                                                                           at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:110) 
                                                                                           at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(ShareTinkerInternals.java:106) 
                                                                                           at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(ShareTinkerInternals.java:91) 
                                                                                           at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:60) 
                                                                                           at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by shanyaodan** [comment]
说是没有读取权限，

**Comment by shwenzhang** [comment]
是不是6.0以上的机器，读sdcard需要加载动态权限

**Comment by shanyaodan** [comment]
不是吧，第一次可以加载成功，清理数据以后再加载就不行了

**Comment by shwenzhang** [comment]
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
at libcore.io.IoBridge.open(IoBridge.java:438)
at java.io.RandomAccessFile.(RandomAccessFile.java:117) 
at java.io.RandomAccessFile.(RandomAccessFile.java:149) 
at java.util.zip.ZipFile.(ZipFile.java:170) 
at java.util.jar.JarFile.(JarFile.java:199) 
at java.util.jar.JarFile.(JarFile.java:182) 
at java.util.jar.JarFile.(JarFile.java:168) 

你可以拿一台4.X或者5.X的机器试试

**Comment by shanyaodan** [comment]
已测试，真的是权限问题的，谢谢了。
