### ISSUE TITLE
启动TinkerPatchService失败

### ISSUE THREAD

**Issue by icespring** [Tencent/tinker#359]
遇到一个崩溃，因为是线上版本，当时还是1.7.3版本的tinker
java.lang.SecurityException: Unable to start service Intent { cmp=./com.tencent.tinker.lib.service.TinkerPatchService (has extras) }: Unable to launch app 10119 for service Intent { cmp=./com.tencent.tinker.lib.service.TinkerPatchService }: process is bad
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1890)
	at android.app.ContextImpl.startService(ContextImpl.java:1863)
	at android.content.ContextWrapper.startService(ContextWrapper.java:516)
	at com.tencent.tinker.lib.service.TinkerPatchService.runPatchService(TinkerPatchService.java:61)
	at com.tencent.tinker.lib.listener.DefaultPatchListener.onPatchReceived(DefaultPatchListener.java:53)

**Comment by shwenzhang** [comment]
新版本已经fix了，应该是小部分机器后台不给权限
