### ISSUE TITLE
install 方法的错误

### ISSUE THREAD

**Issue by liuxang** [Tencent/tinker#37]
如下两方法
```java
 public static void install(ApplicationLike applicationLike) {
        Tinker tinker = new Tinker.Builder(applicationLike.getApplication()).build();
        tinker.install(applicationLike.getTinkerResultIntent());
    }
public static void install(ApplicationLike applicationLike, LoadReporter loadReporter, PatchReporter patchReporter,
                               PatchListener listener, Class<? extends AbstractResultService> resultServiceClass,
                               AbstractPatch upgradePatchProcessor, AbstractPatch repairPatchProcessor) {

        Tinker tinker = new Tinker.Builder(applicationLike.getApplication())
            .tinkerFlags(applicationLike.getTinkerFlags())
            .loadReport(loadReporter)
            .listener(listener)
            .patchReporter(patchReporter)
            .tinkerLoadVerifyFlag(applicationLike.getTinkerLoadVerifyFlag()).build();

        Tinker.create(tinker);
        tinker.install(applicationLike.getTinkerResultIntent(), resultServiceClass, upgradePatchProcessor, repairPatchProcessor);
    }
```

使用默认的install方法有问题；少了个 : **Tinker.create(tinker);**

```java
public static void create(Tinker tinker) {
        if (sInstance != null) {
            throw new TinkerRuntimeException("Tinker instance is already set.");
        }
        sInstance = tinker;
    }
```
使用install(ApplicationLike applicationLike)这样会造成Tinker中 sInstance 无值
那么在某些地方调用
```java
public static Tinker with(Context context) {
        if (!installed) {
            throw new TinkerRuntimeException("you must install tinker before get tinker sInstance");
        }
        if (sInstance == null) {
            synchronized (Tinker.class) {
                if (sInstance == null) {
                    sInstance = new Builder(context).build();
                }
            }
        }
        return sInstance;
    }
```
会重新创建，而这个新的对象没有调用过install方法。
比如在:
**UpgradePatch#tryPatch** 类中的:
```java
  SharePatchInfo oldInfo = manager.getTinkerLoadResultIfPresent().patchInfo;
```
出现空指针，因为getTinkerLoadResultIfPresent是需要调用了install方法后才存在的:
```java
tinkerLoadResult = new TinkerLoadResult();
tinkerLoadResult.parseTinkerResult(getContext(), intentResult);
```

错误如下
```java
09-26 18:37:28.178 4464-4490/com.test:patch E/Tinker.DefaultPatchReporter: tinker patch exception  java.lang.NullPointerException: Attempt to read from field 'com.tencent.tinker.loader.shareutil.SharePatchInfo com.tencent.tinker.lib.tinker.TinkerLoadResult.patchInfo' on a null object reference
                                                                               at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:70)
                                                                               at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:122)
                                                                               at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)



09-26 18:37:28.226 19352-4495/com.test I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
PatchResult: 
isUpgradePatch:true
isSuccess:false
rawPatchFilePath:/storage/emulated/0/patch_signed_7zip.apk
costTime:61
patchVersion:null
patchTinkerID:mytinkerId
baseTinkerID:mytinkerId
Throwable:Attempt to read from field 'com.tencent.tinker.loader.shareutil.SharePatchInfo com.tencent.tinker.lib.tinker.TinkerLoadResult.patchInfo' on a null object reference
```

**Comment by shwenzhang** [comment]
fixed, try with 1.6.1
