### ISSUE TITLE
java.lang.NoSuchMethodException: <init> [class android.app.Application, int, boolean, long, long, class android.content.Intent]

### ISSUE THREAD

**Issue by fqyb1986** [Tencent/tinker#372]
1、tinker从1.7.6升级到1.7.7
2、versionCode保持不变
3、用升级到1.7.7的apk覆盖1.7.6的apk
引起异常，麻烦看一下~
Caused by: java.lang.NoSuchMethodException: <init> [class android.app.Application, int, boolean, long, long, class android.content.Intent]
                                                               at java.lang.Class.getConstructor(Class.java:528)
                                                               at java.lang.Class.getConstructor(Class.java:492)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:107)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:118) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:131) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146) 
                                                               at android.app.Application.attach(Application.java:187) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:999) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:983) 
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:578) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4740) 
                                                               at android.app.ActivityThread.access$1600(ActivityThread.java:153) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1408) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:148) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5477) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by letyouthgoon** [comment]
applicationlike 构造函数 要参考sample工程改

**Comment by fqyb1986** [comment]
构造函数没有问题，全新安装也是可以正常运行的

**Comment by shwenzhang** [comment]
tinkerId是不是没有变

**Comment by fqyb1986** [comment]
是的，tinkerId没有改变

**Comment by Forward0908** [comment]
> tinkerId是不是没有变

修改tinkerId就好了吗，做分包处理抛了这个异常
