### ISSUE TITLE
补丁加载成功后WebView获取资源失败android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by iluhcm** [Tencent/tinker#374]
```
异常类型：app运行时异常

手机型号：小米5s(Android 7.1.1) / 一加3T(Android7.0) / ZUK Z2(Android 7.0)

手机系统版本：Android 7.0+

tinker版本：1.7.7

gradle版本：2.2.3

系统：如:Mac/Windows

WebView版本：52.0.2743.100

堆栈/日志：

打补丁时未修改任何resource，只是简单修改了部分代码(未涉及核心Tinker代码)。

第一次启动主进程时合成补丁，但未加载，可以正常打开WebView并选择类目；

第二次启动主进程时成功加载补丁，打开WebView正常，但选择类目会导致App崩溃。

具体调用栈如下。
```

```
02-27 19:36:14.570 21658-21658/com.xxx.web E/Tinker.TinkerUncaughtExceptionHandler: [e:-1]uncaughtException:Resource ID #0x0
02-27 19:36:15.476 21658-21658/com.xxx.web E/Tinker.UncaughtHandler: catch exception when loading tinker:android.content.res.Resources$NotFoundException: Resource ID #0x0
     at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2101)
     at android.content.res.Resources.getLayout(Resources.java:1115)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
     at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:380)
     at android.widget.ArrayAdapter.getView(ArrayAdapter.java:371)
     at org.chromium.content.browser.input.SelectPopupAdapter.getView(SelectPopupAdapter.java:56)
     at android.widget.AbsListView.obtainView(AbsListView.java:2370)
     at android.widget.ListView.measureHeightOfChildren(ListView.java:1326)
     at android.widget.ListView.onMeasure(ListView.java:1233)
     at android.view.View.measure(View.java:19861)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
     at android.view.View.measure(View.java:19861)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
     at android.view.View.measure(View.java:19861)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
     at android.view.View.measure(View.java:19861)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
     at android.view.View.measure(View.java:19861)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
     at android.view.View.measure(View.java:19861)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
     at android.view.View.measure(View.java:19861)
     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1339)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
     at android.view.Choreographer.doFrame(Choreographer.java:621)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
     at android.os.Handler.handleCallback(Handler.java:751)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6126)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
 
 
 --------- beginning of crash
```

**Comment by shwenzhang** [comment]
如果没有修改资源，tinker并不会替换任何的资源。把加载的整个过程日志给一下把

**Comment by shwenzhang** [comment]
而且选择目录指的是？

**Comment by iluhcm** [comment]
必要条件：
**Android 7.0+系统；涉及资源修改**

复现步骤：
**1、打一个release包；
2、CRUD任意一个资源文件；
3、打补丁包；
4、使用原生WebView打开任意一个包含org.chromium.content.browser.input.SelectPopupAdapter组件的页面(即WebView单选对话框页面)**

**Comment by shwenzhang** [comment]
will fix with 1.7.8

**Comment by shwenzhang** [comment]
try with tinker 1.7.8

**Comment by YuFengZhi** [comment]
@shwenzhang 请教一下在7.0上webview加载不到系统资源的原因是什么呢？
