### ISSUE TITLE
补丁合成成功，但是Resources$NotFoundException

### ISSUE THREAD

**Issue by wyh497823256** [Tencent/tinker#377]
异常类型：app运行时异常

手机型号：三星（SM-5000）、华为（C8817E）

手机系统版本：Android 6.0.1  ，Android 4.0.2

tinker版本：1.7.6

gradle版本：2.14.1

是否使用第三方SDK：  TinkerPatch SDK ，
补充：使用了 AndResGuard ，并且配置 // mappingFile = file("./resource_mapping.txt")
替换了一张图片
系统：Window

堆栈/日志：
错误日志：
03-02 10:23:22.062 13939-13939/? E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wallet.app.mywallet/com.wallet.app.mywallet.function.main.MainActivity}: android.content.res.Resources$NotFoundException: File r/v/a7.xml from drawable resource ID #0x7f040021
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:141)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:136)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
                                                               at dalvik.system.NativeStart.main(Native Method)
                                                            Caused by: android.content.res.Resources$NotFoundException: File r/v/a7.xml from drawable resource ID #0x7f040021
                                                               at android.content.res.Resources.loadDrawable(Resources.java:2160)
                                                               at com.huawei.android.content.res.ResourcesEx.loadDrawable(ResourcesEx.java:636)
                                                               at android.content.res.Resources.getDrawable(Resources.java:747)
                                                               at android.support.v4.content.a.a(Unknown Source)
                                                               at android.support.v7.widget.l.a(Unknown Source)
                                                               at android.support.v7.widget.l.a(Unknown Source)
                                                               at android.support.v7.widget.l.b(Unknown Source)
                                                               at android.support.v7.widget.l.a(Unknown Source)
                                                               at android.support.v7.widget.bi.b(Unknown Source)
                                                               at android.support.v7.a.g.<init>(Unknown Source)
                                                               at android.support.v7.a.l.<init>(Unknown Source)
                                                               at android.support.v7.a.i.<init>(Unknown Source)
                                                               at android.support.v7.a.j.<init>(Unknown Source)
                                                               at android.support.v7.a.f.a(Unknown Source)
                                                               at android.support.v7.a.f.a(Unknown Source)
                                                               at android.support.v7.a.d.i(Unknown Source)
                                                               at android.support.v7.a.d.onCreate(Unknown Source)
                                                               at me.b.a.d.onCreate(Unknown Source)
                                                               at com.wallet.app.mywallet.function.main.MainActivity.onCreate(Unknown Source)
                                                               at android.app.Activity.performCreate(Activity.java:5340)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                               at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:136) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5333) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag LinearLayout
                                                               at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                               at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                               at android.content.res.Resources.loadDrawable(Resources.java:2156)
                                                               at com.huawei.android.content.res.ResourcesEx.loadDrawable(ResourcesEx.java:636) 
                                                               at android.content.res.Resources.getDrawable(Resources.java:747) 
                                                               at android.support.v4.content.a.a(Unknown Source) 
                                                               at android.support.v7.widget.l.a(Unknown Source) 
                                                               at android.support.v7.widget.l.a(Unknown Source) 
                                                               at android.support.v7.widget.l.b(Unknown Source) 
                                                               at android.support.v7.widget.l.a(Unknown Source) 
                                                               at android.support.v7.widget.bi.b(Unknown Source) 
                                                               at android.support.v7.a.g.<init>(Unknown Source) 
                                                               at android.support.v7.a.l.<init>(Unknown Source) 
                                                               at android.support.v7.a.i.<init>(Unknown Source) 
                                                               at android.support.v7.a.j.<init>(Unknown Source) 
                                                               at android.support.v7.a.f.a(Unknown Source) 
                                                               at android.support.v7.a.f.a(Unknown Source) 
                                                               at android.support.v7.a.d.i(Unknown Source) 
                                                               at android.support.v7.a.d.onCreate(Unknown Source) 
                                                               at me.b.a.d.onCreate(Unknown Source) 
                                                               at com.wallet.app.mywallet.function.main.MainActivity.onCreate(Unknown Source) 
                                                               at android.app.Activity.performCreate(Activity.java:5340) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                               at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:136) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5333) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711) 
                                                               at dalvik.system.NativeStart.main(Native Method) 

其他日志：

03-02 10:11:08.582 8641-8641/? D/Tinker.DefaultAppLike: onTrimMemory level:15
03-02 10:11:08.592 9908-9908/? D/Tinker.DefaultAppLike: onTrimMemory level:15
03-02 10:11:50.192 8641-8641/? D/Tinker.DefaultAppLike: onTrimMemory level:15
03-02 10:11:50.202 9908-9908/? D/Tinker.DefaultAppLike: onTrimMemory level:15

03-02 10:23:20.752 13939-13939/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
03-02 10:23:20.762 13939-13939/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.wallet.app.mywallet count:1
03-02 10:23:20.792 13939-13939/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wallet.app.mywallet-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.wallet.app.mywallet-1, /vendor/lib, /system/lib, /data/datalib]]]
03-02 10:23:20.802 13939-13939/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.wallet.app.mywallet/tinker/patch-052c1700/dex/classes.dex.jar", zip file "/data/data/com.wallet.app.mywallet/tinker/patch-052c1700/dex/test.dex.jar", zip file "/data/app/com.wallet.app.mywallet-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.wallet.app.mywallet-1, /vendor/lib, /system/lib, /data/datalib]]], dex size:2
03-02 10:23:20.812 13939-13939/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
03-02 10:23:20.822 13939-13939/? E/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
03-02 10:23:20.822 13939-13939/? I/Tinker.ResourceLoader: monkeyPatchExistingResources resource file:/data/data/com.wallet.app.mywallet/tinker/patch-052c1700/res/resources.apk, use time: 8
03-02 10:23:20.822 13939-13939/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
03-02 10:23:20.832 13939-13939/? D/Tinker.DefaultAppLike: onBaseContextAttached:
03-02 10:23:20.852 13939-13939/? W/Tinker.Tinker: tinker patch directory: /data/data/com.wallet.app.mywallet/tinker
03-02 10:23:20.862 13939-13939/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
03-02 10:23:20.862 13939-13939/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:052c1700be66f3c6c6393241bee28d9e, newVersion:052c1700be66f3c6c6393241bee28d9e, current:052c1700be66f3c6c6393241bee28d9e
03-02 10:23:20.862 13939-13939/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
03-02 10:23:20.862 13939-13939/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.wallet.app.mywallet/tinker, code:0, cost:235
03-02 10:23:20.892 13939-13939/? I/ActivityThread: com.wallet.app.mywallet query other app provider, pkg:com.tinker.debug.DebugToolApplication uid:10432, send to pg
03-02 10:23:20.902 13939-13939/? I/Tinker.Debugger: debugger attached
03-02 10:23:20.902 13939-13939/? D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
03-02 10:23:20.912 13939-13939/? I/Tinker.ServerManager: installTinkerServer, debug value: true appVersion: 1.0.6, channel: default
03-02 10:23:20.992 13939-13939/? D/Tinker.DefaultAppLike: onCreate
03-02 10:23:21.112 13939-13939/? D/Tinker.DefaultAppLike: onTrimMemory level:10
03-02 10:23:22.062 13939-13939/? E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wallet.app.mywallet/com.wallet.app.mywallet.function.main.MainActivity}: android.content.res.Resources$NotFoundException: File r/v/a7.xml from drawable resource ID #0x7f040021
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:141)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:136)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
                                                               at dalvik.system.NativeStart.main(Native Method)
                                                            Caused by: android.content.res.Resources$NotFoundException: File r/v/a7.xml from drawable resource ID #0x7f040021
                                                               at android.content.res.Resources.loadDrawable(Resources.java:2160)
                                                               at com.huawei.android.content.res.ResourcesEx.loadDrawable(ResourcesEx.java:636)
                                                               at android.content.res.Resources.getDrawable(Resources.java:747)
                                                               at android.support.v4.content.a.a(Unknown Source)
                                                               at android.support.v7.widget.l.a(Unknown Source)
                                                               at android.support.v7.widget.l.a(Unknown Source)
                                                               at android.support.v7.widget.l.b(Unknown Source)
                                                               at android.support.v7.widget.l.a(Unknown Source)
                                                               at android.support.v7.widget.bi.b(Unknown Source)
                                                               at android.support.v7.a.g.<init>(Unknown Source)
                                                               at android.support.v7.a.l.<init>(Unknown Source)
                                                               at android.support.v7.a.i.<init>(Unknown Source)
                                                               at android.support.v7.a.j.<init>(Unknown Source)
                                                               at android.support.v7.a.f.a(Unknown Source)
                                                               at android.support.v7.a.f.a(Unknown Source)
                                                               at android.support.v7.a.d.i(Unknown Source)
                                                               at android.support.v7.a.d.onCreate(Unknown Source)
                                                               at me.b.a.d.onCreate(Unknown Source)
                                                               at com.wallet.app.mywallet.function.main.MainActivity.onCreate(Unknown Source)
                                                               at android.app.Activity.performCreate(Activity.java:5340)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                               at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:136) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5333) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag LinearLayout
                                                               at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                               at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                               at android.content.res.Resources.loadDrawable(Resources.java:2156)
                                                               at com.huawei.android.content.res.ResourcesEx.loadDrawable(ResourcesEx.java:636) 
                                                               at android.content.res.Resources.getDrawable(Resources.java:747) 
                                                               at android.support.v4.content.a.a(Unknown Source) 
                                                               at android.support.v7.widget.l.a(Unknown Source) 
                                                               at android.support.v7.widget.l.a(Unknown Source) 
                                                               at android.support.v7.widget.l.b(Unknown Source) 
                                                               at android.support.v7.widget.l.a(Unknown Source) 
                                                               at android.support.v7.widget.bi.b(Unknown Source) 
                                                               at android.support.v7.a.g.<init>(Unknown Source) 
                                                               at android.support.v7.a.l.<init>(Unknown Source) 
                                                               at android.support.v7.a.i.<init>(Unknown Source) 
                                                               at android.support.v7.a.j.<init>(Unknown Source) 
                                                               at android.support.v7.a.f.a(Unknown Source) 
                                                               at android.support.v7.a.f.a(Unknown Source) 
                                                               at android.support.v7.a.d.i(Unknown Source) 
                                                               at android.support.v7.a.d.onCreate(Unknown Source) 
                                                               at me.b.a.d.onCreate(Unknown Source) 
                                                               at com.wallet.app.mywallet.function.main.MainActivity.onCreate(Unknown Source) 
                                                               at android.app.Activity.performCreate(Activity.java:5340) 
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                               at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source) 
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:136) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5333) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:515) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
03-02 10:23:23.312 13795-13795/? D/Tinker.DefaultAppLike: onTrimMemory level:15
03-02 10:23:37.342 1277-1680/? I/ActivityManager: Process com.tinker.debug.DebugToolApplication (pid 13762) has died.
03-02 10:24:49.762 14431-14431/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
03-02 10:24:49.772 14431-14431/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.wallet.app.mywallet count:1
03-02 10:24:49.792 14431-14431/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wallet.app.mywallet-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.wallet.app.mywallet-1, /vendor/lib, /system/lib, /data/datalib]]]
03-02 10:24:49.792 14431-14431/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.wallet.app.mywallet/tinker/patch-052c1700/dex/classes.dex.jar", zip file "/data/data/com.wallet.app.mywallet/tinker/patch-052c1700/dex/test.dex.jar", zip file "/data/app/com.wallet.app.mywallet-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.wallet.app.mywallet-1, /vendor/lib, /system/lib, /data/datalib]]], dex size:2
03-02 10:24:49.792 14431-14431/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
03-02 10:24:49.802 14431-14431/? E/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
03-02 10:24:49.802 14431-14431/? I/Tinker.ResourceLoader: monkeyPatchExistingResources resource file:/data/data/com.wallet.app.mywallet/tinker/patch-052c1700/res/resources.apk, use time: 9
03-02 10:24:49.802 14431-14431/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
03-02 10:24:49.812 14431-14431/? D/Tinker.DefaultAppLike: onBaseContextAttached:
03-02 10:24:49.842 14431-14431/? W/Tinker.Tinker: tinker patch directory: /data/data/com.wallet.app.mywallet/tinker
03-02 10:24:49.842 14431-14431/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0
03-02 10:24:49.852 14431-14431/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:052c1700be66f3c6c6393241bee28d9e, newVersion:052c1700be66f3c6c6393241bee28d9e, current:052c1700be66f3c6c6393241bee28d9e
03-02 10:24:49.852 14431-14431/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
03-02 10:24:49.852 14431-14431/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.wallet.app.mywallet/tinker, code:0, cost:184
03-02 10:24:49.862 1277-1660/? I/ActivityManager: Start proc com.tinker.debug.DebugToolApplication for content provider com.tinker.debug.DebugToolApplication/com.tinker.debug.DebugProvider: pid=14445 uid=10432 gids={50432}
03-02 10:24:49.882 14445-14445/? D/ActivityThread: handleBindApplication:com.tinker.debug.DebugToolApplication
03-02 10:24:49.912 14431-14431/? I/ActivityThread: com.wallet.app.mywallet query other app provider, pkg:com.tinker.debug.DebugToolApplication uid:10432, send to pg
03-02 10:24:49.932 14431-14431/? I/Tinker.Debugger: debugger attached
03-02 10:24:49.932 14431-14431/? D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
03-02 10:24:49.942 14431-14431/? I/Tinker.ServerManager: installTinkerServer, debug value: true appVersion: 1.0.6, channel: default
03-02 10:24:49.972 14431-14431/? D/Tinker.DefaultAppLike: onCreate
03-02 10:24:50.072 14431-14431/? D/Tinker.DefaultAppLike: onTrimMemory level:15
03-02 10:24:50.112 14431-14431/? I/Tinker.UrlLoader: loadData from: http://q.tinkerpatch.com/dev/a6f7d4346cf2cff0/1.0.6?d=091c36b2-c13d-4d2b-a9f8-8806f5570ea3&v=1488421490120
03-02 10:24:50.282 14431-14470/? D/Tinker.UrlConnectionFetcher: response code 200 msg: OK
03-02 10:24:50.292 14431-14470/? D/Tinker.ClientImpl: tinker server sync respond:{"v":1}
03-02 10:24:50.292 14431-14470/? D/Tinker.ClientImpl: sync response in update:version:1
                                                      grayValue:null
                                                      conditions:
                                                      pause:false
                                                      rollback:false
03-02 10:24:50.292 14431-14470/? D/Tinker.ClientImpl: update return false, target version is not latest. current version is:1
03-02 10:24:50.302 14431-14470/? D/Tinker.ClientImpl: Needn't update, sync response is: version:1
                                                      grayValue:null
                                                      conditions:
                                                      pause:false
                                                      rollback:false
                                                      gray: 3
03-02 10:25:24.302 1277-2482/? I/ActivityManager: Process com.tinker.debug.DebugToolApplication (pid 14445) has died.

**Comment by wyh497823256** [comment]
补充：使用了 AndResGuard ，并且配置 // mappingFile = file("./resource_mapping.txt")

**Comment by wyh497823256** [comment]
资源文件 替换了一张图片

**Comment by shwenzhang** [comment]
参考资源混淆的sample，自行解决
