### ISSUE TITLE
google Nexus 5x 7.1系统报错 ： Missing android.support.FILE_PROVIDER_PATHS meta-data

### ISSUE THREAD

**Issue by fireking0415** [Tencent/tinker#379]
错误栈如下： 使用 google nexus 5x 7.1系统 集成是使用tinkerpatch annotation方式集成
java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5856)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
                                                     at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                  Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                     at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:586)
                                                     at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
                                                     at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:375)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5853)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384) 
                                                     at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:154) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by fireking0415** [comment]
sorry 应该是7.0+引起的，先关了

**Comment by Timmy-zzh** [comment]
我也遇到这个问题了,请问你怎么解决的?Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data

**Comment by fireking0415** [comment]
这个不是tinker的问题，是在7.0的 file provider导致的，你可以查查7.0的特性，你就懂了

**Comment by Timmy-zzh** [comment]
ok,已解决,3q
