### ISSUE TITLE
Throwable:Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by coolegos** [Tencent/tinker#384]
接入自己的一个Demo的时候出现的问题。在5.0以上的手机都失败了，PatchResult返回的`Throwable:Thread starting during runtime shutdown`，5.0以下正常。

```
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): tinker patch exception  java.lang.InternalError: Thread starting during runtime shutdown
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at java.lang.Thread.nativeCreate(Native Method)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at java.lang.Thread.start(Thread.java:1063)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at android.app.SharedPreferencesImpl.startLoadFromDisk(SharedPreferencesImpl.java:87)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at android.app.SharedPreferencesImpl.<init>(SharedPreferencesImpl.java:80)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:1059)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:169)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.isTinkerEnableWithSharedPreferences(ShareTinkerInternals.java:265)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:48)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at android.os.Looper.loop(Looper.java:155)
03-08 18:38:14.179 E/Tinker.DefaultPatchReporter(11008): 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-08 18:38:14.189 E/WifiTrafficPoller( 1068): TRAFFIC_STATS_POLL true Token 1479 num clients 30
```

**Comment by coolegos** [comment]
我是自己写的一个CrashHandler可能是这个的问题，改成SampleUncaughtExceptionHandler就OK了。
