### ISSUE TITLE
tinker v1.7.7 加载补丁报错

### ISSUE THREAD

**Issue by xjguo75468722** [Tencent/tinker#387]
assembleDebug 做了基础包
修改了一句 java 代码
修改好 tinker 配置文件, 执行 tinkerPatchDebug.
手机系统：Android 7.0 API 24
手机型号： 华为mate8

报错：
03-10 11:38:52.797 1822-1822/? I/HwResourcesImpl: icon : com.example.administrator.tinkerdemo3 found in app
03-10 11:38:52.801 30539-30554/? E/Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:ShareSecurityCheck file /storage/emulated/0/patch.apk, size 3755 verifyPatchMetaSignature fail
                                                                    at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:139)
                                                                    at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(ShareTinkerInternals.java:106)
                                                                    at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(ShareTinkerInternals.java:91)
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:60)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:156)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                 Caused by: java.io.FileNotFoundException: /storage/emulated/0/patch.apk (Permission denied)
                                                                    at java.util.zip.ZipFile.open(Native Method)
                                                                    at java.util.zip.ZipFile.<init>(ZipFile.java:218)
                                                                    at java.util.zip.ZipFile.<init>(ZipFile.java:147)
                                                                    at java.util.jar.JarFile.<init>(JarFile.java:161)
                                                                    at java.util.jar.JarFile.<init>(JarFile.java:125)
                                                                    at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:110)
                                                                    at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(ShareTinkerInternals.java:106) 
                                                                    at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(ShareTinkerInternals.java:91) 
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:60) 
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:156) 
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
03-10 11:38:52.802 30539-30554/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path:/storage/emulated/0/patch.apk, success:false, cost:28
03-10 11:38:52.807 1822-1822/? W/CfgFilePolicy: No config file found for:/themes/diff/icons
03-10 11:38:52.807 1822-1822/? W/CfgFilePolicy: CFG_DIRS length : 9
03-10 11:38:52.843 1822-1822/? W/CfgFilePolicy: No config file found for:/themes/diff/icons
03-10 11:38:52.843 1822-1822/? W/CfgFilePolicy: CFG_DIRS length : 9
03-10 11:38:52.850 30433-30558/com.example.administrator.tinkerdemo3 I/Tinker.DefaultTinkerResultService: DefaultTinkerResultService received a result:
                                                                                                          PatchResult: 
                                                                                                          isSuccess:false
                                                                                                          rawPatchFilePath:/storage/emulated/0/patch.apk
                                                                                                          costTime:28
                                                                                                          Throwable:Tinker Exception:ShareSecurityCheck

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/23781451/5e8263ea-0588-11e7-9e3f-6ee2b7d78af8.png)

**Comment by TracyZhangLei** [comment]
这种问题怎么不都仔细看看呢，觉得还是该谨慎点，毕竟大家都很忙．
