### ISSUE TITLE
i use tinker which in bugly,why throw this error and how to fix it ,can reply chinese....

### ISSUE THREAD

**Issue by dunwen** [Tencent/tinker#389]
03-11 13:53:51.039 5549-5549/com.sendong.schooloa W/System.err: java.lang.NullPointerException: The mapper function returned a null value.
03-11 13:53:51.039 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
03-11 13:53:51.039 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:246)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10179)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10179)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.Scheduler$1.run(Scheduler.java:134)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-11 13:53:51.040 5549-5549/com.sendong.schooloa E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:The mapper function returned a null value.
03-11 13:53:51.041 5549-5549/com.sendong.schooloa E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.NullPointerException: The mapper function returned a null value.
                                                                                at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
                                                                                at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
                                                                                at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:246)
                                                                                at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
                                                                                at io.reactivex.Observable.subscribe(Observable.java:10179)
                                                                                at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
                                                                                at io.reactivex.Observable.subscribe(Observable.java:10179)
                                                                                at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                                                at io.reactivex.Scheduler$1.run(Scheduler.java:134)
                                                                                at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                                at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:818)
03-11 13:53:51.043 5579-6036/com.sendong.schooloa:ipc I/System.out: [OkHttp] sendRequest<<
03-11 13:53:51.048 5549-5549/com.sendong.schooloa E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.sendong.schooloa, PID: 5549
                                                                    java.lang.NullPointerException: The mapper function returned a null value.
                                                                        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
                                                                        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
                                                                        at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:246)
                                                                        at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
                                                                        at io.reactivex.Observable.subscribe(Observable.java:10179)
                                                                        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
                                                                        at io.reactivex.Observable.subscribe(Observable.java:10179)
                                                                        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                                        at io.reactivex.Scheduler$1.run(Scheduler.java:134)
                                                                        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:818)

**Comment by dunwen** [comment]
not the tinker error...
