### ISSUE TITLE
patch成功后，再次运行app闪退，闪退几次后又回到未patch版本

### ISSUE THREAD

**Issue by sixgodIT** [Tencent/tinker#391]
异常类型：app运行时异常

手机型号：华为荣耀8

手机系统版本：如:Android 7.0

tinker版本：如:1.7.7

gradle版本：如:2.2.3

是否使用第三方SDK： Bugly SDK

系统：Mac

堆栈/日志：

1. 03-13 12:30:10.757 964-964/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.yunxiao.haofenshu/tinker
03-13 12:30:10.758 964-964/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.yunxiao.haofenshu.App
03-13 12:30:10.761 964-964/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.yunxiao.haofenshu/tinker
03-13 12:30:10.762 964-964/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-13 12:30:10.762 964-964/? W/Tinker.Tinker: tinker load fail!
03-13 12:30:10.765 964-964/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
03-13 12:30:10.774 964-964/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@e25cd0a
03-13 12:30:11.052 964-964/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
03-13 12:30:14.302 964-964/? E/CrashReport: Tinker report code:2
03-13 12:30:14.302 964-964/? E/CrashReport: Tinker report code:70
03-13 12:30:14.302 964-964/? E/CrashReport: Tinker report code:3
                                            
                                            [ 03-13 12:30:14.319  1101: 1101 I/         ]
                                            power log dlsym ok
03-13 12:30:14.382 1101-1101/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.yunxiao.haofenshu/tinker
03-13 12:30:14.384 1101-1101/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.yunxiao.haofenshu.App
03-13 12:30:14.390 1101-1101/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.yunxiao.haofenshu/tinker
03-13 12:30:14.390 1101-1101/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-13 12:30:14.390 1101-1101/? W/Tinker.Tinker: tinker load fail!
03-13 12:30:14.394 1101-1101/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
03-13 12:30:14.411 1101-1101/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@e25cd0a
03-13 12:30:14.467 1101-1101/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-13 12:30:14.468 1101-1229/? W/Tinker.UpgradePatchRetry: try copy file: /data/user/0/com.yunxiao.haofenshu/app_tmpPatch/tmpPatch.apk to /data/user/0/com.yunxiao.haofenshu/tinker_temp/temp.apk
03-13 12:30:14.508 1101-1229/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.yunxiao.haofenshu/app_tmpPatch/tmpPatch.apk size: 5265, dest file: /data/user/0/com.yunxiao.haofenshu/tinker/patch-7173e488/patch-7173e488.apk size:5265
03-13 12:30:18.980 1101-1229/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.yunxiao.haofenshu/tinker/patch-7173e488/dex/classes.dex.jar, size: 3137422, use time: 4471
03-13 12:30:20.016 1101-1229/? W/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:3
03-13 12:30:32.429 1101-1229/? I/Tinker.ParallelDex: All dexes are optimized successfully, cost: 12412 ms.
03-13 12:30:32.430 1101-1229/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
03-13 12:30:32.430 1101-1229/? W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
03-13 12:30:32.436 1101-1229/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
03-13 12:30:32.436 1101-1229/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunxiao.haofenshu/tinker_temp/temp.apk
03-13 12:30:32.453 964-1278/? I/CrashReport: Tinker patch success, result: 
                                             PatchResult: 
                                             isSuccess:true
                                             rawPatchFilePath:/data/user/0/com.yunxiao.haofenshu/app_tmpPatch/tmpPatch.apk
                                             costTime:17966
                                             patchVersion:7173e48879947cbb3cd76625c71f2d53
03-13 12:30:32.453 964-1278/? W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /data/user/0/com.yunxiao.haofenshu/app_tmpPatch/tmpPatch.apk
03-13 12:30:32.453 964-1278/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.yunxiao.haofenshu/app_tmpPatch/tmpPatch.apk

2. 03-13 12:30:53.594 1299-1299/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
03-13 12:30:53.596 1299-1299/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.yunxiao.haofenshu count:1
03-13 12:30:53.601 1299-1299/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yunxiao.haofenshu-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yunxiao.haofenshu-1/lib/arm, /system/fake-libs, /data/app/com.yunxiao.haofenshu-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]]
03-13 12:30:53.632 1299-1299/? I/Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/com.yunxiao.haofenshu/tinker/patch-7173e488/dex/classes.dex.jar", zip file "/data/user/0/com.yunxiao.haofenshu/tinker/patch-7173e488/dex/classes2.dex.jar", zip file "/data/user/0/com.yunxiao.haofenshu/tinker/patch-7173e488/dex/test.dex.jar", zip file "/data/app/com.yunxiao.haofenshu-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yunxiao.haofenshu-1/lib/arm, /system/fake-libs, /data/app/com.yunxiao.haofenshu-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]], dex size:3
03-13 12:30:53.633 1299-1299/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
03-13 12:30:53.633 1299-1299/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
03-13 12:30:53.636 1299-1299/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.yunxiao.haofenshu.App
03-13 12:30:53.641 1299-1299/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.yunxiao.haofenshu/tinker
03-13 12:30:53.647 1299-1299/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
03-13 12:30:53.661 1299-1299/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@9216f47
03-13 12:30:53.876 1299-1299/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Unable to start activity ComponentInfo{com.yunxiao.haofenshu/com.yunxiao.haofenshu.start.launcher.LauncherActivity}: java.lang.ClassCastException: com.yunxiao.yxrequest.login.entity.AdData cannot be cast to com.yunxiao.yxrequest.login.entity.AdData
03-13 12:30:53.878 1299-1299/? E/Tinker.TinkerUncaughtExceptionHandler: tinker has fast crash 1 times
03-13 12:30:53.878 1299-1299/? E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yunxiao.haofenshu/com.yunxiao.haofenshu.start.launcher.LauncherActivity}: java.lang.ClassCastException: com.yunxiao.yxrequest.login.entity.AdData cannot be cast to com.yunxiao.yxrequest.login.entity.AdData
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:156)
                                                             at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
                                                          Caused by: java.lang.ClassCastException: com.yunxiao.yxrequest.login.entity.AdData cannot be cast to com.yunxiao.yxrequest.login.entity.AdData
                                                             at com.yunxiao.haofenshu.start.launcher.LauncherActivity.onCreate(LauncherActivity.java:88)
                                                             at android.app.Activity.performCreate(Activity.java:6910)
                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:156) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:6524) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831) 
                                                         
                                                         
                                                         --------- beginning of crash

3. 
03-13 12:31:29.538 1479-1479/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.yunxiao.haofenshu/tinker
03-13 12:31:29.539 1479-1479/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.yunxiao.haofenshu.App
03-13 12:31:29.542 1479-1479/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.yunxiao.haofenshu/tinker
03-13 12:31:29.543 1479-1479/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-13 12:31:29.543 1479-1479/? W/Tinker.Tinker: tinker load fail!
03-13 12:31:29.545 1479-1479/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
03-13 12:31:29.559 1479-1479/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@fa14257
03-13 12:31:29.775 1479-1479/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.yunxiao.haofenshu/tinker_temp/temp.apk is not exist, just return

**Comment by shwenzhang** [comment]
这个是bugly SDK的问题

**Comment by BlackHumor** [comment]
这个问题解决了吗？我现在遇到的和你的问题类型差不多
