### ISSUE TITLE
修复成功后，app自动崩溃

### ISSUE THREAD

**Issue by DengAnbang** [Tencent/tinker#397]
只是修复成功后才崩溃，下次启动，就是修复后的样子，不会再次崩溃，请问这个是正常的吗？

**Comment by DengAnbang** [comment]
03-16 13:49:24.176 6789-6789/com.example.dab.tinkerdemo E/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
03-16 13:49:24.311 6817-6817/com.example.dab.tinkerdemo:patch E/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
03-16 13:49:26.449 1293-1400/? E/whetstone.activity: handleClearDeadAppFromNative
                                                     java.lang.NoSuchMethodException: com.android.server.am.ActivityManagerService#clearDeadAppFromNative()#exact
                                                         at miui.util.ReflectionUtils.findMethodExact(ReflectionUtils.java:242)
                                                         at com.miui.whetstone.server.WhetstoneActivityManagerService.handleClearDeadAppFromNative(WhetstoneActivityManagerService.java:248)
                                                         at com.miui.whetstone.server.WhetstoneActivityManagerService.access$400(WhetstoneActivityManagerService.java:55)
                                                         at com.miui.whetstone.server.WhetstoneActivityManagerService$PromoteLevelManagerHandler.handleMessage(WhetstoneActivityManagerService.java:506)
                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                         at android.os.Looper.loop(Looper.java:148)
                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
03-16 13:49:29.637 1293-2407/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 76)
03-16 13:49:29.646 2331-2900/? E/MemCheckStateMachine: Error! unhandled message  { when=-1ms what=50331650 target=com.android.internal.util.StateMachine$SmHandler }
03-16 13:49:29.658 2888-2902/? E/MiuiVoip: VoipCall_RemoteVoipManager, getCallState: Service is null

**Comment by weinierfei** [comment]
正常情况,wiki里Tinker自定义扩展下的"自定义AbstractResultService类"在处理这儿,去看wiki吧

**Comment by DengAnbang** [comment]
好的，谢谢
