### ISSUE TITLE
一打开APP就报错，文件找不到

### ISSUE THREAD

**Issue by rong5690001** [Tencent/tinker#398]
java.io.FileNotFoundException: http://q.tinkerpatch.com/c/aca2e141c35808bf?d=813785c4-ba00-4cbe-9834-caca3ae58c71&v=1489664329568
                                                                      at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
                                                                      at com.tinkerpatch.sdk.server.c.b$a.run(SourceFile:132)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by shwenzhang** [comment]
这个是tinkerpatch的，而且这个是已经被catch的crash，只是一个提示

**Comment by xsslong** [comment]
请问这个如何解决, 上传的patch下载不下来, 链接http://q.tinkerpatch.com/dev/appkey/tinkerid?d=uuid$v= 打不开, 找不到文件
