### ISSUE TITLE
tinkerEnable=false,抛出java.lang.ClassNotFoundException（clz[@DefaultLifeCycle] extends ApplicationLike）

### ISSUE THREAD

**Issue by julist213** [Tencent/tinker#401]
tinkerVersion 1.7.7
androidVersion 4.4.2

multiDex true .
主dex确实没有clz,然后5.0之后就没问题。
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xxx" on path: DexPathList[[zip file "/data/app/com.xxx.apk"],nativeLibraryDirectories=[/data/app-lib/com.xxx, /vendor/lib, /system/lib, /vendor/lib]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                              at java.lang.Class.classForName(Native Method) 
                                                                              at java.lang.Class.forName(Class.java:251) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:106) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:118) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:131) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146) 
                                                                              at android.app.Application.attach(Application.java:190) 
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:998) 
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:541) 
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5124) 
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:156) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:157) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5872) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674) 
                                                                              at dalvik.system.NativeStart.main(Native Method)

**Comment by shwenzhang** [comment]
需要把tinker的类加入到main dex pattern即可
