### ISSUE TITLE
TinkerRuntimeException: Tinker Exception:createDelegate failed

### ISSUE THREAD

**Issue by easionchang** [Tencent/tinker#402]
在模拟器（V4.4.4）上集成tinker报错：
`catch exception when loading tinker:java.lang.RuntimeException: Unable to instantiate application cn.flyrise.MyTinkerApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:112)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:118)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:131)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:146)
                                                                              at android.app.Application.attach(Application.java:181)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:136) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                              at dalvik.system.NativeStart.main(Native Method) 
                                                                           Caused by: java.lang.ClassNotFoundException: cn.flyrise.MyTinkerApplicationLike
                                                                              at java.lang.Class.classForName(Native Method)
                                                                              at java.lang.Class.forName(Class.java:251)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:106)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:118) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:131) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:146) 
                                                                              at android.app.Application.attach(Application.java:181) 
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:136) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                              at dalvik.system.NativeStart.main(Native Method) 
                                                                           Caused by: java.lang.NoClassDefFoundError: cn/flyrise/MyTinkerApplicationLike
                                                                              at java.lang.Class.classForName(Native Method) 
                                                                              at java.lang.Class.forName(Class.java:251) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:106) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:118) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:131) 
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:146) 
                                                                              at android.app.Application.attach(Application.java:181) 
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                                              at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:136) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                              at dalvik.system.NativeStart.main(Native Method) `

**Comment by easionchang** [comment]
![image](https://cloud.githubusercontent.com/assets/3087267/24090289/ca54b228-0d79-11e7-9529-89dc5350b4e4.png)

**Comment by shwenzhang** [comment]
class not found, 请自行检查接入的问题
