### ISSUE TITLE
load patch报错

### ISSUE THREAD

**Issue by zirconnnn** [Tencent/tinker#407]
异常类型：app运行时异常

手机型号：华为荣耀8 FRD-AL00

手机系统版本：EMUI 5.0 Android 7.0 版本号FRD-AL00C00B377

tinker版本：1.7.7

gradle版本：2.2.2

是否使用第三方SDK：无

系统：Mac

堆栈/日志：
E/Tinker.DefaultLoadReporter: tinker load exception  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String dalvik.system.DexFile.getName()' on a null object reference
                                                                 at com.tencent.tinker.loader.AndroidNClassLoader.createAndroidNClassLoader(Unknown Source)
                                                                 at com.tencent.tinker.loader.AndroidNClassLoader.inject(Unknown Source)
                                                                 at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(Unknown Source)
                                                                 at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(Unknown Source)
                                                                 at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(Unknown Source)
                                                                 at com.tencent.tinker.loader.TinkerLoader.tryLoad(Unknown Source)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(Unknown Source)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(Unknown Source)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source)
                                                                 at android.app.Application.attach(Application.java:189)
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:1011)
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:995)
                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5633)
                                                                 at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                 at android.os.Looper.loop(Looper.java:156)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**patch合成成功但是加载失败，apk未加固，如需其他信息麻烦告知**

**Comment by shwenzhang** [comment]
try with tinker 1.7.8
