### ISSUE TITLE
RuntimeException: Unable to instantiate application 

### ISSUE THREAD

**Issue by likaiyuan559** [Tencent/tinker#411]
集成了Tinker后，目前发现一个华为机器会出现无法运行的问题：
（无论是debug还是release都不能运行，直接崩溃，机器信息请看下图）
（目前项目内没有做混淆处理，dex2jar反编译出来主dex包也包含了BaseApplication且没有被混淆）

`03-21 20:18:58.386 1343-1343/com.heyhou.social E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.heyhou.social, PID: 1343
                                                                 java.lang.RuntimeException: Unable to instantiate application com.heyhou.social.base.BaseApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
at android.app.LoadedApk.makeApplication(LoadedApk.java:525)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)
at android.app.ActivityThread.access$1800(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5336)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:112)
at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:118)
at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:131)
at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:146)
at android.app.Application.attach(Application.java:200)
at android.app.Instrumentation.newApplication(Instrumentation.java:992)
at android.app.Instrumentation.newApplication(Instrumentation.java:976)
at android.app.LoadedApk.makeApplication(LoadedApk.java:520)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)?
at android.app.ActivityThread.access$1800(ActivityThread.java:141)?
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)?
at android.os.Handler.dispatchMessage(Handler.java:102)?
at android.os.Looper.loop(Looper.java:136)?
 at android.app.ActivityThread.main(ActivityThread.java:5336)?
at java.lang.reflect.Method.invokeNative(Native Method)?
at java.lang.reflect.Method.invoke(Method.java:515)?
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)?
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)?
at dalvik.system.NativeStart.main(Native Method)?
Caused by: java.lang.ClassNotFoundException: com.heyhou.social.base.BaseApplicationLike
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:251)
at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:106)
at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:118)?
at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:131)?
at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:146)?
at android.app.Application.attach(Application.java:200)?
at android.app.Instrumentation.newApplication(Instrumentation.java:992)?
at android.app.Instrumentation.newApplication(Instrumentation.java:976)?
at android.app.LoadedApk.makeApplication(LoadedApk.java:520)?
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)?
at android.app.ActivityThread.access$1800(ActivityThread.java:141)?
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)?
at android.os.Handler.dispatchMessage(Handler.java:102)?
at android.os.Looper.loop(Looper.java:136)?
at android.app.ActivityThread.main(ActivityThread.java:5336)?
at java.lang.reflect.Method.invokeNative(Native Method)?
at java.lang.reflect.Method.invoke(Method.java:515)?
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)?
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)?
at dalvik.system.NativeStart.main(Native Method)?
Caused by: java.lang.NoClassDefFoundError: com/heyhou/social/base/BaseApplicationLike
at java.lang.Class.classForName(Native Method)?
at java.lang.Class.forName(Class.java:251)?
at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:106)?
at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:118)?
at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:131)?
at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:146)?
at android.app.Application.attach(Application.java:200)?
at android.app.Instrumentation.newApplication(Instrumentation.java:992)?
at android.app.Instrumentation.newApplication(Instrumentation.java:976)?
at android.app.LoadedApk.makeApplication(LoadedApk.java:520)?
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)?
at android.app.ActivityThread.access$1800(ActivityThread.java:141)?
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)?
at android.os.Handler.dispatchMessage(Handler.java:102)?
at android.os.Looper.loop(Looper.java:136)?
at android.app.ActivityThread.main(ActivityThread.java:5336)?
at java.lang.reflect.Method.invokeNative(Native Method)?
at java.lang.reflect.Method.invoke(Method.java:515)?
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)?
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)?
at dalvik.system.NativeStart.main(Native Method)?
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.heyhou.social.base.BaseApplicationLike" on path: DexPathList[[zip file "/data/app/com.heyhou.social-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.heyhou.social-1, /vendor/lib, /data/cust/lib, /system/lib, /data/datalib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
at java.lang.Class.classForName(Native Method)?
at java.lang.Class.forName(Class.java:251)?
at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:106)?
at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:118)?
at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:131)?
at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:146)?
at android.app.Application.attach(Application.java:200)?
at android.app.Instrumentation.newApplication(Instrumentation.java:992)?
at android.app.Instrumentation.newApplication(Instrumentation.java:976)?
at android.app.LoadedApk.makeApplication(LoadedApk.java:520)?
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4605)?
at android.app.ActivityThread.access$1800(ActivityThread.java:141)?
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)?
at android.os.Handler.dispatchMessage(Handler.java:102)?
at android.os.Looper.loop(Looper.java:136)?
at android.app.ActivityThread.main(ActivityThread.java:5336)?
at java.lang.reflect.Method.invokeNative(Native Method)?
at java.lang.reflect.Method.invoke(Method.java:515)?
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)?
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)?
at dalvik.system.NativeStart.main(Native Method)?`

![screenshot_2017-03-21-16-00-44](https://cloud.githubusercontent.com/assets/18045170/24147623/0ebf62c6-0e76-11e7-9675-5ba22c8e9c6b.jpg)

**Comment by likaiyuan559** [comment]
但是我使用dex2jar将主dex包反编译出来了，里面包含了Application，ApplicationLike且都没有被混淆，Application的指向的ApplicationLike的地址也是正确的呢。

**Comment by shwenzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/8335303/24231446/b46c9604-0fbf-11e7-8966-a60269356719.png)

**Comment by mrldroid** [comment]
那怎么解决呢，没有办法吗
