### ISSUE TITLE
Patch Success，重启App后崩溃。---查明因为proguard 4.7版本导致，建议使用proguard 5.1版本

### ISSUE THREAD

**Issue by motcwang** [Tencent/tinker#415]
异常类型：Patch Success，重启App后崩溃。

手机型号:Samsung Galaxy S7 edge

手机系统版本：:Android 6.0.1

tinker版本：1.7.7

gradle版本：2.2.0

是否使用第三方SDK： 否

系统：OS X

App加载补丁时的日志：
```
03-22 14:49:53.472 2496-2496/com.test.android W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
03-22 14:49:53.492 1296-3037/? I/ActivityManager: Start proc 2727:com.test.android:patch/u0a902 for service com.test.android/com.tencent.tinker.lib.service.TinkerPatchService
03-22 14:49:53.562 2727-2727/com.test.android:patch W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.test.android/tinker
03-22 14:49:53.572 2727-2727/com.test.android:patch W/Tinker.Tinker: tinker patch directory: /data/user/0/com.test.android/tinker
03-22 14:49:53.572 2727-2727/com.test.android:patch W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-22 14:49:53.572 2727-2727/com.test.android:patch W/Tinker.Tinker: tinker load fail!
                                                                       
                                                                       [ 03-22 14:49:53.582  2727: 2727 W/         ]
                                                                       Unable to open '/system/framework/dpmapi.jar': No such file or directory
03-22 14:49:53.652 2727-2727/com.test.android:patch W/Tinker.MyLogImp: new log level: 0
03-22 14:49:53.802 2727-2727/com.test.android:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-22 14:49:53.812 2727-2818/com.test.android:patch W/Tinker.UpgradePatchRetry: try copy file: /data/user/0/com.test.android/files/LKLPatchRaw/patch.zip to /data/user/0/com.test.android/tinker_temp/temp.apk
03-22 14:49:53.822 1296-1499/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.test.android/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE secFlags=0x0 secPriority=0))
03-22 14:49:53.832 1296-1499/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.test.android/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE secFlags=0x0 secPriority=0))
03-22 14:49:53.912 2727-2818/com.test.android:patch W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.test.android/files/LKLPatchRaw/patch.zip size: 1439015, dest file: /data/user/0/com.test.android/tinker/patch-62714b6b/patch-62714b6b.apk size:1439015
03-22 14:50:00.872 2727-2818/com.test.android:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.test.android/tinker/patch-62714b6b/dex/classes.dex.jar, size: 3796888, use time: 6948
03-22 14:50:01.032 2727-2818/com.test.android:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.test.android/tinker/patch-62714b6b/dex/classes2.dex.jar, size: 97316, use time: 156
03-22 14:50:01.032 2727-2818/com.test.android:patch W/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:3
03-22 14:50:01.112 3131-3131/? I/dex2oat: /system/bin/dex2oat --debuggable --dex-file=/data/user/0/com.test.android/tinker/patch-62714b6b/dex/classes2.dex.jar --oat-file=/data/user/0/com.test.android/tinker/patch-62714b6b/odex/classes2.dex.dex
03-22 14:50:01.122 3130-3130/? I/dex2oat: /system/bin/dex2oat --debuggable --dex-file=/data/user/0/com.test.android/tinker/patch-62714b6b/dex/classes.dex.jar --oat-file=/data/user/0/com.test.android/tinker/patch-62714b6b/odex/classes.dex.dex
03-22 14:50:01.142 3137-3137/? I/dex2oat: /system/bin/dex2oat --debuggable --dex-file=/data/user/0/com.test.android/tinker/patch-62714b6b/dex/test.dex.jar --oat-file=/data/user/0/com.test.android/tinker/patch-62714b6b/odex/test.dex.dex
03-22 14:50:01.192 3137-3137/? E/dex2oat: <SS>: oat location is not valid /data/user/0/com.test.android/tinker/patch-62714b6b/odex/test.dex.dex
03-22 14:50:01.412 3131-3131/? E/dex2oat: <SS>: oat location is not valid /data/user/0/com.test.android/tinker/patch-62714b6b/odex/classes2.dex.dex
03-22 14:50:02.392 3130-3167/? W/dex2oat: Verification failed on class com.google.a.h in /data/user/0/com.test.android/tinker/patch-62714b6b/dex/classes.dex.jar because: Verifier rejected class com.google.a.h due to bad method void com.google.a.h.e(int, int)
03-22 14:50:02.392 3130-3162/? W/dex2oat: Verification failed on class com.google.a.g in /data/user/0/com.test.android/tinker/patch-62714b6b/dex/classes.dex.jar because: Verifier rejected class com.google.a.g due to bad method boolean com.google.a.g.b(int)
03-22 14:50:08.332 3130-3130/? E/dex2oat: <SS>: oat location is not valid /data/user/0/com.test.android/tinker/patch-62714b6b/odex/classes.dex.dex
03-22 14:50:08.362 2727-2818/com.test.android:patch W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
03-22 14:50:08.462 2727-2818/com.test.android:patch W/Tinker.ResDiffPatchInternal: success recover large modify file:/data/user/0/com.test.android/tinker/patch-62714b6b/res/resources.arsc, file size:386244, use time:94
03-22 14:50:08.462 2727-2818/com.test.android:patch W/Tinker.ResDiffPatchInternal: success recover all large modify use time:100
03-22 14:50:08.882 2727-2818/com.test.android:patch W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
03-22 14:50:08.912 2496-2496/com.test.android E/Tinker.SampleResultService: patch success, please restart process
03-22 14:50:08.912 2496-3362/com.test.android W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /data/user/0/com.test.android/files/LKLPatchRaw/patch.zip
```

重启后的日志：
```
03-22 14:51:06.872 4323-4323/com.test.android W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
03-22 14:51:06.882 4323-4323/com.test.android W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.test.android count:1
03-22 14:51:06.882 4323-4323/com.test.android W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.test.android/shared_prefs/tinker_own_config_com.test.android.xml.bak
03-22 14:51:06.892 4323-4323/com.test.android W/Tinker.ClassLoaderAdder: checkDexInstall result:true
03-22 14:51:06.892 4323-4323/com.test.android W/Tinker.ResourcePatcher: try to clear typedArray cache!
03-22 14:51:06.892 4323-4323/com.test.android E/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
03-22 14:51:06.902 4323-4323/com.test.android E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.NoSuchMethodError: No virtual method at_()Ljava/lang/String; in class Ljava/lang/StringBuilder; or its super classes (declaration of 'java.lang.StringBuilder' appears in /system/framework/core-libart.jar)
                                                                              at android.support.multidex.a.<clinit>(MultiDex.java:63)
                                                                              at com.test.platform.app.AppLike.onBaseContextAttached(AppLike.java:34)
                                                                              at com.test.android.app.ApplicationExLike.onBaseContextAttached(ApplicationExLike.java:37)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
                                                                              at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
                                                                              at android.app.Application.attach(Application.java:211)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:1020)
                                                                              at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                                              at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
                                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6298)
                                                                              at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:158)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7233)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
03-22 14:51:06.902 4323-4323/com.test.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.test.android, PID: 4323
                                                                  java.lang.NoSuchMethodError: No virtual method at_()Ljava/lang/String; in class Ljava/lang/StringBuilder; or its super classes (declaration of 'java.lang.StringBuilder' appears in /system/framework/core-libart.jar)
                                                                      at android.support.multidex.a.<clinit>(MultiDex.java:63)
                                                                      at com.test.platform.app.AppLike.onBaseContextAttached(AppLike.java:34)
                                                                      at com.test.android.app.ApplicationExLike.onBaseContextAttached(ApplicationExLike.java:37)
                                                                      at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
                                                                      at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
                                                                      at android.app.Application.attach(Application.java:211)
                                                                      at android.app.Instrumentation.newApplication(Instrumentation.java:1020)
                                                                      at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                                      at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6298)
                                                                      at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7233)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

在混淆后才会出现该现象，所以感觉是混淆问题，但是具体不知道是什么原因，烦请建议。

**Comment by tomystang** [comment]
只在这台机器上才会出现吗？如果把混淆过的包装到其他机器上呢？

**Comment by motcwang** [comment]
因为暂时没有别的机器，所以别的机器还没有测试，但是之前的版本是ok的，升级到1.7.7后就是现在这样了。

**Comment by motcwang** [comment]
感谢文神和Tom。
问题描述以及原因：之前混淆使用的是`proguard4.7`版本，发现**patch**后**MultiDex**的`install`方法一直crash，使用`Tinker 1.7.5`却没有这个问题。替换混淆版本`proguard5.1`测试成功。Tom解释因为**1.7.5**版本`ART`环境只合成增量`dex`，所以`MultiDex`是不会进入`Patch Dex`中的，而**1.7.7**去掉了这个逻辑，所以才会产生这个问题，所以建议使用`proguard5.1`版本。
