### ISSUE TITLE
Dex: warning: Ignoring InnerClasses attribute for an anonymous inner class

### ISSUE THREAD

**Issue by zeshaoaaa** [Tencent/tinker#421]
异常类型：编译异常

tinker-support版本：latest.release

gradle版本：:3.3

第三方SDK： Bugly SDK

系统：Windows

`Dex: warning: Ignoring InnerClasses attribute for an anonymous inner class
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 20 more
`

`-keepattributes EnclosingMethod

-keepattributes InnerClasses`

这两句混淆我已经添加了，但是还是报这个错

**Comment by shwenzhang** [comment]
使用第三方sdk的需要先尝试只使用Tinker是否有问题

**Comment by zeshaoaaa** [comment]
@shwenzhang 刚那个问题不见了，但是又出现了 apk is not exist, you must set the correct old apk value。
请问 tinker_support 是你的作品吗？我看到tinker上要配置 oldApk的路径，但是 bugly 的文档上没有写要怎么写这个配置

**Comment by zeshaoaaa** [comment]
@shwenzhang 原来我忘了调整 buildAllFlavorsDir 这个参数，感谢你的回答
