### ISSUE TITLE
java.lang.NoSuchMethodError cannot be cast to java.lang.Exception(线上崩溃)

### ISSUE THREAD

**Issue by balizhuang2012** [Tencent/tinker#423]
异常类型：app运行时异常

手机型号：OPPO R2017

手机系统版本：Android 4.3

tinker版本：1.7.7

gradle版本：2.10

是否使用第三方SDK： TinkerPatch SDK,Bugly SDK,TBS SDK

系统：android

堆栈/日志：
Caused by: java.lang.ClassCastException: java.lang.NoSuchMethodError cannot be cast to java.lang.Exception
	at com.tencent.tinker.loader.shareutil.ShareIntentUtil.getIntentPatchException(ShareIntentUtil.java:67)
	at com.tencent.tinker.lib.tinker.TinkerLoadResult.parseTinkerResult(TinkerLoadResult.java:114)
	at com.tencent.tinker.lib.tinker.Tinker.install(Tinker.java:154)
	at com.tencent.tinker.lib.tinker.TinkerInstaller.install(TinkerInstaller.java:71)
	at ryxq.ya.c(TinkerManager.java:98)
	at ryxq.xz.a(TinkerIniter.java:31)
	at com.duowan.kiwi.KiwiApplication.installTinker(KiwiApplication.java:929)
	at com.duowan.kiwi.KiwiApplication.onCreate(KiwiApplication.java:387)
	at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:173)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1010)
	at ryxq.bww.callApplicationOnCreate(InstrumentationHook.java:366)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4519)
	... 10 more

**Comment by shwenzhang** [comment]
will fix with 1.7.8

**Comment by shwenzhang** [comment]
try with tinker 1.7.8
