### ISSUE TITLE
线上异常：Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by balizhuang2012** [Tencent/tinker#424]
异常类型：app运行时异常

手机型号：HUAWEI KIW-TL00H

手机系统版本：Android 5.1.1

tinker版本：1.7.7

gradle版本：2.10

是否使用第三方SDK： TinkerPatch SDK,Bugly SDK,TBS SDK

系统：android

堆栈/日志：
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.killAllOtherProcess(ShareTinkerInternals.java:298)
	at com.tencent.tinker.lib.reporter.DefaultLoadReporter.onLoadPatchVersionChanged(DefaultLoadReporter.java:94)
	at ryxq.xu.onLoadPatchVersionChanged(SampleLoadReporter.java:138)
	at com.tencent.tinker.lib.tinker.TinkerLoadResult.parseTinkerResult(TinkerLoadResult.java:321)
	at com.tencent.tinker.lib.tinker.Tinker.install(Tinker.java:154)
	at com.tencent.tinker.lib.tinker.TinkerInstaller.install(TinkerInstaller.java:71)
	at ryxq.ya.c(TinkerManager.java:98)
	at ryxq.xz.a(TinkerIniter.java:31)
	at com.duowan.kiwi.KiwiApplication.installTinker(KiwiApplication.java:929)
	at com.duowan.kiwi.KiwiApplication.onCreate(KiwiApplication.java:387)
	at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:173)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
	at ryxq.bww.callApplicationOnCreate(InstrumentationHook.java:366)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4857)
	... 9 more

描述：
am.getRunningAppProcesses()返回空，在我们app的其他调用处已经报过很多次线上案例了，一直找不到重现规律。

**Comment by shwenzhang** [comment]
dev已经fix了
