### ISSUE TITLE
小米4 刷7.1.1系统无法热修复，麻烦看下。

### ISSUE THREAD

**Issue by leiMsnow** [Tencent/tinker#428]
03-30 15:58:22.887 8955-8973/com.dangdang.buy2:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar, size: 3668632, use time: 12529
03-30 15:58:28.054 8955-8973/com.dangdang.buy2:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes2.dex.jar, size: 2579569, use time: 5167
03-30 15:58:28.060 8955-8973/com.dangdang.buy2:patch W/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:3
03-30 15:58:28.120 9160-9160/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/test.dex.jar --oat-fd=43 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/test.dex.dex --compiler-filter=speed
03-30 15:58:28.131 9159-9159/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar --oat-fd=39 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes.dex.dex --compiler-filter=speed
03-30 15:58:28.144 9162-9162/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes2.dex.jar --oat-fd=41 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes2.dex.dex --compiler-filter=speed
03-30 15:58:28.746 9159-9159/? E/dex2oat: Failed to open dex file from oat file. File: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar Error: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
03-30 15:58:28.767 8955-9156/com.dangdang.buy2:patch W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg & --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar --oat-fd=39 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes.dex.dex --compiler-filter=speed) because non-0 exit status
03-30 15:58:28.972 8955-9156/com.dangdang.buy2:patch W/art: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
03-30 15:58:28.974 8955-9156/com.dangdang.buy2:patch E/Tinker.ParallelDex: Failed to optimize dex: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar
                                                                           java.io.IOException: Failed to open dex files from /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar because: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
                                                                               at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                               at dalvik.system.DexFile.openDexFile(DexFile.java:367)
                                                                               at dalvik.system.DexFile.<init>(DexFile.java:148)
                                                                               at dalvik.system.DexFile.loadDex(DexFile.java:219)
                                                                               at dalvik.system.DexFile.loadDex(DexFile.java:187)
                                                                               at com.tencent.tinker.loader.TinkerParallelDexOptimizer$OptimizeWorker.run(BUGLY:131)
                                                                               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                               at java.lang.Thread.run(Thread.java:761)
03-30 15:58:35.990 8955-8973/com.dangdang.buy2:patch E/Tinker.ParallelDex: Dexes optimizing failed, some dexes are not optimized.
03-30 15:58:36.052 9207-9207/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar --oat-fd=38 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes.dex.dex --compiler-filter=speed
03-30 15:58:36.662 9207-9207/? E/dex2oat: Failed to open dex file from oat file. File: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar Error: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
03-30 15:58:36.691 8955-8973/com.dangdang.buy2:patch W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg & --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar --oat-fd=38 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes.dex.dex --compiler-filter=speed) because non-0 exit status
03-30 15:58:36.975 8955-8973/com.dangdang.buy2:patch W/art: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
03-30 15:58:36.981 8955-8973/com.dangdang.buy2:patch E/Tinker.DexDiffPatchInternal: retry dex optimize or load failed, path:/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar
03-30 15:58:36.982 8955-8973/com.dangdang.buy2:patch E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  java.io.IOException: Failed to open dex files from /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar because: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
                                                                                        at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                        at dalvik.system.DexFile.openDexFile(DexFile.java:367)
                                                                                        at dalvik.system.DexFile.<init>(DexFile.java:148)
                                                                                        at dalvik.system.DexFile.loadDex(DexFile.java:219)
                                                                                        at dalvik.system.DexFile.loadDex(DexFile.java:187)
                                                                                        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(BUGLY:193)
                                                                                        at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(BUGLY:77)
                                                                                        at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(BUGLY:132)
                                                                                        at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(BUGLY:129)
                                                                                        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
03-30 15:58:36.984 8955-8973/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/patch-d07d791c.apk
03-30 15:58:36.985 8955-8973/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar
03-30 15:58:36.990 8955-8973/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes2.dex.jar
03-30 15:58:36.992 8955-8973/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/test.dex.jar
03-30 15:58:36.993 8955-8973/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex
03-30 15:58:36.994 8955-8973/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes2.dex.dex
03-30 15:58:36.994 8955-8973/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/test.dex.dex
03-30 15:58:36.994 8955-8973/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex
03-30 15:58:36.994 8955-8973/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c
03-30 15:58:36.995 8955-8973/com.dangdang.buy2:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
03-30 15:58:37.013 8839-8839/com.dangdang.buy2 I/CrashReport: Tinker patch failure, result: 
                                                              PatchResult: 
                                                              isSuccess:false
                                                              rawPatchFilePath:/data/user/0/com.dangdang.buy2/app_tmpPatch/tmpPatch.apk
                                                              costTime:26694
                                                              patchVersion:d07d791c547e493e64a780fc4889fc06
03-30 15:58:37.053 847-1991/system_process W/ActivityManager: Scheduling restart of crashed service com.dangdang.buy2/com.tencent.tinker.lib.service.TinkerPatchService in 1000ms

**Comment by shwenzhang** [comment]
#417 安装格式重新提issue
