### ISSUE TITLE
小米5 android 7.0 运行时异常.

### ISSUE THREAD

**Issue by SadieYuCN** [Tencent/tinker#429]
#### 基本信息
- 异常类型：app运行时异常
- 手机型号：小米5
- 手机系统版本：7.0NRD90M
- tinker版本：如:1.7.7 (bugly:crashreport_upgrade:1.2.4里面的Tinker)
- gradle版本：3.3
- 是否使用第三方SDK： 小米SDK
- 系统：Mac

#### 堆栈/日志：

```java
W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.wukongtv.wkremote.client/tinker
D/Tinker.DefaultAppLike: onBaseContextAttached:
W/Tinker.Tinker: tinker patch directory: /data/user/0/com.wukongtv.wkremote.client/tinker
W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
W/Tinker.Tinker: tinker load fail!
D/Tinker.DefaultAppLike: onCreate
I/CrashReport: TINKER_ID:noadDebug_3.0.6.0
I/CrashReport: NEW_TINKER_ID:
W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(BUGLY:173)
E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:<service android:name="com.xiaomi.push.service.XMPushService" .../> is missing or disabled in AndroidManifest.
E/Tinker.UncaughtHandler: catch exception when loading tinker:com.xiaomi.mipush.sdk.d$a: <service android:name="com.xiaomi.push.service.XMPushService" .../> is missing or disabled in AndroidManifest.
                                                                                          at com.xiaomi.mipush.sdk.d.d(Unknown Source)
                                                                                          at com.xiaomi.mipush.sdk.d.a(Unknown Source)
                                                                                          at com.xiaomi.mipush.sdk.e.run(Unknown Source)
                                                                                          at java.lang.Thread.run(Thread.java:761)
                                                                                      

03-30 15:20:15.450 20796-20897/com.wukongtv.wkremote.client E/CrashReport: #++++++++++Record By Bugly++++++++++#
03-30 15:20:15.450 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
03-30 15:20:15.450 2700-2953/? W/PushService: 2017-03-30 15:20:15,450 - [WARN::PushService] - [Thread:120] try send mi push message. packagename:com.wukongtv.wkremote.client action:Notification
03-30 15:20:15.450 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # PKG NAME: com.wukongtv.wkremote.client
03-30 15:20:15.450 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # APP VER: 3.0.6.0-DEBUG-TEST
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # LAUNCH TIME: 2017-03-30 15:20:15
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # CRASH TYPE: JAVA_CRASH
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # CRASH TIME: 2017-03-30 15:20:15
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # CRASH PROCESS: com.wukongtv.wkremote.client
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # CRASH THREAD: Thread-18
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # REPORT ID: bb413377-eac0-4a2c-b3bb-f49ec22bc168
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # CRASH DEVICE: MI 5 UNROOT
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # RUNTIME AVAIL RAM:1041301504 ROM:20453617664 SD:20453617664
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # RUNTIME TOTAL RAM:2826203136 ROM:26300211200 SD:26300211200
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: # CRASH STACK: 
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: com.xiaomi.mipush.sdk.d$a: <service android:name="com.xiaomi.push.service.XMPushService" .../> is missing or disabled in AndroidManifest.
                                                                               at com.xiaomi.mipush.sdk.d.d(Unknown Source)
                                                                               at com.xiaomi.mipush.sdk.d.a(Unknown Source)
                                                                               at com.xiaomi.mipush.sdk.e.run(Unknown Source)
                                                                               at java.lang.Thread.run(Thread.java:761)
03-30 15:20:15.451 20796-20897/com.wukongtv.wkremote.client E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#                                                                                      
```

- 应用的AndroidManifest中已经加入了如下配置:

```java
<!--小米推送-->
     <service
         android:enabled="true"
         android:process=":pushservice"
         android:name="com.xiaomi.push.service.XMPushService"/>
```

**Comment by shwenzhang** [comment]
这里根本还没有加载补丁，请问具体的问题是？

**Comment by SadieYuCN** [comment]
集成tinker后, 使用Android Studio 在小米5上 run 项目抛出了上面的异常 , 在其他测试机上可正常运行. 
这里并没有执行tinker脚本生成补丁包. 只是run到设备上.

**Comment by shwenzhang** [comment]
没有补丁的时候，tinker并不会改变程序执行的任何行为。是否使用了bugly的一键接入等功能，先使用原版的tinker尝试一下把

**Comment by shwenzhang** [comment]
是否使用了bugly 一键接入？他们的实现好像有些问题，尝试使用原生tinker或者tinkerpatch的一键接入尝试

**Comment by devilWwj** [comment]
Bugly问题可以联系小巫，QQ号：659982592，将appId和，错误log发我。

**Comment by devilWwj** [comment]
经过我跟楼主沟通，采用的是改造Application方式接入的tinker，可以排除不是一键接入的问题导致的 @shwenzhang ，这个问题后面有结论会来结题。

**Comment by SadieYuCN** [comment]
问题已经定位, 跟三方sdk开发人员确认过, 这个问题是三方sdk内部抛出的跟tinker 无关. 
感谢@小巫 童鞋的帮助.
