### ISSUE TITLE
小米4 自刷7.1.1系统无法热修复，详情请进。

### ISSUE THREAD

**Issue by leiMsnow** [Tencent/tinker#430]
异常类型：app运行时异常

手机型号：小米4

手机系统版本：7.1.1

tinker版本：1.7.7

gradle版本：3.3-all

是否使用第三方SDK： Bugly

系统：Mac

堆栈/日志：
03-31 09:44:39.002 18657-18657/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/com.dangdang.buy2/tinker/patch.info
03-31 09:44:39.003 18657-18657/? D/Tinker.DefaultAppLike: onBaseContextAttached:
03-31 09:44:39.004 18657-18657/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.dangdang.buy2.DDClientApplication
03-31 09:44:39.011 18657-18657/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.dangdang.buy2/tinker
03-31 09:44:39.011 18657-18657/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-31 09:44:39.012 18657-18657/? W/Tinker.Tinker: tinker load fail!
03-31 09:44:39.021 18657-18657/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
03-31 09:44:39.022 18657-18657/? D/Tinker.DefaultAppLike: onCreate
03-31 09:44:39.257 18657-18657/? W/System.err:     at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.onCreate(BUGLY:189)
03-31 09:44:39.462 18687-18687/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/com.dangdang.buy2/tinker/patch.info
03-31 09:44:39.463 18687-18687/? D/Tinker.DefaultAppLike: onBaseContextAttached:
03-31 09:44:39.463 18687-18687/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.dangdang.buy2.DDClientApplication
03-31 09:44:39.470 18687-18687/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.dangdang.buy2/tinker
03-31 09:44:39.471 18687-18687/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-31 09:44:39.472 18687-18687/? W/Tinker.Tinker: tinker load fail!
03-31 09:44:39.474 18687-18687/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
03-31 09:44:39.478 18687-18687/? D/Tinker.DefaultAppLike: onCreate
03-31 09:44:39.688 18657-18657/? I/CrashReport: TINKER_ID:6.7.0-patch2
03-31 09:44:39.688 18657-18657/? I/CrashReport: NEW_TINKER_ID:

03-31 09:44:39.794 18687-18687/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-31 09:44:40.859 18657-18657/com.dangdang.buy2 W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.dangdang.buy2/tinker_temp/temp.apk is not exist, just return
03-31 09:44:42.933 18657-18718/com.dangdang.buy2 D/CrashReport: current app version is: [6.7.0.129], base tinkerId:[6.7.0-patch2], patch tinkerId:[], patch version:[1]
03-31 09:44:42.953 18657-18718/com.dangdang.buy2 D/CrashReport: current app version is: [6.7.0.129], base tinkerId:[6.7.0-patch2], patch tinkerId:[], patch version:[1]
03-31 09:44:43.604 847-2009/system_process I/ActivityManager: Start proc 18825:com.dangdang.buy2:patch/u0a103 for service com.dangdang.buy2/com.tencent.tinker.lib.service.TinkerPatchService
03-31 09:44:43.676 18825-18825/com.dangdang.buy2:patch W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/com.dangdang.buy2/tinker/patch.info
03-31 09:44:43.677 18825-18825/com.dangdang.buy2:patch D/Tinker.DefaultAppLike: onBaseContextAttached:
03-31 09:44:43.677 18825-18825/com.dangdang.buy2:patch I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.dangdang.buy2.DDClientApplication
03-31 09:44:43.684 18825-18825/com.dangdang.buy2:patch W/Tinker.Tinker: tinker patch directory: /data/user/0/com.dangdang.buy2/tinker
03-31 09:44:43.685 18825-18825/com.dangdang.buy2:patch W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
03-31 09:44:43.685 18825-18825/com.dangdang.buy2:patch W/Tinker.Tinker: tinker load fail!
03-31 09:44:43.686 18825-18825/com.dangdang.buy2:patch E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
03-31 09:44:43.687 18825-18825/com.dangdang.buy2:patch D/Tinker.DefaultAppLike: onCreate
03-31 09:44:43.881 18825-18825/com.dangdang.buy2:patch W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
03-31 09:44:43.885 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker_temp/temp.apk
03-31 09:44:43.885 18825-18848/com.dangdang.buy2:patch W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
03-31 09:44:43.887 847-865/system_process V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.dangdang.buy2/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
03-31 09:44:43.917 847-865/system_process V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.dangdang.buy2/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
03-31 09:44:43.932 18657-18666/com.dangdang.buy2 E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'close' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                   at java.util.zip.ZipFile.<init>(ZipFile.java:237)
                                                                   at java.util.zip.ZipFile.<init>(ZipFile.java:148)
                                                                   at java.util.jar.JarFile.<init>(JarFile.java:161)
                                                                   at java.util.jar.JarFile.<init>(JarFile.java:125)
                                                                   at com.tencent.bugly.beta.tinker.TinkerUtils.readJarEntry(BUGLY:294)
                                                                   at com.tencent.bugly.beta.tinker.TinkerManager.checkNewPatch(BUGLY:451)
                                                                   at com.tencent.bugly.beta.tinker.TinkerManager.applyPatch(BUGLY:409)
                                                                   at com.tencent.bugly.beta.Beta.applyDownloadedPatch(BUGLY:847)
                                                                   at com.dangdang.buy2.b.onDownloadSuccess(DDClientApplication.java:144)
                                                                   at com.tencent.bugly.proguard.r$1.onDownloadSuccess(BUGLY:149)
                                                                   at com.tencent.bugly.beta.tinker.TinkerManager.onDownloadSuccess(BUGLY:387)
                                                                   at com.tencent.bugly.beta.download.a.onCompleted(BUGLY:195)
                                                                   at com.tencent.bugly.beta.global.d.run(BUGLY:263)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-31 09:44:43.933 18657-18666/com.dangdang.buy2 E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'close' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                   at java.util.zip.ZipFile.<init>(ZipFile.java:237)
                                                                   at java.util.zip.ZipFile.<init>(ZipFile.java:148)
                                                                   at java.util.jar.JarFile.<init>(JarFile.java:161)
                                                                   at java.util.jar.JarFile.<init>(JarFile.java:125)
                                                                   at com.tencent.bugly.beta.tinker.TinkerUtils.readJarEntry(BUGLY:294)
                                                                   at com.tencent.bugly.beta.tinker.TinkerManager.checkNewPatch(BUGLY:451)
                                                                   at com.tencent.bugly.beta.tinker.TinkerManager.applyPatch(BUGLY:409)
                                                                   at com.tencent.bugly.beta.tinker.TinkerManager.onDownloadSuccess(BUGLY:384)
                                                                   at com.tencent.bugly.beta.download.a.onCompleted(BUGLY:195)
                                                                   at com.tencent.bugly.beta.global.d.run(BUGLY:263)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-31 09:44:43.951 18825-18848/com.dangdang.buy2:patch W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.dangdang.buy2/app_tmpPatch/tmpPatch.apk size: 86331, dest file: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/patch-d07d791c.apk size:86331
03-31 09:44:56.701 18825-18848/com.dangdang.buy2:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar, size: 3668632, use time: 12735
03-31 09:45:01.660 18825-18848/com.dangdang.buy2:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes2.dex.jar, size: 2579569, use time: 4959
03-31 09:45:01.665 18825-18848/com.dangdang.buy2:patch W/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:3
03-31 09:45:01.712 18977-18977/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes2.dex.jar --oat-fd=39 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes2.dex.dex --compiler-filter=speed
03-31 09:45:01.761 18978-18978/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar --oat-fd=41 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes.dex.dex --compiler-filter=speed
03-31 09:45:01.765 18979-18979/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/test.dex.jar --oat-fd=43 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/test.dex.dex --compiler-filter=speed
03-31 09:45:02.333 18978-18978/? E/dex2oat: Failed to open dex file from oat file. File: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar Error: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
03-31 09:45:02.347 18825-18974/com.dangdang.buy2:patch W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg & --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar --oat-fd=41 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes.dex.dex --compiler-filter=speed) because non-0 exit status
03-31 09:45:02.586 18825-18974/com.dangdang.buy2:patch W/art: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
03-31 09:45:02.588 18825-18974/com.dangdang.buy2:patch E/Tinker.ParallelDex: Failed to optimize dex: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar
                                                                             java.io.IOException: Failed to open dex files from /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar because: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
                                                                                 at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                 at dalvik.system.DexFile.openDexFile(DexFile.java:367)
                                                                                 at dalvik.system.DexFile.<init>(DexFile.java:148)
                                                                                 at dalvik.system.DexFile.loadDex(DexFile.java:219)
                                                                                 at dalvik.system.DexFile.loadDex(DexFile.java:187)
                                                                                 at com.tencent.tinker.loader.TinkerParallelDexOptimizer$OptimizeWorker.run(BUGLY:131)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                 at java.lang.Thread.run(Thread.java:761)
03-31 09:45:09.182 18825-18848/com.dangdang.buy2:patch E/Tinker.ParallelDex: Dexes optimizing failed, some dexes are not optimized.
03-31 09:45:09.228 19012-19012/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar --oat-fd=39 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes.dex.dex --compiler-filter=speed
03-31 09:45:09.741 19012-19012/? E/dex2oat: Failed to open dex file from oat file. File: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar Error: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
03-31 09:45:09.772 18825-18848/com.dangdang.buy2:patch W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg & --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar --oat-fd=39 --oat-location=/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes.dex.dex --compiler-filter=speed) because non-0 exit status
03-31 09:45:09.972 18825-18848/com.dangdang.buy2:patch W/art: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
03-31 09:45:09.977 18825-18848/com.dangdang.buy2:patch E/Tinker.DexDiffPatchInternal: retry dex optimize or load failed, path:/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar
03-31 09:45:09.978 18825-18848/com.dangdang.buy2:patch E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  java.io.IOException: Failed to open dex files from /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar because: Failure to verify dex file '/data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar': Found virtual method with same index as direct method: 29418
                                                                                          at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                          at dalvik.system.DexFile.openDexFile(DexFile.java:367)
                                                                                          at dalvik.system.DexFile.<init>(DexFile.java:148)
                                                                                          at dalvik.system.DexFile.loadDex(DexFile.java:219)
                                                                                          at dalvik.system.DexFile.loadDex(DexFile.java:187)
                                                                                          at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(BUGLY:193)
                                                                                          at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(BUGLY:77)
                                                                                          at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(BUGLY:132)
                                                                                          at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(BUGLY:129)
                                                                                          at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
03-31 09:45:09.979 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/patch-d07d791c.apk
03-31 09:45:09.980 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes.dex.jar
03-31 09:45:09.983 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/classes2.dex.jar
03-31 09:45:09.986 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex/test.dex.jar
03-31 09:45:09.986 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/dex
03-31 09:45:09.987 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/classes2.dex.dex
03-31 09:45:09.987 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex/test.dex.dex
03-31 09:45:09.987 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c/odex
03-31 09:45:09.987 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker/patch-d07d791c
03-31 09:45:09.988 18825-18848/com.dangdang.buy2:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
03-31 09:45:10.007 18825-18848/com.dangdang.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.dangdang.buy2/tinker_temp/temp.apk
03-31 09:45:10.007 18825-18848/com.dangdang.buy2:patch W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
03-31 09:45:10.009 847-865/system_process V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.dangdang.buy2/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
03-31 09:45:10.010 18657-18657/com.dangdang.buy2 I/CrashReport: Tinker patch failure, result: 
                                                                PatchResult: 
                                                                isSuccess:false
                                                                rawPatchFilePath:/data/user/0/com.dangdang.buy2/app_tmpPatch/tmpPatch.apk
                                                                costTime:26102
                                                                patchVersion:d07d791c547e493e64a780fc4889fc06
03-31 09:45:10.054 847-12724/system_process W/ActivityManager: Scheduling restart of crashed service com.dangdang.buy2/com.tencent.tinker.lib.service.TinkerPatchService in 1000ms

**Comment by leiMsnow** [comment]
补充，该patch在华为6.0系统可以成功、vivox7的6.0系统也可以成功。

**Comment by shwenzhang** [comment]
是否使用了bugly 一键接入？尝试使用原生tinker或者tinkerpatch的一键接入尝试

**Comment by tomystang** [comment]
如果换了接入方式还是不行的话，麻烦把旧包、新包和补丁包一起发到我的邮箱吧：tys1b0037f@qq.com

**Comment by SadieYuCN** [comment]
好的.

**Comment by devilWwj** [comment]
Bugly问题可以联系小巫，QQ号：659982592，将appId和，错误log发我。
