### ISSUE TITLE
Jenkins生成补丁出现java.io.IOException: proguard.ParseException: Unknown option

### ISSUE THREAD

**Issue by yuanshenbin** [Tencent/tinker#436]
异常类型：编译异常

手机型号：无

手机系统版本：无

tinker版本：1.7.7

gradle版本：2.2.2

是否使用第三方SDK： 否

系统：Window

先汇报下情况，日志在下面 @ @！
我用的是Jenkins编译的
情况1：默认生成apk包和补丁的路径都没有修改。  生成apk包，补丁，通过
情况2：只修改生成包路径放到app下，跟build路径一个级别，动态侵入修改 appVersion,appCode,TinkerId,patchVersion
  生成apk成功，生成补丁失败
情况3： 默认生成apk包和补丁的路径都没有修改。动态侵入修改 appVersion,appCode,TinkerId,patchVersion
情况4：把情况2和3在studio里编译，都没任何问题
  生成apk成功，生成补丁失败

情况2和3日志一样的

日志如下：

----------------------tinker build warning ------------------------------------
tinker auto operation: 
excluding annotation processor and source template from app packaging. Enable dx jumboMode to reduce package size.
enable dx jumboMode to reduce package size.
disable preDexLibraries to prevent ClassDefNotFoundException when your app is booting.

tinker will change your build configs:
we will add TINKER_ID=1.0.0 in your build output manifest file build/intermediates/manifests/full/*

if minifyEnabled is true
you will find the gen proguard rule file at build/intermediates/tinker_intermediates/tinker_proguard.pro
and we will help you to put it in the proguardFiles.

if multiDexEnabled is true
you will find the gen multiDexKeepProguard file at build/intermediates/tinker_intermediates/tinker_multidexkeep.pro
and we will help you to put it in the MultiDexKeepProguardFile.

if applyResourceMapping file is exist
we will build app apk with resource R.txt file
if resources.arsc has changed, you should use applyResource mode to build the new apk!
-----------------------------------------------------------------
:clean
:app:clean
:app:preBuild UP-TO-DATE
:app:extractProguardFiles
:app:preXiaomiReleaseBuild
:app:checkXiaomiReleaseManifest
:app:preXiaomiDebugBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2501Library
:app:prepareComAndroidSupportAppcompatV72501Library
:app:prepareComAndroidSupportDesign2501Library
:app:preXiaomiDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportMultidex101Library
:app:prepareComAndroidSupportRecyclerviewV72501Library
:app:prepareComAndroidSupportSupportCompat2501Library
:app:prepareComAndroidSupportSupportCoreUi2501Library
:app:prepareComAndroidSupportSupportCoreUtils2501Library
:app:prepareComAndroidSupportSupportFragment2501Library
:app:prepareComAndroidSupportSupportMediaCompat2501Library
:app:prepareComAndroidSupportSupportV42501Library
:app:prepareComAndroidSupportSupportVectorDrawable2501Library
:app:prepareComAndroidSupportTransition2501Library
:app:prepareComTencentTinkerTinkerAndroidLib177Library
:app:prepareComTencentTinkerTinkerAndroidLoader177Library
:app:prepareXiaomiReleaseDependencies
:app:compileXiaomiReleaseAidl
:app:compileXiaomiReleaseRenderscript
:app:generateXiaomiReleaseBuildConfig
:app:generateXiaomiReleaseResValues
:app:generateXiaomiReleaseResources
:app:mergeXiaomiReleaseResources
:app:processXiaomiReleaseManifest
:app:tinkerProcessXiaomiReleaseManifesttinker add tinker_id_1.0.0 to your AndroidManifest.xml C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\build\intermediates\manifests\full\xiaomi\release\AndroidManifest.xml
tinker add com.jackytinker.Application to dex loader pattern
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml

:app:tinkerProcessXiaomiReleaseResourceIdwe build app apk with apply resource mapping file C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\AppBase/app-1.0.0-0408-12-19-28/xiaomi/app-xiaomi-release-R.txt
tinker gen resource public.xml in build/intermediates/tinker_intermediates/public.xml
tinker gen resource idx.xml in build/intermediates/tinker_intermediates/idx.xml

:app:processXiaomiReleaseResources
:app:generateXiaomiReleaseSources
:app:incrementalXiaomiReleaseJavaCompilationSafeguard
:app:compileXiaomiReleaseJavaWithJavac
:app:compileXiaomiReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
*
*
注: Creating file:/C:/Program%20Files%20(x86)/Jenkins/workspace/JackyTinker/app/build/generated/source/apt/xiaomi/release/tinker/sample/android/app/SampleApplication.java
注: Creating file:/C:/Program%20Files%20(x86)/Jenkins/workspace/JackyTinker/app/build/generated/source/apt/xiaomi/release/com/jackytinker/Application.java
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
:app:compileXiaomiReleaseNdk UP-TO-DATE
:app:compileXiaomiReleaseSources
:app:lintVitalXiaomiRelease
:app:mergeXiaomiReleaseShaders
:app:compileXiaomiReleaseShaders
:app:generateXiaomiReleaseAssets
:app:mergeXiaomiReleaseAssets
:app:tinkerProcessXiaomiReleaseProguardtry update tinker proguard file with C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\build\intermediates\tinker_intermediates\tinker_proguard.pro
try add applymapping C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\AppBase/app-1.0.0-0408-12-19-28/xiaomi/app-xiaomi-release-mapping.txt to build the package
now proguard files is [C:\Program Files (x86)\Jenkins\workspace\JackyTinker\build\intermediates\proguard-files\proguard-android.txt-2.2.2, C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\proguard-rules.pro, C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\build\intermediates\tinker_intermediates\tinker_proguard.pro]

:app:processXiaomiReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForXiaomiRelease
:app:transformClassesAndResourcesWithProguardForXiaomiRelease
Warning: Exception while processing task java.io.IOException: proguard.ParseException: Unknown option '(' in line 1 of file 'C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\build\intermediates\tinker_intermediates\tinker_proguard.pro'
:app:transformClassesAndResourcesWithProguardForXiaomiRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForXiaomiRelease'.
> java.io.IOException: proguard.ParseException: Unknown option '(' in line 1 of file 'C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\build\intermediates\tinker_intermediates\tinker_proguard.pro'

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesAndResourcesWithProguardForXiaomiRelease'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.io.IOException: proguard.ParseException: Unknown option '(' in line 1 of file 'C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\build\intermediates\tinker_intermediates\tinker_proguard.pro'
	at com.android.builder.tasks.Job.awaitRethrowExceptions(Job.java:79)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.transform(ProGuardTransform.java:180)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more
Caused by: java.io.IOException: proguard.ParseException: Unknown option '(' in line 1 of file 'C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\build\intermediates\tinker_intermediates\tinker_proguard.pro'
	at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:268)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:61)
	at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:170)
	at com.android.builder.tasks.Job.runTask(Job.java:51)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:223)
Caused by: proguard.ParseException: Unknown option '(' in line 1 of file 'C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\build\intermediates\tinker_intermediates\tinker_proguard.pro'
	at proguard.ConfigurationParser.parse(ConfigurationParser.java:217)
	at com.android.build.gradle.internal.transforms.BaseProguardAction.applyConfigurationFile(BaseProguardAction.java:137)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:230)
	... 5 more

BUILD FAILED

Total time: 21.127 secs
Build step 'Invoke Gradle script' changed build result to FAILURE
Build step 'Invoke Gradle script' marked build as failure
Finished: FAILURE

**Comment by yuanshenbin** [comment]
排查了一下午，好像混搅出问题了，不设置混搅，在jenkins的流程都正常，有点奇怪，为什么设置混搅在studio正常，在jenkins里面就混搅出问题， 求解，-----

**Comment by shwenzhang** [comment]
Caused by: java.io.IOException: proguard.ParseException: Unknown option '(' in line 1 of file 
C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\build\intermediates\tinker_intermediates\tinker_proguard.pro

看看这个文件内容是什么

**Comment by yuanshenbin** [comment]
-applymapping C:\Program Files (x86)\Jenkins\workspace\JackyTinker\app\AppBase/app-1.0.0-0409-20-34-59/app-release-mapping.txt
-keepattributes *Annotation* 
-dontwarn com.tencent.tinker.anno.AnnotationProcessor 
-keep @com.tencent.tinker.anno.DefaultLifeCycle public class *
-keep public class * extends android.app.Application {
    *;
}

-keep public class com.tencent.tinker.loader.app.ApplicationLifeCycle {
    *;
}
-keep public class * implements com.tencent.tinker.loader.app.ApplicationLifeCycle {
    *;
}

-keep public class com.tencent.tinker.loader.TinkerLoader {
    *;
}
-keep public class * extends com.tencent.tinker.loader.TinkerLoader {
    *;
}
-keep public class com.tencent.tinker.loader.TinkerTestDexLoad {
    *;
}

#your dex.loader patterns here
-keep class tinker.sample.android.app.BaseBuildInfo
-keep class com.jackytinker.Application
-keep class com.tencent.tinker.loader.**

**Comment by shwenzhang** [comment]
-applymapping C:\Program Files (x86)  路径不识别，把这个x86干掉

**Comment by yuanshenbin** [comment]
非常感谢，重新安装路径了，已经解决了

在 2017-04-10 12:55:36，"shwenzhang" <notifications@github.com> 写道：


-applymapping C:\Program Files (x86) 路径不识别，把这个x86干掉
