### ISSUE TITLE
android 7.0 会出现TinkerRuntimeException: Tinker Exception:ShareSecurityCheck file的错误

### ISSUE THREAD

**Issue by aliciaxia** [Tencent/tinker#478]
异常类型：app运行时异常
手机型号：HUAWEI MHA-AL100

手机系统版本:Android 7.0 

tinker版本:1.7.7

gradle版本:2.3.2

是否使用热更新SDK：没使用

系统:Mac

堆栈/日志：
05-19 10:37:30.333 18334-18334/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.xxx.xxx/tinker
05-19 10:37:30.335 18334-18334/? I/Tinker.TestTinkerPatchListener: application maxMemory:384
05-19 10:37:30.336 18334-18334/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
05-19 10:37:30.336 18334-18334/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
05-19 10:37:30.336 18334-18334/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, systemOTA:false
05-19 10:37:30.337 18334-18334/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
05-19 10:37:30.337 18334-18334/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code:-2, cost:1
05-19 10:37:30.337 18334-18334/? W/Tinker.Tinker: tinker load fail!
05-19 10:37:30.895 18334-18384/? I/Tinker.TestTinkerPatchListener: receive a patch file: /data/user/0com.xxx.xxx/cache/test_patch_4_17_16.apk, file size:24576
                                                                    
                                                                    [ 05-19 10:37:30.906 18450:18450 I/         ]
                                                                    power log dlsym ok
05-19 10:37:30.943 18334-18334/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad tinker service is running, just return
05-19 10:37:30.972 18450-18450/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.xxx.xxx/tinker
05-19 10:37:30.973 18450-18450/? I/Tinker.TestTinkerPatchListener: application maxMemory:384
05-19 10:37:30.975 18450-18450/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
05-19 10:37:30.975 18450-18450/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
05-19 10:37:30.975 18450-18450/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, systemOTA:false
05-19 10:37:30.975 18450-18450/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
05-19 10:37:30.975 18450-18450/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code:-2, cost:1
05-19 10:37:30.976 18450-18450/? W/Tinker.Tinker: tinker load fail!
05-19 10:37:31.049 18450-18486/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
05-19 10:37:31.050 18450-18450/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
05-19 10:37:31.057 18450-18486/? W/Tinker.UpgradePatchRetry: try copy file: /data/user/0/com.xxx.xxxcache/test_patch_4_17_16.apk to /data/user/0/com.xxx.xxx/tinker_temp/temp.apk
05-19 10:37:31.070 18450-18486/? I/Tinker.TinkerPatchService: try to increase patch process priority
05-19 10:37:31.081 18450-18486/? I/Tinker.DefaultPatchReporter: patchReporter onPatchException: patch exception path:/data/user/0/com.xxx.xxx/cache/test_patch_4_17_16.apk, throwable:Tinker Exception:ShareSecurityCheck file /data/user/0/com.xxx.xxx/cache/test_patch_4_17_16.apk, size 24576 verifyPatchMetaSignature fail
05-19 10:37:31.081 18450-18486/? E/Tinker.DefaultPatchReporter: tinker patch exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
05-19 10:37:31.083 18450-18486/? E/Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:ShareSecurityCheck file /data/user/0/com.xxx.xxx/cache/test_patch_4_17_16.apk, size 24576 verifyPatchMetaSignature fail
                                                                    at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:139)
                                                                    at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(ShareTinkerInternals.java:106)
                                                                    at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(ShareTinkerInternals.java:91)
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:60)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                    at android.os.Looper.loop(Looper.java:156)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                 Caused by: java.util.zip.ZipException: error in opening zip file
                                                                    at java.util.zip.ZipFile.open(Native Method)
                                                                    at java.util.zip.ZipFile.<init>(ZipFile.java:218)
                                                                    at java.util.zip.ZipFile.<init>(ZipFile.java:147)
                                                                    at java.util.jar.JarFile.<init>(JarFile.java:161)
                                                                    at java.util.jar.JarFile.<init>(JarFile.java:125)
                                                                    at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(ShareSecurityCheck.java:110)
                                                                    at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(ShareTinkerInternals.java:106) 
                                                                    at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(ShareTinkerInternals.java:91) 
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:60) 
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                    at android.os.Looper.loop(Looper.java:156) 
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
05-19 10:37:31.084 18450-18486/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path:/data/user/0/com.xxx.xxx/cache/test_patch_4_17_16.apk, success:false, cost:15
05-19 10:37:31.084 18450-18486/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.xxx/tinker_temp/temp.apk
05-19 10:37:41.552 18567-18567/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.xxx.xxx/tinker
05-19 10:37:41.554 18567-18567/? I/Tinker.TestTinkerPatchListener: application maxMemory:384
05-19 10:37:41.555 18567-18567/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxx/tinker
05-19 10:37:41.555 18567-18567/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.7
05-19 10:37:41.556 18567-18567/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, systemOTA:false
05-19 10:37:41.556 18567-18567/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
05-19 10:37:41.556 18567-18567/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxx/tinker, code:-2, cost:0
05-19 10:37:41.556 18567-18567/? W/Tinker.Tinker: tinker load fail!
05-19 10:37:41.753 18567-18567/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return

为什么会在7.0出现java.util.zip.ZipException: error in opening zip file，没找到解决办法，求教

**Comment by simpleton** [comment]
@aliciaxia 是否有读写sdcard的权限？

**Comment by aliciaxia** [comment]
@simpleton 7.0的机器是一半几率会现这个错误，一半几率是合成成功，同一个patch包

**Comment by aliciaxia** [comment]
读写权限是有的，不然一次也不成功

**Comment by aliciaxia** [comment]
本来想root这台华为查一下包的情况，但还需要申请解锁，解锁要求在这台华为手机登录账号超过14天。。。。不过看android 7.0的系统源码的zip的open跟6.0的打开zip是不一样的

**Comment by aliciaxia** [comment]
而且是android 7.0 Release版的patch遇到这种更新率低的问题，android 7.0的debug版包测试几乎没问题，
以下是gradle的设置区别：
   release {
            minifyEnabled true
            shrinkResources true
            proguardFiles 'proguard-android-optimize.txt', 'annotations.pro', 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            initWith(buildTypes.beta)
            versionNameSuffix ".debug"
            debuggable true
            minifyEnabled false
            shrinkResources false
            buildConfigField "String", "BUILD_TIME", "\"DEBUG\""
            buildConfigField "String", "GIT_SHA", "\"DEBUG\""
            aaptOptions.setProperty("cruncherEnabled",false)
        }

**Comment by shwenzhang** [comment]
这个问题我们线上也遇到，只有几十例那样子。

**Comment by aliciaxia** [comment]
我这边还没监测这个机器版本的失败率，这边QA的测试机正好是这款；
@shwenzhang 
对这个问题有什么计划么？几率很低不处理了？

**Comment by shwenzhang** [comment]
这块我们也复现不了，比例是几十/几千万，暂时先不处理

**Comment by lyqaiym** [comment]
怎么解决的？我的是部分成功，部分出现这个。16个成功，44个失败

**Comment by checkming** [comment]
@aliciaxia  我也遇到了这个问题，通过手机导入补丁包去加载时是可以正常加载补丁修复，但是通过从服务器里下载补丁文件，程序在尝试修复时就会在堆栈里报这个错，自然也就没有修复成功，请问你解决了吗？
