### ISSUE TITLE
Oppo R9s 补丁合成成功，运行异常

### ISSUE THREAD

**Issue by zdnuist** [Tencent/tinker#480]
异常类型：app运行时异常

手机型号：Oppo R9s

手机系统版本：Android 7.1.1

tinker版本：1.7.9

gradle版本:3.3

是否使用热更新SDK： TinkerPatch SDK 

系统：Window 10

堆栈/日志：
05-19 16:52:17.897 13002-13002/? E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:247)
                                                                   at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:161)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:130)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
                                                                   at android.app.Application.attach(Application.java:198)
                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
                                                                   at android.app.Instrumentation.newApplication(Instrumentation.java:993)
                                                                   at android.app.LoadedApk.makeApplication(LoadedApk.java:843)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5663)
                                                                   at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:186)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6477)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

**Comment by shwenzhang** [comment]
这个是触发了启动保护，这个不是真正的crash。你要把启动过程crash的日志发出来

**Comment by zdnuist** [comment]
05-22 11:53:06.486 3359-3359/? E/System: java.lang.Throwable
                                             at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:50)
                                             at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                                             at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
                                             at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
                                             at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:555)
                                             at android.app.LoadedApk.getClassLoader(LoadedApk.java:588)
                                             at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:6489)
                                             at android.app.LoadedApk.getResources(LoadedApk.java:812)
                                             at android.app.ContextImpl.<init>(ContextImpl.java:2116)
                                             at android.app.ContextImpl.createAppContext(ContextImpl.java:2057)
                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5580)
                                             at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:186)
                                             at android.app.ActivityThread.main(ActivityThread.java:6477)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
