### ISSUE TITLE
打差异报的时候报错了

### ISSUE THREAD

**Issue by salmanit** [Tencent/tinker#513]
是否使用热更新SDK： tinkerpatch-gradle-plugin:1.1.6

系统：window

堆栈/日志：

Class Lcom/umeng/analytics/AnalyticsConfig; will be added into changed classes dex ...
**org.jf.util.ExceptionWithContext: Class Lcom/umeng/analytics/AnalyticsConfig; has already been interned**
        at org.jf.dexlib2.writer.builder.BuilderClassPool.internClass(BuilderClassPool.java:74)
        at org.jf.dexlib2.writer.builder.DexBuilder.internClassDef(DexBuilder.java:139)

打差异包的时候提示上边那个友盟啥东西错误了。完事就挂掉了。这个也不知道咋解决。

**Comment by salmanit** [comment]
Class Landroid/support/constraint/R; will be added into changed classes dex ...
org.jf.util.ExceptionWithContext: Class Landroid/support/constraint/R; has already been interned
        at org.jf.dexlib2.writer.builder.BuilderClassPool.internClass(BuilderClassPool.java:74)

有时候是这个错误提示，反正都是提示has already been interned 差异包总是失败

**Comment by shwenzhang** [comment]
cahnge to 1.1.7
