### ISSUE TITLE
assembleDebug编译的可以运行项目，assembleRelease编译的无法运行项目崩溃

### ISSUE THREAD

**Issue by caocao123** [Tencent/tinker#515]
### 机型：
小米note3 android5.0
build.gradle:2.2.2
### Tinker版本（TinkerPatch SDK）:
com.tinkerpatch.tinker:tinker-android-anno:1.7.11
com.tinkerpatch.sdk:tinkerpatch-android-sdk:1.1.7
### 项目编译版本:
minSdkVersion 15
targetSdkVersion 25
###系统：
Window
### 描述:
我拿一个含有百度地图的项目来测试，按照官网的介绍，我分别使用了assembleDebug，assembleRelease编译版来运行
### 结果:
assembleDebug能够完美运行项目，assembleRelease编译完后，安装直接发生崩溃异常
### 错误日志：
Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.ExceptionInInitializerError
                                                               at com.baidu.platform.comapi.c.a(Unknown Source)
                                                               at com.baidu.mapapi.g.a(Unknown Source)
                                                               at com.baidu.mapapi.g.a(Unknown Source)
                                                               at **_com.example.gao.mapcar.base.CarApplication.onCreate(SourceFile:56)_**
                                                               at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.onCreate(SourceFile:113)
                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4772)
                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:169)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                               at android.os.Looper.loop(Looper.java:194)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5556)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                            **_Caused by: java.lang.ClassNotFoundException: Didn't find class "com.baidu.mapapi.model.ParcelItem" on path: DexPathList[[zip file "/data/app/com.example.gao.mapcar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.gao.mapcar-1/lib/arm, /vendor/lib, /system/lib]]_**
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                               at com.baidu.platform.comjni.tools.JNITools.initClass(Native Method)
                                                               at com.baidu.platform.comjni.tools.c.b(Unknown Source)
                                                               at com.baidu.platform.comapi.b.<clinit>(Unknown Source)
                                                               at com.baidu.platform.comapi.c.a(Unknown Source) 
                                                               at com.baidu.mapapi.g.a(Unknown Source) 
                                                               at com.baidu.mapapi.g.a(Unknown Source) 
                                                               at com.example.gao.mapcar.base.CarApplication.onCreate(SourceFile:56) 
                                                               at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.onCreate(SourceFile:113) 
                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4772) 
                                                               at android.app.ActivityThread.access$1500(ActivityThread.java:169) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                               at android.os.Looper.loop(Looper.java:194) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5556) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
                                                           	Suppressed: java.lang.ClassNotFoundException: com.baidu.mapapi.model.ParcelItem
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                               		... 20 more
                                                            **_Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available_**
06-13 14:11:57.015 22384-22384/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.gao.mapcar, PID: 22384
                                                   java.lang.ExceptionInInitializerError
                                                       at com.baidu.platform.comapi.c.a(Unknown Source)
                                                       at com.baidu.mapapi.g.a(Unknown Source)
                                                       at com.baidu.mapapi.g.a(Unknown Source)
                                                       at com.example.gao.mapcar.base.CarApplication.onCreate(SourceFile:56)
                                                       at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.onCreate(SourceFile:113)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4772)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:169)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5556)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                    **_Caused by: java.lang.ClassNotFoundException: Didn't find class "com.baidu.mapapi.model.ParcelItem" on path: DexPathList[[zip file "/data/app/com.example.gao.mapcar-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.gao.mapcar-1/lib/arm, /vendor/lib, /system/lib]]_**
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at com.baidu.platform.comjni.tools.JNITools.initClass(Native Method)
                                                       at com.baidu.platform.comjni.tools.c.b(Unknown Source)
                                                       at com.baidu.platform.comapi.b.<clinit>(Unknown Source)
                                                       at com.baidu.platform.comapi.c.a(Unknown Source) 
                                                       at com.baidu.mapapi.g.a(Unknown Source) 
                                                       at com.baidu.mapapi.g.a(Unknown Source) 
                                                       at com.example.gao.mapcar.base.CarApplication.onCreate(SourceFile:56) 
                                                       at com.tinkerpatch.sdk.loader.TinkerPatchReflectApplication.onCreate(SourceFile:113) 
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4772) 
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:169) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                       at android.os.Looper.loop(Looper.java:194) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5556) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
                                                   	Suppressed: java.lang.ClassNotFoundException: com.baidu.mapapi.model.ParcelItem
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                       		... 20 more
                                                    **_Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available_**

错误日志中，有一行说：com.example.gao.mapcar.base.CarApplication.onCreate(SourceFile:56)我的第56行有问题，我去查看了下是我初始化百度地图的时候出现的问题，**但是assembleDebug能够完美运行项目且能完美运行，assembleRelease直接发生崩溃异常**
### 补充:
如果我通过assembleDebug拿到apk后，然后通过360来签名，是可以成功的

**Comment by shwenzhang** [comment]
这个一般跟tinker无关，查看一下混淆的规则。tinker对混淆规则只是做了添加
