### ISSUE TITLE
初次集成Tinker ，下载补丁包成功 但是报签名异常 

### ISSUE THREAD

**Issue by AndroidCrow** [Tencent/tinker#522]
loadData from url: http://q.tinkerpatch.com/edbcddcee7b81f3f/11/file4?d=033f7bec-396a-45c0-aa30-4cfc20a2ed99&v=1497578658784, method:GET, body:null
06-16 10:04:19.041 8404-8440/? I/Tinker.UrlConnectionFetcher: response code 200 msg: OK
06-16 10:04:19.051 8404-8440/? I/Tinker.PatchRequestCallback: TinkerPatchRequestCallback: onPatchUpgrade, file:/data/data/myapp.hotfix/tinker_server/11_4.apk, newVersion:4, currentVersion:0
06-16 10:04:19.061 8404-8440/? E/ShareSecurityCheck: /data/data/myapp.hotfix/tinker_server/11_4.apk
                                                     java.security.SignatureException: error:04091077:rsa routines:INT_RSA_VERIFY:wrong signature length
                                                         at com.android.org.conscrypt.NativeCrypto.X509_verify(Native Method)
                                                         at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:349)
                                                         at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:384)
                                                         at org.apache.harmony.security.utils.WrappedX509Certificate.verify(WrappedX509Certificate.java:156)
                                                         at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.check(SourceFile:158)
                                                         at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(SourceFile:133)
                                                         at com.tinkerpatch.sdk.server.callback.TinkerPatchRequestCallback.onPatchUpgrade(SourceFile:155)
                                                         at com.tinkerpatch.sdk.server.a.a$1$1.onDataReady(SourceFile:1178)
                                                         at com.tinkerpatch.sdk.server.a.a$3.onDataReady(SourceFile:1298)
                                                         at com.tinkerpatch.sdk.server.b.a$1.onDataReady(SourceFile:1060)
                                                         at com.tinkerpatch.sdk.server.b.a$a.run(SourceFile:124)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
                                                         at java.lang.Thread.run(Thread.java:818)
06-16 10:04:19.061 8404-8440/? E/Tinker.PatchRequestCallback: onPatchUpgrade, signature check failed. file: /data/data/myapp.hotfix/tinker_server/11_4.apk, version:4

这是什么原因

**Comment by shwenzhang** [comment]
签名不一致，tinkerpatch问题请到他们的github group提问

**Comment by lyqaiym** [comment]
怎么解决的？我的是部分成功，部分出现这个

**Comment by lyqaiym** [comment]
怎么解决的？我的是部分成功，部分出现这个。16个成功，44个失败
