### ISSUE TITLE
在1加3t，H2OS公测第九版上，打补丁失败，应用奔溃

### ISSUE THREAD

**Issue by lowwor** [Tencent/tinker#529]
```
异常类型：下发补丁成功，在其他机型上打补丁成功，但在1加3T上打补丁失败，应用奔溃

手机型号：一加3T

手机系统版本：Android 7.1.1，ONEPLUSA3010_28_170614，H2OS公测第九版

tinker版本：1.7.11

gradle版本：3.3

热更新SDK： Bugly SDK 1.3.1

系统：Windows 10



```
```
堆栈/日志：
06-26 11:12:27.288 27773-27773/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
06-26 11:12:27.289 27773-27773/? D/Tinker.TinkerInternals: same fingerprint:OnePlus/OnePlus3/OnePlus3T:7.1.1/NMF26F/05151900:user/release-keys
06-26 11:12:27.291 27773-27773/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.xxx.xxxx count:1
06-26 11:12:27.306 27773-27773/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.xxxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxxx-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]]
06-26 11:12:27.307 27773-27773/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.xxx.xxxx/tinker/patch-2897680b/odex, dex size:2
06-26 11:12:27.326 27773-27773/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/com.xxx.xxxx/tinker/patch-2897680b/dex/changed_classes.dex.jar", zip file "/data/user/0/com.xxx.xxxx/tinker/patch-2897680b/dex/test.dex.jar", zip file "/data/app/com.xxx.xxxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxxx-1/lib/arm64, /system/fake-libs64, /data/app/com.xxx.xxxx-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]], dex size:2
06-26 11:12:27.326 27773-27773/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
06-26 11:12:27.329 27773-27773/? W/Tinker.ResourcePatcher: try to clear typedArray cache!
        06-26 11:12:27.330 27773-27773/? I/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
06-26 11:12:27.330 27773-27773/? I/Tinker.ResourceLoader: monkeyPatchExistingResources resource file:/data/user/0/com.xxx.xxxx/tinker/patch-2897680b/res/resources.apk, use time: 3
06-26 11:12:27.330 27773-27773/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
        06-26 11:12:27.330 27773-27773/? D/Tinker.DefaultAppLike: onBaseContextAttached:
06-26 11:12:27.333 27773-27773/? I/Tinker.TinkerPatchListener: application maxMemory:256
06-26 11:12:27.335 27773-27773/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.xxx.xxxx/tinker
06-26 11:12:27.335 27773-27773/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
06-26 11:12:27.336 27773-27773/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.xxx.xxxx, main process:true, systemOTA:false, oatDir:odex, useInterpretMode:false
06-26 11:12:27.336 27773-27773/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:2897680b77c07b1bc4131914946ebb1a, newVersion:2897680b77c07b1bc4131914946ebb1a, current:2897680b77c07b1bc4131914946ebb1a
06-26 11:12:27.336 27773-27773/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
06-26 11:12:27.336 27773-27773/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.xxx.xxxx/tinker, code: 0, cost: 76ms
06-26 11:12:27.353 27773-27773/? D/Tinker.DefaultAppLike: onCreate
06-26 11:12:27.809 27773-27773/? W/CrashReport: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/com.xxx.xxxx/tinker/patch-2897680b/dex/changed_classes.dex.jar", zip file "/data/user/0/com.xxx.xxxx/tinker/patch-2897680b/dex/test.dex.jar", zip file "/data/app/com.xxx.xxxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxxx-1/lib/arm64, /system/fake-libs64, /data/app/com.xxx.xxxx-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libBugly.so"
06-26 11:12:27.844 27773-27773/? I/CrashReport: TINKER_ID:env_debugRelease_4c206e7
06-26 11:12:27.844 27773-27773/? I/CrashReport: NEW_TINKER_ID:env_debugRelease_685713c
06-26 11:12:27.851 27773-27838/? W/CrashReport: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/com.xxx.xxxx/tinker/patch-2897680b/dex/changed_classes.dex.jar", zip file "/data/user/0/com.xxx.xxxx/tinker/patch-2897680b/dex/test.dex.jar", zip file "/data/app/com.xxx.xxxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxxx-1/lib/arm64, /system/fake-libs64, /data/app/com.xxx.xxxx-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libBugly.so"
06-26 11:12:30.949 27773-27837/? D/CrashReport: app version is: [1.5.1.327], [deviceId:862561032226779|460000471254602|1dc10c345ff927cf], channel: [env_debug], base tinkerId:[env_debugRelease_4c206e7], patch tinkerId:[env_debugRelease_685713c], patch version:[2]
06-26 11:12:30.956 27773-27837/? D/CrashReport: app version is: [1.5.1.327], [deviceId:862561032226779|460000471254602|1dc10c345ff927cf], channel: [env_debug], base tinkerId:[env_debugRelease_4c206e7], patch tinkerId:[env_debugRelease_685713c], patch version:[2]
06-26 11:12:31.587 27773-27773/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Package not found: com.google.android.webview
06-26 11:12:31.701 27773-27773/? E/Tinker.TinkerUncaughtExceptionHandler: tinker has fast crash 2 times
06-26 11:12:31.701 27773-27773/? E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.RuntimeException: Package not found: com.google.android.webview
at android.webkit.WebViewDelegate.getPackageId(WebViewDelegate.java:163)
at com.android.webview.chromium.WebViewDelegateFactory$ProxyDelegate.getPackageId(WebViewDelegateFactory.java:168)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.startChromiumLocked(WebViewChromiumFactoryProvider.java:10511)
at com.android.webview.chromium.WebViewChromiumFactoryProvider$1.run(WebViewChromiumFactoryProvider.java:2082)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6324)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)


--------- beginning of crash
```

**Comment by shwenzhang** [comment]
因为使用了第三方sdk, 请先使用tinker sample 测试

**Comment by lowwor** [comment]
tinker sample 没问题，应该是bugly的问题。
