### ISSUE TITLE
android 7.1.1（nexus6）系统上加载patch 文件失败

### ISSUE THREAD

**Issue by moonljt521** [Tencent/tinker#535]
异常类型：app运行时异常

手机型号：如:Nexus 6

手机系统版本：Android 7.1.1 

tinker版本：1.7.9

gradle版本：2.2.2

是否使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK

系统：如:Mac

日志：
通过多次试验，每次的情况不一样：大致分为两种：
1 、06-29 18:12:24.491 31745-31745/com.hongyuanshidai.liankecoach I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/patch_signed_7zip.apk, file size:980449
06-29 18:12:24.513 31745-31745/com.hongyuanshidai.liankecoach W/Tinker.UpgradePatchRetry: onPatchListenerCheck, retry count 4 must exceed than max retry count
06-29 18:12:24.513 31745-31745/com.hongyuanshidai.liankecoach I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.hongyuanshidai.liankecoach/tinker_temp/temp.apk
06-29 18:12:24.514 31745-31745/com.hongyuanshidai.liankecoach I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/patch_signed_7zip.apk, code: -12

结果：没有更新成功

2、
UncaughtHandler: catch exception when loading tinker:java.lang.IllegalAccessError: Field 'android.support.multidex.a.c' is inaccessible to class 'android.support.multidex.a' (declaration of 'android.support.multidex.a' appears in /data/user/0/com.hongyuanshidai.liankecoach/tinker/patch-cbf2127d/dex/classes.dex.jar)
                                                               at android.support.multidex.a.<clinit>(Unknown Source)
                                                               at android.support.multidex.a.a(Unknown Source)
                                                               at com.hongyuanshidai.common.BaseApplication.attachBaseContext(Unknown Source)
                                                               at android.app.Application.attach(Application.java:189)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:993)
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
                                                               at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

结果：重启app崩溃

-----------------------------------------------
我在另外一台魅族 M3 Note（5.1）上加载patch 文件正常

**Comment by shwenzhang** [comment]
-12是超过了重试次数，你这边是否使用了bugly的SDK，他们之前似乎有一个bug会导致类似的问题

**Comment by moonljt521** [comment]
没有

**Comment by shwenzhang** [comment]
请在sample中尝试复现，然后把链接给到这边
