### ISSUE TITLE
NumberFormatException: For input string: "0x20000"

### ISSUE THREAD

**Issue by shizhy1986** [Tencent/tinker#54]
java.lang.NumberFormatException: For input string: "0x20000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at net.dongliu.apk.parser.struct.xml.Attributes.getInt(Attributes.java:40)
	at net.dongliu.apk.parser.parser.ApkMetaTranslator.onStartTag(ApkMetaTranslator.java:56)
	at net.dongliu.apk.parser.parser.CompositeXmlStreamer.onStartTag(CompositeXmlStreamer.java:19)
	at net.dongliu.apk.parser.parser.BinaryXmlParser.readXmlNodeStartTag(BinaryXmlParser.java:189)
	at net.dongliu.apk.parser.parser.BinaryXmlParser.parse(BinaryXmlParser.java:101)
	at net.dongliu.apk.parser.AbstractApkParser.transBinaryXml(AbstractApkParser.java:164)
	at net.dongliu.apk.parser.AbstractApkParser.parseManifestXml(AbstractApkParser.java:123)
	at net.dongliu.apk.parser.AbstractApkParser.parseApkMeta(AbstractApkParser.java:105)
	at net.dongliu.apk.parser.AbstractApkParser.getApkMeta(AbstractApkParser.java:56)
	at com.tencent.tinker.build.apkparser.AndroidManifest.getAndroidManifest(AndroidManifest.java:66)

apkParser有bug，不能识别0x20000

**Comment by shizhy1986** [comment]
用源码build出来的patch plugin，提示osdetector插件无法找到？

**Comment by 15189611** [comment]
同问 我有遇到了次错误，在Debug中~~~

**Comment by shwenzhang** [comment]
0x20000是放在哪里的？把原始xml贴出来看一下

**Comment by 15189611** [comment]
<uses-feature
        android:glEsVersion="0x20000"
        android:required="true" />

原始

	
	<uses-feature
		android:glEsVersion="0x00020000"
		android:required="true" />

**Comment by shwenzhang** [comment]
恩，我在考虑要不要把apk-parser接过来自己搞。原作者好像相应的不是非常快

**Comment by 15189611** [comment]
需要等待你的修复？还是我可以将这个声明注释掉让他跑？

**Comment by shwenzhang** [comment]
#63 ，1.7.0会fix

**Comment by 15189611** [comment]
ok

**Comment by junyuecao** [comment]
貌似apk-parser已经是2.1.6了, 这里用的还是2.1.2

**Comment by shwenzhang** [comment]
will fix with 1.7.0

**Comment by shwenzhang** [comment]
please try with v1.6.2

**Comment by shwenzhang** [comment]
@shizhy1986 , please try with 1.7.0
