### ISSUE TITLE
Format specifier throwing MissingFormatArgumentException in debugLog

### ISSUE THREAD

**Issue by simpleton** [Tencent/tinker#540]
异常类型：app运行时异常

手机型号: 不限
手机系统版本：不限
tinker版本：如:1.7.11
gradle版本：如:3.3

是否使用热更新SDK： TinkerPatch SDK
系统：Mac

堆栈/日志：
```java
java.util.MissingFormatArgumentException: Format specifier: 22d
at java.util.Formatter.getArgument(Formatter.java:1111)
at java.util.Formatter.doFormat(Formatter.java:1076)
at java.util.Formatter.format(Formatter.java:1042)
at java.util.Formatter.format(Formatter.java:1011)
at java.lang.String.format(String.java:1999)
at java.lang.String.format(String.java:1973)
at com.tencent.tinker.lib.util.TinkerLog$1.w(TinkerLog.java:49)
at com.tencent.tinker.lib.util.TinkerLog.w(TinkerLog.java:93)
at com.tinkerpatch.sdk.server.callback.TinkerPatchRequestCallback.onPatchSyncFail(SourceFile:219)
at com.tinkerpatch.sdk.server.a.a$1.onLoadFailed(SourceFile:200)
at com.tinkerpatch.sdk.server.a.a$2.onLoadFailed(SourceFile:258)
at com.tinkerpatch.sdk.server.b.a$1.onLoadFailed(SourceFile:65)
at com.tinkerpatch.sdk.server.b.a$a.run(SourceFile:126)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by simpleton** [comment]
ref https://github.com/TinkerPatch/tinkerpatch-sdk/issues/43

**Comment by shwenzhang** [comment]
fix by dev
