### ISSUE TITLE
Tinker 1.7.11报ava.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation 同样配置1.7.7没问题

### ISSUE THREAD

**Issue by asdzheng** [Tencent/tinker#544]
异常类型：app运行时异常

手机型号：如:Xiaomi HM 2A

手机系统版本：如:Android 4.4.4

tinker版本：如:1.7.11

gradle版本：如:2.3.1

使用热更新SDK： Bugly SDK

系统：Win10

Tinker1.7.11补丁生效后运行出现的错误日志：

07-05 10:41:06.612 31590-31590/com.mewe.wolf W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
07-05 10:41:06.622 31590-31590/com.mewe.wolf I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/data/com.mewe.wolf/tinker/patch.info , oldVer:bd1a8040bc9bf74e53d972b24c7e16c7, newVer:bd1a8040bc9bf74e53d972b24c7e16c7, fingerprint:Xiaomi/full_lte26007/lte26007:4.4.4/KTU84Q/7.5.19:user/release-keys, oatDir:odex
07-05 10:41:06.632 31590-31590/com.mewe.wolf W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.mewe.wolf count:1
07-05 10:41:06.642 31590-31590/com.mewe.wolf I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]]
07-05 10:41:06.642 31590-31590/com.mewe.wolf I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/data/com.mewe.wolf/tinker/patch-bd1a8040/odex, dex size:2
07-05 10:41:06.642 31590-31590/com.mewe.wolf I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.mewe.wolf/tinker/patch-bd1a8040/dex/changed_classes.dex.jar", zip file "/data/data/com.mewe.wolf/tinker/patch-bd1a8040/dex/test.dex.jar", zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]], dex size:2
07-05 10:41:06.642 31590-31590/com.mewe.wolf W/Tinker.ClassLoaderAdder: checkDexInstall result:true
07-05 10:41:06.642 31590-31590/com.mewe.wolf I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
07-05 10:41:06.642 31590-31590/com.mewe.wolf D/Tinker.DefaultAppLike: onBaseContextAttached:
07-05 10:41:06.652 31590-31590/com.mewe.wolf I/Tinker.TinkerPatchListener: application maxMemory:96
07-05 10:41:06.662 31590-31590/com.mewe.wolf W/Tinker.Tinker: tinker patch directory: /data/data/com.mewe.wolf/tinker
07-05 10:41:06.662 31590-31590/com.mewe.wolf I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
07-05 10:41:06.662 31590-31590/com.mewe.wolf I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.mewe.wolf, main process:true, systemOTA:false, oatDir:odex, useInterpretMode:false
07-05 10:41:06.662 31590-31590/com.mewe.wolf I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:, newVersion:bd1a8040bc9bf74e53d972b24c7e16c7, current:bd1a8040bc9bf74e53d972b24c7e16c7
07-05 10:41:06.662 31590-31590/com.mewe.wolf I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
07-05 10:41:06.662 31590-31590/com.mewe.wolf I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchVersionChanged: patch version change from  to bd1a8040bc9bf74e53d972b24c7e16c7
07-05 10:41:06.662 31590-31590/com.mewe.wolf I/Tinker.DefaultLoadReporter: onLoadPatchVersionChanged, try kill all other process
07-05 10:41:06.662 31590-31590/com.mewe.wolf I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.mewe.wolf/tinker, code: 0, cost: 101ms
07-05 10:41:06.822 31590-31590/com.mewe.wolf D/Tinker.DefaultAppLike: onCreate
07-05 10:41:06.972 31590-31590/com.mewe.wolf I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@42048a40
07-05 10:41:06.992 31590-31590/com.mewe.wolf D/CrashReport-Native: Parsing line: 5f495000-5f496000 r--s 00003000 b3:14 179499     /data/data/com.mewe.wolf/tinker/patch-bd1a8040/dex/changed_classes.dex.jar
07-05 10:41:06.992 31590-31590/com.mewe.wolf D/CrashReport-Native: Parsing line: 5f498000-5f499000 r--s 00000000 b3:14 179500     /data/data/com.mewe.wolf/tinker/patch-bd1a8040/dex/test.dex.jar
07-05 10:41:06.992 31590-31590/com.mewe.wolf D/CrashReport-Native: Parsing line: 5f499000-5f49a000 r--p 00000000 b3:14 179503     /data/data/com.mewe.wolf/tinker/patch-bd1a8040/odex/test.dex.dex
07-05 10:41:06.992 31590-31590/com.mewe.wolf D/CrashReport-Native: Parsing line: 5fdbb000-5fdc4000 r--p 00000000 b3:14 179502     /data/data/com.mewe.wolf/tinker/patch-bd1a8040/odex/changed_classes.dex.dex
07-05 10:41:07.102 31590-31590/com.mewe.wolf I/CrashReport: TINKER_ID:2.0.6-SNAPSHOT
07-05 10:41:07.102 31590-31590/com.mewe.wolf I/CrashReport: NEW_TINKER_ID:2.0.8-SNAPSHOT
07-05 10:41:07.452 31590-31590/com.mewe.wolf W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(BUGLY:173)
07-05 10:41:07.862 31590-31609/com.mewe.wolf E/mewewolf: Class ref in pre-verified class resolved to unexpected implementation 
                                                          com.mewe.wolf.service.user.UserSvr.onStart(UserSvr.java:42)
                                                         com.mewe.core.h.i.b(ServiceMgr.java:141)
                                                         com.mewe.core.h.i.a(ServiceMgr.java:78)
                                                         com.mewe.core.h.i.a(ServiceMgr.java:44)
                                                         com.mewe.core.h.g.a(ServiceCenter.java:48)
                                                         com.mewe.core.h.f.a(SC.java:12)
                                                         com.mewe.wolf.service.im.b.d.f(IMFriendShipModule.java:258)
                                                         com.mewe.wolf.service.im.b.d.d(IMFriendShipModule.java:46)
                                                         com.mewe.wolf.service.im.b.d.<init>(IMFriendShipModule.java:42)
                                                         com.mewe.wolf.service.im.IMService.b(IMService.java:63)
                                                         com.mewe.wolf.service.im.IMService.onStart(IMService.java:54)
                                                         com.mewe.core.h.i.b(ServiceMgr.java:143)
                                                         com.mewe.core.h.i.a(ServiceMgr.java:78)
                                                         com.mewe.core.h.i.a(ServiceMgr.java:44)
                                                         com.mewe.core.h.g.a(ServiceCenter.java:48)
                                                         com.mewe.core.h.f.a(SC.java:12)
                                                         com.mewe.wolf.game.c.a(GameInit.java:16)
                                                         com.mewe.wolf.c.a(ModuleMgr.java:34)
                                                         com.mewe.wolf.c.b(ModuleMgr.java:25)
                                                         com.mewe.wolf.WolfApplication.onArkServiceInit(WolfApplication.java:131)
                                                         com.mewe.core.app.BaseApp.initInMainProcess(BaseApp.java:131)
                                                         com.mewe.core.app.BaseApp.onCreate(BaseApp.java:111)
                                                         com.mewe.wolf.WolfApplication.onCreate(WolfApplication.java:68)
                                                         com.tencent.tinker.loader.app.TinkerApplication.onCreate(BUGLY:173)
                                                         com.mewe.wolf.BaseApplication.onCreate(BaseApplication.java:21)
                                                         android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                         android.app.ActivityThread.handleBindApplication(ActivityThread.java:4455)
                                                         android.app.ActivityThread.access$1500(ActivityThread.java:147)
                                                         android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
                                                         android.os.Handler.dispatchMessage(Handler.java:102)
                                                         android.os.Looper.loop(Looper.java:136)
                                                         android.app.ActivityThread.main(ActivityThread.java:5135)
                                                         java.lang.reflect.Method.invokeNative(Native Method)
                                                         java.lang.reflect.Method.invoke(Method.java:515)
                                                         com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
                                                         com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
                                                         dalvik.system.NativeStart.main(Native Method)
                                                         (P:31590)(T:1)(C:CrashProxy)at (CrashProxy.java:40)
07-05 10:41:07.882 31590-31590/com.mewe.wolf E/CrashReport: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                                at com.mewe.wolf.service.user.UserSvr.onStart(UserSvr.java:42)
                                                                at com.mewe.core.h.i.b(ServiceMgr.java:141)
                                                                at com.mewe.core.h.i.a(ServiceMgr.java:78)
                                                                at com.mewe.core.h.i.a(ServiceMgr.java:44)
                                                                at com.mewe.core.h.g.a(ServiceCenter.java:48)
                                                                at com.mewe.core.h.f.a(SC.java:12)
                                                                at com.mewe.wolf.service.im.b.d.f(IMFriendShipModule.java:258)
                                                                at com.mewe.wolf.service.im.b.d.d(IMFriendShipModule.java:46)
                                                                at com.mewe.wolf.service.im.b.d.<init>(IMFriendShipModule.java:42)
                                                                at com.mewe.wolf.service.im.IMService.b(IMService.java:63)
                                                                at com.mewe.wolf.service.im.IMService.onStart(IMService.java:54)
                                                                at com.mewe.core.h.i.b(ServiceMgr.java:143)
                                                                at com.mewe.core.h.i.a(ServiceMgr.java:78)
                                                                at com.mewe.core.h.i.a(ServiceMgr.java:44)
                                                                at com.mewe.core.h.g.a(ServiceCenter.java:48)
                                                                at com.mewe.core.h.f.a(SC.java:12)
                                                                at com.mewe.wolf.game.c.a(GameInit.java:16)
                                                                at com.mewe.wolf.c.a(ModuleMgr.java:34)
                                                                at com.mewe.wolf.c.b(ModuleMgr.java:25)
                                                                at com.mewe.wolf.WolfApplication.onArkServiceInit(WolfApplication.java:131)
                                                                at com.mewe.core.app.BaseApp.initInMainProcess(BaseApp.java:131)
                                                                at com.mewe.core.app.BaseApp.onCreate(BaseApp.java:111)
                                                                at com.mewe.wolf.WolfApplication.onCreate(WolfApplication.java:68)
                                                                at com.tencent.tinker.loader.app.TinkerApplication.onCreate(BUGLY:173)
                                                                at com.mewe.wolf.BaseApplication.onCreate(BaseApplication.java:21)
                                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4455)
                                                                at android.app.ActivityThread.access$1500(ActivityThread.java:147)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:136)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
                                                                at dalvik.system.NativeStart.main(Native Method)
07-05 10:41:08.192 31590-31590/com.mewe.wolf E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Class ref in pre-verified class resolved to unexpected implementation
07-05 10:41:08.202 31590-31590/com.mewe.wolf E/Tinker.TinkerUncaughtExceptionHandler: tinker has fast crash 1 times
07-05 10:41:08.202 31590-31590/com.mewe.wolf E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                                           at com.mewe.wolf.service.user.UserSvr.onStart(UserSvr.java:42)
                                                                           at com.mewe.core.h.i.b(ServiceMgr.java:141)
                                                                           at com.mewe.core.h.i.a(ServiceMgr.java:78)
                                                                           at com.mewe.core.h.i.a(ServiceMgr.java:44)
                                                                           at com.mewe.core.h.g.a(ServiceCenter.java:48)
                                                                           at com.mewe.core.h.f.a(SC.java:12)
                                                                           at com.mewe.wolf.service.im.b.d.f(IMFriendShipModule.java:258)
                                                                           at com.mewe.wolf.service.im.b.d.d(IMFriendShipModule.java:46)
                                                                           at com.mewe.wolf.service.im.b.d.<init>(IMFriendShipModule.java:42)
                                                                           at com.mewe.wolf.service.im.IMService.b(IMService.java:63)
                                                                           at com.mewe.wolf.service.im.IMService.onStart(IMService.java:54)
                                                                           at com.mewe.core.h.i.b(ServiceMgr.java:143)
                                                                           at com.mewe.core.h.i.a(ServiceMgr.java:78)
                                                                           at com.mewe.core.h.i.a(ServiceMgr.java:44)
                                                                           at com.mewe.core.h.g.a(ServiceCenter.java:48)
                                                                           at com.mewe.core.h.f.a(SC.java:12)
                                                                           at com.mewe.wolf.game.c.a(GameInit.java:16)
                                                                           at com.mewe.wolf.c.a(ModuleMgr.java:34)
                                                                           at com.mewe.wolf.c.b(ModuleMgr.java:25)
                                                                           at com.mewe.wolf.WolfApplication.onArkServiceInit(WolfApplication.java:131)
                                                                           at com.mewe.core.app.BaseApp.initInMainProcess(BaseApp.java:131)
                                                                           at com.mewe.core.app.BaseApp.onCreate(BaseApp.java:111)
                                                                           at com.mewe.wolf.WolfApplication.onCreate(WolfApplication.java:68)
                                                                           at com.tencent.tinker.loader.app.TinkerApplication.onCreate(BUGLY:173)
                                                                           at com.mewe.wolf.BaseApplication.onCreate(BaseApplication.java:21)
                                                                           at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4455)
                                                                           at android.app.ActivityThread.access$1500(ActivityThread.java:147)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
                                                                           at dalvik.system.NativeStart.main(Native Method)
07-05 10:41:08.202 31590-31590/com.mewe.wolf E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.mewe.wolf, PID: 31590
                                                               java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                                   at com.mewe.wolf.service.user.UserSvr.onStart(UserSvr.java:42)
                                                                   at com.mewe.core.h.i.b(ServiceMgr.java:141)
                                                                   at com.mewe.core.h.i.a(ServiceMgr.java:78)
                                                                   at com.mewe.core.h.i.a(ServiceMgr.java:44)
                                                                   at com.mewe.core.h.g.a(ServiceCenter.java:48)
                                                                   at com.mewe.core.h.f.a(SC.java:12)
                                                                   at com.mewe.wolf.service.im.b.d.f(IMFriendShipModule.java:258)
                                                                   at com.mewe.wolf.service.im.b.d.d(IMFriendShipModule.java:46)
                                                                   at com.mewe.wolf.service.im.b.d.<init>(IMFriendShipModule.java:42)
                                                                   at com.mewe.wolf.service.im.IMService.b(IMService.java:63)
                                                                   at com.mewe.wolf.service.im.IMService.onStart(IMService.java:54)
                                                                   at com.mewe.core.h.i.b(ServiceMgr.java:143)
                                                                   at com.mewe.core.h.i.a(ServiceMgr.java:78)
                                                                   at com.mewe.core.h.i.a(ServiceMgr.java:44)
                                                                   at com.mewe.core.h.g.a(ServiceCenter.java:48)
                                                                   at com.mewe.core.h.f.a(SC.java:12)
                                                                   at com.mewe.wolf.game.c.a(GameInit.java:16)
                                                                   at com.mewe.wolf.c.a(ModuleMgr.java:34)
                                                                   at com.mewe.wolf.c.b(ModuleMgr.java:25)
                                                                   at com.mewe.wolf.WolfApplication.onArkServiceInit(WolfApplication.java:131)
                                                                   at com.mewe.core.app.BaseApp.initInMainProcess(BaseApp.java:131)
                                                                   at com.mewe.core.app.BaseApp.onCreate(BaseApp.java:111)
                                                                   at com.mewe.wolf.WolfApplication.onCreate(WolfApplication.java:68)
                                                                   at com.tencent.tinker.loader.app.TinkerApplication.onCreate(BUGLY:173)
                                                                   at com.mewe.wolf.BaseApplication.onCreate(BaseApplication.java:21)
                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4455)
                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:147)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1271)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
                                                                   at dalvik.system.NativeStart.main(Native Method)
07-05 10:41:10.912 31590-31631/com.mewe.wolf D/CrashReport: app version is: [2.0.6-SNAPSHOT.0], [deviceId:868291028998066|null|8200cb1c9714ee92], channel: [official], base tinkerId:[2.0.6-SNAPSHOT], patch tinkerId:[2.0.8-SNAPSHOT], patch version:[2]

使用Tinker1.7.7版本补丁生效后成功运行的日志：

07-05 10:04:55.222 20753-20753/com.mewe.wolf W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
07-05 10:04:55.232 20753-20753/com.mewe.wolf W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.mewe.wolf count:1
07-05 10:04:55.252 20753-20753/com.mewe.wolf I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]]
07-05 10:04:55.262 20753-20753/com.mewe.wolf I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/classes.dex.jar", zip file "/data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/test.dex.jar", zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]], dex size:2
07-05 10:04:55.262 20753-20753/com.mewe.wolf W/Tinker.ClassLoaderAdder: checkDexInstall result:true
07-05 10:04:55.262 20753-20753/com.mewe.wolf I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
07-05 10:04:55.322 20753-20753/com.mewe.wolf D/Tinker.DefaultAppLike: onBaseContextAttached:
07-05 10:04:55.382 20753-20753/com.mewe.wolf W/Tinker.Tinker: tinker patch directory: /data/data/com.mewe.wolf/tinker
07-05 10:04:55.472 20753-20753/com.mewe.wolf D/Tinker.DefaultAppLike: onCreate
07-05 10:04:55.582 20753-20753/com.mewe.wolf I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@4205cbd8
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 5f495000-5f496000 r--s 00335000 b3:14 179366     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/classes.dex.jar
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 5f496000-5f497000 r--s 00000000 b3:14 179439     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/test.dex.jar
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 5f497000-5f498000 r--p 00000000 b3:14 179300     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/test.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 5fdb6000-6032f000 r--p 00000000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 6032f000-60331000 r--p 00579000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 60331000-60332000 r--p 0057b000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 60332000-60333000 r--p 0057c000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 60333000-6033d000 r--p 0057d000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 6033d000-6033f000 r--p 00587000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 6033f000-60499000 r--p 00589000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 60499000-6049c000 r--p 006e3000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 6049c000-6049d000 r--p 006e6000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 6049d000-6049e000 r--p 006e7000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 6049e000-6052a000 r--p 006e8000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 6052a000-6052c000 r--p 00774000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.612 20753-20753/com.mewe.wolf D/CrashReport-Native: Parsing line: 6052c000-606bc000 r--p 00776000 b3:14 179442     /data/data/com.mewe.wolf/tinker/patch-0451b9bb/odex/classes.dex.dex
07-05 10:04:55.682 20753-20753/com.mewe.wolf I/CrashReport: TINKER_ID:2.1.0-SNAPSHOT
07-05 10:04:55.682 20753-20753/com.mewe.wolf I/CrashReport: NEW_TINKER_ID:2.1.2-SNAPSHOT
07-05 10:04:55.932 20753-20753/com.mewe.wolf W/System.err:     at com.tencent.tinker.loader.app.TinkerApplication.onCreate(BUGLY:173)
07-05 10:04:56.192 20817-20817/com.mewe.wolf:marsservice W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
07-05 10:04:56.192 20817-20817/com.mewe.wolf:marsservice W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.mewe.wolf:marsservice count:1
07-05 10:04:56.222 20817-20817/com.mewe.wolf:marsservice I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]]
07-05 10:04:56.222 20817-20817/com.mewe.wolf:marsservice I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/classes.dex.jar", zip file "/data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/test.dex.jar", zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]], dex size:2
07-05 10:04:56.222 20817-20817/com.mewe.wolf:marsservice W/Tinker.ClassLoaderAdder: checkDexInstall result:true
07-05 10:04:56.222 20817-20817/com.mewe.wolf:marsservice I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
07-05 10:04:56.242 20817-20817/com.mewe.wolf:marsservice D/Tinker.DefaultAppLike: onBaseContextAttached:
07-05 10:04:56.292 20817-20817/com.mewe.wolf:marsservice W/Tinker.Tinker: tinker patch directory: /data/data/com.mewe.wolf/tinker
07-05 10:04:56.312 20817-20817/com.mewe.wolf:marsservice D/Tinker.DefaultAppLike: onCreate
07-05 10:04:56.382 20849-20849/com.mewe.wolf:QALSERVICE W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
07-05 10:04:56.392 20849-20849/com.mewe.wolf:QALSERVICE W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.mewe.wolf:QALSERVICE count:1
07-05 10:04:56.402 20849-20849/com.mewe.wolf:QALSERVICE I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]]
07-05 10:04:56.412 20849-20849/com.mewe.wolf:QALSERVICE I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/classes.dex.jar", zip file "/data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/test.dex.jar", zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]], dex size:2
07-05 10:04:56.412 20849-20849/com.mewe.wolf:QALSERVICE W/Tinker.ClassLoaderAdder: checkDexInstall result:true
07-05 10:04:56.412 20849-20849/com.mewe.wolf:QALSERVICE I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
07-05 10:04:56.422 20849-20849/com.mewe.wolf:QALSERVICE D/Tinker.DefaultAppLike: onBaseContextAttached:
07-05 10:04:56.492 20849-20849/com.mewe.wolf:QALSERVICE W/Tinker.Tinker: tinker patch directory: /data/data/com.mewe.wolf/tinker
07-05 10:04:56.552 20849-20849/com.mewe.wolf:QALSERVICE D/Tinker.DefaultAppLike: onCreate
07-05 10:04:56.552 20817-20817/com.mewe.wolf:marsservice W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
07-05 10:04:57.012 20849-20849/com.mewe.wolf:QALSERVICE W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
07-05 10:04:57.912 21010-21010/com.mewe.wolf:xg_service_v3 W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
07-05 10:04:57.912 21010-21010/com.mewe.wolf:xg_service_v3 W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.mewe.wolf:xg_service_v3 count:1
07-05 10:04:57.942 21010-21010/com.mewe.wolf:xg_service_v3 I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]]
07-05 10:04:57.942 21010-21010/com.mewe.wolf:xg_service_v3 I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/classes.dex.jar", zip file "/data/data/com.mewe.wolf/tinker/patch-0451b9bb/dex/test.dex.jar", zip file "/data/app/com.mewe.wolf-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mewe.wolf-1, /vendor/lib, /system/lib]]], dex size:2
07-05 10:04:57.942 21010-21010/com.mewe.wolf:xg_service_v3 W/Tinker.ClassLoaderAdder: checkDexInstall result:true
07-05 10:04:57.942 21010-21010/com.mewe.wolf:xg_service_v3 I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
07-05 10:04:57.962 21010-21010/com.mewe.wolf:xg_service_v3 D/Tinker.DefaultAppLike: onBaseContextAttached:
07-05 10:04:58.022 21010-21010/com.mewe.wolf:xg_service_v3 W/Tinker.Tinker: tinker patch directory: /data/data/com.mewe.wolf/tinker
07-05 10:04:58.052 21010-21010/com.mewe.wolf:xg_service_v3 D/Tinker.DefaultAppLike: onCreate
07-05 10:04:58.912 21010-21010/com.mewe.wolf:xg_service_v3 W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
07-05 10:05:00.492 20753-20753/com.mewe.wolf W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/data/com.mewe.wolf/tinker_temp/temp.apk is not exist, just return
07-05 10:05:00.602 20753-20795/com.mewe.wolf D/CrashReport: current app version is: [2.1.0-SNAPSHOT.0], channel: [null], base tinkerId:[2.1.0-SNAPSHOT], patch tinkerId:[2.1.2-SNAPSHOT], patch version:[1]

备注：首先wiki里关于这个问题的描述我已验证无数遍都没问题,以下是关于tinker的配置

dex.loader =  [com.tencent.tinker.loader.*, com.asdzheng.BaseApplication]

BaseApplication :
   public BaseApplication() {
        super(ShareConstants.TINKER_ENABLE_ALL, "com.asdzhen.WolfApplication",
                "com.tencent.tinker.loader.TinkerLoader", false);
    }

WolfApplication extends DefaultApplicationLike...

**Comment by shwenzhang** [comment]
如果1.7.7没有问题，1.7.11有问题的话，估计就是main dex pattern的问题。你这边可以把dalvik的日志也给一下，就可以看出来了

**Comment by asdzheng** [comment]
刚测了一下，应该是加固isProtected=true，但是运行的apk包并没有加固导致的
