### ISSUE TITLE
Resources$NotFoundException 华为 7.0   56次crash

### ISSUE THREAD

**Issue by liangxianshen** [Tencent/tinker#548]
自7月4号至今 发完补丁 ， 在华为的7.0的手机上 有56次crash  ，出现这个问题的上一个补丁也有问题--> https://github.com/Tencent/tinker/issues/543

异常类型：app运行时异常

手机型号：华为duk-al20、

手机系统版本：7.0

tinker版本：如:1.0.6

gradle版本：如:3.3.0

是否使用热更新SDK： Bugly SDK

系统：win8

堆栈/日志：

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.duia.cet4/com.duia.cet4.activity.main.MainActivity_}: android.view.InflateException: Binary XML file line #9: Binary XML file line #15: Error inflating class <unknown>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6585)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #15: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:656)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
	at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:728)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:796)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1005)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:454)
	at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:290)
	at android.app.Activity.setContentView(Activity.java:2515)
	at com.duia.cet4.activity.main.MainActivity_.setContentView(SourceFile:59)
	at com.duia.cet4.activity.main.MainActivity_.onCreate(SourceFile:44)
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6585)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.duia.cet4:drawable/jiinhua with resource ID #0x7f02031a
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/jiinhua.png from drawable resource ID #0x7f02031a
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:935)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:769)
	at android.content.res.Resources.loadDrawable(Resources.java:921)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:983)
	at android.view.View.<init>(View.java:4193)
	at android.widget.ImageView.<init>(ImageView.java:157)
	at android.widget.ImageView.<init>(ImageView.java:152)
	at android.widget.ImageView.<init>(ImageView.java:148)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:656)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
	at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:728)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:796)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1005)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:454)
	at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:290)
	at android.app.Activity.setContentView(Activity.java:2515)
	at com.duia.cet4.activity.main.MainActivity_.setContentView(SourceFile:59)
	at com.duia.cet4.activity.main.MainActivity_.onCreate(SourceFile:44)
	at android.app.Activity.performCreate(Activity.java:6910)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6585)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by: android.content.res.Resources$NotFoundException: failed to add asset path /data/user/0/com.duia.cet4/tinker/patch-f86ac223/res/resources.apk
	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:275)
	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:332)
	at android.app.ResourcesManager.getOrCreateResources(ResourcesManager.java:612)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:690)
	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1989)
	at android.app.ActivityThreadUtils.getTopLevelResources(ActivityThreadUtils.java:24)
	at huawei.android.hwtheme.HwThemeManagerImpl.updateHwtResource(HwThemeManagerImpl.java:492)
	at android.hwtheme.HwThemeManager.updateHwtResource(HwThemeManager.java:311)
	at android.app.LoadedApk.getResources(LoadedApk.java:803)
	at android.graphics.Bitmap.getDefaultDensity(Bitmap.java:222)
	at android.graphics.Bitmap.<init>(Bitmap.java:196)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:701)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:508)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1152)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:930)
	... 42 more
android.view.InflateException: Binary XML file line #9: Binary XML file line #15: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:656)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
	at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:728)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:796)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1005)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:454)
	at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:290)
	at android.app.Activity.

**Comment by shwenzhang** [comment]
这个是bugly sdk的问题
