### ISSUE TITLE
Can't verify patch that is signed by keystore providing by WoSign CA 

### ISSUE THREAD

**Issue by simpleton** [Tencent/tinker#555]
异常类型：app运行时异常

手机系统版本：不限
tinker版本：如:1.7.11
gradle版本：如:2.12
系统：如:Mac

堆栈/日志：
```java
07-19 02:22:44.388 2622-2658/? E/ShareSecurityCheck: /data/user/0/com.tinkerpatch.easy_sample/tinker_server/3.0.1_14.apk
java.security.SignatureException
     at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:353)
     at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:384)
     at org.apache.harmony.security.utils.WrappedX509Certificate.verify(WrappedX509Certificate.java:156)
     at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.a(Unknown Source)
     at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.a(Unknown Source)
     at com.tinkerpatch.sdk.server.callback.TinkerPatchRequestCallback.onPatchUpgrade(Unknown Source)
     at com.tinkerpatch.sdk.server.a.a$1$1.onDataReady(Unknown Source)
     at com.tinkerpatch.sdk.server.a.a$3.onDataReady(Unknown Source)
     at com.tinkerpatch.sdk.server.b.a$1.onDataReady(Unknown Source)
     at com.tinkerpatch.sdk.server.b.a$a.run(Unknown Source)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
```
Here is keystore:
[Android.keystore.zip](https://github.com/Tencent/tinker/files/1156949/Android.keystore.zip)

The warning `The signer's certificate chain is not validated.` is produced when we run jarsigner as below:
```bash
jarsigner -verbose -strict -sigalg SHA256withRSA -digestalg SHA1 -tsa http://timestamp.digicert.com -keystore ./keystore/Android.keystore -storepass Wangpeiming110 -keypass Wangpeiming110 -signedjar ./tmp.apk ./app/build/outputs/tinkerPatch/release/patch_unsigned.apk android.keystore
```

**Comment by simpleton** [comment]
run `jarsigner -certs -verbose -verify -keystore ./keystore/Android.keystore [apk_path]` will output the below error:
```
[CertPath not validated: Path does not chain with any of the trust anchors]
```

**Comment by shwenzhang** [comment]
fixed by dev

**Comment by shwenzhang** [comment]
try with 1.8.0
