### ISSUE TITLE
can't find TINKER_ID from the new apk manifest file, it must be set!

### ISSUE THREAD

**Issue by gaoxuxu** [Tencent/tinker#57]
项目中配置了

```
splits {
        abi {
            enable true
            reset()
            include 'armeabi','x86'
            universalApk true
        }
    }
```

执行```./gradlew tinkerPatch${flavor}${buildType}```时，会报

```
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,jar
com.tencent.tinker.build.util.TinkerPatchException: can't find TINKER_ID from the new apk manifest file, it must be set!
        at com.tencent.tinker.build.info.PatchInfoGen.addTinkerID(PatchInfoGen.java:58)
        at com.tencent.tinker.build.info.PatchInfoGen.gen(PatchInfoGen.java:65)
        at com.tencent.tinker.build.info.PatchInfo.gen(PatchInfo.java:43)
        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:70)
        at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
        at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
        at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
```

检查```${buildDir}/intermediates/manifests/full```文件夹下的```AndroidManifest.xml```

发现```${flavor}/${buildType}```下的```AndroidManifest.xml```最后是加了```TINKER_ID```的，

而```${flavor}/${abi}/${buildType}```下的```AndroidManifest.xml```中没有添加```TINKER_ID```

检查日志发现，报错时取的apk文件是```${flavor}-armabi-${buildType}.apk```，而实际上如果取```${flavor}-universal-${buildType}.apk```的话应该是没有问题的

**Comment by shwenzhang** [comment]
@gaoxuxu , please try with 1.7.0
