### ISSUE TITLE
Android 7.1.1 Failure to verify dex file

### ISSUE THREAD

**Issue by qingyizeng** [Tencent/tinker#571]
异常类型：app运行时异常

手机型号：MI 3W

手机系统版本：CyanogenMod Android 7.1.1

tinker版本：1.7.11

gradle版本：3.3

是否使用热更新SDK： Bugly SDK

系统: Mac

堆栈/日志：
08-03 13:17:13.636 26498-26498/? D/Tinker.DefaultAppLike: onCreate
08-03 13:17:13.798 26255-26268/com.xxx.buy2 E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'close' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                   at java.util.zip.ZipFile.<init>(ZipFile.java:237)
                                                                   at java.util.zip.ZipFile.<init>(ZipFile.java:148)
                                                                   at java.util.jar.JarFile.<init>(JarFile.java:161)
                                                                   at java.util.jar.JarFile.<init>(JarFile.java:125)
                                                                   at com.tencent.bugly.beta.tinker.TinkerUtils.readJarEntry(BUGLY:304)
                                                                   at com.tencent.bugly.beta.tinker.TinkerManager.checkNewPatch(BUGLY:461)
                                                                   at com.tencent.bugly.beta.tinker.TinkerManager.applyPatch(BUGLY:415)
                                                                   at com.tencent.bugly.beta.tinker.TinkerManager.onDownloadSuccess(BUGLY:390)
                                                                   at com.tencent.bugly.beta.download.a.onCompleted(BUGLY:192)
                                                                   at com.tencent.bugly.beta.global.d.run(BUGLY:263)
                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-03 13:17:13.873 26498-26530/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
08-03 13:17:13.875 26498-26498/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
08-03 13:17:13.880 26498-26530/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker_temp/temp.apk
08-03 13:17:13.881 26498-26530/? W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
08-03 13:17:13.882 26498-26530/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker_temp/temp.apk
08-03 13:17:13.882 26498-26530/? W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
08-03 13:17:13.883 26498-26530/? I/Tinker.TinkerPatchService: try to increase patch process priority
08-03 13:17:13.884 846-874/system_process V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.xxx.buy2/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
08-03 13:17:13.891 846-874/system_process V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.xxx.buy2/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
08-03 13:17:13.920 26498-26530/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:cea929d09e0881f1c949f768aef7fd6b
08-03 13:17:13.921 26498-26530/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.xxx.buy2/tinker/patch.info (No such file or directory)
08-03 13:17:13.922 26498-26530/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.xxx.buy2/tinker/patch.info (No such file or directory)
08-03 13:17:13.922 26498-26530/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.xxx.buy2/tinker/patch-cea929d0
08-03 13:17:13.927 26498-26530/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.xxx.buy2/app_tmpPatch/tmpPatch.apk size: 113037, dest file: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/patch-cea929d0.apk size:113037
08-03 13:17:27.241 26498-26530/com.xxx.buy2:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes.dex.jar, size: 3633059, use time: 13312
08-03 13:17:32.721 26498-26530/com.xxx.buy2:patch W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes2.dex.jar, size: 3087910, use time: 5479
08-03 13:17:32.721 26498-26530/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/test.dex.jar
08-03 13:17:32.723 26498-26530/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
08-03 13:17:32.724 26498-26530/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:3, optimizeDexDirectory:/data/user/0/com.xxx.buy2/tinker/patch-cea929d0/odex/
08-03 13:17:32.727 26498-26611/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes.dex.jar, size: 3633059
08-03 13:17:32.733 26498-26612/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes2.dex.jar, size: 3087910
08-03 13:17:33.867 26498-26611/com.xxx.buy2:patch E/Tinker.ParallelDex: Failed to optimize dex: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes.dex.jar
                                                                             java.io.IOException: Failed to open dex files from /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes.dex.jar because: Failure to verify dex file '/data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes.dex.jar': Found virtual method with same index as direct method: 31834
                                                                                 at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                 at dalvik.system.DexFile.openDexFile(DexFile.java:367)
                                                                                 at dalvik.system.DexFile.<init>(DexFile.java:148)
                                                                                 at dalvik.system.DexFile.loadDex(DexFile.java:219)
                                                                                 at dalvik.system.DexFile.loadDex(DexFile.java:187)
                                                                                 at com.tencent.tinker.loader.TinkerParallelDexOptimizer$OptimizeWorker.run(BUGLY:152)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                 at java.lang.Thread.run(Thread.java:761)
08-03 13:17:33.868 26498-26611/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: fail to parallel optimize dex /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes.dex.jar use time 1135
08-03 13:17:33.868 26498-26611/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/test.dex.jar, size: 470
08-03 13:17:33.972 26498-26611/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/test.dex.jar, opt file size: 20904, use time 104
08-03 13:17:42.245 26498-26612/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes2.dex.jar, opt file size: 22716840, use time 8377
08-03 13:17:42.245 26498-26530/com.xxx.buy2:patch E/Tinker.ParallelDex: Dexes optimizing failed, some dexes are not optimized.
08-03 13:17:42.246 26498-26530/com.xxx.buy2:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchDexOptFail: dex opt fail path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/patch-cea929d0.apk, dex size: 1
08-03 13:17:42.247 26498-26530/com.xxx.buy2:patch E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  java.io.IOException: Failed to open dex files from /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes.dex.jar because: Failure to verify dex file '/data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes.dex.jar': Found virtual method with same index as direct method: 31834
                                                                                          at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                                          at dalvik.system.DexFile.openDexFile(DexFile.java:367)
                                                                                          at dalvik.system.DexFile.<init>(DexFile.java:148)
                                                                                          at dalvik.system.DexFile.loadDex(DexFile.java:219)
                                                                                          at dalvik.system.DexFile.loadDex(DexFile.java:187)
                                                                                          at com.tencent.tinker.loader.TinkerParallelDexOptimizer$OptimizeWorker.run(BUGLY:152)
                                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                          at java.lang.Thread.run(Thread.java:761)
08-03 13:17:42.249 26498-26530/com.xxx.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/patch-cea929d0.apk
08-03 13:17:42.250 26498-26530/com.xxx.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes.dex.jar
08-03 13:17:42.253 26498-26530/com.xxx.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/classes2.dex.jar
08-03 13:17:42.255 26498-26530/com.xxx.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex/test.dex.jar
08-03 13:17:42.255 26498-26530/com.xxx.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/dex
08-03 13:17:42.256 26498-26530/com.xxx.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/odex/test.dex.dex
08-03 13:17:42.256 26498-26530/com.xxx.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/odex/classes2.dex.dex
08-03 13:17:42.256 26498-26530/com.xxx.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0/odex
08-03 13:17:42.256 26498-26530/com.xxx.buy2:patch I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.xxx.buy2/tinker/patch-cea929d0
08-03 13:17:42.257 26498-26530/com.xxx.buy2:patch I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:28330
08-03 13:17:42.257 26498-26530/com.xxx.buy2:patch E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
08-03 13:17:42.257 26498-26530/com.xxx.buy2:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /data/user/0/com.xxx.buy2/app_tmpPatch/tmpPatch.apk, success: false, cost: 28374
08-03 13:17:42.280 26255-26659/com.xxx.buy2 I/Tinker.TinkerResultService: TinkerResultService receive result: 
                                                                               PatchResult: 
                                                                               isSuccess:false
                                                                               rawPatchFilePath:/data/user/0/com.xxx.buy2/app_tmpPatch/tmpPatch.apk
                                                                               costTime:28374
08-03 13:17:42.282 26255-26255/com.xxx.buy2 I/CrashReport: Tinker patch failure, result: 
                                                                PatchResult: 
                                                                isSuccess:false
                                                                rawPatchFilePath:/data/user/0/com.xxx.buy2/app_tmpPatch/tmpPatch.apk
                                                                costTime:28374

**Comment by tomystang** [comment]
@qingyizeng 
你好，方便把旧apk、新apk和补丁包发到我的邮箱tys1b0037f@qq.com吗？我看下是不是patch结果错了。
