### ISSUE TITLE
热更新，合成失败，

### ISSUE THREAD

**Issue by AnselHall** [Tencent/tinker#578]
使用的bugly集成的热更，

异常类型：app运行时异常

手机型号：努比亚 NX511J  真机

手机系统版本：Android 5.0.2,level 21

Bugly version: v2.4.0

tinker版本：1.7.11

gradle版本：2.14.1

是否使用热更新SDK： Bugly SDK

系统：Mac

堆栈/日志：
08-15 10:32:22.750 23558-23586/? E/Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:can't recognize dex mode:1266457422,jar
                                                                    at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.<init>(Unknown Source)
                                                                    at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.c.d.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.c.d.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.c.d.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.c.f.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(Unknown Source)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by AnselHall** [comment]
Bugly 异常的log
08-15 10:55:51.890 26151-26151/? I/CrashReport: Tinker patch failure, result: 
                                                PatchResult: 
                                                isSuccess:false
                                                rawPatchFilePath:/data/data/com.ansel.tinkerdemo/app_tmpPatch/tmpPatch.apk
                                                costTime:64
                                                Throwable:Tinker Exception:can't recognize dex mode:1266457422,jar

**Comment by dahutiger** [comment]
@AnselHall 我们也遇到类似的问题，请问这个问题你们怎么解决的？求教！
https://github.com/Tencent/tinker/issues/673
