### ISSUE TITLE
tinker load exception

### ISSUE THREAD

**Issue by zzdxwangdong** [Tencent/tinker#592]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：cool-pad A8

手机系统版本：5.1.1

tinker版本：如:1.7.7

gradle版本：如:2.10

是否使用热更新SDK： 如 TinkerPatch SDK 或者 Bugly SDK

09-01 17:37:28.266 9986-9986/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
09-01 17:37:28.266 9986-9986/? E/Tinker.DefaultLoadReporter: tinker load exception  java.lang.reflect.InvocationTargetException
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(SourceFile:171)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:135)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:156)
                                                                 at android.app.Application.attach(Application.java:181)
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:997)
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:981)
                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665)
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:155)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5446)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:736)
                                                              Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:ShareSecurityCheck file /data/data/com.busap.myvideo/tinker/patch-4d3807ef/patch-4d3807ef.apk, size 98304 verifyPatchMetaSignature fail
                                                                 at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(SourceFile:139)
                                                                 at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(SourceFile:106)
                                                                 at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(SourceFile:91)
                                                                 at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(SourceFile:160)
                                                                 at com.tencent.tinker.loader.TinkerLoader.tryLoad(SourceFile:56)
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(SourceFile:171) 
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:135) 
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:156) 
                                                                 at android.app.Application.attach(Application.java:181) 
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:997) 
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:981) 
                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:573) 
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665) 
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5446) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:736) 
                                                              Caused by: java.util.zip.ZipException: End Of Central Directory signature not found
                                                                 at java.util.zip.ZipFile.readCentralDir(ZipFile.java:401)
                                                                 at java.util.zip.ZipFile.<init>(ZipFile.java:163)
                                                                 at java.util.jar.JarFile.<init>(JarFile.java:199)
                                                                 at java.util.jar.JarFile.<init>(JarFile.java:182)
                                                                 at java.util.jar.JarFile.<init>(JarFile.java:168)
                                                                 at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.verifyPatchMetaSignature(SourceFile:110)
                                                                 at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkSignatureAndTinkerID(SourceFile:106) 
                                                                 at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.checkTinkerPackage(SourceFile:91) 
                                                                 at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(SourceFile:160) 
                                                                 at com.tencent.tinker.loader.TinkerLoader.tryLoad(SourceFile:56) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(SourceFile:171) 
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:135) 
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:156) 
                                                                 at android.app.Application.attach(Application.java:181) 
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:997) 
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:981) 
                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:573) 
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665) 
                                                                 at android.app.ActivityThread.access$1500(ActivityThread.java:155) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5446) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:736)

**Comment by shwenzhang** [comment]
补丁包没有签名
