### ISSUE TITLE
Tinker patch的时候报错

### ISSUE THREAD

**Issue by BlackHumor** [Tencent/tinker#593]
异常类型：app运行时异常

手机型号：如:小米 Note2

手机系统版本：如:Android 6.0

tinker版本：如:1.7.11  Bugly_upgrade:1.3.1

gradle版本：Android Gradle Plugin 2.3.3

是否使用热更新SDK： Bugly SDK

系统：如:Windows 10

堆栈/日志：
09-02 18:16:31.277 8482-8482/? D/Tinker.TinkerManager: onDownloadSuccess.
09-02 18:16:31.277 8482-8482/? D/Tinker.TinkerManager: check if has new patch.
09-02 18:16:31.277 8482-8482/? D/Tinker.TinkerManager: has new patch.
09-02 18:16:31.287 8482-8482/? D/Tinker.TinkerManager: starting patch.
09-02 18:16:31.287 8482-8482/? I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/com.隐藏起来.隐藏起来/app_tmpPatch/tmpPatch.apk, file size:63573
09-02 18:16:31.287 8482-8482/? I/Tinker.TinkerPatchListener: get platform:null
09-02 18:16:31.297 1234-2537/? I/ActivityManager: bindServiceLocked, r: ServiceRecord{c1aadeb u0 euid: 0 com.隐藏起来.隐藏起来/com.tencent.tinker.lib.service.TinkerPatchService}, euid: 0
09-02 18:16:31.297 1234-2537/? I/ActivityManager: mAm.startProcessLocked for service: ServiceRecord{c1aadeb u0 euid: 0 com.隐藏起来.隐藏起来/com.tencent.tinker.lib.service.TinkerPatchService}, appinfo euid: 0
09-02 18:16:31.307 1234-2537/? I/ActivityManager: Start proc 8651:com.隐藏起来.隐藏起来:patch/u0a484 for service com.隐藏起来.隐藏起来/com.tencent.tinker.lib.service.TinkerPatchService
09-02 18:16:31.377 8651-8651/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
09-02 18:16:31.377 8651-8651/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-02 18:16:31.397 8651-8651/? I/Tinker.TinkerPatchListener: application maxMemory:192
09-02 18:16:31.397 8651-8651/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.隐藏起来.隐藏起来/tinker
09-02 18:16:31.397 8651-8651/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
09-02 18:16:31.397 8651-8651/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.隐藏起来.隐藏起来:patch, main process:false, systemOTA:false, oatDir:null, useInterpretMode:false
09-02 18:16:31.397 8651-8651/? W/Tinker.TinkerLoadResult: tinker is disable, just return
09-02 18:16:31.397 8651-8651/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.隐藏起来.隐藏起来/tinker, code: -1, cost: 6ms
09-02 18:16:31.397 8651-8651/? W/Tinker.Tinker: tinker load fail!
09-02 18:16:31.397 8651-8651/? D/Tinker.DefaultAppLike: onCreate
09-02 18:16:31.437 8651-8651/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@c9204ed
09-02 18:16:32.247 8651-8801/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
09-02 18:16:32.257 8651-8801/? W/Tinker.UpgradePatchRetry: try copy file: /data/user/0/com.隐藏起来.隐藏起来/app_tmpPatch/tmpPatch.apk to /data/user/0/com.隐藏起来.隐藏起来/tinker_temp/temp.apk
09-02 18:16:32.267 8651-8801/? I/Tinker.TinkerPatchService: try to increase patch process priority
09-02 18:16:32.277 1234-1257/? I/ActivityManager: bindServiceLocked, r: ServiceRecord{b606e24 u0 euid: 0 com.隐藏起来.隐藏起来/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}, euid: 0
09-02 18:16:32.317 8651-8801/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:abf99f74698fbbdf8ddd581806635f65
09-02 18:16:32.317 8651-8801/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.隐藏起来.隐藏起来/tinker/patch.info: open failed: ENOENT (No such file or directory)
09-02 18:16:32.317 8651-8801/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.隐藏起来.隐藏起来/tinker/patch.info: open failed: ENOENT (No such file or directory)
09-02 18:16:32.317 8651-8801/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.隐藏起来.隐藏起来/tinker/patch-abf99f74
09-02 18:16:32.317 8651-8801/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.隐藏起来.隐藏起来/app_tmpPatch/tmpPatch.apk size: 63573, dest file: /data/user/0/com.隐藏起来.隐藏起来/tinker/patch-abf99f74/patch-abf99f74.apk size:63573
09-02 18:16:37.347 8651-8651/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder
09-02 18:16:37.347 8651-8651/? W/Tinker.TinkerUncaughtExceptionHandler: tinker is not loaded
09-02 18:16:37.347 8651-8651/? E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.ClassCastException: android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder
                                                             at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:111)
                                                             at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1310)
                                                             at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1327)
                                                             at android.os.Handler.handleCallback(Handler.java:743)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:150)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
09-02 18:16:37.477 1234-2744/? W/ActivityManager: Scheduling restart of crashed service com.隐藏起来.隐藏起来/com.tencent.tinker.lib.service.TinkerPatchService in 1000ms
09-02 18:16:37.477 1234-2744/? W/ActivityManager: Scheduling restart of crashed service com.隐藏起来.隐藏起来/com.tencent.tinker.lib.service.TinkerPatchService$InnerService in 10400ms
09-02 18:16:37.497 8482-8482/? D/Tinker.DefaultAppLike: onTrimMemory level:5
09-02 18:16:47.877 1234-1297/? I/ActivityManager: bindServiceLocked, r: ServiceRecord{b606e24 u0 euid: 0 com.隐藏起来.隐藏起来/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}, euid: 0
09-02 18:16:47.877 1234-1297/? I/ActivityManager: mAm.startProcessLocked for service: ServiceRecord{b606e24 u0 euid: 0 com.隐藏起来.隐藏起来/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}, appinfo euid: 0
09-02 18:16:47.897 1234-1297/? I/ActivityManager: Start proc 9017:com.隐藏起来.隐藏起来:patch/u0a484 for service com.隐藏起来.隐藏起来/com.tencent.tinker.lib.service.TinkerPatchService$InnerService
09-02 18:16:47.987 9017-9017/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
09-02 18:16:47.987 9017-9017/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-02 18:16:47.997 9017-9017/? I/Tinker.TinkerPatchListener: application maxMemory:192
09-02 18:16:48.007 9017-9017/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.隐藏起来.隐藏起来/tinker
09-02 18:16:48.007 9017-9017/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
09-02 18:16:48.007 9017-9017/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.隐藏起来.隐藏起来:patch, main process:false, systemOTA:false, oatDir:null, useInterpretMode:false
09-02 18:16:48.007 9017-9017/? W/Tinker.TinkerLoadResult: tinker is disable, just return
09-02 18:16:48.007 9017-9017/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.隐藏起来.隐藏起来/tinker, code: -1, cost: 7ms
09-02 18:16:48.007 9017-9017/? W/Tinker.Tinker: tinker load fail!
09-02 18:16:48.007 9017-9017/? D/Tinker.DefaultAppLike: onCreate
09-02 18:16:48.107 9017-9017/? I/CrashReport: backup java handler: com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler@5a4f4d2
09-02 18:16:49.057 9017-9017/? D/Tinker.DefaultAppLike: onTrimMemory level:5
09-02 18:16:54.337 9017-9017/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder
09-02 18:16:54.337 9017-9017/? W/Tinker.TinkerUncaughtExceptionHandler: tinker is not loaded
09-02 18:16:54.337 9017-9017/? E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.ClassCastException: android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder
                                                             at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:111)
                                                             at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1310)
                                                             at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1327)
                                                             at android.os.Handler.handleCallback(Handler.java:743)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:150)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by shwenzhang** [comment]
具体先联系一下bugly的人员吧，非官方版tinker我们一些细节也不太清楚他们怎么处理的

09-02 18:16:37.347 8651-8651/? E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.ClassCastException: android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder
at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:111)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1310)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1327)

**Comment by pan-haos** [comment]
有具体的原因嘛，实际上DefaultApplicationlike的子类还没有调用就进入application的生命周期了，是因为androidN以上用了AndroidNClassloader去加载其余类的原因么

**Comment by lurongshuang** [comment]
麻烦问一下 怎么解决了呢
