### ISSUE TITLE
multiDexKeepProguard 

### ISSUE THREAD

**Issue by goodWiner** [Tencent/tinker#596]
异常类型：app运行时异常

手机型号：华为6

手机系统版本：Android 7.0 

tinker版本：1.7.5

gradle版本：2.3.3

系统：windows

堆栈/日志：
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lefthand.application.ZSApplication" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.lefthand.zhand-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.lefthand.zhand-1, /vendor/lib, /system/lib, /data/datalib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:976)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:532)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4587) 
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5315) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                       at dalvik.system.NativeStart.main(Native Method) 

已经使用Tinker一段时间了，突然间报错，配置一直没有改过。
我们设置了multiDexKeepProguard file("keep_in_main_dex.pro")和正确的loader。但是发现build生成的mainfest_keep.txt中并没有自己keep的内容，而components.flags中有keep的内容。

**Comment by shwenzhang** [comment]
升级tinker版本
