### ISSUE TITLE
一加A5000机型补丁后运行出现ClassCastException

### ISSUE THREAD

**Issue by hqzxzwb** [Tencent/tinker#597]
异常类型：app运行时异常

手机型号：ONEPLUS A5000
手机系统版本：Android 7.1.1

tinker版本：1.7.11

gradle版本：3.3

是否使用热更新SDK： 未使用

系统：Mac

堆栈/日志：
java.lang.ClassCastException: fm.qingting.qtradio.ad.dynamic.SimpleVideoView cannot be cast to fm.qingting.qtradio.ad.dynamic.SimpleVideoView
	at fm.qingting.qtradio.ad.dynamic.VideoAdActivity.onCreate(VideoAdActivity.java)
	at android.app.Activity.performCreate(Activity.java:6743)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2715)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2848)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6334)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

可以看到cast目标类和对象类型其实是相同的，猜测是原始类与补丁中的类均被加载了。
仅ONEPLUS A5000，安卓7.1.1会出现该问题，其他机型与系统版本没有收集到这个错误。

**Comment by nEdAy** [comment]
mark

**Comment by sunshinehu** [comment]
同出现该问题，仅7.1.1，关注中

**Comment by shwenzhang** [comment]
cast问题在7.0以上都有可能遇到，需要排除
1. 是否在tinker替换classloader之前有去加载其他的类
2. 是否使用了原来Application的classloader去加载这些类
3. 是否由于某些系统的缓存机制

**Comment by hqzxzwb** [comment]
我想这里你讲“原来Application”指的是TinkerApplication的子类？集成时特别留意了这些问题，直接从代码来看不可能是1或2的情况。不知有没有其他推荐的验证方式？另，统计上只有这一个机型出现问题，不符合1或者2的特征。

**Comment by shwenzhang** [comment]
这个问题是一加部分手机做了缓存view的操作，已经通知他们修改实现的方式

**Comment by deathfish** [comment]
一加 8.x ～ 10.x 机型依然会报这个错误

**Comment by a694320253** [comment]
华为也遇到这个问题
