### ISSUE TITLE
加载完补丁包，重启后findViewById返回null

### ISSUE THREAD

**Issue by zmylls** [Tencent/tinker#598]
异常类型：app运行时异常

手机型号：荣耀9 ；乐视Lex 620；

手机系统版本：Android 7.0+ ；Android6.0

tinker版本：1.8.1

gradle版本：3.3

系统：如:Mac

堆栈/日志：

打补丁时修改过一些java文件和布局文件，修改的内容比较零散，但未添加图片，组件等内容。
补丁加载成功，SampleResultServie中的PatchResult返回成功状态。
退出重启应用，出现崩溃，findViewById 查找控件，返回空，但控件已经正常设置。
日志如下：

 Attempt to invoke virtual method 'void android.view.ViewGroup.setBackgroundColor(int)' on a null object reference
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                      at android.os.Looper.loop(Looper.java:156)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6577)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setBackgroundColor(int)' on a null object reference
                                                                      at com.jianbao.doctor.activity.page.HomePage.initUI(HomePage.java:296)
                                                                      at com.jianbao.doctor.activity.page.TabPageView.<init>(TabPageView.java:20)
                                                                      at com.jianbao.doctor.activity.page.HomePage.<init>(HomePage.java:245)
                                                                      at com.jianbao.doctor.activity.MainActivity.switchTabPage(MainActivity.java:323)
                                                                      at com.jianbao.doctor.activity.MainActivity.initState(MainActivity.java:190)
                                                                      at com.appbase.BaseActivity.setContentView(BaseActivity.java:112)
                                                                      at com.jianbao.doctor.activity.MainActivity.onCreate(Native Method)
                                                                      at android.app.Activity.performCreate(Activity.java:6910)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
                                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                      at android.os.Looper.loop(Looper.java:156) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6577) 
                                                                      at java.lang.reflect.Method.invoke(Native Method)

**Comment by nEdAy** [comment]
mark

**Comment by shwenzhang** [comment]
详细的patch，加载跟crash前后文日志

**Comment by HangmanFu** [comment]
在覆盖安装老版本apk时，多个机型遇到相同问题， mark

**Comment by beyondxia** [comment]
同样的问题，覆盖安装后出现，清理缓存可以解决

**Comment by hqzxzwb** [comment]
@beyondxia 是指清理app的缓存文件夹吗？最近正打算升级到1.8.1，如果这样可行的话，我就加上在patch完成后清理一下缓存的逻辑。

**Comment by shwenzhang** [comment]
覆盖安装会出现问题，是否是因为tinker id在版本升级时没有更新

**Comment by zmylls** [comment]
这个问题之前碰到的，相关crash和patch都没有保存到，请有相同问题同学，帮我上传一下你所遇到的详细crash和patch

**Comment by beyondxia** [comment]
@shwenzhang 不是清理app缓存，是清理掉tinker和tinker_temp文件夹
