### ISSUE TITLE
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by jsoncoco** [Tencent/tinker#599]
异常类型：app运行时异常

手机型号：小米3报错，小米4没有问题

手机系统版本：系统4.4.4报错，系统6.0.1没有问题,7.0系统也没有问题

tinker版本：1.8.1

gradle版本：3.3

热更新SDK：TinkerPatch SDK

系统：windows

堆栈/日志：
1. java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                     at com.snooker.activity.SNKApplication.onCreate(SNKApplication.java:44)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4359)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:136)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5032)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

我自己的SNKApplication继承SampleApplication，

SampleApplication为@DefaultLifeCycle(application = "tinker.sample.android.app.SampleApplication",  flags = ShareConstants.TINKER_ENABLE_ALL)
public class SNKApplicationLike extends DefaultApplicationLike {
}构建出来的，

Build.gradle的设置为
 dex {
            dexMode = "jar"
            pattern = ["classes*.dex", "assets/secondary-dex-?.jar"]
            loader = [
                    "tinker.sample.android.app.BaseBuildInfo",
                    "com.snooker.activity.SNKApplication",
                    "com.tencent.tinker.loader.*" 
                        ]
        }
        lib {
            pattern = ["lib/armeabi/*.so"]
        }
｝
报的错误是在Runnable这一行，是补丁合成成功，重新启动是报错，基本包没有问题，是补丁后的包出现问题，下面是application的onCreate方法。
 @Override
    public void onCreate() {
        super.onCreate();
        final Context context = this;
        new Runnable() {
            @Override
            public void run() {
                //初始化DbFlow
                initDbFlow();
                //初始化EventBus
                initEventBus();
                ///初始化百度和友盟统计
                initStatistics();
                //初始化ShareSdk
                initShareSDK();
                //设置ButterKnife是否显示日志
                ButterKnife.setDebug(Url.isDebug);
                //初始化环信
                ImHelper.getInstance().init(context);
                //初始化文件系统
                initFile();
                //初始化城市数据
                initCityData(context);
            }
        }.run();
    }

**Comment by jsoncoco** [comment]
SNKApplication中没有重写构造函数

**Comment by jsoncoco** [comment]
以解决

**Comment by jsoncoco** [comment]
已解决！！！

**Comment by mhlistener** [comment]
@jsoncoco 请问下你是怎么解决这个问题的

**Comment by xw8852** [comment]
@mhlistener  非常抱歉，我都忘记了....
