### ISSUE TITLE
在打Release包isProtectedApp = true的时候，热更新失败

### ISSUE THREAD

**Issue by tmexcept** [Tencent/tinker#601]
在打Release包的时候，isProtectedApp = false的时候，能够正常运行，并热更新成功
isProtectedApp = true的时候，热更新失败
```
异常类型：app运行时异常

手机型号：vivo X5Pro D

手机系统版本：Android 5.0

tinker版本：1.8.0

gradle版本：如:2.3.3

是否使用热更新SDK： 否

系统：windows10

堆栈/日志：

09-13 16:02:25.441 24358-24358/? D/Tinker.DefaultAppLike: onCreate
09-13 16:02:25.778 24358-24358/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
09-13 16:06:14.798 24358-24358/? D/Tinker.DefaultAppLike: onTrimMemory level:20
09-13 16:06:25.261 24358-24358/? I/Tinker.SamplePatchListener: receive a patch file: /storage/sdcard0/patch_signed.apk, file size:5968
09-13 16:06:25.264 24358-24358/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
09-13 16:06:25.266 24358-24358/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
09-13 16:06:25.268 24358-24358/? I/Tinker.SamplePatchListener: get platform:all
09-13 16:06:25.271 732-1434/? D/ActivityManager: app: com.tinker.app:patch, app uid: 10179, user 0, intent ComponentInfo{com.tinker.app/com.tencent.tinker.lib.service.TinkerPatchService}, calling uid 10178, mCallerApp ProcessRecord{36d7a35c 24358:com.tinker.app/u0a179}
09-13 16:06:25.292 732-1434/? I/ActivityManager: Start proc com.tinker.app:patch for service com.tinker.app/com.tencent.tinker.lib.service.TinkerPatchService: pid=24557 uid=10179 gids={50179, 9997, 1028, 1015} abi=arm64-v8a
09-13 16:06:25.342 24557-24557/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
09-13 16:06:25.344 24557-24557/? D/Tinker.DefaultAppLike: onBaseContextAttached:
09-13 16:06:25.348 24557-24557/? I/Tinker.SamplePatchListener: application maxMemory:256
09-13 16:06:25.350 24557-24557/? W/Tinker.Tinker: tinker patch directory: /data/data/com.tinker.app/tinker
09-13 16:06:25.352 24557-24557/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.0
09-13 16:06:25.353 24557-24557/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.tinker.app:patch, main process:false, systemOTA:false, fingerPrint:vivo/bbk6752_lwt_l/bbk6752_lwt_l:5.0/LRX21M/1461052371:user/release-keys, oatDir:null, useInterpretMode:false
09-13 16:06:25.354 24557-24557/? W/Tinker.TinkerLoadResult: tinker is disable, just return
09-13 16:06:25.354 24557-24557/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/data/com.tinker.app/tinker, code: -1, cost: 3ms
09-13 16:06:25.354 24557-24557/? W/Tinker.Tinker: tinker load fail!
09-13 16:06:25.357 24557-24557/? D/Tinker.DefaultAppLike: onCreate
09-13 16:06:25.358 24557-24557/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@342cc5f1 className=com.tencent.tinker.lib.service.TinkerPatchService packageName=com.tinker.app intent=null}
09-13 16:06:25.359 24557-24557/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@342cc5f1 className=com.tencent.tinker.lib.service.TinkerPatchService packageName=com.tinker.app intent=null}
09-13 16:06:25.359 24557-24557/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService@24c5e5d6, flags=0, startId=1
09-13 16:06:25.359 24557-24557/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@342cc5f1 startId=1 args=Intent { cmp=com.tinker.app/com.tencent.tinker.lib.service.TinkerPatchService (has extras) }}
09-13 16:06:25.359 24557-24557/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
09-13 16:06:25.359 24557-24578/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
09-13 16:06:25.365 24557-24578/? W/Tinker.UpgradePatchRetry: try copy file: /storage/sdcard0/patch_signed.apk to /data/data/com.tinker.app/tinker_temp/temp.apk
09-13 16:06:25.382 24557-24578/? I/Tinker.TinkerPatchService: try to increase patch process priority
09-13 16:06:25.391 24557-24557/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@3536d02d className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=com.tinker.app intent=null}
09-13 16:06:25.397 24557-24557/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@3536d02d className=com.tencent.tinker.lib.service.TinkerPatchService$InnerService packageName=com.tinker.app intent=null}
09-13 16:06:25.397 24557-24557/? D/ActivityThread: SVC-Calling onStartCommand: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@b928962, flags=0, startId=1
09-13 16:06:25.397 24557-24557/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@3536d02d startId=1 args=Intent { cmp=com.tinker.app/com.tencent.tinker.lib.service.TinkerPatchService$InnerService }}
09-13 16:06:25.397 24557-24557/? D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService$InnerService@b928962
09-13 16:06:25.412 24557-24578/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:21e43dfd5735c5c277e2bc11fb4e85c9
09-13 16:06:25.415 24557-24578/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/data/com.tinker.app/tinker/patch.info: open failed: ENOENT (No such file or directory)
09-13 16:06:25.415 24557-24578/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/data/com.tinker.app/tinker/patch.info: open failed: ENOENT (No such file or directory)
09-13 16:06:25.416 24557-24578/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/data/com.tinker.app/tinker/patch-21e43dfd
09-13 16:06:25.419 24557-24578/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/sdcard0/patch_signed.apk size: 5968, dest file: /data/data/com.tinker.app/tinker/patch-21e43dfd/patch-21e43dfd.apk size:5968
09-13 16:06:25.429 24557-24578/? I/Tinker.DexDiffPatchInternal: try Extracting /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/changed_classes.dex.jar
09-13 16:06:25.434 24557-24578/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
09-13 16:06:25.434 24557-24578/? I/Tinker.DexDiffPatchInternal: try Extracting /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/test.dex.jar
09-13 16:06:25.437 24557-24578/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
09-13 16:06:25.448 24557-24578/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/test.dex.jar
09-13 16:06:25.448 24557-24578/? I/Tinker.DexDiffPatchInternal: merge classN dex file /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/tinker_classN.apk, result: true, size: 472, use: 11ms
09-13 16:06:25.450 24557-24578/? I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:2, optimizeDexDirectory:/data/data/com.tinker.app/tinker/patch-21e43dfd/odex/
09-13 16:06:25.452 24557-24578/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/changed_classes.dex.jar, size: 1553
09-13 16:06:25.520 24557-24578/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/changed_classes.dex.jar, opt file:/data/data/com.tinker.app/tinker/patch-21e43dfd/odex/changed_classes.dex.dex, opt file size: 12720, use time 69
09-13 16:06:25.520 24557-24578/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/tinker_classN.apk, size: 472
09-13 16:06:25.521 24557-24578/? E/Tinker.ParallelDex: Failed to optimize dex: /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/tinker_classN.apk
                                                       java.io.IOException: Zip archive '/data/data/com.tinker.app/tinker/patch-21e43dfd/dex/tinker_classN.apk' doesn't contain classes.dex (error msg: Entry not found)
                                                           at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                           at dalvik.system.DexFile.openDexFile(DexFile.java:295)
                                                           at dalvik.system.DexFile.<init>(DexFile.java:111)
                                                           at dalvik.system.DexFile.loadDex(DexFile.java:151)
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125)
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76)
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53)
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322)
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182)
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85)
                                                           at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136)
                                                           at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                           at android.os.Looper.loop(Looper.java:194)
                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
09-13 16:06:25.522 24557-24578/? I/Tinker.DexDiffPatchInternal: fail to parallel optimize dex /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/tinker_classN.apk use time 2
09-13 16:06:25.522 24557-24578/? I/Tinker.DefaultPatchReporter: patchReporter onPatchDexOptFail: dex opt fail path: /data/data/com.tinker.app/tinker/patch-21e43dfd/patch-21e43dfd.apk, dex size: 1
09-13 16:06:25.522 24557-24578/? E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  java.io.IOException: Zip archive '/data/data/com.tinker.app/tinker/patch-21e43dfd/dex/tinker_classN.apk' doesn't contain classes.dex (error msg: Entry not found)
                                                                    at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                    at dalvik.system.DexFile.openDexFile(DexFile.java:295)
                                                                    at dalvik.system.DexFile.<init>(DexFile.java:111)
                                                                    at dalvik.system.DexFile.loadDex(DexFile.java:151)
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125)
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76)
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85)
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
09-13 16:06:25.523 24557-24578/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tinker.app/tinker/patch-21e43dfd/patch-21e43dfd.apk
09-13 16:06:25.524 24557-24578/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/changed_classes.dex.jar
09-13 16:06:25.524 24557-24578/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tinker.app/tinker/patch-21e43dfd/dex/tinker_classN.apk
09-13 16:06:25.524 24557-24578/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tinker.app/tinker/patch-21e43dfd/dex
09-13 16:06:25.524 24557-24578/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tinker.app/tinker/patch-21e43dfd/odex/changed_classes.dex.dex
09-13 16:06:25.524 24557-24578/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tinker.app/tinker/patch-21e43dfd/odex
09-13 16:06:25.524 24557-24578/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tinker.app/tinker/patch-21e43dfd
09-13 16:06:25.525 24557-24578/? I/Tinker.DexDiffPatchInternal: recover dex result:false, cost:104
09-13 16:06:25.525 24557-24578/? E/Tinker.UpgradePatch: UpgradePatch tryPatch:new patch recover, try patch dex failed
09-13 16:06:25.525 24557-24578/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/sdcard0/patch_signed.apk, success: false, cost: 143
09-13 16:06:25.525 24557-24578/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/data/com.tinker.app/tinker_temp/temp.apk
09-13 16:06:25.538 24557-24557/? D/ActivityThread: SVC-Destroying service: com.tencent.tinker.lib.service.TinkerPatchService@24c5e5d6
09-13 16:06:25.541 24358-24590/? I/Tinker.SampleResultService: SampleResultService receive result: 
                                                               PatchResult: 
                                                               isSuccess:false
                                                               rawPatchFilePath:/storage/sdcard0/patch_signed.apk
                                                               costTime:143
                                                               patchVersion:21e43dfd5735c5c277e2bc11fb4e85c9

**Comment by tmexcept** [comment]
1.8.0版本加固有问题，1.8.1的可以了[#577](https://github.com/Tencent/tinker/issues/577)

**Comment by tmexcept** [comment]
版本修改为1.8.1之后，打Release包之后可以正常热更新，但是使用爱加密加固签名之后tinker的log日志看不到了，而且也没有热更新成功

**Comment by tmexcept** [comment]
1.8.1版本加固是没问题的，1.8版本有问题[577](https://github.com/Tencent/tinker/issues/577)
