### ISSUE TITLE
tinker patch在华为的多款机型上找不到资源

### ISSUE THREAD

**Issue by hamberluo** [Tencent/tinker#603]
```
Fatal Exception: android.content.res.Resources$NotFoundException: failed to add asset path /data/user/0/com.xxx/tinker/patch-475b71f4/res/resources.apk
       at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:275)
       at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:332)
       at android.app.ResourcesManager.getOrCreateResources(ResourcesManager.java:612)
       at android.app.ResourcesManager.getResources(ResourcesManager.java:690)
       at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1989)
       at android.app.ActivityThreadUtils.getTopLevelResources(ActivityThreadUtils.java:24)
       at huawei.android.hwtheme.HwThemeManagerImpl.updateHwtResource(HwThemeManagerImpl.java:491)
       at android.hwtheme.HwThemeManager.updateHwtResource(HwThemeManager.java:311)
       at android.app.LoadedApk.getResources(LoadedApk.java:803)
       at android.view.Display.getRealSize(Display.java:889)
       at android.view.HwViewRootImpl.getDisplayPoint(HwViewRootImpl.java:106)
       at android.view.HwViewRootImpl.filterDecorPointerEvent(HwViewRootImpl.java:80)
       at android.view.ViewRootImpl$EarlyPostImeInputStage.processPointerEvent(ViewRootImpl.java:4649)
       at android.view.ViewRootImpl$EarlyPostImeInputStage.onProcess(ViewRootImpl.java:4608)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6676)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6650)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6611)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6803)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:346)
       at android.os.Looper.loop(Looper.java:138)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by shwenzhang** [comment]
机型？tinker的版本？请按格式提交issue

**Comment by hamberluo** [comment]
tinker版本 1.8.1 机型是华为多款主流机型

**Comment by shwenzhang** [comment]
问题是否还存在，请按格式重新提交issue
