### ISSUE TITLE
使用爱加密之后热更新失败

### ISSUE THREAD

**Issue by yyzheng123** [Tencent/tinker#609]
异常类型：app运行时异常/编译异常

手机型号：华为PLK-AL 10C00B220

手机系统版本：Android 5.0.2

tinker版本：如:1.8.0

gradle版本：gradle-4.0-milestone-1-all.zip

系统：windows 

操作过程：
一.
    不使用加密方式的情况下 release包热更新正常。

二.
     1.将isProtectedApp = true，打release包，生成base_release.apk
     2.加密base_release包，签名。
     3.修改代码
     4.打差异包（基于base_release）生成patch_signed_7zip.apk
     5.执行热修复代码（失败）

09-18 17:40:36.758 29794-29937/? E/Tinker.ParallelDex: Failed to optimize dex: /data/data/com.xxx.driver/tinker/patch-7331fa3c/dex/tinker_classN.apk
                                                       java.io.IOException: Zip archive '/data/data/com.xxx.driver/tinker/patch-7331fa3c/dex/tinker_classN.apk' doesn't contain classes.dex (error msg: Entry not found)
                                                           at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                           at dalvik.system.DexFile.openDexFile(DexFile.java:303)
                                                           at dalvik.system.DexFile.<init>(DexFile.java:115)
                                                           at dalvik.system.DexFile.loadDex(DexFile.java:155)
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125)
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76)
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53)
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322)
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182)
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85)
                                                           at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136)
                                                           at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                           at android.os.Looper.loop(Looper.java:135)
                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                        Caused by: java.io.IOException: Failed to open oat file from dex location '/data/data/com.xxx.driver/tinker/patch-7331fa3c/dex/tinker_classN.apk'
                                                           at dalvik.system.DexFile.openDexFileNative(Native Method) 
                                                           at dalvik.system.DexFile.openDexFile(DexFile.java:303) 
                                                           at dalvik.system.DexFile.<init>(DexFile.java:115) 
                                                           at dalvik.system.DexFile.loadDex(DexFile.java:155) 
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125) 
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76) 
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53) 
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322) 
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182) 
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85) 
                                                           at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136) 
                                                           at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                           at android.os.Looper.loop(Looper.java:135) 
                                                           at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                        Caused by: java.io.IOException: Failed to open oat file from /data/data/com.xxx.driver/tinker/patch-7331fa3c/dex/arm/tinker_classN.odex (error Failed to open oat filename for reading: No such file or directory) (no dalvik_cache availible) and relocation failed.
                                                           at dalvik.system.DexFile.openDexFileNative(Native Method) 
                                                           at dalvik.system.DexFile.openDexFile(DexFile.java:303) 
                                                           at dalvik.system.DexFile.<init>(DexFile.java:115) 
                                                           at dalvik.system.DexFile.loadDex(DexFile.java:155) 
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125) 
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76) 
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53) 
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322) 
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182) 
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85) 
                                                           at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136) 
                                                           at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                           at android.os.Looper.loop(Looper.java:135) 
                                                           at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                        Caused by: java.io.IOException: 
                                                           at dalvik.system.DexFile.openDexFileNative(Native Method) 
                                                           at dalvik.system.DexFile.openDexFile(DexFile.java:303) 
                                                           at dalvik.system.DexFile.<init>(DexFile.java:115) 
                                                           at dalvik.system.DexFile.loadDex(DexFile.java:155) 
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125) 
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76) 
                                                           at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53) 
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322) 
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182) 
                                                           at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85) 
                                                           at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136) 
                                                           at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                           at android.os.Looper.loop(Looper.java:135) 
                                                           at android.os.HandlerThread.run(HandlerThread.java:61) 
09-18 17:40:36.758 29794-29937/? E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  java.io.IOException: Zip archive '/data/data/com.xxx.driver/tinker/patch-7331fa3c/dex/tinker_classN.apk' doesn't contain classes.dex (error msg: Entry not found)
                                                                    at dalvik.system.DexFile.openDexFileNative(Native Method)
                                                                    at dalvik.system.DexFile.openDexFile(DexFile.java:303)
                                                                    at dalvik.system.DexFile.<init>(DexFile.java:115)
                                                                    at dalvik.system.DexFile.loadDex(DexFile.java:155)
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125)
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76)
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85)
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                 Caused by: java.io.IOException: Failed to open oat file from dex location '/data/data/com.xxx.driver/tinker/patch-7331fa3c/dex/tinker_classN.apk'
                                                                    at dalvik.system.DexFile.openDexFileNative(Native Method) 
                                                                    at dalvik.system.DexFile.openDexFile(DexFile.java:303) 
                                                                    at dalvik.system.DexFile.<init>(DexFile.java:115) 
                                                                    at dalvik.system.DexFile.loadDex(DexFile.java:155) 
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125) 
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76) 
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53) 
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322) 
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182) 
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85) 
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136) 
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                 Caused by: java.io.IOException: Failed to open oat file from /data/data/com.xxxx.driver/tinker/patch-7331fa3c/dex/arm/tinker_classN.odex (error Failed to open oat filename for reading: No such file or directory) (no dalvik_cache availible) and relocation failed.
                                                                    at dalvik.system.DexFile.openDexFileNative(Native Method) 
                                                                    at dalvik.system.DexFile.openDexFile(DexFile.java:303) 
                                                                    at dalvik.system.DexFile.<init>(DexFile.java:115) 
                                                                    at dalvik.system.DexFile.loadDex(DexFile.java:155) 
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125) 
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76) 
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53) 
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322) 
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182) 
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85) 
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136) 
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                 Caused by: java.io.IOException: 
                                                                    at dalvik.system.DexFile.openDexFileNative(Native Method) 
                                                                    at dalvik.system.DexFile.openDexFile(DexFile.java:303) 
                                                                    at dalvik.system.DexFile.<init>(DexFile.java:115) 
                                                                    at dalvik.system.DexFile.loadDex(DexFile.java:155) 
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer$OptimizeWorker.run(TinkerDexOptimizer.java:125) 
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:76) 
                                                                    at com.tencent.tinker.loader.TinkerDexOptimizer.optimizeAll(TinkerDexOptimizer.java:53) 
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.dexOptimizeDexFiles(DexDiffPatchInternal.java:322) 
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:182) 
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85) 
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136) 
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by shwenzhang** [comment]
这个是爱加密的问题，他们新版本已经修复
