### ISSUE TITLE
华为荣耀6 app运行时异常

### ISSUE THREAD

**Issue by ArcherLucky** [Tencent/tinker#610]
异常类型：app运行时异常

手机型号：华为荣耀6 Plus

手机系统版本:Android 4.4.4

tinker版本：1.8.1

gradle版本：2.3.3

热更新SDK： Bugly 1.2.7

系统：Windows 10

堆栈/日志：
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lefthand.application.ZSApplication" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.lefthand.zhand-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.lefthand.zhand-1, endorb, /systemb, /data/datalib]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                        at android.app.Instrumentation.newApplication(Instrumentation.java:976)
                                                                        at android.app.LoadedApk.makeApplication(LoadedApk.java:532)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4587) 
                                                                        at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:136) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5315) 
                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                        at dalvik.system.NativeStart.main(Native Method) 

```

**Comment by shwenzhang** [comment]
![image](https://user-images.githubusercontent.com/8335303/30846060-9d5f5f36-a2c8-11e7-90f8-06267622f665.png)
分包问题， main dex pattern
