### ISSUE TITLE
OPPO 7.1.1 ClassCastException

### ISSUE THREAD

**Issue by LoliZh** [Tencent/tinker#613]
异常类型：app运行时异常
手机型号：OPPO r11 plus
手机系统版本：7.1.1
tinker版本：1.8.0
gradle版本：2.10
是否使用热更新SDK：否
系统：mac

堆栈/日志：
java.lang.ClassCastException: com.tencent.tinker.lib.service.PatchResult cannot be cast to com.tencent.tinker.lib.service.PatchResult
	at com.tencent.tinker.lib.service.AbstractResultService.onHandleIntent(AbstractResultService.java:64)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:185)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by shwenzhang** [comment]
这个应该是使用bugly 或者 tinkerpatch 第三方sdk才会出现的问题
