### ISSUE TITLE
小米6加载补丁成功后，启动app时必现崩溃，报空指针异常，但代码逻辑没问题，其它手机正常。

### ISSUE THREAD

**Issue by zhaomin33** [Tencent/tinker#630]
小米6加载热修复补丁成功，但是启动app时必现崩溃，报空指针异常，但是这个出现空指针的地方是在application 的onCreate()方法赋值的，程序逻辑无问题，正常运行不会出现空指针，怀疑是加载补丁后，application的代码出现了错乱，求大神指点！

```
异常类型：app运行时异常

手机型号：小米6

手机系统版本 ：Android 7.1.1

tinker版本：如:1.7.11

是否使用热更新SDK： 无

系统：Mac

堆栈/日志：
10-12 17:05:38.183 15467-15467/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
10-12 17:05:38.184 15467-15467/? D/Tinker.TinkerInternals: same fingerprint:Xiaomi/sagit/sagit:7.1.1/NMF26X/V8.2.27.0.NCACNEC:user/release-keys
10-12 17:05:38.185 15467-15467/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.wali.live count:1
10-12 17:05:38.197 15467-15467/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.wali.live-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wali.live-1/lib/arm, /system/fake-libs, /data/app/com.wali.live-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]]
10-12 17:05:38.197 15467-15467/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.wali.live/tinker/patch-faacf630/odex, dex size:8
10-12 17:05:38.198 15467-15467/? W/System: ClassLoader referenced unknown path: 
10-12 17:05:38.236 15467-15467/? I/Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/com.wali.live/tinker/patch-faacf630/dex/classes.dex.jar", zip file "/data/user/0/com.wali.live/tinker/patch-faacf630/dex/classes2.dex.jar", zip file "/data/user/0/com.wali.live/tinker/patch-faacf630/dex/classes3.dex.jar", zip file "/data/user/0/com.wali.live/tinker/patch-faacf630/dex/classes4.dex.jar", zip file "/data/user/0/com.wali.live/tinker/patch-faacf630/dex/classes5.dex.jar", zip file "/data/user/0/com.wali.live/tinker/patch-faacf630/dex/classes6.dex.jar", zip file "/data/user/0/com.wali.live/tinker/patch-faacf630/dex/classes7.dex.jar", zip file "/data/user/0/com.wali.live/tinker/patch-faacf630/dex/test.dex.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.wali.live-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wali.live-1/lib/arm, /system/fake-libs, /data/app/com.wali.live-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]], dex size:8
10-12 17:05:38.236 15467-15467/? W/Tinker.ClassLoaderAdder: checkDexInstall result:true
10-12 17:05:38.239 15467-15467/? W/Tinker.ResourcePatcher: try to clear typedArray cache!
10-12 17:05:38.240 15467-15467/? I/Tinker.ResourcePatcher: checkResUpdate success, found test resource assets file only_use_to_test_tinker_resource.txt
10-12 17:05:38.240 15467-15467/? I/Tinker.ResourceLoader: monkeyPatchExistingResources resource file:/data/user/0/com.wali.live/tinker/patch-faacf630/res/resources.apk, use time: 4
10-12 17:05:38.240 15467-15467/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
10-12 17:05:38.242 15467-15467/? D/Tinker.DefaultAppLike: onBaseContextAttached:
10-12 17:05:38.243 15467-15467/? D/PRETTYLOGGER: ╔════════════════════════════════════════════════════════════════════════════════════════
10-12 17:05:38.243 15467-15467/? D/PRETTYLOGGER: ║ Thread: main
10-12 17:05:38.243 15467-15467/? D/PRETTYLOGGER: ╟────────────────────────────────────────────────────────────────────────────────────────
10-12 17:05:38.244 15467-15467/? D/PRETTYLOGGER: ║ SampleApplicationLike.onBaseContextAttached  (SampleApplicationLike.java:73)
10-12 17:05:38.244 15467-15467/? D/PRETTYLOGGER: ║    MyLog.c  (MyLog.java:86)
10-12 17:05:38.244 15467-15467/? D/PRETTYLOGGER: ╟────────────────────────────────────────────────────────────────────────────────────────
10-12 17:05:38.244 15467-15467/? D/PRETTYLOGGER: ║ SampleApplicationLike: onBaseContextAttached 
10-12 17:05:38.244 15467-15467/? D/PRETTYLOGGER: ╚════════════════════════════════════════════════════════════════════════════════════════
10-12 17:05:38.244 15467-15467/? I/MultiDex: VM with version 2.1.0 has multidex support
10-12 17:05:38.244 15467-15467/? I/MultiDex: install
10-12 17:05:38.244 15467-15467/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
10-12 17:05:38.248 806-1163/? V/audio_hw_primary: out_get_latency: Latency 8
10-12 17:05:38.249 15467-15467/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.wali.live/tinker
10-12 17:05:38.251 15467-15467/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
10-12 17:05:38.252 15467-15467/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:0, process name:com.wali.live, main process:true, systemOTA:false, oatDir:odex, useInterpretMode:false
10-12 17:05:38.252 15467-15467/? I/Tinker.TinkerLoadResult: parseTinkerResult oldVersion:faacf630e0a6a1bbe8b0a55e6bef065e, newVersion:faacf630e0a6a1bbe8b0a55e6bef065e, current:faacf630e0a6a1bbe8b0a55e6bef065e
10-12 17:05:38.252 806-806/? E/AudioFlinger: open /proc/1589/cmdline error
10-12 17:05:38.252 806-806/? I/AudioFlinger: setAppName(), name=[], active=[0]
10-12 17:05:38.252 806-1163/? V/audio_hw_primary: out_get_latency: Latency 8
10-12 17:05:38.252 15467-15467/? I/Tinker.TinkerLoadResult: oh yeah, tinker load all success
10-12 17:05:38.252 15467-15467/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.wali.live/tinker, code: 0, cost: 74ms
....
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.app.Application.getResources()' on a null object reference
                                                       at com.base.h.c.a.a(DisplayUtils.java:24)
                                                       at com.base.h.c.a.d(DisplayUtils.java:68)
                                                       at com.base.activity.BaseActivity.<clinit>(BaseActivity.java:55)
                                                       at java.lang.Class.newInstance(Native Method) 
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1079) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2572) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6165) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)

**Comment by shwenzhang** [comment]
是否已经解决？修改资源的时候是否apply resource id？把崩溃地方的源码贴出来看看
