### ISSUE TITLE
运行tinkerPatchDebug 空指针异常

### ISSUE THREAD

**Issue by kinzirva** [Tencent/tinker#631]
异常类型：运行tinkerpatchDebug npt

tinker版本：如:1.7.11

gradle版本：如:2.10

系统：如:Mac

堆栈/日志：
Gen classes2.dex for dalvik full dex file:/Users/ybf326/smart-git/smartgit-dxy/aspirin-2016/app/build/outputs/tinkerPatch/debug/tempPatchedDexes/classes2.dex, size:7874368, md5:cec858ec01538bf3d7f2d9e52a05f4a9
DexDecoder:write meta file data: classes.dex,,f014c099c077938b98120eaffaedd19a,f014c099c077938b98120eaffaedd19a,843dfb95162db4a4a454e2063ac80447,226877916,jar
DexDecoder:write meta file data: classes2.dex,,cec858ec01538bf3d7f2d9e52a05f4a9,cec858ec01538bf3d7f2d9e52a05f4a9,204931248c67d2844956130fecb1c217,4210070646,jar

Add test install result dex: /Users/ybf326/smart-git/smartgit-dxy/aspirin-2016/app/build/outputs/tinkerPatch/debug/tinker_result/test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,jar

java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at com.tencent.tinker.build.info.PatchInfoGen.gen(PatchInfoGen.java:68)
	at com.tencent.tinker.build.info.PatchInfo.gen(PatchInfo.java:40)
	at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:70)
	at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
	at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
	at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.tinkerPatch(TinkerPatchSchemaTask.groovy:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by shwenzhang** [comment]
gradle tinkerPatch配置中packageConfig字段传入了空值
