### ISSUE TITLE
verifyPatchMetaSignature fail

### ISSUE THREAD

**Issue by lebonbill** [Tencent/tinker#632]
合成补丁时失败,出现verifyPatchMetaSignature fail,都是release包,都有签名,根据官方的demo来写的

异常类型：合成patch失败

手机型号：如:华为P9

手机系统版本：如:Android 6.0

tinker版本：如:1.7.7

gradle版本：如:2.1.3

是否使用热更新SDK：  Bugly SDK

系统：windows 8

tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:ShareSecurityCheck file /data/user/0/bill.testhotfix/app_tmpPatch/tmpPatch.apk, size 3779 verifyPatchMetaSignature fail
                                                                  at com.tencent.tinker.loader.shareutil.ShareSecurityCheck.a(Unknown Source)
                                                                  at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.a(Unknown Source)
                                                                  at com.tencent.tinker.loader.shareutil.ShareTinkerInternals.a(Unknown Source)
                                                                  at com.tencent.tinker.lib.c.g.a(Unknown Source)
                                                                  at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(Unknown Source)
                                                                  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:150)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                               Caused by: java.lang.SecurityException: META-INF/MANIFEST.MF has invalid digest for assets/dex_meta.txt in assets/dex_meta.txt
                                                                  at java.util.jar.JarVerifier.invalidDigest(JarVerifier.java:140)
                                                                  at java.util.jar.JarVerifier.-wrap0(JarVerifier.java)
                                                                  at java.util.jar.JarVerifier$VerifierEntry.verify(JarVerifier.java:132)
                                                                  at java.util.jar.JarFile$JarFileInputStream.read(JarFile.java:117)
                                                                  at java.io.BufferedInputStream.read(BufferedInputStream.java:290)
                                                                  at java.io.InputStream.read(InputStream.java:162)
                                                                  at com.tencent.tinker.loader.shareutil.SharePatchFileUtil.a(Unknown Source)

**Comment by lebonbill** [comment]
已解决了

**Comment by lyqaiym** [comment]
怎么解决的？我的是部分成功，部分出现这个

**Comment by lyqaiym** [comment]
怎么解决的？我的是部分成功，部分出现这个。16个成功，44个失败

**Comment by Hodaren** [comment]
你这解决了也不说解决的办法，真是醉了，还不如别说已解决

**Comment by mgtvott** [comment]
patch包签名的时候指定摘要及算法  -digestalg SHA1 -sigalg SHA1withRSA
