### ISSUE TITLE
android 依赖com.facebook.react:react-native 库，无法启动DevSettingsActivity。下面是详细log。

### ISSUE THREAD

**Issue by gzbbxu** [Tencent/tinker#633]
com.ifreetalk.ftalk E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Unable to start activity ComponentInfo{com.ifreetalk.ftalk/com.facebook.react.devsupport.DevSettingsActivity}: android.view.InflateException: Binary XML file line #29: Error inflating class com.android.ui.ManageSimPreference
com.ifreetalk.ftalk E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ifreetalk.ftalk/com.facebook.react.devsupport.DevSettingsActivity}: android.view.InflateException: Binary XML file line #29: Error inflating class com.android.ui.ManageSimPreference
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2825)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2886)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:186)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6491)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
                                                                              Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class com.android.ui.ManageSimPreference
                                                                                 at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:443)
                                                                                 at android.preference.GenericInflater.rInflate(GenericInflater.java:483)
                                                                                 at android.preference.GenericInflater.rInflate(GenericInflater.java:495)
                                                                                 at android.preference.GenericInflater.inflate(GenericInflater.java:327)
                                                                                 at android.preference.GenericInflater.inflate(GenericInflater.java:264)
                                                                                 at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:280)
                                                                                 at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1534)
                                                                                 at com.facebook.react.devsupport.DevSettingsActivity.onCreate(DevSettingsActivity.java:28)
                                                                                 at android.app.Activity.performCreate(Activity.java:6967)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2886) 
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:186) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6491) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804) 
                                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.ui.ManageSimPreference" on path: DexPathList[[zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.ifreetalk.ftalk-2/base.apk"],nativeLibraryDirectories=[/vendor/lib/openssl, /data/app/com.ifreetalk.ftalk-2/lib/arm, /system/fake-libs, /data/app/com.ifreetalk.ftalk-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                 at android.preference.GenericInflater.createItem(GenericInflater.java:376)
                                                                                 at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:432)
                                                                                 at android.preference.GenericInflater.rInflate(GenericInflater.java:483) 
                                                                                 at android.preference.GenericInflater.rInflate(GenericInflater.java:495) 
                                                                                 at android.preference.GenericInflater.inflate(GenericInflater.java:327) 
                                                                                 at android.preference.GenericInflater.inflate(GenericInflater.java:264) 
                                                                                 at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:280) 
                                                                                 at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1534) 
                                                                                 at com.facebook.react.devsupport.DevSettingsActivity.onCreate(DevSettingsActivity.java:28) 
                                                                                 at android.app.Activity.performCreate(Activity.java:6967) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2886) 
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:186) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6491) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)

**Comment by shwenzhang** [comment]
引用react-native 的接入方式，请参考之前的issue
