### ISSUE TITLE
java.lang.ClassCastException：PatchResult

### ISSUE THREAD

**Issue by nEdAy** [Tencent/tinker#634]
异常类型：app运行时异常（两例）

手机型号：oppo R1  1t

手机系统版本：Android 7.1

tinker版本：1.8.1

gradle版本：2.10

是否使用热更新SDK： 否

系统：Win 

堆栈/日志：
java.lang.ClassCastException: com.tencent.tinker.lib.service.PatchResult cannot be cast to com.tencent.tinker.lib.service.PatchResult
	at com.tencent.tinker.lib.service.AbstractResultService.onHandleIntent(TbsSdkJava:64)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:185)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by shwenzhang** [comment]
这个一般是因为补丁过程错误删除了原来的补丁，请检查自己补丁升级以及回退的逻辑

**Comment by balizhuang2012** [comment]
@shwenzhang 为何总是oppo r11这机型重现呢 其他7.1机型没有
