### ISSUE TITLE
Android 8.0补丁合成失败

### ISSUE THREAD

**Issue by MrXiao2015** [Tencent/tinker#641]
问题：Android 8.0补丁合成失败
异常类型：app运行时异常
手机型号：Nexus 5X
手机系统版本：Android 8.0.0 
tinker版本：1.7.11
堆栈/日志：
```
E/Tinker.DexDiffPatchInternal: parallel dex optimizer file changed_classes.dex.dex is not exist, just wait 12 times
10-25 11:31:31.569 4541-4572/com.xx.xx.debug:patch I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: changed_classes.dex.dex, size 0
10-25 11:31:31.572 4541-4572/com.xx.xx.debug:patch E/Tinker.DexDiffPatchInternal: final parallel dex optimizer file changed_classes.dex.dex is not exist, return false
10-25 11:31:31.577 4541-4572/com.xx.xx.debug:patch I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: test.dex.dex, size 0
10-25 11:31:31.580 4541-4572/com.xx.xx.debug:patch E/Tinker.DexDiffPatchInternal: final parallel dex optimizer file test.dex.dex is not exist, return false
10-25 11:31:31.584 4541-4572/com.xx.xx.debug:patch I/Tinker.DefaultPatchReporter: patchReporter onPatchDexOptFail: dex opt fail path: /data/user/0/com.xx.xx.debug/files/patch/patch-xx.apk, dex size: 2
10-25 11:31:31.589 4541-4572/com.xx.xx.debug:patch E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexOptExist failed
                                                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.waitAndCheckDexOptFile(DexDiffPatchInternal.java:116)
                                                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:149)
                                                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                                                    at android.os.HandlerThread.run(HandlerThread.java:65)
```
解压补丁包，发现存在changed_classes.dex

**Comment by qinci** [comment]
异常类型：app运行时异常

手机型号：Nexus 6P

手机系统版本：Android 8.0.0

tinker版本：1.7.11

gradle版本：2.3.2


也遇到了同样的问题，同样的错误日志

**Comment by suzeyu1992** [comment]
我也遇到同样的问题了,  型号和上面一样!!

**Comment by TracyZhangLei** [comment]
升级tinker到1.8.x,1.7.11不支持android8.0.　@shwenzhang wiki文档也该更新一下了，现在写的还是支持到7.x

**Comment by shwenzhang** [comment]
OK，1.8.1在8.0上面会有一个小bug.近期会发1.9.0会完美支持

**Comment by h2oiswater** [comment]
我也是遇到这个 明明文件在 可是却报这个错误 file not exist
