### ISSUE TITLE
TinkerMultidexConfigTask: FileNotFoundException(manifest_keep.txt)

### ISSUE THREAD

**Issue by vilsteven** [Tencent/tinker#649]
异常类型：编译异常

**tinker版本：1.9.0**

gradle版本：4.1

**Android gradle plugin版本：3.0.0**

是否使用热更新SDK：否

系统：Mac & Windows

说明：
使用以下几种操作，会遇到此异常
1. Android Studio 3.0 中，直接执行**菜单栏中的 rebuild project**，出错
2. 在Android Studio 的Gradle Task管理栏中，先执行 clean，再执行 assembleDebug，出错
3. 终端中先执行gradle clean 再执行 gradle assembleDebug，出错（其实和2是一样的）

有两种情况可以编译通过
1. Androig Gradle plugin 使用 3.0.0，执行Android Studio**菜单栏中的clean**，任务完全执行结束后，直接run，是可以的。
2. Androig Gradle plugin 使用低于3.0.0的版本，比如 2.3.3，是正常的

堆栈/日志：

**重点部分：**

:Android_Client:generateDebugAssets
:Android_Client:mergeDebugAssets
:Android_Client:tinkerProcessDebugMultidexKeep
try update tinker multidex keep proguard file with /Users/vilsteven/WorkSpace/Android_TCTravel/Android_Client/build/intermediates/tinker_intermediates/tinker_multidexkeep.pro

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Android_Client:tinkerProcessDebugMultidexKeep'.
> java.io.FileNotFoundException: /Users/vilsteven/WorkSpace/Android_TCTravel/Android_Client/build/intermediates/multi-dex/debug/manifest_keep.txt (No such file or directory)

。。。

Caused by: java.io.FileNotFoundException: /Users/vilsteven/WorkSpace/Android_TCTravel/Android_Client/build/intermediates/multi-dex/debug/manifest_keep.txt (No such file or directory)
	at com.tencent.tinker.build.gradle.task.TinkerMultidexConfigTask.updateTinkerProguardConfig(TinkerMultidexConfigTask.groovy:114)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

**完整：**

:Android_Client:splitsDiscoveryTaskDebug
:Android_Client:tinkerProcessDebugManifest
tinker add tinker_id_44273a4 to your AndroidManifest.xml /Users/vilsteven/WorkSpace/Android_TCTravel/Android_Client/build/intermediates/manifests/full/debug/AndroidManifest.xml
tinker gen AndroidManifest.xml in build/intermediates/tinker_intermediates/AndroidManifest.xml

:Android_Client:tinkerProcessDebugResourceId
apply resource mapping file /app-debug-1102-10-11-38-R.txt is illegal, just ignore

:Android_Client:compileDebugNdk NO-SOURCE
:Android_Client:mergeDebugShaders
:Android_Client:compileDebugShaders
:Android_Client:generateDebugAssets
:Android_Client:mergeDebugAssets
:Android_Client:tinkerProcessDebugMultidexKeep
try update tinker multidex keep proguard file with /Users/vilsteven/WorkSpace/Android_TCTravel/Android_Client/build/intermediates/tinker_intermediates/tinker_multidexkeep.pro

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Android_Client:tinkerProcessDebugMultidexKeep'.
> java.io.FileNotFoundException: /Users/vilsteven/WorkSpace/Android_TCTravel/Android_Client/build/intermediates/multi-dex/debug/manifest_keep.txt (No such file or directory)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':Android_Client:tinkerProcessDebugMultidexKeep'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: /Users/vilsteven/WorkSpace/Android_TCTravel/Android_Client/build/intermediates/multi-dex/debug/manifest_keep.txt (No such file or directory)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 27 more
Caused by: java.io.FileNotFoundException: /Users/vilsteven/WorkSpace/Android_TCTravel/Android_Client/build/intermediates/multi-dex/debug/manifest_keep.txt (No such file or directory)
	at com.tencent.tinker.build.gradle.task.TinkerMultidexConfigTask.updateTinkerProguardConfig(TinkerMultidexConfigTask.groovy:114)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 39 more

**Comment by shwenzhang** [comment]
具体的android gradle版本是？我这边使用rc2, 没有复现

**Comment by weining** [comment]
遇到了同样的情况

**Comment by vilsteven** [comment]
@shwenzhang 3.0.0正式版，Android Studio也是3.0.0正式版，gradle是用的4.1

**Comment by shwenzhang** [comment]
fixed by 1.9.1

**Comment by githubliruiyuan** [comment]
@shwenzhang 大神啊，bugly热更什么时候更新到对应1.9.1的版本

**Comment by zijing07** [comment]
@githubliruiyuan 你解决了吗？ @shwenzhang
