### ISSUE TITLE
补丁合成异常

### ISSUE THREAD

**Issue by hhj836** [Tencent/tinker#656]
异常类型：合成异常

手机型号：oppo a53m

手机系统版本：如:Android 5.1.1

tinker版本：1.9.0

gradle版本：3.3

是否使用热更新SDK：无

系统：windows

check dex optimizer file exist: /data/data/com.peach.app.debug/tinker/patch-670cd6dd/odex/tinker_classN.dex, size 0
.debug:patch E/Tinker.DexDiffPatchInternal: final parallel dex optimizer file tinker_classN.dex is not exist, return false
.debug:patch E/Tinker.DefaultPatchReporter: onPatchDexOptFail:  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexOptExist failed
                                                                                            at com.tencent.tinker.lib.patch.DexDiffPatchInternal.waitAndCheckDexOptFile(DexDiffPatchInternal.java:121)
                                                                                            at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:152)
                                                                                            at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
                                                                                            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:159)
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by shwenzhang** [comment]
这个可能是op po手机做的异步dex2oat优化导致，最终oat的文件并没有落地

**Comment by hhj836** [comment]
这个手机用demo运行是没问题的。应该是和我项目有关系，大概什么会导致这个原因呢

**Comment by shwenzhang** [comment]
你的项目比较大把，本地可以复现？

**Comment by hhj836** [comment]
是不小，有很多依赖的工程，打了几次包都是报这个，

**Comment by shwenzhang** [comment]
麻烦把完整的补丁合成过程的日志贴上来看一下

**Comment by hhj836** [comment]
给我下QQ或者微信的联系方式吧。。。

**Comment by DoomTeam** [comment]
这个问题有解决吗，我也遇到了同样的问题

**Comment by shwenzhang** [comment]
尝试新版本，把等待的时间延长了
