### ISSUE TITLE
OPPO 7.1.1 ClassCastException

### ISSUE THREAD

**Issue by LoliZh** [Tencent/tinker#661]
异常类型：com.tencent.tinker.lib.service.PatchResult cannot be cast to com.tencent.tinker.lib.service.PatchResult

手机型号：OPPO R11

手机系统版本：Android 7.1.1

tinker版本：1.8.0

gradle版本：2.1.0

是否使用热更新SDK：no

系统：Mac

堆栈/日志：
java.lang.ClassCastException: com.tencent.tinker.lib.service.PatchResult cannot be cast to com.tencent.tinker.lib.service.PatchResult
	at com.tencent.tinker.lib.service.AbstractResultService.onHandleIntent(AbstractResultService.java:64)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:185)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tomystang** [comment]
@LoliZh 
试试升级到1.9.1？如果还是必现的话，发一下app/build/output/tinkerPatch目录到我的邮箱吧：yinshengtang@foxmail.com

**Comment by LoliZh** [comment]
@tomystang  好的，3Q! 从crash情况来看，1.8.0也不是必现的，我先升级到1.9.1试试

**Comment by ding33211** [comment]
@LoliZh 老哥，1.9.1解决了么，因为这个问题暂时都不敢用啊

**Comment by shwenzhang** [comment]
这个问题大部分是因为在回调中错误处理，即手动的去cleanPatch导致

**Comment by LoliZh** [comment]
@ding33211 @shwenzhang   最近没上过patch，所以也没有去验证问题是否解决。我之前在LoadReport的onLoadFileNotFound回调中有用过checkAndCleanPatch()，我看tinker的源码中这块逻辑在1.8.0里已经被注掉了，可能跟这块有关，后面有机会验证下
