### ISSUE TITLE
Patch包合成的时候Crash

### ISSUE THREAD

**Issue by liangzhichao01** [Tencent/tinker#664]
异常类型：app运行时异常/编译异常

手机型号：如:华为 H30-C00

手机系统版本：如:Android 4.3

tinker版本：如:1.9.0

gradle版本：如:2.14.1

系统：如:Mac

patch包正常打出，push到手机后手动触发合成，并且已经合成成功，杀掉app后，重启Crash。
日志信息如下：
11-13 18:41:00.899 28587-28587/? I/Tinker.TinkerLoader: tryLoadPatchFiles: load end, ok!
11-13 18:41:00.929 28587-28587/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.p1.mobile.putong.app.Putong: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:524)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4701)
                                                               at android.app.ActivityThread.access$1600(ActivityThread.java:148)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                               at android.os.Looper.loop(Looper.java:137)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5473)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:525)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
                                                               at dalvik.system.NativeStart.main(Native Method)
                                                            Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:114)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
                                                               at android.app.Application.attach(Application.java:196)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:519)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4701) 
                                                               at android.app.ActivityThread.access$1600(ActivityThread.java:148) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:137) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5473) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:525) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                               at com.p1.mobile.android.app.AppLike.<clinit>(AppLike.java:58)
                                                               at java.lang.reflect.Constructor.constructNative(Native Method)
                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:111)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                               at android.app.Application.attach(Application.java:196) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:519) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4701) 
                                                               at android.app.ActivityThread.access$1600(ActivityThread.java:148) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:137) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5473) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:525) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
另外，确认AppLike是在main dex中。
出错的源码是在TinkerApplication的createDelegate()方法中，请问该问题应该如何解决？

**Comment by liangzhichao01** [comment]
能不能帮忙看下，困扰很久了！

**Comment by shwenzhang** [comment]
Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
在Dalvik的日志可以看到具体出问题的是哪个类，文档有说如何排查这个问题，一般是因为接入不当

**Comment by pmathticol** [comment]
我这边也出现这个问题了

**Comment by liangxianshen** [comment]
> 我这边也出现这个问题了

一样  由于maindex爆超过65535 我指定了maindexlist.txt后出现的  仅仅出现在5.0以下
