### ISSUE TITLE
SampleApplicationLike  is not accessible from java.lang.Class<com.tencent.tinker.loader.app.TinkerApplication>

### ISSUE THREAD

**Issue by zhang625480** [Tencent/tinker#685]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：IVVI  i3p-01

手机系统版本：如:Android 6.0.1 (如是编译异常，则可以不填)

tinker版本：如:1.9.1

gradle版本：如:3.0.0

是否使用热更新SDK：否

系统：如:Mac

堆栈/日志：
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: tinker.sample.android, PID: 7424
                  java.lang.RuntimeException: Unable to instantiate application com.emag.software.tinkerapplicationdemo.MyApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:595)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4798)
                      at android.app.ActivityThread.access$1600(ActivityThread.java:166)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:5617)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:752)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
                   Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                      at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:114)
                      at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)
                      at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)
                      at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
                      at android.app.Application.attach(Application.java:187)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                      at android.app.Instrumentation.newApplication(Instrumentation.java:988)
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:590)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4798) 
                      at android.app.ActivityThread.access$1600(ActivityThread.java:166) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:5617) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:752) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642) 
                   Caused by: java.lang.IllegalAccessException: java.lang.Class<com.emag.software.tinkerapplicationdemo.SampleApplicationLike> is not accessible from java.lang.Class<com.tencent.tinker.loader.app.TinkerApplication>
                      at java.lang.reflect.Constructor.newInstance(Native Method)
                      at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:111)
                      at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                      at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                      at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                      at android.app.Application.attach(Application.java:187) 
                      at android.app.Instrumentation.newApplication(Instrumentation.java:1004) 
                      at android.app.Instrumentation.newApplication(Instrumentation.java:988) 
                      at android.app.LoadedApk.makeApplication(LoadedApk.java:590) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4798) 
                      at android.app.ActivityThread.access$1600(ActivityThread.java:166) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:5617) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:752) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642) 

已添加
defaultConfig {
        /**
         * you can use multiDex and install it in your ApplicationLifeCycle implement
         */
        multiDexEnabled true

        //tinker分包规则
        multiDexKeepProguard file("./tinker_multidexkeep.pro")
    }


烦请大神解惑 谢谢

**Comment by tomystang** [comment]
你是用Annotation让tinker自动生成Application类的吗？发一下AndroidManifest和SampleApplicationLike的Annotation吧。

**Comment by zhang625480** [comment]
是通过注解的方式自动生成的
@SuppressWarnings("unused")
@DefaultLifeCycle(application = "com.emag.software.tinkerapplicationdemo.MyApplication",
        flags = ShareConstants.TINKER_ENABLE_ALL,
        loadVerifyFlag = false)
class SampleApplicationLike extends DefaultApplicationLike {...

**Comment by zhang625480** [comment]
AndroidManifest:
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.emag.software.tinkerapplicationdemo">

    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

    <application
        android:name=".MyApplication"...

**Comment by zhang625480** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.emag.software.tinkerapplicationdemo">
    <application
        android:name=".MyApplication"...

**Comment by zhang625480** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.emag.software.tinkerapplicationdemo">
    <application
        android:name=".MyApplication"

**Comment by zhang625480** [comment]
package="com.emag.software.tinkerapplicationdemo"

<application
        android:name=".MyApplication"...

**Comment by zhang625480** [comment]
我解包看了下     SampleApplicationLike和TinkerApplication还是被分配到两个dex里面了  分包注入到主dex的方法也是按照之前issues里面 提供的方式添加的  目前不确定问题在哪边  是否和分包有关系

**Comment by zhang625480** [comment]
buildType： 
multiDexKeepProguard file("./tinker_multidexkeep.pro")
            multiDexKeepFile file("./tinker_multidexkeep.pro")
tinker_multidexkeep.pro：
#tinker multidex keep patterns:
-keep public class * implements com.tencent.tinker.loader.app.ApplicationLifeCycle {
    <init>(...);
    void onBaseContextAttached(android.content.Context);
}

-keep public class * extends com.tencent.tinker.loader.TinkerLoader {
    <init>(...);
}

-keep public class * extends android.app.Application {
     <init>();
     void attachBaseContext(android.content.Context);
}

-keep class com.tencent.tinker.loader.TinkerTestAndroidNClassLoader {
    <init>(...);
}

#your dex.loader patterns here
-keep class tinker.sample.android.app.BaseBuildInfo {
    <init>(...);
}

-keep class com.emag.software.tinkerapplicationdemo.MyApplication {
    <init>(...);
}

-keep class com.tencent.tinker.loader.** {
    <init>(...);
}

**Comment by haipinghuang** [comment]
我也遇到了这个问题：
异常类型：app运行时异常
手机型号：oppo A57
手机系统版本：android6.0.1
tinker版本：tinker-support:1.1.1
gradle版本：如:3.0.1
是否使用热更新SDK：否
系统：win10

堆栈/日志：
E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.tjhf.base.BaseApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:619)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4938)
                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:165)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:179)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5739)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
                                                            Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:114)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:120)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:133)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:148)
                                                               at android.app.Application.attach(Application.java:196)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:998)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:614)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4938) 
                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:165) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:179) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5739) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674) 
                                                            Caused by: java.lang.ClassNotFoundException: com.tjhf.base.MyApplicationLike
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.Class.forName(Class.java:324)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:108)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:120) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:133) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:148) 
                                                               at android.app.Application.attach(Application.java:196) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:998) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:614) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4938) 
                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:165) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:179) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5739) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674) 
                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tjhf.base.MyApplicationLike" on path: DexPathList[[zip file "/data/app/com.tjhf-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tjhf-2/lib/arm, /data/app/com.tjhf-2/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                               at java.lang.Class.classForName(Native Method) 
                                                               at java.lang.Class.forName(Class.java:324) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:108) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:120) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:133) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:148) 
                                                               at android.app.Application.attach(Application.java:196) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:998) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:614) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4938) 
                                                               at android.app.ActivityThread.access$1800(ActivityThread.java:165) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:179) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5739) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674) 
                                                           	Suppressed: java.lang.ClassNotFoundException: com.tjhf.base.MyApplicationLike
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                               		... 20 more
                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

补充：
因为是日常调试，打包时注释了apply from: 'tinker-support.gradle'
application用的是通过注解的方式自动生成，

此问题经常出现，偶尔多clean几次，然后重新打包又ok；
烦请大神帮忙解决，谢谢

**Comment by shwenzhang** [comment]
@zhang625480 把你的tinker配置也贴出来看看

**Comment by StevenRogers** [comment]
class SampleApplicationLike extends DefaultApplicationLike  修改成 public class SampleApplicationLike extends DefaultApplicationLike
