### ISSUE TITLE
Tinker Exception:can't recognize dex mode

### ISSUE THREAD

**Issue by scean** [Tencent/tinker#689]
生成patch上传以后，在应用的时候会出现这样的异常，导致合成失败，现在的操作步骤都是按照官方文档上进行操作的，有大神知道这个问题的原因吗？

11-28 14:14:34.421 14559-14582/? E/Tinker.DefaultPatchReporter: tinker patch exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
11-28 14:14:34.421 14559-14582/? E/Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:can't recognize dex mode:587325968,jar
                                                                    at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.<init>(Unknown Source)
                                                                    at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.c.d.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.c.d.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.c.d.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.c.f.a(Unknown Source)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(Unknown Source)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by FreeFlash** [comment]
你好，请问这个问题找到原因了吗，我现在也遇到了这个问题

**Comment by xdlove77** [comment]
你好 ，  这个问题找到原因了么！！！

**Comment by tomystang** [comment]
应该是base包和patch包的tinker版本不一致，确定已经升级了tinker之后，重新打一下base包和patch包再试试看吧。

**Comment by wzhangmoumou** [comment]
您好，问题解决了没，我也遇到了。。

**Comment by shwenzhang** [comment]
Patch gradle版本跟tinker APP版本不一致
