### ISSUE TITLE
编译报错：Minimum supported Gradle version is 4.1. Current version is 3.5.

### ISSUE THREAD

**Issue by LeonXtp** [Tencent/tinker#703]
确定我的`gradle`版本已经是4.1：
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```
并且删除`/tinker-sample-android`下的整个`/.gradle`目录，clean之后只生成一个4.1的目录。然后运行
```
gradle assembleDebug --stacktrace
```
之后，就出现了3.5的目录。

异常类型：编译异常

tinker版本：1.9.1

Gradle : 4.1

Android Studio 3.0.1

Gradle plugin for Android 3.0.1

是否使用热更新SDK：否

系统：Archlinux

堆栈/日志：

```
gradle assembleDebug --stacktrace --info

Initialized native services in: /home/bianjp/.gradle/native
Found daemon DaemonInfo{pid=17377, address=[ccb751ef-54a6-4fa1-b843-42c4a6ce665c port:39711, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1512461786900, context=DefaultDaemonContext[uid=211276ae-7fc0-467b-a0d0-2d64a59735ae,javaHome=/usr/lib/jvm/java-8-openjdk,daemonRegistryDir=/home/bianjp/.gradle/daemon,pid=17377,idleTimeout=10800000,daemonOpts=-Xmx1536m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]} however its context does not match the desired criteria.
At least one daemon option is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=/usr/lib/jvm/java-8-openjdk,daemonRegistryDir=/home/bianjp/.gradle/daemon,pid=18577,idleTimeout=null,daemonOpts=-XX:MaxPermSize=1024m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx2048m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]
Actual: DefaultDaemonContext[uid=211276ae-7fc0-467b-a0d0-2d64a59735ae,javaHome=/usr/lib/jvm/java-8-openjdk,daemonRegistryDir=/home/bianjp/.gradle/daemon,pid=17377,idleTimeout=10800000,daemonOpts=-Xmx1536m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]

  Looking for a different daemon...
Connected to daemon DaemonInfo{pid=17099, address=[9246b443-4b99-490c-b38b-c01d6d28e7c2 port:45391, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1512463980500, context=DefaultDaemonContext[uid=e086e822-a2ba-47c6-9036-3b50492ca4bf,javaHome=/usr/lib/jvm/java-8-openjdk,daemonRegistryDir=/home/bianjp/.gradle/daemon,pid=17099,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=1024m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx2048m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]}. Dispatching request Build{id=73ee7103-e4aa-40f5-8ef4-611a3e831a05.1, currentDir=/home/bianjp/repos/android/hotfix/tinker/tinker-sample-android}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@48793bef from daemon DaemonInfo{pid=17099, address=[9246b443-4b99-490c-b38b-c01d6d28e7c2 port:45391, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1512463980500, context=DefaultDaemonContext[uid=e086e822-a2ba-47c6-9036-3b50492ca4bf,javaHome=/usr/lib/jvm/java-8-openjdk,daemonRegistryDir=/home/bianjp/.gradle/daemon,pid=17099,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=1024m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx2048m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 17099). The daemon log file: /home/bianjp/.gradle/daemon/3.5/daemon-17099.out.log
Starting 6th build in daemon [uptime: 39 mins 19.074 secs, performance: 100%]
Executing build with daemon context: DefaultDaemonContext[uid=e086e822-a2ba-47c6-9036-3b50492ca4bf,javaHome=/usr/lib/jvm/java-8-openjdk,daemonRegistryDir=/home/bianjp/.gradle/daemon,pid=17099,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=1024m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx2048m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]
Creating new cache for plugin-use-metadata, path /home/bianjp/.gradle/caches/3.5/plugin-resolution/plugin-use-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@6b14e231
Creating new cache for client-status, path /home/bianjp/.gradle/caches/3.5/plugin-resolution/client-status.bin, access org.gradle.cache.internal.DefaultCacheAccess@6b14e231
Starting Build
Settings evaluated using settings file '/home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/settings.gradle'.
Projects loaded. Root project using build file '/home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/build.gradle'.
Included projects: [root project 'tinker-sample-android', project ':app']
Evaluating root project 'tinker-sample-android' using build file '/home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/build.gradle'.
Creating new cache for metadata-2.23/module-metadata, path /home/bianjp/.gradle/caches/modules-2/metadata-2.23/module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@49af7582
Creating new cache for metadata-2.23/artifact-at-repository, path /home/bianjp/.gradle/caches/modules-2/metadata-2.23/artifact-at-repository.bin, access org.gradle.cache.internal.DefaultCacheAccess@49af7582
Evaluating project ':app' using build file '/home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/app/build.gradle'.
Creating new cache for fileHashes, path /home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/.gradle/3.5/taskHistory/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@19ddab97

FAILURE: Build failed with an exception.

* Where:
Build file '/home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/app/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 4.1. Current version is 3.5. If using the gradle wrapper, try editing the distributionUrl in /home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/gradle/wrapper/gradle-wrapper.properties to gradle-4.1-all.zip

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:648)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:126)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:207)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuildAction.execute(DefaultGradleLauncher.java:204)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:146)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.android.application']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:156)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:113)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:44)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
        at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
        at build_7g2h92wvv2snjidb8fo08zku2.run(/home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/app/build.gradle:1)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 62 more
Caused by: java.lang.RuntimeException: Minimum supported Gradle version is 4.1. Current version is 3.5. If using the gradle wrapper, try editing the distributionUrl in /home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/gradle/wrapper/gradle-wrapper.properties to gradle-4.1-all.zip
        at com.android.build.gradle.BasePlugin.checkGradleVersion(BasePlugin.java:580)
        at com.android.build.gradle.BasePlugin.configureProject(BasePlugin.java:286)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.apply(BasePlugin.java:265)
        at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:120)
        at com.android.build.gradle.AppPlugin.apply(AppPlugin.java:47)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:140)
        ... 72 more


BUILD FAILED

Total time: 0.54 secs
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Build file '/home/bianjp/repos/android/hotfix/tinker/tinker-sample-android/app/build.gradle' line: 1
A problem occurred evaluating project ':app'.] from daemon DaemonInfo{pid=17099, address=[9246b443-4b99-490c-b38b-c01d6d28e7c2 port:45391, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1512463980500, context=DefaultDaemonContext[uid=e086e822-a2ba-47c6-9036-3b50492ca4bf,javaHome=/usr/lib/jvm/java-8-openjdk,daemonRegistryDir=/home/bianjp/.gradle/daemon,pid=17099,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=1024m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx2048m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]} (build should be done).

```

**Comment by shwenzhang** [comment]
tinker sample使用的就是4.1的，应该没有使用到3.5的

**Comment by weinierfei** [comment]
看你本地环境变量是不是配置了3.5版本?

**Comment by LeonXtp** [comment]
@weinierfei @shwenzhang 
谢谢，我本地的gradle版本确实是3.5
遇到此问题的同学可以排查一下，执行命令查看本地`gradle`版本：

```bash
gradle -v
```

我的升级`gradle`之后是这样：
```bash

------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.11.9-1-ARCH amd64
```
我的系统是Archlinux，升级gradle很简单，执行命令：
```bash
sudo pacman -S gradle
```
就可以完成gradle升级
