### ISSUE TITLE
tinker修复之后报Shared library "/data/app/com.fenqile.fenqile-2/lib/arm/libstlport_shared.so" already opened by ClassLoader 0x2000c3; can't open in ClassLoader 0xffe35c64 com.fenqile.log.FqlFileLog.void <clinit>()(FqlFileLog.java:34)

### ISSUE THREAD

**Issue by Owenli0202** [Tencent/tinker#706]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：小米，三星，vivo...

手机系统版本：Android 7.0+

tinker版本：1.8.1

gradle版本：如:2.3.1

是否使用热更新SDK： TinkerPatch SDK

系统：Winodws

堆栈/日志：

0:27:24.543 28168 28168 I Adreno : Build Date : 01/02/17
--
112-06 10:27:24.543 28168 28168 I Adreno : OpenGL ES Shader Compiler Version: XE031.09.00.03
212-06 10:27:24.543 28168 28168 I Adreno : Local Branch :
312-06 10:27:24.543 28168 28168 I Adreno : Remote Branch : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.00.00.269.013
412-06 10:27:24.543 28168 28168 I Adreno : Remote Branch : NONE
512-06 10:27:24.543 28168 28168 I Adreno : Reconstruct Branch : NOTHING
612-06 10:27:24.543 27554 28230 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
712-06 10:27:24.544 27554 28230 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
812-06 10:27:24.552 28214 28214 I WebViewFactory: Loading com.google.android.webview version 60.0.3112.116 (code 311211650)
912-06 10:27:24.571 28190 28190 I Adreno : QUALCOMM build : 5451aae, I25dc76dc3f
1012-06 10:27:24.571 28190 28190 I Adreno : Build Date : 01/02/17
1112-06 10:27:24.571 28190 28190 I Adreno : OpenGL ES Shader Compiler Version: XE031.09.00.03
1212-06 10:27:24.571 28190 28190 I Adreno : Local Branch :
1312-06 10:27:24.571 28190 28190 I Adreno : Remote Branch : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.00.00.269.013
1412-06 10:27:24.571 28190 28190 I Adreno : Remote Branch : NONE
1512-06 10:27:24.571 28190 28190 I Adreno : Reconstruct Branch : NOTHING
1612-06 10:27:24.603 28214 28214 I cr_LibraryLoader: Time to load native libraries: 2 ms (timestamps 9347-9349)
1712-06 10:27:24.610 28214 28214 I chromium: [INFO:library_loader_hooks.cc(144)] Chromium logging enabled: level = 0, default verbosity = 0
1812-06 10:27:24.611 28214 28214 I cr_LibraryLoader: Expected native library version number "60.0.3112.116", actual native library version number "60.0.3112.116"
1912-06 10:27:24.641 28214 28214 W cr_AwBrowserProcess: Using WebView from more than one process at once in a single app is not supported. https://crbug.com/558377
2012-06 10:27:24.647 28214 28214 I cr_BrowserStartup: Initializing chromium process, singleProcess=true
2112-06 10:27:24.679 28190 28190 D baidu_location_service: baidu location service start1 ...28190
2212-06 10:27:24.694 28190 28190 D ConnectivityManager: requestNetwork; CallingUid : 10294, CallingPid : 28190
2312-06 10:27:24.697 28214 28214 I Adreno : QUALCOMM build : 5451aae, I25dc76dc3f
2412-06 10:27:24.697 28214 28214 I Adreno : Build Date : 01/02/17
2512-06 10:27:24.697 28214 28214 I Adreno : OpenGL ES Shader Compiler Version: XE031.09.00.03
2612-06 10:27:24.697 28214 28214 I Adreno : Local Branch :
2712-06 10:27:24.697 28214 28214 I Adreno : Remote Branch : refs/tags/AU_LINUX_ANDROID_LA.UM.5.5.R1.07.00.00.269.013
2812-06 10:27:24.697 28214 28214 I Adreno : Remote Branch : NONE
2912-06 10:27:24.697 28214 28214 I Adreno : Reconstruct Branch : NOTHING
3012-06 10:27:24.700 28190 28190 W Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
3112-06 10:27:24.861 28168 28168 D ConnectivityManager: requestNetwork; CallingUid : 10294, CallingPid : 28168
3212-06 10:27:24.873 28168 28321 I System.out: (HTTPLog)-Static: HongbaoModeServiceAPI: getService class android.os.ServiceManager
3312-06 10:27:24.879 28168 28321 D NetworkSecurityConfig: No Network Security Config specified, using platform default
3412-06 10:27:24.881 28168 28321 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
3512-06 10:27:24.882 28168 28321 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
3612-06 10:27:24.885 28190 28270 D jsengine: init JSFrm version 0.21.4
3712-06 10:27:24.915 28168 28168 W Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
3812-06 10:27:24.997 28168 28290 D jsengine: init JSFrm version 0.21.4
3912-06 10:27:25.000 28214 28229 W art : Suspending all threads took: 8.909ms
4012-06 10:27:25.019 28190 28202 W art : Suspending all threads took: 21.045ms
4112-06 10:27:25.027 28190 28202 I art : Background sticky concurrent mark sweep GC freed 36086(1552KB) AllocSpace objects, 14(1184KB) LOS objects, 36% free, 5MB/9MB, paused 23.161ms total 324.527ms
4212-06 10:27:25.027 28190 28285 I BaiduApiAuth: BaiduApiAuth SDK Version:1.0.20
4312-06 10:27:25.052 27554 27554 D baidu_location_client: baidu location connected ...
4412-06 10:27:25.062 27554 27554 D baidu_location_client: baidu location connected ...
4512-06 10:27:25.069 28214 28214 I TpnsSecurity: JNI_OnLoad
4612-06 10:27:25.114 28214 28330 D jsengine: init JSFrm version 0.21.4
4712-06 10:27:25.163 28190 28340 W DeviceId: galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
4812-06 10:27:25.163 28190 28340 W DeviceId: galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
4912-06 10:27:25.163 28190 28340 W DeviceId: galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
5012-06 10:27:25.197 28190 28348 D NetworkSecurityConfig: No Network Security Config specified, using platform default
5112-06 10:27:25.203 27554 27794 I System.out: pool-8-thread-1 calls detatch()
5212-06 10:27:25.207 28190 28348 I System.out: (HTTPLog)-Static: HongbaoModeServiceAPI: getService class android.os.ServiceManager
5312-06 10:27:25.210 28190 28348 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
5412-06 10:27:25.211 28190 28348 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
5512-06 10:27:25.216 27554 27564 I art : Background sticky concurrent mark sweep GC freed 155082(9MB) AllocSpace objects, 77(2MB) LOS objects, 26% free, 28MB/38MB, paused 26.948ms total 924.584ms
5612-06 10:27:25.225 27554 27794 I System.out: Thread-2592(ApacheHTTPLog):isSBSettingEnabled false
5712-06 10:27:25.225 27554 27794 I System.out: Thread-2592(ApacheHTTPLog):isShipBuild true
5812-06 10:27:25.225 27554 27794 I System.out: Thread-2592(ApacheHTTPLog):getDebugLevel 0x4f4c
5912-06 10:27:25.225 27554 27794 I System.out: Thread-2592(ApacheHTTPLog):Smart Bonding Setting is false
6012-06 10:27:25.225 27554 27794 I System.out: Thread-2592(ApacheHTTPLog):SmartBonding Setting is false, SHIP_BUILD is true, log to file is false, DBG is false, DEBUG_LEVEL (1-LOW, 2-MID, 3-HIGH) is 1
6112-06 10:27:25.315 27554 28088 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
6212-06 10:27:25.321 27554 28088 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
6312-06 10:27:25.379 28168 28325 E SQLiteLog: (10) POSIX Error : 9 SQLite Error : 3850
6412-06 10:27:25.387 28190 28190 D baidu_location_service: baidu location service stop ...
6512-06 10:27:25.401 27554 27794 I System.out: pool-8-thread-1 calls detatch()
6612-06 10:27:25.443 28214 28214 D ConnectivityManager: requestNetwork; CallingUid : 10294, CallingPid : 28214
6712-06 10:27:25.478 28214 28214 W Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
6812-06 10:27:25.538 28168 28314 E SQLiteLog: (10) POSIX Error : 9 SQLite Error : 3850
6912-06 10:27:25.729 28168 28354 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
7012-06 10:27:25.743 28168 28354 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
7112-06 10:27:25.978 27554 27559 I art : Do full code cache collection, code=91KB, data=124KB
7212-06 10:27:26.012 27554 27559 I art : After code cache collection, code=60KB, data=64KB
7312-06 10:27:26.314 28190 28190 I baidu_location_service: LocationAuthManager Authentication Error errorcode = 0 , msg = {"status":0,"message":"","ak":"Q7YCRdV5MZmieGlcEOvZEMQr","token":"c0cf7YbOPiCHTSdWWACoO+uoqbqD6pUpnhYQmLC86S5mn4UQ\/0F1Q\/QY6EZe6E+n1+nvkiHK0T5I\/iPLlDy6DgzMnNNd3WLVDfQ5qZ081rUnY2bQ4T8Yd3sKuGgIdItJySFhZJPQXe1Io0d7BDy4gLVStN6Aj9WyliQeZ633U4K8KemouA","uid":"1264769797","sk":"ovIhcuDeV6m7pEGWj1Cl9jWHvONnNIIz"}
7412-06 10:27:26.321 28190 28377 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
7512-06 10:27:26.321 27554 28088 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
7612-06 10:27:26.321 28190 28377 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
7712-06 10:27:26.324 27554 28088 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
7812-06 10:27:26.332 28214 28214 I XgStat : [main(1): TbsSdkJava:40] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__1000001
7912-06 10:27:26.333 28214 28214 D XgStat : [main(1): TbsSdkJava:256] - firstRead
8012-06 10:27:26.334 28214 28214 I XgStat : [main(1): TbsSdkJava:40] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__3
8112-06 10:27:26.381 28190 28285 D baidu_location_service: baidu location service has stoped ...
8212-06 10:27:26.381 28190 28285 I Process : Sending signal. PID: 28190 SIG: 9
8312-06 10:27:26.410 28214 28229 W art : Suspending all threads took: 12.662ms
8412-06 10:27:26.437 28214 28368 D XgStat : [XgStat(2571): TbsSdkJava:682] - send Event:{"ky":"Axg2100264266","et":1000,"ui":"359583077803916","mc":"02:00:00:00:00:00","ut":1,"ch":"xgsdk","mid":"1fef675e89d43aae4a3d99b03e798d9a1944349d","si":0,"cts":1512527245,"ts":1512527245,"sv":"3.1","dts":-6,"ei":"SdkService","kv2":{"srv_stime":1511410544690,"srv_etime":1511411066025,"srv_startTime":2,"srv_freason":[".keepalive",".keepalive"],"hb_suc":0,"hb_failed":0,"con_suc":1,"con_failed":0}}
8512-06 10:27:26.453 28214 28368 E XgStat : [XgStat(2571): TbsSdkJava:190] - [http://pingma.qq.com:80/mstat/report/?index=1512527245]Send request(eventsize:1,401bytes), content:[{"ky":"Axg2100264266","et":1000,"ui":"359583077803916","mc":"02:00:00:00:00:00","ut":1,"ch":"xgsdk","mid":"1fef675e89d43aae4a3d99b03e798d9a1944349d","si":0,"cts":1512527245,"ts":1512527245,"sv":"3.1","dts":-6,"ei":"SdkService","kv2":{"srv_stime":1511410544690,"srv_etime":1511411066025,"srv_startTime":2,"srv_freason":[".keepalive",".keepalive"],"hb_suc":0,"hb_failed":0,"con_suc":1,"con_failed":0}}]
8612-06 10:27:26.519 28214 28368 D NetworkSecurityConfig: No Network Security Config specified, using platform default
8712-06 10:27:26.532 28214 28368 I System.out: Thread-2571(ApacheHTTPLog):Reading from variable values from setDefaultValuesToVariables
8812-06 10:27:26.532 28214 28368 I System.out: Thread-2571(ApacheHTTPLog):isSBSettingEnabled false
8912-06 10:27:26.532 28214 28368 I System.out: Thread-2571(ApacheHTTPLog):isShipBuild true
9012-06 10:27:26.532 28214 28368 I System.out: Thread-2571(ApacheHTTPLog):getDebugLevel 0x4f4c
9112-06 10:27:26.532 28214 28368 I System.out: Thread-2571(ApacheHTTPLog):Smart Bonding Setting is false
9212-06 10:27:26.532 28214 28368 I System.out: Thread-2571(ApacheHTTPLog):SmartBonding Setting is false, SHIP_BUILD is true, log to file is false, DBG is false, DEBUG_LEVEL (1-LOW, 2-MID, 3-HIGH) is 1
9312-06 10:27:26.562 28214 28214 I XINGE : [PushServiceManager] Service's first running at com.fenqile.fenqile version : 3.1
9412-06 10:27:26.584 27554 27564 W art : Suspending all threads took: 12.489ms
9512-06 10:27:26.608 28214 28369 W XgStat : [tpush.working.thread(2572): TbsSdkJava:175] - startHorseTask key:34
9612-06 10:27:26.651 27554 27564 I art : Background partial concurrent mark sweep GC freed 164714(9MB) AllocSpace objects, 33(1120KB) LOS objects, 37% free, 26MB/42MB, paused 15.901ms total 210.290ms
9712-06 10:27:26.661 27554 27554 D ConnectivityManager: unregisterNetworkCallback; CallingUid : 10294, CallingPid : 27554
9812-06 10:27:26.664 27554 28100 E ConnectivityManager.CallbackHandler: callback not found for RELEASED message
9912-06 10:27:26.811 28214 28369 W System : ClassLoader referenced unknown path:
10012-06 10:27:26.813 27554 27554 D ViewRootImpl@57a9261[HomeActivity]: ViewPostImeInputStage processPointer 0
10112-06 10:27:26.817 28214 28368 I System.out: XgStat calls detatch()
10212-06 10:27:26.830 27554 27554 V BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
10312-06 10:27:26.830 27554 27554 V BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
10412-06 10:27:26.830 27554 27554 V BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
10512-06 10:27:26.830 27554 27554 V BoostFramework: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
10612-06 10:27:26.830 27554 27554 V BoostFramework: mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
10712-06 10:27:26.834 27554 27554 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@da2d817
10812-06 10:27:26.875 28214 28389 I System.out: (HTTPLog)-Static: HongbaoModeServiceAPI: getService class android.os.ServiceManager
10912-06 10:27:26.877 28214 28389 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
11012-06 10:27:26.878 28214 28389 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
11112-06 10:27:26.895 27554 27554 D ViewRootImpl@57a9261[HomeActivity]: ViewPostImeInputStage processPointer 1
11212-06 10:27:26.907 27554 27554 D TingYun : OkHttpInstrumentation3 - wrapping Instructor
11312-06 10:27:26.968 28214 28369 V XINGE : [PushServiceNetworkHandler] Register(2100264266,ef6d49b52dacedbe23eb1c85c701fb21,,,-1),token: 1fef675e89d43aae4a3d99b03e798d9a1944349d
11412-06 10:27:27.052 28214 28369 V XINGE : [PushServiceNetworkHandler] Register(2100264266,ef6d49b52dacedbe23eb1c85c701fb21,,,-1),token: 1fef675e89d43aae4a3d99b03e798d9a1944349d
11512-06 10:27:27.124 27554 27554 D TingYun : OkHttpInstrumentation3 - wrapping Instructor
11612-06 10:27:27.196 27554 28110 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
11712-06 10:27:27.197 27554 28110 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
11812-06 10:27:27.218 27554 28403 D SensorManager: registerListener :: 13, Step Counter, 0, 0,
11912-06 10:27:27.250 27554 27554 D SensorManager: unregisterListener ::
12012-06 10:27:27.422 28214 28388 I XINGE : [TpnsClient] Connect to Xinge Server succeed!
12112-06 10:27:27.459 28214 28388 I MID : [Thread-7(2581): null:-1] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__1000001
12212-06 10:27:27.463 28214 28388 D MID : [Thread-7(2581): null:-1] - readNewVersionMidEntity:{"imei":"359583077803916","mac":"02:00:00:00:00:00","mid":"1fef675e89d43aae4a3d99b03e798d9a1944349d","ts":1508333812868}
12312-06 10:27:27.603 28168 28354 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
12412-06 10:27:27.604 28168 28354 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
12512-06 10:27:27.853 27554 27564 W art : Suspending all threads took: 10.421ms
12612-06 10:27:27.873 27554 28182 I XINGE : [XGPushManager] XG register push success with token : 1fef675e89d43aae4a3d99b03e798d9a1944349d
12712-06 10:27:27.895 27554 27559 I art : Do partial code cache collection, code=106KB, data=125KB
12812-06 10:27:27.900 27554 27559 I art : After code cache collection, code=106KB, data=125KB
12912-06 10:27:27.900 27554 27559 I art : Increasing code cache capacity to 512KB
13012-06 10:27:27.916 27554 27554 W Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.fenqile.fenqile/tinker
13112-06 10:27:27.917 27554 27554 D Tinker.DefaultAppLike: onBaseContextAttached:
13212-06 10:27:27.917 27554 27554 I MultiDex: VM with version 2.1.0 has multidex support
13312-06 10:27:27.917 27554 27554 I MultiDex: install
13412-06 10:27:27.918 27554 27554 I MultiDex: VM has multidex support, MultiDex support library is disabled.
13512-06 10:27:27.922 27554 27554 I Tinker.SamplePatchListener: application maxMemory:256
13612-06 10:27:27.925 27554 27554 W Tinker.Tinker: tinker patch directory: /data/user/0/com.fenqile.fenqile/tinker
13712-06 10:27:27.928 27554 27554 I Tinker.Tinker: try to install tinker, isEnable: true, version: 1.8.1
13812-06 10:27:27.928 27554 27554 I Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.fenqile.fenqile, main process:true, systemOTA:false, fingerPrint:samsung/hero2qltezc/hero2qltechn:7.0/NRD90M/G9350ZCU2BQK3:user/release-keys, oatDir:null, useInterpretMode:false
13912-06 10:27:27.929 27554 28182 I XINGE : [XGPushManager] XG register push success with token : 1fef675e89d43aae4a3d99b03e798d9a1944349d
14012-06 10:27:27.929 27554 27554 W Tinker.TinkerLoadResult: can't find patch file, is ok, just return
14112-06 10:27:27.929 27554 27554 I Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.fenqile.fenqile/tinker, code: -2, cost: 5ms
14212-06 10:27:27.929 27554 27554 W Tinker.Tinker: tinker load fail!
14312-06 10:27:27.933 27554 27554 D Tinker.DefaultAppLike: onCreate
14412-06 10:27:27.941 27554 27554 W art : 0xffd8bed8
14512-06 10:27:27.942 27554 27554 D AndroidRuntime: Shutting down VM
14612-06 10:27:27.942 27554 27554 E Tinker.SampleUncaughtExHandler: uncaughtException:Shared library "/data/app/com.fenqile.fenqile-1/lib/arm/libstlport_shared.so" already opened by ClassLoader 0x100243; can't open in ClassLoader 0xffd8bf34
14712-06 10:27:27.943 27554 27564 I art : Background sticky concurrent mark sweep GC freed 204738(13MB) AllocSpace objects, 32(636KB) LOS objects, 30% free, 29MB/42MB, paused 17.999ms total 157.911ms
14812-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.fenqile.fenqile-1/lib/arm/libstlport_shared.so" already opened by ClassLoader 0x100243; can't open in ClassLoader 0xffd8bf34
14912-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at java.lang.Runtime.loadLibrary0(Runtime.java:977)
15012-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at java.lang.System.loadLibrary(System.java:1567)
15112-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at com.fenqile.c.b.<clinit>(TbsSdkJava:34)
15212-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at com.fenqile.c.a.a(TbsSdkJava:63)
15312-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at com.fenqile.c.a.a(TbsSdkJava:46)
15412-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at com.fenqile.base.BaseApp.onCreate(TbsSdkJava:162)
15512-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TbsSdkJava:173)
15612-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
15712-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at cn.jiguang.a.a.d.a.a.d.callApplicationOnCreate(Unknown Source)
15812-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at android.app.LoadedApk.makeApplication(LoadedApk.java:856)
15912-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at android.app.ActivityThread.handleReceiver(ActivityThread.java:3286)
16012-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at android.app.ActivityThread.-wrap20(ActivityThread.java)
16112-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1712)
16212-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at android.os.Handler.dispatchMessage(Handler.java:102)
16312-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at android.os.Looper.loop(Looper.java:154)
16412-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at android.app.ActivityThread.main(ActivityThread.java:6646)
16512-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at java.lang.reflect.Method.invoke(Native Method)
16612-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
16712-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
16812-06 10:27:28.067 27554 28427 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
16912-06 10:27:28.068 27554 28427 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
17012-06 10:27:28.553 28168 28354 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
17112-06 10:27:28.554 28168 28354 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

**Comment by tomystang** [comment]
检查一下你的java代码里是不是有其他加载了so的类在patch加载之前提前被引用了？

**Comment by Owenli0202** [comment]
没有被提前应用，在7.0以上系统，三星S8上面出现概率最高

**Comment by Owenli0202** [comment]
1 java.lang.Runtime.loadLibrary0(Runtime.java:989)
--
2 java.lang.System.loadLibrary(System.java:1567)
3 com.fenqile.c.b.<clinit>(FqlFileLog.java:34)
4 com.fenqile.c.b.a(FqlFileLog.java:39)
5 com.fenqile.c.a.a(AppLog.java:63)
6 com.fenqile.c.a.a(AppLog.java:46)
7 com.fenqile.base.BaseApp.onCreate(BaseApp.java:162)
8 com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:173)
9 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
10 cn.jiguang.a.a.d.a.a.d.callApplicationOnCreate(Unknown Source)
11 android.app.LoadedApk.makeApplication(LoadedApk.java:856)
12 android.app.ActivityThread.handleReceiver(ActivityThread.java:3378)

看错误栈是有极光推送调起来的

**Comment by shwenzhang** [comment]
它的初始化比tinker更早？

**Comment by shwenzhang** [comment]
有可能是这个SO的内部加载是每次都会new一个classloader去加载的，导致同一个so被不同的classloader加载了

14812-06 10:27:27.943 27554 27554 E Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.fenqile.fenqile-1/lib/arm/libstlport_shared.so" already opened by ClassLoader 0x100243; can't open in ClassLoader 0xffd8bf34

**Comment by Owenli0202** [comment]
这是微信开源的xlog需要的so，如果是so内部每次都new一个classloader应该是必现的才对，但是实际上手偶现的

**Comment by Owenli0202** [comment]
没有比tinker早

**Comment by maxwell-nc** [comment]
同出现此问题，求解决方案

**Comment by whikko** [comment]
请教一下这个问题是怎么解决的？我也出现了

**Comment by wangxiaxin** [comment]
同求

**Comment by xiangjunshi** [comment]
怎么解决的
