### ISSUE TITLE
can't find TINKER_ID from the old apk manifest file

### ISSUE THREAD

**Issue by summerHearts** [Tencent/tinker#707]
com.tencent.tinker.build.util.TinkerPatchException: can't find TINKER_ID from the old apk manifest file, it must be set!
	at com.tencent.tinker.build.info.PatchInfoGen.addTinkerID(PatchInfoGen.java:48)
	at com.tencent.tinker.build.info.PatchInfoGen.gen(PatchInfoGen.java:65)
	at com.tencent.tinker.build.info.PatchInfo.gen(PatchInfo.java:40)
	at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:70)
	at com.tencent.tinker.patch.CliMain.run(CliMain.java:106)
	at com.tencent.tinker.patch.CliMain.main(CliMain.java:54)

我在old.apk中添加了TinkerID 依然说找不到

**Comment by lpjhblpj** [comment]
我也碰到这问题了，不知道哪出错了，
