### ISSUE TITLE
命令行接入方式无法加载补丁: tinker dex check fail:Tinker Exception:checkDexInstall failed

### ISSUE THREAD

**Issue by daemon369** [Tencent/tinker#710]
异常类型：app运行时异常

手机型号：Meizu MX6

手机系统版本：Android 7.1.1

tinker版本：1.9.2

gradle版本：4.1

是否使用热更新SDK：无

系统：Mac
```
使用项目附带的tinker-sample-android项目，通过gradle方式打包加载补丁成功，而使用命令行的方式生成的补丁包加载失败：

12-12 14:53:12.795 8620-8620/tinker.sample.android I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/tinker.sample.android/tinker/patch-053390b8/dex/tinker_classN.apk md5, use time: 0
12-12 14:53:12.796 8620-8620/tinker.sample.android I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/tinker.sample.android/tinker/patch-053390b8/odex, dex size:1
12-12 14:53:12.811 8620-8620/tinker.sample.android I/Tinker.ClassLoaderAdder: after loaded classloader: com.tencent.tinker.loader.AndroidNClassLoader[DexPathList[[zip file "/data/user/0/tinker.sample.android/tinker/patch-053390b8/dex/tinker_classN.apk", zip file "/data/app/tinker.sample.android-1/base.apk"],nativeLibraryDirectories=[/data/app/tinker.sample.android-1/lib/arm64, /system/lib64, /vendor/lib64]]], dex size:1
12-12 14:53:12.813 8620-8620/tinker.sample.android W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
12-12 14:53:12.820 8620-8620/tinker.sample.android I/Tinker.SamplePatchListener: application maxMemory:256
12-12 14:53:12.824 8620-8620/tinker.sample.android W/Tinker.Tinker: tinker patch directory: /data/user/0/tinker.sample.android/tinker
12-12 14:53:12.826 8620-8620/tinker.sample.android E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
12-12 14:53:12.834 8620-8620/tinker.sample.android E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
                                                                                     at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:84)
                                                                                     at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:194)
                                                                                     at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:259)
                                                                                     at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:163)
                                                                                     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
                                                                                     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
                                                                                     at android.app.Application.attach(Application.java:201)
                                                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1011)
                                                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:995)
                                                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:810)
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5697)
                                                                                     at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1717)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                     at android.os.Looper.loop(Looper.java:203)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6475)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by shwenzhang** [comment]
你的tinker接入配置，编译的时候是否出现warning

**Comment by daemon369** [comment]
@shwenzhang 没有warning，打包补丁时也没有问题，就是加载补丁时失败

**Comment by daemon369** [comment]
打包补丁时的日志：
```
special configFile file path:/Users/name/patch/tinker_config.xml
reading config file, /Users/name/patch/tinker_config.xml
unknown package config tag configFiled
-----------------------Tinker patch begin-----------------------
configuration:
oldApk:/Users/name/patch/old/a.apk
newApk:/Users/name/patch/new/a.apk
outputFolder:/Users/name/patch/tinkerPatch
isIgnoreWarning:false
isProtectedApp:false
7-ZipPath:/usr/local/bin/7za
useSignAPk:true
package meta fields:
filed name:patchMessage, filed value:tinker is sample to use
filed name:platform, filed value:all
dex configs:
dexMode: jar
dexPattern:assets/secondary-dex-.\.jar
dexPattern:classes.*\.dex
dex loader:tinker.sample.android.app.BaseBuildInfo
lib configs:
libPattern:lib/.*/.*\.so
resource configs:
resPattern:AndroidManifest\.xml
resPattern:res/.*
resPattern:resources\.arsc
resPattern:assets/.*
resIgnore change:assets/sample_meta\.txt
largeModSize:100kb
useApplyResource:false

Analyze old and new apk files:
old apk: a.apk, size=1417785, md5=a93902a8b9f535b46ae3dd37eece8770
new apk: a.apk, size=1417613, md5=30fba87ba2974928fd68aa55b6055918


Manifest has no changes, skip rest decode works.
UnZipping apk to /Users/name/patch/tinkerPatch/a-old
UnZipping apk to /Users/name/patch/tinkerPatch/a-new
ApkParser: resources.arsc is not equal, reason: string pool is changed
Found large modify resource: resources.arsc size:190428
Check for loader classes in dex: classes.dex

Gen classes.dex patch file:/Users/name/patch/tinkerPatch/tinker_result/classes.dex, size:779, md5:916db4ac83d01ff761d0482b30a827f9
Verifying if patched new dex is logically the same as original new dex: a-new/classes.dex ...

Gen classes.dex for dalvik full dex file:/Users/name/patch/tinkerPatch/tempPatchedDexes/classes.dex, size:2159700, md5:e4cf4a5df8888a45a4a4b19d81335501
DexDecoder:write meta file data: classes.dex,,e4cf4a5df8888a45a4a4b19d81335501,e4cf4a5df8888a45a4a4b19d81335501,916db4ac83d01ff761d0482b30a827f9,1382764938,750660435,jar

Add test install result dex: /Users/name/patch/tinkerPatch/tinker_result/test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,0,jar
Add Test resource file: assets/only_use_to_test_tinker_resource.txt
Final normal zip resource: resources_out.zip, size=431597, md5=6b5aee0904c532bb9bc7b47e1c295f59
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
Current 7za path:/usr/local/bin/7za
Result: final signed patch result: /Users/name/patch/tinkerPatch/patch_signed.apk, size=4891
Result: final signed with 7zip patch result: /Users/name/patch/tinkerPatch/patch_signed_7zip.apk, size=5334
Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 443 byte, you should choose patch_signed.apk at these time!
Tinker patch done, total time cost: 4.779000s
Tinker patch done, you can go to file to find the output /Users/name/patch/tinkerPatch
-----------------------Tinker patch end-------------------------
```

**Comment by daemon369** [comment]
@shwenzhang 使用项目中附带的`tinker-sample-android`项目，只是把gradle从`3.0.0-rc2`改为`3.0.1`

**Comment by shwenzhang** [comment]
只有命令行接入会遇到这个问题？

**Comment by daemon369** [comment]
@shwenzhang 是的，命令行接入才遇到的问题

**Comment by shwenzhang** [comment]
你可以diff一下两个基础包跟补丁包差别在哪里

**Comment by FnAndroid** [comment]
同样的问题

**Comment by ranhuanbin** [comment]
> 打包补丁时的日志：
> 
> ```
> special configFile file path:/Users/name/patch/tinker_config.xml
> reading config file, /Users/name/patch/tinker_config.xml
> unknown package config tag configFiled
> -----------------------Tinker patch begin-----------------------
> configuration:
> oldApk:/Users/name/patch/old/a.apk
> newApk:/Users/name/patch/new/a.apk
> outputFolder:/Users/name/patch/tinkerPatch
> isIgnoreWarning:false
> isProtectedApp:false
> 7-ZipPath:/usr/local/bin/7za
> useSignAPk:true
> package meta fields:
> filed name:patchMessage, filed value:tinker is sample to use
> filed name:platform, filed value:all
> dex configs:
> dexMode: jar
> dexPattern:assets/secondary-dex-.\.jar
> dexPattern:classes.*\.dex
> dex loader:tinker.sample.android.app.BaseBuildInfo
> lib configs:
> libPattern:lib/.*/.*\.so
> resource configs:
> resPattern:AndroidManifest\.xml
> resPattern:res/.*
> resPattern:resources\.arsc
> resPattern:assets/.*
> resIgnore change:assets/sample_meta\.txt
> largeModSize:100kb
> useApplyResource:false
> 
> Analyze old and new apk files:
> old apk: a.apk, size=1417785, md5=a93902a8b9f535b46ae3dd37eece8770
> new apk: a.apk, size=1417613, md5=30fba87ba2974928fd68aa55b6055918
> 
> 
> Manifest has no changes, skip rest decode works.
> UnZipping apk to /Users/name/patch/tinkerPatch/a-old
> UnZipping apk to /Users/name/patch/tinkerPatch/a-new
> ApkParser: resources.arsc is not equal, reason: string pool is changed
> Found large modify resource: resources.arsc size:190428
> Check for loader classes in dex: classes.dex
> 
> Gen classes.dex patch file:/Users/name/patch/tinkerPatch/tinker_result/classes.dex, size:779, md5:916db4ac83d01ff761d0482b30a827f9
> Verifying if patched new dex is logically the same as original new dex: a-new/classes.dex ...
> 
> Gen classes.dex for dalvik full dex file:/Users/name/patch/tinkerPatch/tempPatchedDexes/classes.dex, size:2159700, md5:e4cf4a5df8888a45a4a4b19d81335501
> DexDecoder:write meta file data: classes.dex,,e4cf4a5df8888a45a4a4b19d81335501,e4cf4a5df8888a45a4a4b19d81335501,916db4ac83d01ff761d0482b30a827f9,1382764938,750660435,jar
> 
> Add test install result dex: /Users/name/patch/tinkerPatch/tinker_result/test.dex, size:584
> DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,0,jar
> Add Test resource file: assets/only_use_to_test_tinker_resource.txt
> Final normal zip resource: resources_out.zip, size=431597, md5=6b5aee0904c532bb9bc7b47e1c295f59
> Generate unsigned apk: patch_unsigned.apk
> Signing apk: patch_signed.apk
> Signing key algorithm is SHA1withRSA
> Try use 7za to compress the patch file: patch_signed_7zip.apk, will cost much more time
> Current 7za path:/usr/local/bin/7za
> Result: final signed patch result: /Users/name/patch/tinkerPatch/patch_signed.apk, size=4891
> Result: final signed with 7zip patch result: /Users/name/patch/tinkerPatch/patch_signed_7zip.apk, size=5334
> Warning: patch_signed_7zip.apk is bigger than patch_signed.apk 443 byte, you should choose patch_signed.apk at these time!
> Tinker patch done, total time cost: 4.779000s
> Tinker patch done, you can go to file to find the output /Users/name/patch/tinkerPatch
> -----------------------Tinker patch end-------------------------
> ```

请问一下你这个问题后来解决了吗?

**Comment by TracyZhangLei** [comment]
也遇到了

**Comment by TracyZhangLei** [comment]
同样遇到了，我想知道这个值是怎么变成true的
