### ISSUE TITLE
集成tinker以后安卓端RN的code push下发更新无法合并成功

### ISSUE THREAD

**Issue by mirantisD** [Tencent/tinker#712]
异常类型： 通过CodePush下发的更新不能正常安装，重启后RN页面报异常错误

手机型号：所有

手机系统版本：所有

tinker版本：如:1.9.0

是否使用热更新SDK： Bugly SDK

系统：如:Mac

堆栈/日志：
React: Exception in native call
                                                                      com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/data/com.*.*/files/CodePush/a64c7935a760cbf2205ede42a1ded1f85c79542ae2ea65b4b93e29948f2b8ea3/CodePush/index.android.bundle: No such file or directory
                                                                          at com.facebook.react.cxxbridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
                                                                          at com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromFile(Proguard:203)
                                                                          at com.facebook.react.cxxbridge.JSBundleLoader$2.loadScript(Proguard:53)
                                                                          at com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle(Proguard:216)
                                                                          at com.facebook.react.ReactInstanceManager.createReactContext(Proguard:994)
                                                                          at com.facebook.react.ReactInstanceManager.access$600(Proguard:109)
                                                                          at com.facebook.react.ReactInstanceManager$4.run(Proguard:746)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by mirantisD** [comment]
为什么说是codepush的问题
