### ISSUE TITLE
布局使用 @*android 资源编译报错误

### ISSUE THREAD

**Issue by tianfuchao** [Tencent/tinker#718]
异常类型：
编译异常，三方库 layout文件使用了@*android:color/transparent 无法生成补丁包
手机型号：

手机系统版本：

tinker版本：
tinker:1.9.1

gradle版本：
3.3

是否使用热更新SDK： 
无

系统：
Mac

堆栈/日志：

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tinker:tinkerProcessDebugResourceId'.
> com.tencent.tinker.build.aapt.AaptUtil$AaptUtilException: Invalid reference '@*android:color/transparent' in '/Users/TianFuchao/Documents/启明/项目/解放/android/fawjiefang_basic/tinker/build/intermediates/res/merged/debug/layout/rx_webview.xml'

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':tinker:tinkerProcessDebugResourceId'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: com.tencent.tinker.build.aapt.AaptUtil$AaptUtilException: Invalid reference '@*android:color/transparent' in '/Users/TianFuchao/Documents/启明/项目/解放/android/fawjiefang_basic/tinker/build/intermediates/res/merged/debug/layout/rx_webview.xml'
	at com.tencent.tinker.build.aapt.AaptUtil.collectResource(AaptUtil.java:95)
	at com.tencent.tinker.build.aapt.AaptUtil$collectResource.call(Unknown Source)
	at com.tencent.tinker.build.gradle.task.TinkerResourceIdTask.applyResourceId(TinkerResourceIdTask.groovy:63)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 20 more
Caused by: com.tencent.tinker.build.aapt.AaptUtil$AaptUtilException: Invalid reference '@*android:color/transparent' in '/Users/TianFuchao/Documents/启明/项目/解放/android/fawjiefang_basic/tinker/build/intermediates/res/merged/debug/layout/rx_webview.xml'
	at com.tencent.tinker.build.aapt.AaptUtil.processXmlFile(AaptUtil.java:280)
	at com.tencent.tinker.build.aapt.AaptUtil.processXmlFilesForIds(AaptUtil.java:112)
	at com.tencent.tinker.build.aapt.AaptUtil.collectResource(AaptUtil.java:93)
	... 30 more

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。
