### ISSUE TITLE
clean project后再生成补丁合并补丁失败

### ISSUE THREAD

**Issue by miaosen** [Tencent/tinker#720]
异常类型：app运行时异常

手机型号：华为平板m3

app编译版本：Android 4.4

手机系统版本：Android 6.0

tinker版本：1.8.0

gradle版本：如:2.3.3

是否使用热更新SDK： 否

系统：如:windows7

堆栈/日志：
`
E: Bad dex jar file: /data/user/0/com.gzpykj.rcms/tinker/patch-b3e69c14/dex/classes.dex.jar
   java.io.FileNotFoundException: /data/user/0/com.gzpykj.rcms/tinker/patch-b3e69c14/dex/classes.dex.jar: open failed: ENOENT (No such file or directory)
       at libcore.io.IoBridge.open(IoBridge.java:459)
       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
       at java.util.zip.ZipFile.<init>(ZipFile.java:170)
       at java.util.zip.ZipFile.<init>(ZipFile.java:131)
       at com.tencent.tinker.loader.shareutil.SharePatchFileUtil.verifyDexFileMd5(SharePatchFileUtil.java:254)
       at com.tencent.tinker.loader.shareutil.SharePatchFileUtil.verifyDexFileMd5(SharePatchFileUtil.java:239)
       at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(DexDiffPatchInternal.java:525)
       at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:172)
       at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85)
       at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136)
       at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.os.HandlerThread.run(HandlerThread.java:61)
    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Posix.open(Native Method)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
       at libcore.io.IoBridge.open(IoBridge.java:445)
       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117) 
       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149) 
       at java.util.zip.ZipFile.<init>(ZipFile.java:170) 
       at java.util.zip.ZipFile.<init>(ZipFile.java:131) 
       at com.tencent.tinker.loader.shareutil.SharePatchFileUtil.verifyDexFileMd5(SharePatchFileUtil.java:254) 
       at com.tencent.tinker.loader.shareutil.SharePatchFileUtil.verifyDexFileMd5(SharePatchFileUtil.java:239) 
       at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(DexDiffPatchInternal.java:525) 
       at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(DexDiffPatchInternal.java:172) 
       at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(DexDiffPatchInternal.java:85) 
       at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(UpgradePatch.java:136) 
       at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(TinkerPatchService.java:129) 
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:150) 
       at android.os.HandlerThread.run(HandlerThread.java:61) `

**Comment by tomystang** [comment]
检查下整个编base包和patch包的操作流程有没有问题？

**Comment by miaosen** [comment]
谢谢！流程没问题。找到原因了，在新线程调用安装方法TinkerInstaller.onReceiveUpgradePatch()就会出现这个错误，之后在UI线程重试也一直是这个错误，不是clean的造成的，解决方法是回到UI线程加载补丁；
我默认从网络加载补丁然后重试的时候是取离线的，测试的时候发现断网时加载补丁成功联网时加载失败才想到是这个问题
