### ISSUE TITLE
Tinker Exception:can't recognize dex mode:0,jar

### ISSUE THREAD

**Issue by jinxiaojing** [Tencent/tinker#721]
异常类型：合并补丁包异常
手机型号：

手机系统版本：如:Android 7.0 (如是编译异常，则可以不填)

tinker版本：如:release

gradle版本：如3.3

Bugly SDK

系统：如:win
Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:can't recognize dex mode:0,jar
                                                                    at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.<init>(BUGLY:65)
                                                                    at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.parseDexDiffPatchInfo(BUGLY:92)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(BUGLY:273)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(BUGLY:166)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(BUGLY:79)
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(BUGLY:133)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(BUGLY:129)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)

 TinkerResultService receive result: 
                                                               PatchResult: 
                                                               isSuccess:false
                                                               rawPatchFilePath:/data/data/com.wanplus.wp/app_tmpPatch/tmpPatch.apk
                                                               costTime:60
                                                               Throwable:Tinker Exception:can't recognize dex mode:0,jar

**Comment by jinxiaojing** [comment]
TinkerManager: onDownloadSuccess.
12-14 16:58:00.992 18849-18849/? D/Tinker.TinkerManager: check if has new patch.
12-14 16:58:01.007 18849-18849/? D/Tinker.TinkerManager: has new patch.
12-14 16:58:01.009 18849-18849/? D/Tinker.TinkerManager: starting patch.
12-14 16:58:01.009 18849-18849/? I/Tinker.TinkerPatchListener: receive a patch file: /data/user/0/com.wanplus.wp/app_tmpPatch/tmpPatch.apk, file size:9619
12-14 16:58:01.024 18849-18849/? I/Tinker.TinkerPatchListener: get platform:null
12-14 16:58:01.045 1261-2572/? I/ActivityManager: Start proc 19056:com.wanplus.wp:patch/u0a317 for service com.wanplus.wp/com.tencent.tinker.lib.service.TinkerPatchService
12-14 16:58:01.115 19056-19056/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
12-14 16:58:01.115 19056-19056/? D/Tinker.DefaultAppLike: onBaseContextAttached:
12-14 16:58:01.116 19056-19056/? I/Tinker.ReflectApp: with app realApplication from manifest applicationName:com.wanplus.wp.app.WanPlusApp
12-14 16:58:01.119 19056-19056/? I/Tinker.TinkerPatchListener: application maxMemory:256
12-14 16:58:01.121 19056-19056/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.wanplus.wp/tinker
12-14 16:58:01.121 19056-19056/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.7.11
12-14 16:58:01.121 19056-19056/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.wanplus.wp:patch, main process:false, systemOTA:false, oatDir:null, useInterpretMode:false
12-14 16:58:01.121 19056-19056/? W/Tinker.TinkerLoadResult: tinker is disable, just return
12-14 16:58:01.121 19056-19056/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.wanplus.wp/tinker, code: -1, cost: 6ms
12-14 16:58:01.122 19056-19056/? W/Tinker.Tinker: tinker load fail!
12-14 16:58:01.123 19056-19056/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
12-14 16:58:01.127 19056-19056/? D/Tinker.DefaultAppLike: onCreate
12-14 16:58:01.259 19056-19056/? I/art:     at void com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.onCreate() (BUGLY:189)
12-14 16:58:01.259 19056-19056/? I/art:     at void com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.onCreate() (BUGLY:189)
12-14 16:58:01.286 19056-19056/? I/art:     at void com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.onCreate() (BUGLY:189)
12-14 16:58:01.287 19056-19056/? I/art:     at void com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.onCreate() (BUGLY:189)
12-14 16:58:01.351 19056-19097/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
12-14 16:58:01.353 19056-19097/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.wanplus.wp/tinker_temp/temp.apk
12-14 16:58:01.359 19056-19097/? W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
12-14 16:58:01.363 19056-19056/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
12-14 16:58:01.365 19056-19097/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.wanplus.wp/tinker_temp/temp.apk
12-14 16:58:01.366 19056-19097/? W/Tinker.UpgradePatchRetry: onPatchServiceStart retry more than max count, delete retry info file!
12-14 16:58:01.366 19056-19097/? I/Tinker.TinkerPatchService: try to increase patch process priority
12-14 16:58:01.368 1261-1340/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.wanplus.wp/com.tencent.tinker.lib.service.TinkerPatchService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0))
12-14 16:58:01.383 1261-1340/? V/ActivityManager: Attempted to start a foreground service (ComponentInfo{com.wanplus.wp/com.tencent.tinker.lib.service.TinkerPatchService$InnerService}) with a broken notification (no icon: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0))
12-14 16:58:01.409 19056-19097/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:ecb0184adf844986c961135a4a1a2d45
12-14 16:58:01.413 19056-19097/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.wanplus.wp/tinker/patch.info (No such file or directory)
12-14 16:58:01.413 19056-19097/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.wanplus.wp/tinker/patch.info (No such file or directory)
12-14 16:58:01.413 19056-19097/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.wanplus.wp/tinker/patch-ecb0184a
12-14 16:58:01.414 19056-19097/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /data/user/0/com.wanplus.wp/app_tmpPatch/tmpPatch.apk size: 9619, dest file: /data/user/0/com.wanplus.wp/tinker/patch-ecb0184a/patch-ecb0184a.apk size:9619
12-14 16:58:01.415 19056-19097/? I/Tinker.DefaultPatchReporter: patchReporter onPatchException: patch exception path: /data/user/0/com.wanplus.wp/app_tmpPatch/tmpPatch.apk, throwable: Tinker Exception:can't recognize dex mode:0,ja
