### ISSUE TITLE
使用命令行生成patch报错

### ISSUE THREAD

**Issue by Cloud-lys** [Tencent/tinker#723]
异常类型：使用命令行生成patch报错

手机型号：

手机系统版本：使用的sdk26

tinker版本：1.9.2.jar

gradle版本：3.0.0

是否使用热更新SDK： 否

系统：Window

UnZipping apk to C:\Users\lys\Desktop\TinkerDemo\out\old
UnZipping apk to C:\Users\lys\Desktop\TinkerDemo\out\new
Check for loader classes in dex: classes.dex
com.tencent.tinker.android.dex.DexException: com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
        at com.tencent.tinker.android.dex.Dex.<init>(Dex.java:142)
        at com.tencent.tinker.build.util.ExcludedClassModifiedChecker.checkIfExcludedClassWasModifiedInNewDex(ExcludedClassModifiedChecker.java:76)
        at com.tencent.tinker.build.decoder.DexDiffDecoder.patch(DexDiffDecoder.java:136)
        at com.tencent.tinker.build.decoder.UniqueDexDiffDecoder.patch(UniqueDexDiffDecoder.java:39)
        at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:176)
        at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:138)
        at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
        at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
        at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:113)
        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
        at com.tencent.tinker.patch.CliMain.run(CliMain.java:106)
        at com.tencent.tinker.patch.CliMain.main(CliMain.java:54)
Caused by: com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
        at com.tencent.tinker.android.dex.TableOfContents.readHeader(TableOfContents.java:159)
        at com.tencent.tinker.android.dex.TableOfContents.readFrom(TableOfContents.java:145)
        at com.tencent.tinker.android.dex.Dex.loadFrom(Dex.java:171)
        at com.tencent.tinker.android.dex.Dex.<init>(Dex.java:140)
        ... 11 more
java.lang.RuntimeException: com.tencent.tinker.android.dex.DexException: com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
        at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:179)
        at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:138)
        at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
        at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
        at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:113)
        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
        at com.tencent.tinker.patch.CliMain.run(CliMain.java:106)
        at com.tencent.tinker.patch.CliMain.main(CliMain.java:54)
Caused by: com.tencent.tinker.android.dex.DexException: com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
        at com.tencent.tinker.android.dex.Dex.<init>(Dex.java:142)
        at com.tencent.tinker.build.decoder.DexDiffDecoder.collectAddedOrDeletedClasses(DexDiffDecoder.java:523)
        at com.tencent.tinker.build.decoder.DexDiffDecoder.patch(DexDiffDecoder.java:172)
        at com.tencent.tinker.build.decoder.UniqueDexDiffDecoder.patch(UniqueDexDiffDecoder.java:39)
        at com.tencent.tinker.build.decoder.ApkDecoder$ApkFilesVisitor.visitFile(ApkDecoder.java:176)
        ... 7 more
Caused by: com.tencent.tinker.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
        at com.tencent.tinker.android.dex.TableOfContents.readHeader(TableOfContents.java:159)
        at com.tencent.tinker.android.dex.TableOfContents.readFrom(TableOfContents.java:145)
        at com.tencent.tinker.android.dex.Dex.loadFrom(Dex.java:171)
        at com.tencent.tinker.android.dex.Dex.<init>(Dex.java:140)
        ... 11 more

使用命令行java -jar tinker.jar -old old.apk -new new.apk -config tinker_config.xml -out output_path
如果仅仅是layout有差异,可以生成patch
但是如果有代码上的差异时(我在方法里面增加了个toast弹框),patch文件便无法生成
看上述信息,感觉像是反编译的时候失败了,但是不太确定,也无从下手,求助

**Comment by Cloud-lys** [comment]
又尝试了一下,如果是通过gradle 2.14.1然后对应依赖全部降低就没问题,

感觉是gradle 3.0.0的不兼容
