### ISSUE TITLE
依赖的aar包中出现转换异常

### ISSUE THREAD

**Issue by KZax1l** [Tencent/tinker#727]
异常类型：java.lang.ClassCastException

手机型号：华为荣耀8 FRD-AL00

手机系统版本：Android 7.0

tinker版本：com.tencent.bugly:tinker-support:1.1.1

gradle版本：3.3

是否使用热更新SDK：使用的是Bugly的tinker-support

系统：Windows

堆栈/日志：
java.lang.ClassCastException: com.example.administrator.tinker.WorkApplication cannot be cast to com.example.app_support.AppSupportApplication
     at com.example.app_support.AppSupportActivity.onCreate(AppSupportActivity.java:20)
     at com.example.administrator.tinker.SettingsActivity.onCreate(SettingsActivity.java:15)
     at android.app.Activity.performCreate(Activity.java:6915)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
     at android.app.ActivityThread.-wrap12(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
     at android.os.Handler.dispatchMessage(Handler.java:105)
     at android.os.Looper.loop(Looper.java:156)
     at android.app.ActivityThread.main(ActivityThread.java:6523)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

刚开始提示`Class ref in pre-verified class resolved to unexpected implementation`错误，然后根据官方提示配置了dexLoader，在4.1.1的模拟器上测试，没问题了，但在真机荣耀8上运行就出现上面的问题了，不知道是怎么回事。

**Comment by KZax1l** [comment]
经测试，是Bugly中tinker-support的问题，换成tinker就没问题了。
