### ISSUE TITLE
Android 7.0 补丁修复后  云信sdk服务崩溃

### ISSUE THREAD

**Issue by liuliuh** [Tencent/tinker#728]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：如:小米 华为等(如是编译异常，则可以不填)

手机系统版本 ：Android 7.0 (如是编译异常，则可以不填)

tinker版本：如:1.9.1

gradle版本：如:2.10

是否使用热更新SDK： Bugly SDK

系统：如:Mac

堆栈/日志：
12-26 13:52:32.186 22430-22430/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Unable to start service com.netease.nimlib.service.ResponseService@b82e6a1 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.netease.nimlib.j.b.a.a(java.lang.String, java.lang.String)' on a null object reference
12-26 13:52:32.187 22430-22430/? E/Tinker.TinkerUncaughtExceptionHandler: tinker has fast crash 1 times
12-26 13:52:32.187 22430-22430/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to start service com.netease.nimlib.service.ResponseService@b82e6a1 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.netease.nimlib.j.b.a.a(java.lang.String, java.lang.String)' on a null object reference
                                                               at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3314)
                                                               at android.app.ActivityThread.-wrap21(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                            Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.netease.nimlib.j.b.a.a(java.lang.String, java.lang.String)' on a null object reference
                                                               at com.netease.nimlib.j.b.b.a.s(Unknown Source)
                                                               at com.netease.nimlib.service.ResponseService.onStartCommand(Unknown Source)
                                                               at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3297)
                                                               at android.app.ActivityThread.-wrap21(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:154) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
                                                           
                                                           
                                                           --------- beginning of crash
12-26 13:52:32.255 22470-22470/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Unable to create service com.netease.nimlib.service.NimService: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.netease.nimlib.j.b.a.a(java.lang.String, java.lang.String)' on a null object reference
12-26 13:52:32.257 22470-22470/? E/Tinker.TinkerUncaughtExceptionHandler: tinker has fast crash 2 times
12-26 13:52:32.258 22470-22470/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to create service com.netease.nimlib.service.NimService: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.netease.nimlib.j.b.a.a(java.lang.String, java.lang.String)' on a null object reference
                                                               at android.app.ActivityThread.handleCreateService(ActivityThread.java:3172)
                                                               at android.app.ActivityThread.-wrap5(ActivityThread.java)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:154)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                            Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.netease.nimlib.j.b.a.a(java.lang.String, java.lang.String)' on a null object reference
                                                               at com.netease.nimlib.j.b.b.a.t(Unknown Source)
                                                               at com.netease.nimlib.service.NimService.onCreate(Unknown Source)
                                                               at android.app.ActivityThread.handleCreateService(ActivityThread.java:3162)
                                                               at android.app.ActivityThread.-wrap5(ActivityThread.java) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                               at android.os.Looper.loop(Looper.java:154) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by xuyunqiang** [comment]
请问你解决了么   我也遇到7.0系统上 也接入云信sdk 补丁无效的问题  方便的话 加个我qq 1539140295 一起讨论下

**Comment by shwenzhang** [comment]
bugly版本的tinker的问题，请在sample工程尝试是否可以复现

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。
