### ISSUE TITLE
补丁下载成功，应用失败

### ISSUE THREAD

**Issue by yychai** [Tencent/tinker#736]
使用bugly-tinker的时候补丁包合成和下载都是成功的，但是提示补丁应用失败，异常如下：

```
异常类型：app运行时异常

手机型号：google pixel XL

手机系统版本：Android 7.1.2

tinker版本：bugly tinker support 1.1.1 (tinker 1.9.0)

gradle版本：如:3.0.1

是否使用热更新SDK：使用了 Bugly SDK

系统：如:Windows10

堆栈/日志：
Tinker.DefaultPatchReporter: tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:can't recognize dex mode:2179262980,jar
                                                                    at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.<init>(SourceFile:65)
                                                                    at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.parseDexDiffPatchInfo(SourceFile:92)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(SourceFile:273)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(SourceFile:166)
                                                                    at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(SourceFile:79)
                                                                    at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(SourceFile:133)
                                                                    at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(SourceFile:129)
                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)

01-03 16:10:16.793 24749-24749/? E/yychai: PatchResult: 
                                           isSuccess:false
                                           rawPatchFilePath:/data/user/0/com.iflytek.ringdiyclient/app_tmpPatch/tmpPatch.apk
                                           costTime:61
                                           Throwable:Tinker Exception:can't recognize dex mode:2179262980,jar

**Comment by tomystang** [comment]
如果你除了bugly的包之外还引入了tinker的包，要保证bugly里的tinker和你引入的tinker版本一致才行的

**Comment by yychai** [comment]
多谢回复，确实是这个问题，bugly-tinker的文档没有最新的更新，我接入的时候使用了support 1.1.1，但是bugly:crashreport_upgrade:使用的是1.3.1，换成使用1.3.4现在可以接入正常打补丁了！多谢！

**Comment by Archer-cat** [comment]
你好  我用的最新官方的Bugly Android热更新使用指南   也是到下载成功了 补丁应用失败,这个和multidex  依赖的版本有关系吗  我用的androidx.multidex:multidex:2.0.1
