### ISSUE TITLE
7.1手机合成patch重启崩溃

### ISSUE THREAD

**Issue by xueweiyang** [Tencent/tinker#741]
异常类型：app运行时异常

手机型号：小米Note3

手机系统版本：如:Android 7.1

bugly版本：如:1.1.1

gradle版本：如:3.0.1

是否使用热更新SDK： Bugly SDK

系统：如:Mac

堆栈/日志：
01-09 09:50:44.871 30437-30513/com.qeeniao.mobile.kdjz E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:com.alibaba.wireless.security.mainplugin.SecurityGuardMainPlugin cannot be cast to com.alibaba.wireless.security.open.initialize.ISecurityGuardPlugin
01-09 09:50:44.880 30437-30513/com.qeeniao.mobile.kdjz E/Tinker.TinkerUncaughtExceptionHandler: tinker has fast crash 1 times
01-09 09:50:44.880 30437-30513/com.qeeniao.mobile.kdjz E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.ClassCastException: com.alibaba.wireless.security.mainplugin.SecurityGuardMainPlugin cannot be cast to com.alibaba.wireless.security.open.initialize.ISecurityGuardPlugin
                                                                                     at com.alibaba.wireless.security.framework.b.a(Unknown Source)
                                                                                     at com.alibaba.wireless.security.framework.b.c(Unknown Source)
                                                                                     at com.alibaba.wireless.security.framework.b.c(Unknown Source)
                                                                                     at com.alibaba.wireless.security.open.initialize.b.a(Unknown Source)
                                                                                     at com.alibaba.wireless.security.open.initialize.c.run(Unknown Source)
                                                                                     at java.lang.Thread.run(Thread.java:760)

看了一些issue，版本也升级到最新了，可还是有问题

**Comment by simpleton** [comment]
使用了相关的加固？`alibaba.wireless.security.mainplugin`是什么sdk呢？

**Comment by xueweiyang** [comment]
嗯，已经解决了，改变sdk初始化的顺序就好了
