### ISSUE TITLE
资源修复成功，但是修复代码却失败，5.0以下会出现

### ISSUE THREAD

**Issue by BuleB** [Tencent/tinker#761]
异常类型：app运行时异常

手机型号：小米pad2 4.4.4，红米 4.2.1

手机系统版本：Android 5.0以下都会出现问题，试过了5.0,6.0,7.0的手机

tinker版本：如:1.9.1

gradle版本：如:2.3.3

是否使用热更新SDK： 否

系统：如:WIN10

堆栈/日志：
.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application ***.***.***.***.OwnApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598)
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:162)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                               at android.os.Looper.loop(Looper.java:153)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5383)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                               at dalvik.system.NativeStart.main(Native Method)
                                                            Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:114)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
                                                               at ***.***.***.***.OwnApplication.attachBaseContext(OwnApplication.java:29)
                                                               at android.app.Application.attach(Application.java:157)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:984)
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:968)
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598) 
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:153) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5383) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: java.lang.ClassNotFoundException: ***.***.***.***.App
                                                               at java.lang.Class.classForName(Native Method)
                                                               at java.lang.Class.forName(Class.java:217)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108)
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                               at ***.***.***.***.OwnApplication.attachBaseContext(OwnApplication.java:29) 
                                                               at android.app.Application.attach(Application.java:157) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:984) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:968) 
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598) 
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:153) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5383) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: java.lang.NoClassDefFoundError: com/zhl/enteacher/aphone/App
                                                               at java.lang.Class.classForName(Native Method) 
                                                               at java.lang.Class.forName(Class.java:217) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                               at ***.***.***.***.OwnApplication.attachBaseContext(OwnApplication.java:29) 
                                                               at android.app.Application.attach(Application.java:157) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:984) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:968) 
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598) 
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:153) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5383) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                            Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                               at dalvik.system.DexFile.defineClass(Native Method)
                                                               at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:211)
                                                               at dalvik.system.DexPathList.findClass(DexPathList.java:302)
                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:51)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                               at java.lang.Class.classForName(Native Method) 
                                                               at java.lang.Class.forName(Class.java:217) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                               at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                               at ***.***.***.***.OwnApplication.attachBaseContext(OwnApplication.java:29) 
                                                               at android.app.Application.attach(Application.java:157) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:984) 
                                                               at android.app.Instrumentation.newApplication(Instrumentation.java:968) 
                                                               at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598) 
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:153) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:5383) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                               at dalvik.system.NativeStart.main(Native Method) 
01-30 09:48:14.701 11829-11829/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.RuntimeException: Unable to instantiate application ***.***.***.***.OwnApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598)
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:162)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:153)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5383)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                       at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:114)
                                                       at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)
                                                       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)
                                                       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
                                                       at ***.***.***.***.OwnApplication.attachBaseContext(OwnApplication.java:29)
                                                       at android.app.Application.attach(Application.java:157)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:984)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:968)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598) 
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:153) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5383) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.ClassNotFoundException: ***.***.***.***.App
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.Class.forName(Class.java:217)
                                                       at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108)
                                                       at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                       at ***.***.***.***.OwnApplication.attachBaseContext(OwnApplication.java:29) 
                                                       at android.app.Application.attach(Application.java:157) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:984) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:968) 
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598) 
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:153) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5383) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.NoClassDefFoundError: com/zhl/enteacher/aphone/App
                                                       at java.lang.Class.classForName(Native Method) 
                                                       at java.lang.Class.forName(Class.java:217) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                       at ***.***.***.***.OwnApplication.attachBaseContext(OwnApplication.java:29) 
                                                       at android.app.Application.attach(Application.java:157) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:984) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:968) 
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598) 
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:153) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5383) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                       at dalvik.system.DexFile.defineClass(Native Method)
                                                       at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:211)
                                                       at dalvik.system.DexPathList.findClass(DexPathList.java:302)
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:51)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                       at java.lang.Class.classForName(Native Method) 
                                                       at java.lang.Class.forName(Class.java:217) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                       at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                       at ***.***.***.***.OwnApplication.attachBaseContext(OwnApplication.java:29) 
                                                       at android.app.Application.attach(Application.java:157) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:984) 
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:968) 
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4598) 
                                                       at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                       at android.os.Looper.loop(Looper.java:153) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5383) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:511) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                       at dalvik.system.NativeStart.main(Native Method) 

----
想请大佬帮忙定位下问题，昨天下午出现的，我已经看了很久issue,也尝试排除一些问题，发现修改代码会导致这种崩溃，修改资源却不会问题！所以想请帮忙定位下问题！劳烦大家

**Comment by BuleB** [comment]
问题解决了，我在这个地方写错了，之前是写的App,也就是实现类
![image](https://user-images.githubusercontent.com/11595221/35550813-0e771284-05c7-11e8-80cf-16d7a4dfb783.png)
