### ISSUE TITLE
适配Android 8 后台服务限制

### ISSUE THREAD

**Issue by blackberry2016** [Tencent/tinker#763]
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

```
IntentService is a service, and is therefore subject to the new restrictions on background services. As a result, many apps that rely on IntentService do not work properly when targeting Android 8.0 or higher
```

**Comment by iluhcm** [comment]
有一个类似的问题，不过是ZUK厂商的低版本机型，

```
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid service notification: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1525)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5504)
```

机型：ZUK Z2121  
系统版本：6.0.1

产生原因应该是`TinkerPatchService#increasingPriority#startForeground`(L160)导致的。

**Comment by tomystang** [comment]
已在1.9.5版本上修复。
