### ISSUE TITLE
部分手机运行crash 

### ISSUE THREAD

**Issue by wxrOL** [Tencent/tinker#779]
异常类型：app运行时异常

手机型号： oppo R7s

手机系统版本：Android 4.4.4

tinker版本：1.9.1

gradle版本：4.4

是否使用热更新SDK： bugly sdk 未开启热更新

系统：Mac

堆栈/日志：
Process: com.tongzhuo.tongzhuogame, PID: 6729
                                                                         java.lang.RuntimeException: Unable to instantiate application com.tongzhuo.tongzhuogame.app.App: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:519)
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4678)
                                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:174)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                             at android.os.Looper.loop(Looper.java:229)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
                                                                             at dalvik.system.NativeStart.main(Native Method)
                                                                          Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:114)
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:120)
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:133)
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:148)
                                                                             at android.app.Application.attach(Application.java:181)
                                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:514)
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4678) 
                                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:174) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                             at android.os.Looper.loop(Looper.java:229) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5493) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
                                                                             at dalvik.system.NativeStart.main(Native Method) 
                                                                          Caused by: java.lang.VerifyError: com/tongzhuo/tongzhuogame/app/AppLike
                                                                             at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                             at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(BUGLY:111)
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(BUGLY:120) 
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:133) 
                                                                             at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:148) 
                                                                             at android.app.Application.attach(Application.java:181) 
                                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:514) 
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4678) 
                                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:174) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                             at android.os.Looper.loop(Looper.java:229) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5493) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
                                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by gdky005** [comment]
可以尝试下这个。

这个问题并不是 tinker 的问题，而是在分包的时候，这个类依赖的类，没有被打到主 dex 里面，所以要排查 这个类 继承的类，还有实现的类，是否都在主 dex 里面。

具体问题错误原因是： 找不到依赖的类，所以无法初始化该类，抛出了找不到类异常。



总结就是：遇到找不到类的错误，不一定是 真的找不到这个类（大多数是这个），也可能是这个类依赖的类找不到。 

我的问题就是，CallBack 没有在主 Dex 里面。
![image](https://user-images.githubusercontent.com/3477872/37751449-90ed7c16-2dcd-11e8-8378-8878f0428923.png)

留给后人。

**Comment by liufsd** [comment]
我的没有继承类了的。在5.1设备上是可以的，在4.4设备启动就crash了的。同一个包。

**Comment by gdky005** [comment]
你这个肯定是分包的问题，试试  keep_main_dex 。

**Comment by liufsd** [comment]
嗯 我加了keep，在5.1的设备正常。4.4的设备跑不起来。我看了下dex里面有的。然而还是crash。

**Comment by gdky005** [comment]
给你分享我的一个处理方法吧。

把之前可以在 4.4 运行打包成功 Apk 节点的 keep_main_dex 复制一份，放到 你最新的 dexknife 的配置文件里面。应该没问题，如果还是报错的话，看看错误日志缺少什么，就再加一份。

忘记说了，我使用的 dexkinfe 的分包策略。 能崩溃，说明你此刻 AS 的分配已经出问题了，或者说 你 keep 的太多了，需要换条路走走。

**Comment by liufsd** [comment]
我keep里面写的就是，tinker自动生成的的那个配置文件。
所以我的问题是：难道是因为我的Application初始化的东西比多，而初始化会引入一些类，分包之后这些类找不到了的，所以导致tinker初始化app的时候crash？单独keep tinker不够？？？

**Comment by gdky005** [comment]
看你的项目吧。如果一直崩溃，可以尝试 dexkinfe。

**Comment by liufsd** [comment]
我看了一下，  我的apk里面第一个dex中有tinker的。依旧crash。sorry，我不太熟悉这一块机制。但应该你说的没错，就是分包的问题。不过不清楚为什么5.1的设备跑起来是好好的呢？ 同一个apk.

**Comment by liufsd** [comment]
估计是这个说法吧：

```
5.0以上系统本身支持multidex，install其实是没运行的。
Application类中有import的类都必须在第一个dex中，和install前后没有关系。CLassLoader 在加载Application类时如果找不到import就会出错，加载时机要远早于 multidex.install
```
