### ISSUE TITLE
加载补丁后异常Rejecting class ryxq.bqt because it failed compile-time verification

### ISSUE THREAD

**Issue by balizhuang2012** [Tencent/tinker#780]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：vivo vivo X6D
手机系统版本：如:Android 5.1

tinker版本：如:1.9.2

gradle版本：如:2.3.3

是否使用热更新SDK： 否

系统：如:Mac

堆栈/日志：
java.lang.VerifyError: Rejecting class ryxq.bqt because it failed compile-time verification (declaration of 'ryxq.bqt' appears in /data/data/com.duowan.kiwi/tinker/patch-06df221e/dex/tinker_classN.apk:classes4.dex)
	at ryxq.bpu.a(ViewHolderBinder.java:358)
	at com.duowan.kiwi.homepage.tab.BaseRecommendFragment.a(BaseRecommendFragment.java:763)
	at com.duowan.biz.ui.PullAbsListFragment$1.b(PullAbsListFragment.java:225)
	at ryxq.ajy.a(ArkAdapter.java:257)
	at ryxq.ajy.a(ArkAdapter.java:296)
	at ryxq.ajy.getView(ArkAdapter.java:241)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2542)
	at android.widget.ListView.makeAndAddView(ListView.java:1894)
	at android.widget.ListView.fillDown(ListView.java:710)
	at android.widget.ListView.fillFromTop(ListView.java:771)
	at android.widget.ListView.layoutChildren(ListView.java:1681)
	at android.widget.AbsListView.onLayout(AbsListView.java:2294)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1195)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1959)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1813)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1722)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:639)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:574)
	at android.view.View.layout(View.java:16001)
	at android.view.ViewGroup.layout(ViewGroup.java:5181)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2569)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2244)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1307)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6697)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:822)
	at android.view.Choreographer.doCallbacks(Choreographer.java:625)
	at android.view.Choreographer.doFrame(Choreographer.java:594)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:808)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5714)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by balizhuang2012** [comment]
之前看见这个issues，已经被关了，但新版本tinker还是有类似问题。
出问题的类反编译看了，确实也有aput指令。
https://github.com/Tencent/tinker/issues/491

**Comment by balizhuang2012** [comment]
如何上传附件呢，我想上传一下相关的类的smali文件
