### ISSUE TITLE
Tinker移入项目运行报错: <

### ISSUE THREAD

**Issue by l114624915** [Tencent/tinker#79]
hi，xxxBaseApplicationLike extends DefaultApplicationLike
onBaseContextAttached中做了自己应用的初始化工作

 private void initUM() {
        PushAgent mPushAgent = PushAgent.getInstance(XXXBaseApplicationContext.context);
        mPushAgent.enable(); 
       ......
}
错误日志见附件
09-28 18:27:52.789 31527-31527/com.xxxx.android E/Tinker.SampleUncaughtExHandler: uncaughtException:Unable to instantiate application com.xxxx.android.base.XXXBaseApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
09-28 18:27:52.807 31527-31527/com.xxxx.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.xxxx.android, PID: 31527
                                                                       java.lang.RuntimeException: Unable to instantiate application com.xxxx.android.base.XXXBaseApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
                                                                           at android.app.LoadedApk.makeApplication(LoadedApk.java:580)
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4699)
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:153)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                        Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onBaseContextAttached method not found
                                                                           at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:140)
                                                                           at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154)
                                                                           at android.app.Application.attach(Application.java:191)
                                                                           at android.app.Instrumentation.newApplication(Instrumentation.java:998)
                                                                           at android.app.Instrumentation.newApplication(Instrumentation.java:982)
                                                                           at android.app.LoadedApk.makeApplication(LoadedApk.java:575)
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4699) 
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:153) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:138)
                                                                           at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154) 
                                                                           at android.app.Application.attach(Application.java:191) 
                                                                           at android.app.Instrumentation.newApplication(Instrumentation.java:998) 
                                                                           at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                                           at android.app.LoadedApk.makeApplication(LoadedApk.java:575) 
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4699) 
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:153) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.content.Context.getMainLooper()' on a null object reference
                                                                           at com.umeng.message.PushAgent.<init>(PushAgent.java:78)
                                                                           at com.umeng.message.PushAgent.getInstance(PushAgent.java:89)
                                                                           at com.xxxx.android.base.XXXBaseApplicationLike.initUM(XXXBaseApplicationLike.java:181)
                                                                           at com.xxxx.android.base.XXXBaseApplicationLike.init(XXXBaseApplicationLike.java:144)
                                                                           at com.xxxx.android.base.XXXBaseApplicationLike.onBaseContextAttached(XXXBaseApplicationLike.java:134)
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:138) 
                                                                           at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:154) 
                                                                           at android.app.Application.attach(Application.java:191) 
                                                                           at android.app.Instrumentation.newApplication(Instrumentation.java:998) 
                                                                           at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
                                                                           at android.app.LoadedApk.makeApplication(LoadedApk.java:575) 
                                                                           at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4699) 
                                                                           at android.app.ActivityThread.access$1600(ActivityThread.java:153) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5438) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by shwenzhang** [comment]
整个逻辑跟之前application的生命周期一致，请确保逻辑正确移动

**Comment by l114624915** [comment]
生命周期没发现问题在LIKE中注释掉三方初始化就可以运行了，

PushAgent mPushAgent = PushAgent.getInstance(XXXBaseApplicationContext.context);
ShareSDK.initSDK(XXXBaseApplicationContext.application);

Tinker对这块有做限制吗？

还有为什么 bakApk文件夹没生成 ，app/buid.gradle是按着sample移的
修改了loader = ["com.tencent.tinker.loader.*",
                      "com.xxx.android.base.xxxBaseApplication",
                      //use sample, let BaseBuildInfo unchangeable with tinker
                      "com.xxx.android.base.BaseBuildInfo"
            ]

**Comment by shwenzhang** [comment]
没有对第三方做限制，需要具体看看第三方的初始化做了什么事情。具体问题具体分析

**Comment by l114624915** [comment]
为什么 bakApk文件夹没生成?  app\build.gradle  中def bakPath = file("${buildDir}/bakApk/")下面部分都是拷贝tinker-sample中的，求助。

**Comment by l114624915** [comment]
<img width="276" alt="error" src="https://cloud.githubusercontent.com/assets/11226749/18940426/ad23ad24-863a-11e6-862a-ac431f6f8d57.png">

**Comment by andrewhunter0** [comment]
我自己加了一句代码：
def bakPath = file("${buildDir}/bakApk/")
if (!bakPath.isFile()) {
    bakPath.mkdir()
}

**Comment by l114624915** [comment]
加了只生成了空的bakApk,应该是没执行 /**
     * bak apk and mapping
     */
    tasks.all {
        if ("assemble${taskName.capitalize()}".equalsIgnoreCase(it.name))
为什么？

**Comment by junyuecao** [comment]
你用了flavor吗？

**Comment by l114624915** [comment]
有  productFlavors {
        XXX {}
    }
    productFlavors.all {
        flavor -> flavor.manifestPlaceholders = [UMENG_CHANNEL_VALUE: name]
    }

**Comment by junyuecao** [comment]
可以手动copy apk到bakApk里，或者像 https://github.com/Tencent/tinker/pull/83 一样改改代码

**Comment by l114624915** [comment]
去掉productFlavors就好了,感谢~~

**Comment by l114624915** [comment]
听说下个版本会支持。
