### ISSUE TITLE
补丁包下发后激活不成功-报异常

### ISSUE THREAD

**Issue by landsnail** [Tencent/tinker#791]
```
异常类型：app运行时异常/编译异常

手机型号：如:红米 note3(如是编译异常，则可以不填)

手机系统版本：如:Android 6.0.1 (如是编译异常，则可以不填)

tinker版本：如:1.1.1

gradle版本：如:4.10

是否使用热更新SDK： 是

系统：如:Mac

堆栈/日志：
Tinker.DefaultPatchReporter: 
tinker patch exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:can't recognize dex mode:1400297053,jar
                                                                  at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.<init>(BUGLY:65)
                                                                  at com.tencent.tinker.loader.shareutil.ShareDexDiffPatchInfo.parseDexDiffPatchInfo(BUGLY:92)
                                                                  at com.tencent.tinker.lib.patch.DexDiffPatchInternal.extractDexDiffInternals(BUGLY:273)
                                                                  at com.tencent.tinker.lib.patch.DexDiffPatchInternal.patchDexExtractViaDexDiff(BUGLY:166)
                                                                  at com.tencent.tinker.lib.patch.DexDiffPatchInternal.tryRecoverDexFiles(BUGLY:79)
                                                                  at com.tencent.tinker.lib.patch.UpgradePatch.tryPatch(BUGLY:133)
                                                                  at com.tencent.tinker.lib.service.TinkerPatchService.onHandleIntent(BUGLY:129)
                                                                  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。
