### ISSUE TITLE
怎么在debug模式下完全禁用tinker

### ISSUE THREAD

**Issue by 08carmelo** [Tencent/tinker#800]
我的目的：  debug模式不编译tinker相关

异常类型：app运行时异常

手机型号：如:华为

手机系统版本：如:Android 4.4 

tinker版本：如:1.9.0

gradle版本：如:3.0.0

我将tinkerEnable = false， 并且注释掉gradle中tinker打包的task代码，再注释掉：TinkerManager.init(this);  编译可以通过，运行时报错：
`03-21 13:37:29.613 15350-15350/com.lubansoft.bimview4phone E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.lubansoft.myluban.application.MyLubanApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:531)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585)
                                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:139)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                                      Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:114)
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
                                                                                         at android.app.Application.attach(Application.java:194)
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:992)
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:976)
                                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:526)
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585) 
                                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                                      Caused by: java.lang.ClassNotFoundException: com.lubansoft.myluban.application.MyLubanApplicationLike
                                                                                         at java.lang.Class.classForName(Native Method)
                                                                                         at java.lang.Class.forName(Class.java:251)
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108)
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                                                         at android.app.Application.attach(Application.java:194) 
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
                                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:526) 
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585) 
                                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                                      Caused by: java.lang.NoClassDefFoundError: com/lubansoft/myluban/application/MyLubanApplicationLike
                                                                                         at java.lang.Class.classForName(Native Method) 
                                                                                         at java.lang.Class.forName(Class.java:251) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                                                         at android.app.Application.attach(Application.java:194) 
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
                                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:526) 
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585) 
                                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                                         at dalvik.system.NativeStart.main(Native Method) 
                                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lubansoft.myluban.application.MyLubanApplicationLike" on path: DexPathList[[zip file "/data/app/com.lubansoft.bimview4phone-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.lubansoft.bimview4phone-2, /vendor/lib, /system/lib, /data/datalib]]
                                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                                         at java.lang.Class.classForName(Native Method) 
                                                                                         at java.lang.Class.forName(Class.java:251) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) 
                                                                                         at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
                                                                                         at android.app.Application.attach(Application.java:194) 
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:992) 
                                                                                         at android.app.Instrumentation.newApplication(Instrumentation.java:976) 
                                                                                         at android.app.LoadedApk.makeApplication(LoadedApk.java:526) 
                                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585) 
                                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:139) 
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) 
                                                                                         at dalvik.system.NativeStart.main(Native Method) 
`

**Comment by xingstarx** [comment]
看这个https://github.com/Tencent/tinker/issues/501

**Comment by yeshengwu** [comment]
在gradle里有apply plugin这条语句   注释掉

**Comment by catdrinker** [comment]
用 gradle 脚本判断当前环境，release就apply tinker的gradle文件即可，当然建议上jenkins构建机会更不影响本地开发

**Comment by 1wayticket** [comment]
def enableTinker = getGradle().getStartParameter().getTaskRequests().toString().contains("Release")
gradle 4.x是生效的

> 在gradle里有apply plugin这条语句： apply from: 'tinker-support.gradle' 注释掉



> 我的目的： debug模式不编译tinker相关
> 
> 异常类型：app运行时异常
> 
> 手机型号：如:华为
> 
> 手机系统版本：如:Android 4.4
> 
> tinker版本：如:1.9.0
> 
> gradle版本：如:3.0.0
> 
> 我将tinkerEnable = false， 并且注释掉gradle中tinker打包的task代码，再注释掉：TinkerManager.init(this); 编译可以通过，运行时报错： `03-21 13:37:29.613 15350-15350/com.lubansoft.bimview4phone E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.lubansoft.myluban.application.MyLubanApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed at android.app.LoadedApk.makeApplication(LoadedApk.java:531) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585) at android.app.ActivityThread.access$1800(ActivityThread.java:139) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:136) at android.app.ActivityThread.main(ActivityThread.java:5294) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:515) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680) at dalvik.system.NativeStart.main(Native Method) Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:114) at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120) at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133) at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) at android.app.Application.attach(Application.java:194) at android.app.Instrumentation.newApplication(Instrumentation.java:992) at android.app.Instrumentation.newApplication(Instrumentation.java:976) at android.app.LoadedApk.makeApplication(LoadedApk.java:526) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585)  at android.app.ActivityThread.access$1800(ActivityThread.java:139)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:136)  at android.app.ActivityThread.main(ActivityThread.java:5294)  at java.lang.reflect.Method.invokeNative(Native Method)  at java.lang.reflect.Method.invoke(Method.java:515)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)  at dalvik.system.NativeStart.main(Native Method)  Caused by: java.lang.ClassNotFoundException: com.lubansoft.myluban.application.MyLubanApplicationLike at java.lang.Class.classForName(Native Method) at java.lang.Class.forName(Class.java:251) at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108) at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)  at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)  at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)  at android.app.Application.attach(Application.java:194)  at android.app.Instrumentation.newApplication(Instrumentation.java:992)  at android.app.Instrumentation.newApplication(Instrumentation.java:976)  at android.app.LoadedApk.makeApplication(LoadedApk.java:526)  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585)  at android.app.ActivityThread.access$1800(ActivityThread.java:139)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:136)  at android.app.ActivityThread.main(ActivityThread.java:5294)  at java.lang.reflect.Method.invokeNative(Native Method)  at java.lang.reflect.Method.invoke(Method.java:515)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)  at dalvik.system.NativeStart.main(Native Method)  Caused by: java.lang.NoClassDefFoundError: com/lubansoft/myluban/application/MyLubanApplicationLike at java.lang.Class.classForName(Native Method)  at java.lang.Class.forName(Class.java:251)  at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108)  at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)  at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)  at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)  at android.app.Application.attach(Application.java:194)  at android.app.Instrumentation.newApplication(Instrumentation.java:992)  at android.app.Instrumentation.newApplication(Instrumentation.java:976)  at android.app.LoadedApk.makeApplication(LoadedApk.java:526)  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585)  at android.app.ActivityThread.access$1800(ActivityThread.java:139)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:136)  at android.app.ActivityThread.main(ActivityThread.java:5294)  at java.lang.reflect.Method.invokeNative(Native Method)  at java.lang.reflect.Method.invoke(Method.java:515)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)  at dalvik.system.NativeStart.main(Native Method)  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lubansoft.myluban.application.MyLubanApplicationLike" on path: DexPathList[[zip file "/data/app/com.lubansoft.bimview4phone-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.lubansoft.bimview4phone-2, /vendor/lib, /system/lib, /data/datalib]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) at java.lang.ClassLoader.loadClass(ClassLoader.java:497) at java.lang.ClassLoader.loadClass(ClassLoader.java:457) at java.lang.Class.classForName(Native Method)  at java.lang.Class.forName(Class.java:251)  at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:108)  at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:120)  at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:133)  at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)  at android.app.Application.attach(Application.java:194)  at android.app.Instrumentation.newApplication(Instrumentation.java:992)  at android.app.Instrumentation.newApplication(Instrumentation.java:976)  at android.app.LoadedApk.makeApplication(LoadedApk.java:526)  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4585)  at android.app.ActivityThread.access$1800(ActivityThread.java:139)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:136)  at android.app.ActivityThread.main(ActivityThread.java:5294)  at java.lang.reflect.Method.invokeNative(Native Method)  at java.lang.reflect.Method.invoke(Method.java:515)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)  at dalvik.system.NativeStart.main(Native Method)  `
