### ISSUE TITLE
补丁合成成功，调用部分页面的databinding提示cast错误，或者no static method 错误

### ISSUE THREAD

**Issue by AndwareSsj** [Tencent/tinker#817]
异常类型：app运行时异常

手机型号：Huawei p9 (EVA-AL10)

手机系统版本：如:Android 7.0 (如是编译异常，则可以不填)

tinker版本：如:1.9.1

gradle版本：如:3.1.0

是否使用热更新SDK： NO

系统：Mac

报错日志：

第一种
```
04-19 10:17:57.687 10057-10057/? E/Tinker.SampleUncaughtExHandler: uncaughtException:No static method a(Landroid/view/View;Landroid/databinding/DataBindingComponent;)Lcom/vstone/wealth/android/a/cf; in class Lcom/vstone/wealth/android/a/cf; or its super classes (declaration of 'com.vstone.wealth.android.a.cf' appears in /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/changed_classes.dex.jar)
04-19 10:17:57.687 10057-10057/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.NoSuchMethodError: No static method a(Landroid/view/View;Landroid/databinding/DataBindingComponent;)Lcom/vstone/wealth/android/a/cf; in class Lcom/vstone/wealth/android/a/cf; or its super classes (declaration of 'com.vstone.wealth.android.a.cf' appears in /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/changed_classes.dex.jar)
        at android.databinding.DataBinderMapper.getDataBinder(DataBinderMapper.java:37)
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:173)
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:140)
        at com.vstone.wealth.android.base.BaseFragment.onCreateView(BaseFragment.java:90)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onStart(RxAppCompatActivity.java:66)
        at com.vstone.wealth.android.base.BaseActivity.onStart(BaseActivity.java:121)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
        at android.app.Activity.performStart(Activity.java:6935)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
04-19 10:17:57.688 10057-10057/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vstone.wealth.android, PID: 10057
    java.lang.NoSuchMethodError: No static method a(Landroid/view/View;Landroid/databinding/DataBindingComponent;)Lcom/vstone/wealth/android/a/cf; in class Lcom/vstone/wealth/android/a/cf; or its super classes (declaration of 'com.vstone.wealth.android.a.cf' appears in /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/changed_classes.dex.jar)
        at android.databinding.DataBinderMapper.getDataBinder(DataBinderMapper.java:37)
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:173)
        at android.databinding.DataBindingUtil.bind(DataBindingUtil.java:140)
        at com.vstone.wealth.android.base.BaseFragment.onCreateView(BaseFragment.java:90)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onStart(RxAppCompatActivity.java:66)
        at com.vstone.wealth.android.base.BaseActivity.onStart(BaseActivity.java:121)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
        at android.app.Activity.performStart(Activity.java:6935)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

第二种
```
04-19 10:22:06.664 10408-10408/? E/Tinker.SampleUncaughtExHandler: uncaughtException:Unable to start activity ComponentInfo{com.vstone.wealth.android/com.vstone.wealth.android.ui.activity.SearchActivity}: java.lang.ClassCastException: com.vstone.wealth.android.a.dj cannot be cast to com.vstone.wealth.android.a.hq
04-19 10:22:06.665 10408-10408/? E/Tinker.TinkerApplicationHelper: it is not safety to clean patch when tinker is loaded, you should kill all your process after clean!
04-19 10:22:06.665 10408-10408/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/info.lock
    safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/patch-b06d788a.apk
    safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/changed_classes.dex.jar
    safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/tinker_classN.apk
    safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex
    safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex/changed_classes.dex.dex
04-19 10:22:06.666 10408-10408/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex/tinker_classN.dex
    safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex
    safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a
    safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch.info
    safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker
04-19 10:22:06.666 10408-10408/? E/Tinker.SampleUncaughtExHandler: tinker has fast crash more than 3, we just clean patch!
04-19 10:22:06.666 10408-10408/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vstone.wealth.android/com.vstone.wealth.android.ui.activity.SearchActivity}: java.lang.ClassCastException: com.vstone.wealth.android.a.dj cannot be cast to com.vstone.wealth.android.a.hq
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.ClassCastException: com.vstone.wealth.android.a.dj cannot be cast to com.vstone.wealth.android.a.hq
        at com.vstone.wealth.android.ui.fragment.search.SearchFragment.e(SearchFragment.java:90)
        at com.vstone.wealth.android.base.BaseFragment.onCreateView(BaseFragment.java:92)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onStart(RxAppCompatActivity.java:66)
        at com.vstone.wealth.android.base.BaseActivity.onStart(BaseActivity.java:121)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
        at android.app.Activity.performStart(Activity.java:6935)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
    
    
    --------- beginning of crash
```

合成日志：

```
04-19 10:24:22.642 11572-11572/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.vstone.wealth.android/tinker
04-19 10:24:22.649 11572-11572/? I/Tinker.SamplePatchListener: application maxMemory:384
04-19 10:24:22.649 11572-11572/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.vstone.wealth.android/tinker
04-19 10:24:22.649 11572-11572/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
04-19 10:24:22.649 11572-11572/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.vstone.wealth.android, main process:true, systemOTA:false, fingerPrint:HUAWEI/EVA-AL10/HWEVA:7.0/HUAWEIEVA-AL10/C00B399SP02:user/release-keys, oatDir:null, useInterpretMode:false
04-19 10:24:22.650 11572-11572/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
04-19 10:24:22.650 11572-11572/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.vstone.wealth.android/tinker, code: -2, cost: 1ms
04-19 10:24:22.650 11572-11572/? W/Tinker.Tinker: tinker load fail!
04-19 10:24:22.662 11572-11572/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
04-19 10:24:23.786 11675-11675/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.vstone.wealth.android/tinker
04-19 10:24:23.793 11675-11675/? I/Tinker.SamplePatchListener: application maxMemory:384
04-19 10:24:23.794 11675-11675/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.vstone.wealth.android/tinker
04-19 10:24:23.794 11675-11675/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
04-19 10:24:23.794 11675-11675/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.vstone.wealth.android:filedownloader, main process:false, systemOTA:false, fingerPrint:HUAWEI/EVA-AL10/HWEVA:7.0/HUAWEIEVA-AL10/C00B399SP02:user/release-keys, oatDir:null, useInterpretMode:false
04-19 10:24:23.794 11675-11675/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
04-19 10:24:23.794 11675-11675/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.vstone.wealth.android/tinker, code: -2, cost: 1ms
04-19 10:24:23.794 11675-11675/? W/Tinker.Tinker: tinker load fail!
04-19 10:24:23.796 11675-11675/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
04-19 10:24:23.943 11572-11572/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/com.vstone.wealth.android/tinker_temp/temp.apk is not exist, just return
04-19 10:24:24.693 11675-11675/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
04-19 10:24:24.695 11572-11572/? I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/Android/data/com.vstone.wealth.android/cache/287abcead8d0d5403fe311b0a526d253, file size:37900
04-19 10:24:24.699 11572-11572/? I/Tinker.SamplePatchListener: get platform:all
04-19 10:24:24.767 11762-11762/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
04-19 10:24:24.774 11762-11762/? I/Tinker.SamplePatchListener: application maxMemory:384
04-19 10:24:24.774 11762-11762/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.vstone.wealth.android/tinker
04-19 10:24:24.775 11762-11762/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
04-19 10:24:24.775 11762-11762/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.vstone.wealth.android:patch, main process:false, systemOTA:false, fingerPrint:HUAWEI/EVA-AL10/HWEVA:7.0/HUAWEIEVA-AL10/C00B399SP02:user/release-keys, oatDir:null, useInterpretMode:false
04-19 10:24:24.775 11762-11762/? W/Tinker.TinkerLoadResult: tinker is disable, just return
04-19 10:24:24.775 11762-11762/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.vstone.wealth.android/tinker, code: -1, cost: 1ms
04-19 10:24:24.775 11762-11762/? W/Tinker.Tinker: tinker load fail!
04-19 10:24:24.777 11762-11762/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
04-19 10:24:25.646 11762-11817/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
04-19 10:24:25.648 11762-11817/? I/Tinker.TinkerPatchService: try to increase patch process priority
04-19 10:24:25.682 11762-11762/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
04-19 10:24:25.683 11762-11817/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:b06d788af36867c6d72432847907664c
04-19 10:24:25.683 11762-11817/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.vstone.wealth.android/tinker/patch.info (No such file or directory)
    read property failed, e:java.io.FileNotFoundException: /data/user/0/com.vstone.wealth.android/tinker/patch.info (No such file or directory)
04-19 10:24:25.683 11762-11817/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a
04-19 10:24:25.684 11762-11817/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/Android/data/com.vstone.wealth.android/cache/287abcead8d0d5403fe311b0a526d253 size: 37900, dest file: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/patch-b06d788a.apk size:37900
04-19 10:24:25.686 11762-11817/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/changed_classes.dex.jar
04-19 10:24:25.697 11762-11817/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
    try Extracting /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/test.dex.jar
04-19 10:24:25.698 11762-11817/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
04-19 10:24:25.700 11762-11817/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/test.dex.jar
04-19 10:24:25.700 11762-11817/? I/Tinker.DexDiffPatchInternal: merge classN dex file /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/tinker_classN.apk, result: true, size: 470, use: 2ms
    patch recover, try to optimize dex file count:2, optimizeDexDirectory:/data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex/
    start to parallel optimize dex /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/changed_classes.dex.jar, size: 38238
04-19 10:24:25.728 11822-11822/? I/dex2oat: /system/bin/dex2oat -j4 --dex-file=/data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/changed_classes.dex.jar --oat-fd=76 --oat-location=/data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex/changed_classes.dex.dex --compiler-filter=speed
04-19 10:24:25.759 11762-11762/? I/Tinker.SamplePatchListener: receive a patch file: /storage/emulated/0/Android/data/com.vstone.wealth.android/cache/287abcead8d0d5403fe311b0a526d253, file size:37900
04-19 10:24:25.761 11762-11762/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadPatchListenerReceiveFail: patch receive fail: /storage/emulated/0/Android/data/com.vstone.wealth.android/cache/287abcead8d0d5403fe311b0a526d253, code: -4
04-19 10:24:26.491 11762-11817/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/changed_classes.dex.jar, opt file:/data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex/changed_classes.dex.dex, opt file size: 430720, use time 790
    start to parallel optimize dex /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/tinker_classN.apk, size: 470
04-19 10:24:26.558 11855-11855/? I/dex2oat: /system/bin/dex2oat -j4 --dex-file=/data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/tinker_classN.apk --oat-fd=74 --oat-location=/data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex/tinker_classN.dex --compiler-filter=speed
04-19 10:24:26.620 11762-11817/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/dex/tinker_classN.apk, opt file:/data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex/tinker_classN.dex, opt file size: 21120, use time 129
04-19 10:24:26.621 11762-11817/? I/Tinker.DexDiffPatchInternal: recover dex result:true, cost:936
04-19 10:24:26.621 11762-11817/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
04-19 10:24:26.621 11762-11817/? W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
04-19 10:24:26.622 11762-11817/? I/Tinker.DexDiffPatchInternal: raw dex count: 2, dex opt dex count: 2, final wait times: 16
04-19 10:24:26.625 11762-11817/? I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex/changed_classes.dex.dex, size 430720
    check dex optimizer file exist: /data/user/0/com.vstone.wealth.android/tinker/patch-b06d788a/odex/tinker_classN.dex, size 21120
    check dex optimizer file format: changed_classes.dex.dex, size 430720
04-19 10:24:26.628 11762-11817/? I/Tinker.DexDiffPatchInternal: check dex optimizer file format: tinker_classN.dex, size 21120
04-19 10:24:26.629 11762-11817/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.vstone.wealth.android/tinker/patch.info , oldVer:, newVer:b06d788af36867c6d72432847907664c, fingerprint:HUAWEI/EVA-AL10/HWEVA:7.0/HUAWEIEVA-AL10/C00B399SP02:user/release-keys, oatDir:odex
04-19 10:24:26.631 11762-11817/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
04-19 10:24:26.632 11762-11817/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/emulated/0/Android/data/com.vstone.wealth.android/cache/287abcead8d0d5403fe311b0a526d253, success: true, cost: 983

```

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。
