### ISSUE TITLE
请教关于DexMerge方案的问题

### ISSUE THREAD

**Issue by DozenWang** [Tencent/tinker#82]
想验证一下 DexMerge 方案，通过DexMerger 合成的dex 无法通过DexFile.loadDex() 加载，正常打包出的dex是可以加载的，怀疑是DexMerger 合成dex的格式有问题，不知楼主是否遇到过类似的问题，error log 如下：

```
 DexOpt: incorrect opt magic number (0xff ff ff ff)
09-28 21:06:52.097 15388-15464/? D/dalvikvm: ODEX file is stale or bad; removing and retrying (/data/data/com.demo.dexmerge/files/dex/output_opt.dex)
09-28 21:06:52.117 15388-15464/? D/dalvikvm: DexOpt: --- BEGIN 'output.dex' (bootstrap=0) ---
09-28 21:06:52.297 15388-15464/? W/dalvikvm: DexOpt: --- END 'output.dex' --- status=0xff00, process failed
09-28 21:06:52.297 15388-15464/? E/dalvikvm: Unable to extract+optimize DEX from '/data/data/com.demo.dexmerge/files/dex/output.dex'
09-28 21:06:52.297 15388-15464/? I/dalvikvm: Zip is good, but no classes.dex inside, and no valid .odex file in the same directory
09-28 21:06:52.297 15388-15464/? W/System.err: java.io.IOException: unable to open DEX file
09-28 21:06:52.297 15388-15464/? W/System.err:     at dalvik.system.DexFile.openDexFileNative(Native Method)
09-28 21:06:52.297 15388-15464/? W/System.err:     at dalvik.system.DexFile.openDexFile(DexFile.java:296)
09-28 21:06:52.297 15388-15464/? W/System.err:     at dalvik.system.DexFile.<init>(DexFile.java:111)
09-28 21:06:52.297 15388-15464/? W/System.err:     at dalvik.system.DexFile.loadDex(DexFile.java:151)
09-28 21:06:52.297 15388-15464/? W/System.err:     at com.demo.dexmerge.MainActivity$1$1.run(MainActivity.java:38)
```
合成代码如下：
```
DexBuffer dexA = new DexBuffer(new File("patch1.dex"));
DexBuffer dexB = new DexBuffer(new File("patch2.dex"));
DexBuffer merged = new DexMerger(dexA, dexB, CollisionPolicy.FAIL).merge();
File dexFile = new File("output.dex");
merged.writeTo(dexFile);

```

loadDex代码：

`   DexFile dex = DexFile.loadDex(dexPath, odexPath, 0);`

**Comment by shwenzhang** [comment]
如果想把dexdiff拆出来，不是直接就可以拆的

**Comment by DozenWang** [comment]
主要还是想对比一下dexmerge的方案

**Comment by tomystang** [comment]
给一下dexPath和odexPath吧，系统貌似没有读到你的dex，而是当成zip来处理了。

还有，直接用dex merger会遇到问题，旧dex和包含修改类的dex可能会存在交集(同名类)，看你的调用方法，遇到这种情况的话会合成失败，正确的做法是把那个小点的包含修改类的dex放前面，旧dex放后面，然后collision policy用KeepFirst。

**Comment by DozenWang** [comment]
`dexPath: /data/data/com.demo.dexmerge/files/dex/output.dex  odexPath: /data/data/com.demo.dexmerge/files/dex/output.dex`
查了一下dx 的源码 不是调用的问题， 通过dexmerge 直接打出的dex 格式确实存在问题， 通过`dexdump -c "output.dex" `  提示 Failed structural verification of "output.dex" ， 我是直接把两个不相关的jar 通过dx 打包出dex , 然后再调用的DexMerge , 我再看看dx的逻辑吧，猜测在调用dexmerge前需要一些预处理

**Comment by tomystang** [comment]
额，我的意思不是说现在这个报错是DexMerger引起的 ，而是将来你要把DexMerger方案跑起来的时候可能会遇到我说的这个坑，毕竟DexMerger设计的时候默认了参与Merge的两个Dex没有任何交集，你找到为何生成的Dex的格式出问题之后实验一下应该就会遇到了。

**Comment by DozenWang** [comment]
@tomystang 明白 多谢解惑

**Comment by tomystang** [comment]
嗯嗯，不客气！
