### ISSUE TITLE
tinker生成补丁包时报NoSuchMethodError

### ISSUE THREAD

**Issue by lindamoon** [Tencent/tinker#824]
异常类型：编译异常

tinker版本：1.9

gradle版本：4.5

是否使用热更新SDK： Bugly SDK

系统：windows7

问题描述: 在第二次生成patch时报这个错，第一个patch已成功上传下发，中途可以确定代码有删改，isProtectedApp改为false时，不会报这个错

堆栈/日志：
Building changed classes dex: E:\app_proj\xxxxx\app\build\outputs\apk\tinkerPatch\release\tinker_result\changed_classes.dex, size: 0

java.lang.NoSuchMethodError: org.jf.dexlib2.writer.builder.DexBuilder.makeDexBuilder()Lorg/jf/dexlib2/writer/builder/DexBuilder;
	at com.tencent.tinker.build.decoder.DexDiffDecoder.generateChangedClassesDexFile(DexDiffDecoder.java:246)
	at com.tencent.tinker.build.decoder.DexDiffDecoder.onAllPatchesEnd(DexDiffDecoder.java:196)
	at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:123)
	at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
	at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
	at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
	at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.tinkerPatch(TinkerPatchSchemaTask.groovy:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:49:14: Task execution finished 'buildTinkerPatchRelease'.

**Comment by lindamoon** [comment]
应该是这个的问题:classpath 'com.android.tools.build:gradle:3.0.0',用3.2 alpha版本会报这个错，3.0正常
