### ISSUE TITLE
加载补丁重启后崩溃

### ISSUE THREAD

**Issue by zlg2338781286** [Tencent/tinker#837]
异常类型：app运行时异常

手机型号：三星Galaxy S6 SM-9208

手机系统版本：如:Android 6.0.0 (如是编译异常，则可以不填)

tinker版本：如:1.8.1

gradle版本：如:2.2.3

是否使用热更新SDK：无

系统:Mac
日志：E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to create service com.water.richprocess.MySyncServic: java.lang.RuntimeException: Unable to instantiate application com.businesshall.base.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Tinker instance is already set.
                                                             at android.app.ActivityThread.handleCreateService(ActivityThread.java:3818)
                                                             at android.app.ActivityThread.access$2100(ActivityThread.java:222)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:158)
                                                             at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                          Caused by: java.lang.RuntimeException: Unable to instantiate application com.businesshall.base.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Tinker instance is already set.
                                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:676)
                                                             at android.app.ActivityThread.handleCreateService(ActivityThread.java:3789)
                                                             at android.app.ActivityThread.access$2100(ActivityThread.java:222) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:158) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                          Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Tinker instance is already set.
                                                             at com.tencent.tinker.lib.tinker.Tinker.create(Tinker.java:123)
                                                             at com.tencent.tinker.lib.tinker.TinkerInstaller.install(TinkerInstaller.java:70)
                                                             at com.businesshall.base.ApplicationExLike.installTinker(ApplicationExLike.java:582)
                                                             at com.businesshall.base.ApplicationExLike.onBaseContextAttached(ApplicationExLike.java:571)
                                                             at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
                                                             at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
                                                             at android.app.Application.attach(Application.java:211)
                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:1020)
                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
                                                             at android.app.ActivityThread.handleCreateService(ActivityThread.java:3789) 
                                                             at android.app.ActivityThread.access$2100(ActivityThread.java:222) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:158) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
05-10 20:25:27.151 6601-6601/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to create service com.water.richprocess.MySyncServic: java.lang.RuntimeException: Unable to instantiate application com.businesshall.base.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Tinker instance is already set.
                                                             at android.app.ActivityThread.handleCreateService(ActivityThread.java:3818)
                                                             at android.app.ActivityThread.access$2100(ActivityThread.java:222)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:158)
                                                             at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                          Caused by: java.lang.RuntimeException: Unable to instantiate application com.businesshall.base.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Tinker instance is already set.
                                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:676)
                                                             at android.app.ActivityThread.handleCreateService(ActivityThread.java:3789)
                                                             at android.app.ActivityThread.access$2100(ActivityThread.java:222) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:158) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                          Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:Tinker instance is already set.
                                                             at com.tencent.tinker.lib.tinker.Tinker.create(Tinker.java:123)
                                                             at com.tencent.tinker.lib.tinker.TinkerInstaller.install(TinkerInstaller.java:70)
                                                             at com.businesshall.base.ApplicationExLike.installTinker(ApplicationExLike.java:582)
                                                             at com.businesshall.base.ApplicationExLike.onBaseContextAttached(ApplicationExLike.java:571)
                                                             at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
                                                             at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:146)
                                                             at android.app.Application.attach(Application.java:211)
                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:1020)
                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:1004)

我们的版本已上线几个月了，发现问题需要修复，现在加载补丁后重启崩溃，日志如上，之前上线前我们打包测试过正常的，现在比较急，谢谢 @dodola @gryamy

**Comment by tomystang** [comment]
检查一下TinkerInstaller.install是不是在某些条件下被调用了两次？
