### ISSUE TITLE
 Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onCreate method not found

### ISSUE THREAD

**Issue by nysin** [Tencent/tinker#841]
异常类型：app运行时异常

手机型号：任何手机
手机系统版本：任何版本
tinker版本：1.7.5

gradle版本：如:2.3.3

是否使用热更新SDK： 使用 Bugly SDK

系统：Mac

堆栈/日志：
java.lang.RuntimeException: Unable to create application 
xxx.xxx.xxxx.application.MainApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onCreate method not found
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5879)
        at android.app.ActivityThread.access$1100(ActivityThread.java:193)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onCreate method not found
        at com.tencent.tinker.loader.app.TinkerApplication.delegateMethod(TinkerApplication.java:183)
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:192)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5874)
        at android.app.ActivityThread.access$1100(ActivityThread.java:193) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.delegateMethod(TinkerApplication.java:181)
        at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:192) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5874) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:193) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 

为啥我这已启动就报错呢，

**Comment by tomystang** [comment]
检查一下tinker的类是不是被混淆了？

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。
