### ISSUE TITLE
卸载patch过程中和卸载后NotFoundException，需要强制杀掉进程才可用吗

### ISSUE THREAD

**Issue by hory1918** [Tencent/tinker#843]
异常类型：app运行时异常

手机型号：华为p9 plus

手机系统版本：Android 7.0 

tinker版本：1.9.1

gradle版本：3.0.1

是否使用热更新SDK： 无

系统：win10

TinkerUncaughtHandler catch exception:android.content.res.Resources$NotFoundException: failed to add asset path /data/user/0/com.example.myapplication/tinker/patch-6db2b5c2/res/resources.apk
                                                                                               at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:275)
                                                                                               at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:332)
                                                                                               at android.app.ResourcesManager.getOrCreateResources(ResourcesManager.java:612)
                                                                                               at android.app.ResourcesManager.getResources(ResourcesManager.java:690)
                                                                                               at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1989)
                                                                                               at android.app.ActivityThreadUtils.getTopLevelResources(ActivityThreadUtils.java:24)
                                                                                               at huawei.android.hwtheme.HwThemeManagerImpl.updateHwtResource(HwThemeManagerImpl.java:681)
                                                                                               at android.hwtheme.HwThemeManager.updateHwtResource(HwThemeManager.java:311)
                                                                                               at android.app.LoadedApk.getResources(LoadedApk.java:803)
                                                                                               at android.graphics.Bitmap.getDefaultDensity(Bitmap.java:222)
                                                                                               at android.graphics.Bitmap.<init>(Bitmap.java:196)
                                                                                               at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:1070)
                                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:1040)
                                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:1007)
                                                                                               at android.graphics.drawable.RippleDrawable.updateMaskShaderIfNeeded(RippleDrawable.java:902)
                                                                                               at android.graphics.drawable.RippleDrawable.drawBackgroundAndRipples(RippleDrawable.java:999)
                                                                                               at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:822)
                                                                                               at android.view.View.getDrawableRenderNode(View.java:17493)
                                                                                               at android.view.View.drawBackground(View.java:17429)
                                                                                               at android.view.View.draw(View.java:17241)
                                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16215)
                                                                                               at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                                               at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16178)
                                                                                               at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                                               at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16178)
                                                                                               at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                                               at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16178)
                                                                                               at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                                               at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16178)
                                                                                               at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                                               at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16178)
                                                                                               at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                                               at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                                               at android.view.View.updateDisplayListIfDirty(View.java:16178)
                                                                                               at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:677)
                                                                                               at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:683)
                                                                                               at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:797)
                                                                                               at android.view.ViewRootImpl.draw(ViewRootImpl.java:2997)
                                                                                               at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2791)
                                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2382)
                                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
                                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6774)
                                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                                               at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
                                                                                               at android.os.Handler.handleCallback(Handler.java:761)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                               at android.os.Looper.loop(Looper.java:156)
                                                                                           	at android.app.ActivityThread.

**Comment by tomystang** [comment]
是的，卸载补丁后一定记得同时kill掉所有进程，否则容易产生各种问题，如ClassNotFound, ClassCastException或者找不到资源id等等。
