### ISSUE TITLE
编译报ArrayIndexOutOfBoundsException错误

### ISSUE THREAD

**Issue by winxinxinxin** [Tencent/tinker#845]
引入科大讯飞的msc.jar 3.0，编译报错。关闭tinker后正常编译运行。

异常类型：编译异常

tinker版本：如:1.7.5

gradle版本：如:2.3.3

是否使用热更新SDK： 使用 TinkerPatch SDK ， Bugly SDK

系统：Mac

堆栈/日志：（编译错误日志）
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
 at org.objectweb.asm.ClassReader.a(Unknown Source)
 at org.objectweb.asm.ClassReader.a(Unknown Source)
 at org.objectweb.asm.ClassReader.a(Unknown Source)
 at org.objectweb.asm.ClassReader.b(Unknown Source)
 at org.objectweb.asm.ClassReader.accept(Unknown Source)
 at org.objectweb.asm.ClassReader.accept(Unknown Source)
 at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processClass(AuxiliaryClassInjector.java:119)
 at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJarHelper(AuxiliaryClassInjector.java:97)
 at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector.processJar(AuxiliaryClassInjector.java:69)
 at com.tencent.tinker.build.auxiliaryclass.AuxiliaryClassInjector$processJar$0.call(Unknown Source)
 at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform$_transform_closure5.doCall(AuxiliaryInjectTransform.groovy:287)
 at sun.reflect.GeneratedMethodAccessor401.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
 at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
 at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
 at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
 at groovy.lang.Closure.call(Closure.java:414)
 at groovy.lang.Closure.call(Closure.java:430)
 at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
 at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
 at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2068)
 at org.codehaus.groovy.runtime.dgm$164.invoke(Unknown Source)
 at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
 at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
 at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
 at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
 at com.tencent.tinker.build.gradle.transform.AuxiliaryInjectTransform.transform(AuxiliaryInjectTransform.groovy:264)
 at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
 at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
 at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
 at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
 at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
 at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
 at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
 at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
 at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
 ... 81 more

**Comment by tomystang** [comment]
已知问题，升级到最新版吧。
