### ISSUE TITLE
AndroidP DP2 上加载补丁失败(资源加载时，mStringBlocks字段反射异常)

### ISSUE THREAD

**Issue by sailor1861** [Tencent/tinker#847]
背景说明：
实测在Android P DP1上，是可以正常加载补丁的； 在Android P DP2上，加载补丁失败，报错误--mStringBlocks字段反射异常；

异常类型：app运行时异常

手机型号：Pixel

手机系统版本：如:Android 9.0
ROM版本：Android P DP2 ;
最新DP2： sailfish-ppp2.180412.013-factory-18f60ec5

tinker版本：如:1.9.6

是否使用热更新SDK： 无

系统：Windows

堆栈/日志：
异常logcat：
05-25 14:57:49.972 9016-9016/? I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-23
05-25 14:57:49.972 9016-9016/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: patch load resource exception: java.lang.NoSuchFieldException: Field mStringBlocks not found in class android.content.res.AssetManager
05-25 14:57:49.980 9016-9016/? I/Tinker.DefaultLoadReporter: res exception disable tinker forever with sp
05-25 14:57:49.980 9016-9016/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
05-25 14:57:49.981 9016-9016/? E/Tinker.DefaultLoadReporter: tinker load exception  java.lang.NoSuchFieldException: Field mStringBlocks not found in class android.content.res.AssetManager
                                                                 at com.tencent.tinker.loader.shareutil.ShareReflectUtil.findField(ShareReflectUtil.java:55)
                                                                 at com.tencent.tinker.loader.TinkerResourcePatcher.isResourceCanPatch(TinkerResourcePatcher.java:103)
                                                                 at com.tencent.tinker.loader.TinkerResourceLoader.checkComplete(TinkerResourceLoader.java:122)
                                                                 at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:224)
                                                                 at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:59)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:174)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:138)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:159)
                                                                 at android.app.Application.attach(Application.java:212)
                                                                 at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
                                                                 at android.app.LoadedApk.makeApplication(LoadedApk.java:1001)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5836)
                                                                 at android.app.ActivityThread.access$1000(ActivityThread.java:198)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6649)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)

**Comment by tomystang** [comment]
已在1.9.8版本fix，预计6月22号发布。
