### ISSUE TITLE
华为7.0系统Resources$NotFoundException导致的大量crash

### ISSUE THREAD

**Issue by kiitos** [Tencent/tinker#871]
已搜索相关issue，发现类似问题已被close掉，故提交此issue烦请关注

异常类型：app运行时异常

手机型号：华为多款7.0系统手机

手机系统版本：Android 7.0

tinker版本：1.9.1(Bugly SDK集成)

gradle版本：3.3

是否使用热更新SDK： Bugly SDK1.3.4(集成tinker1.9.1)

系统：Linux

堆栈/日志：
1Caused by: android.content.res.Resources$NotFoundException: failed to add asset path /data/user/0/com.ifeng.news2/tinker/patch-58af56eb/res/resources.apk
2    at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:275)
3    at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:332)
4    at android.app.ResourcesManager.getOrCreateResources(ResourcesManager.java:612)
5    at android.app.ResourcesManager.getResources(ResourcesManager.java:690)
6    at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1989)
7    at android.app.ActivityThreadUtils.getTopLevelResources(ActivityThreadUtils.java:24)
8    at huawei.android.hwtheme.HwThemeManagerImpl.updateHwtResource(HwThemeManagerImpl.java:681)
9    at android.hwtheme.HwThemeManager.updateHwtResource(HwThemeManager.java:311)
10    at android.app.LoadedApk.getResources(LoadedApk.java:803)
11    at android.view.Display.getRealSize(Display.java:889)
12    at org.chromium.ui.display.PhysicalDisplayAndroid.updateFromDisplay(PhysicalDisplayAndroid.java:21)
13    at org.chromium.ui.display.DisplayAndroidManager$DisplayListenerBackendImpl.onDisplayChanged(DisplayAndroidManager.java:30)
14    at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:495)
15    at android.os.Handler.dispatchMessage(Handler.java:105)
16    at android.os.Looper.loop(Looper.java:156)
17    at android.app.ActivityThread.main(ActivityThread.java:6523)
18    at java.lang.reflect.Method.invoke(Native Method)
19    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
20    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

查阅之前issue列表相关问题，@shwenzhang 回复是手动删除了补丁导致，我们线上有大量华为7.0手机报出这个问题，应该不是用户主动清除补丁。我们的场景是：通过bugly平台针对同一基线版本先后下发过两次补丁包，不知是否与此相关，请问此问题如何解决，谢谢。

**Comment by kiitos** [comment]
![crash](https://user-images.githubusercontent.com/16589527/41706162-a80a3b72-756d-11e8-8c6d-51965c646503.png)

**Comment by a1018875550** [comment]
这个统计图是用什么工具的？

**Comment by kiitos** [comment]
是监控后台的统计图

**Comment by kiitos** [comment]
@tomystang 请问 #843  回复中的“卸载补丁后一定记得同时kill掉所有进程”这个如何理解，是否在最新版tinker sdk 1.9.8中已做处理。如果使用bugly接入热更新sdk，针对同一基线版本下发多次patch，按照目前bugly的逻辑，新的patch上传后会自动停掉之前的patch，这样是否会出现“卸载补丁没有同时kill掉所有进程”从而导致上述Resources$NotFoundException的问题，谢谢！

**Comment by tomystang** [comment]
> ……新的patch上传后会自动停掉之前的patch……
如果bugly是调用了tinker的删除补丁的api来“停掉”补丁，那估计很可能他确实没有kill其他进程。你可以在本地尝试一次，然后看logcat里出现tinker删文件的log（会有一堆tinker的路径打出来）之后主进程和其他进程有没有退出就知道了。
