### ISSUE TITLE
SimpleDrawableView加载错误

### ISSUE THREAD

**Issue by hwldzh** [Tencent/tinker#901]
堆栈日志：
Caused by: android.view.InflateException: Binary XML file line #169: Binary XML file line #169: Error inflating class com.facebook.drawee.view.SimpleDraweeView
     Caused by: android.view.InflateException: Binary XML file line #169: Error inflating class com.facebook.drawee.view.SimpleDraweeView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at com.mucfc.muapp.widget.TitleBar.init(TitleBar.java:135)
        at com.mucfc.muapp.widget.TitleBar.<init>(TitleBar.java:227)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:442)
        at android.app.Activity.setContentView(Activity.java:2509)
        at com.mucfc.muapp.ui.base.activity.BaseActivity.onCreate(BaseActivity.java:131)
        at com.mucfc.muapp.ui.welcome.activity.WelcomeActivity.onCreate(WelcomeActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:7007)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2821)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2929)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:185)
        at android.app.ActivityThread.main(ActivityThread.java:6615)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)
     Caused by: java.lang.NullPointerException: SimpleDraweeView was not initialized!
        at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:226)

```
异常类型：app运行时异常（补丁提示修复成功，重启后crash）

手机型号：OPPO R11s

手机系统版本：Android 7.1 

tinker版本：1.9.1

gradle版本：3.3

是否使用热更新SDK： 无

系统：android

**Comment by luyang7415445** [comment]
没有人解答这块儿吗，我们也遇到这种问题，量很多

**Comment by tomystang** [comment]
> SimpleDraweeView was not initialized.

疑似这个View必须的初始化流程被跳过了，很肯能是ART的内联行为导致的。尝试一下1.9.14版本吧，如果仍有问题，请补充log之后重开这个issue。

**Comment by tuke0919** [comment]
> > SimpleDraweeView was not initialized.
> 
> 疑似这个View必须的初始化流程被跳过了，很肯能是ART的内联行为导致的。尝试一下1.9.14版本吧，如果仍有问题，请补充log之后重开这个issue。

您好，我遇到了同样的问题“SimpleDraweeView was not initialized”，在MainApplication的onCreate，里对Fresco做了初始化：
![image](https://user-images.githubusercontent.com/13417140/64224336-be8bd080-cf09-11e9-804b-4525604dd2a7.png)

日志如下：
2019-09-03 22:04:41.671 11088-11088/com.netease.vopen E/VopenLog: Tinker: VopenApp initFresco
2019-09-03 22:04:41.676 11088-11088/com.netease.vopen E/VopenLog: **Tinker: VopenApp initFresco Fresco.initialize**

2019-09-03 22:04:41.690 11088-11088/com.netease.vopen E/VopenLog: VopenApp:  **welcomePid = 11088 CurProcessName = com.netease.vopen**
2019-09-03 22:04:41.691 11088-11088/com.netease.vopen E/VopenLog: VopenApp:  **supplier = false**
2019-09-03 22:04:41.691 11088-11088/com.netease.vopen E/VopenLog: **VopenApp:  hasBeenInitialized = true**

但是我在欢迎页WelcomeActivity.java的layout xml文件里使用SimpleDraweeView，也出现上面“SimpleDraweeView was not initialized”的错误，源码说是 没有使用“Fresco.initialize”初始化，但是如上所示，在主进程里 确实调用了“Fresco.initialize”初始化，但是在WelcomeActivity中使用显示没有初始化，日志如下：

2019-09-03 22:04:42.719 11088-11088/com.netease.vopen E/VopenLog: WelcomeActivity:  **welcomePid = 11088 CurProcessName = com.netease.vopen**
2019-09-03 22:04:42.719 11088-11088/com.netease.vopen E/VopenLog: WelcomeActivity:  **supplier = true**
2019-09-03 22:04:42.719 11088-11088/com.netease.vopen E/VopenLog: WelcomeActivity:  **hasBeenInitialized = false**

**Comment by tuke0919** [comment]
tinker.gradle 发到你gmail邮箱了 @tomystang
