### ISSUE TITLE
Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception

### ISSUE THREAD

**Issue by suzfsir** [Tencent/tinker#903]
08-15 16:04:11.861 2059-2371/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:length=2; index=321433792
    tinker has fast crash 1 times
08-15 16:04:11.863 2059-2371/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.ArrayIndexOutOfBoundsException: length=2; index=321433792
        at com.tencent.tmassistantbase.a.g.a(SourceFile:428)
        at com.tencent.tmassistantbase.a.g.b(SourceFile:307)
        at com.tencent.tmassistantbase.a.g.a(SourceFile:95)
        at com.tencent.tmassistantbase.a.g.a(SourceFile:481)
        at com.tencent.tmapkupdatesdk.internal.logic.protocol.b.b(SourceFile:178)
        at com.tencent.tmapkupdatesdk.internal.logic.a.a(SourceFile:186)
        at com.tencent.tmapkupdatesdk.internal.logic.a.handleMessage(SourceFile:98)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.os.HandlerThread.run(HandlerThread.java:61)
08-15 16:04:11.876 2059-2371/? E/AndroidRuntime: FATAL EXCEPTION: apkupdate_asyctask
    Process: com.xingjiabi.shengsheng, PID: 2059
    java.lang.ArrayIndexOutOfBoundsException: length=2; index=321433792
        at com.tencent.tmassistantbase.a.g.a(SourceFile:428)
        at com.tencent.tmassistantbase.a.g.b(SourceFile:307)
        at com.tencent.tmassistantbase.a.g.a(SourceFile:95)
        at com.tencent.tmassistantbase.a.g.a(SourceFile:481)
        at com.tencent.tmapkupdatesdk.internal.logic.protocol.b.b(SourceFile:178)
        at com.tencent.tmapkupdatesdk.internal.logic.a.a(SourceFile:186)
        at com.tencent.tmapkupdatesdk.internal.logic.a.handleMessage(SourceFile:98)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.os.HandlerThread.run(HandlerThread.java:61)
08-15 16:04:12.030 2393-2393/? E/BMActivityThread: no bm file.

app启动崩溃  目前只在一款手机发生崩溃 qiku 8681-A01，其他手机没有问题，希望告知怎么修改

**Comment by tomystang** [comment]
App有加固过？
直接安装base包和新包会有问题吗？

**Comment by tomystang** [comment]
此issue非活动时间太长，故先关闭。可先尝试Tinker的最新版本，若问题仍然存在，请补充日志等细节并重新开启此issue。
