### ISSUE TITLE
小米8.0系统下载补丁包成功后无法应用

### ISSUE THREAD

**Issue by sdgSnow** [Tencent/tinker#906]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：补丁修复失败

手机型号：如:小米max2

手机系统版本：Android8.0

tinker版本：如:1.9.6

gradle版本：如:3.1.3

是否使用热更新SDK： Bugly SDK

系统：如:win

日志：
![image](https://user-images.githubusercontent.com/30679644/44245873-b7febe00-a20d-11e8-93aa-c5f38f572709.png)



08-17 10:18:49.306 1555-2663/? E/whetstone.activity: java.lang.NoSuchMethodException: com.android.server.am.ExtraActivityManagerService#getExecutingServicesSize(int)#exact
        at miui.util.ReflectionUtils.findMethodExact(ReflectionUtils.java:242)
        at com.miui.whetstone.server.WhetstoneActivityManagerService.isProcessExecutingServices(WhetstoneActivityManagerService.java:439)
        at com.miui.whetstone.server.IWhetstoneActivityManager$Stub.onTransact(IWhetstoneActivityManager.java:288)
        at android.os.Binder.execTransact(Binder.java:677)
    
08-17 10:18:49.308 4099-4246/? E/PowerKeeper.FrozenApp: getOomAdjByPid, don't read actual proc, pass it pid = 13528
08-17 10:20:34.636 1555-1646/? E/BatteryStatsService: no controller energy info supplied
    no controller energy info supplied

**Comment by sdgSnow** [comment]
我下载补丁包成功后就会修复失败，小米7.1系统是可以的，8.0就不行，其他测试机也可以，华为三星一加的8.0都可以

**Comment by LoveRain1997** [comment]
同样的环境，同样的问题，我用官方demo测试了一下也不行。

**Comment by Klay-11** [comment]
小米8.0出现了这个情况，补丁合成失效。试试最新版本1.9.8看看是否解决？

**Comment by Klay-11** [comment]
我司8.0小米测试机无效，补丁一直不消失，说明合成失败。

**Comment by sunkeding** [comment]
1.9.8版本也无法解决。。亲测。。。

**Comment by zhq217217** [comment]
只要是8.0的系统都不行，1.9.8版本也不行
