### ISSUE TITLE
撤销更新的时候会出现启动闪退

### ISSUE THREAD

**Issue by ytsxg123** [Tencent/tinker#907]
异常类型：RuntimeException

手机型号：小米MI 5X

手机系统版本：如:Android 7.1.2 MIUI 9.6

tinker版本：如:1.9.6

gradle版本：如:4.4

是否使用热更新SDK： 如使用

系统：如:Android

08-17 13:49:23.761 14576-14576/com.sxg.buglydemo E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
08-17 13:49:23.762 14576-14576/com.sxg.buglydemo E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkSafeModeCount fail
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:251)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:163)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
        at com.sxg.buglydemo.App.attachBaseContext(App.java:34)
        at android.app.Application.attach(Application.java:193)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
        at android.app.Instrumentation.newApplication(Instrumentation.java:993)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:800)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5533)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6396)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
08-17 13:49:23.774 14576-14576/com.sxg.buglydemo E/Tinker.TinkerManager: NOT tinker ApplicationLike object

**Comment by tomystang** [comment]
目前删除补丁之后要马上重启，不然已经加载的补丁被删除了就会导致正在运行的进程发生crash。
