### ISSUE TITLE
AndroidN,O 加载到patch 以后重启app crash了.

### ISSUE THREAD

**Issue by zrbaihld** [Tencent/tinker#910]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：启动crash

手机型号：华为,小米,魅族

手机系统版本：Android 7.0 Android 8.0

tinker版本：1.9.1

gradle版本：2.3.3

是否使用热更新SDK：  Bugly SDK

系统：windows

堆栈/日志：
08-21 13:42:50.006 31735-31735/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Rejecting class android.baoming.ui.contollers.main.LaunchActivity that attempts to sub-type erroneous class android.baoming.ui.contollers.common.base.BaseActivity (declaration of 'android.baoming.ui.contollers.main.LaunchActivity' appears in /data/user/0/android.baoming/tinker/patch-848895a4/dex/tinker_classN.apk)
        08-21 13:42:50.007 31735-31735/? E/Tinker.TinkerApplicationHelper: it is not safety to clean patch when tinker is loaded, you should kill all your process after clean!
        08-21 13:42:50.007 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/info.lock
        08-21 13:42:50.007 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/patch-848895a4/patch-848895a4.apk
        08-21 13:42:50.009 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/patch-848895a4/dex/tinker_classN.apk
        08-21 13:42:50.011 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/patch-848895a4/dex
        08-21 13:42:50.011 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/patch-848895a4/odex/tinker_classN.dex
        08-21 13:42:50.011 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/patch-848895a4/odex
        08-21 13:42:50.011 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/patch-848895a4/res/resources.apk
        08-21 13:42:50.011 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/patch-848895a4/res
        08-21 13:42:50.011 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/patch-848895a4
        08-21 13:42:50.011 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker/patch.info
        08-21 13:42:50.011 31735-31735/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/android.baoming/tinker
        08-21 13:42:50.012 31735-31735/? E/Tinker.TinkerUncaughtExceptionHandler: tinker has fast crash more than 3, we just clean patch!
        08-21 13:42:50.012 31735-31735/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.VerifyError: Rejecting class android.baoming.ui.contollers.main.LaunchActivity that attempts to sub-type erroneous class android.baoming.ui.contollers.common.base.BaseActivity (declaration of 'android.baoming.ui.contollers.main.LaunchActivity' appears in /data/user/0/android.baoming/tinker/patch-848895a4/dex/tinker_classN.apk)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
        Caused by: java.lang.VerifyError: Verifier rejected class android.baoming.ui.contollers.common.base.BaseActivity: android.baoming.ui.contollers.common.base.LifeApplication android.baoming.ui.contollers.common.base.BaseActivity.j() failed to verify: android.baoming.ui.contollers.common.base.LifeApplication android.baoming.ui.contollers.common.base.BaseActivity.j(): [0x4] returning 'Reference: android.baoming.ui.contollers.common.base.BaseApplication', but expected from declaration 'Reference: android.baoming.ui.contollers.common.base.LifeApplication' (declaration of 'android.baoming.ui.contollers.common.base.BaseActivity' appears in /data/user/0/android.baoming/tinker/patch-848895a4/dex/tinker_classN.apk)
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1083) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
        08-21 13:42:50.012 31735-31735/? E/AndroidRuntime: FATAL EXCEPTION: main
        Process: android.baoming, PID: 31735
        java.lang.VerifyError: Rejecting class android.baoming.ui.contollers.main.LaunchActivity that attempts to sub-type erroneous class android.baoming.ui.contollers.common.base.BaseActivity (declaration of 'android.baoming.ui.contollers.main.LaunchActivity' appears in /data/user/0/android.baoming/tinker/patch-848895a4/dex/tinker_classN.apk)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
        Caused by: java.lang.VerifyError: Verifier rejected class android.baoming.ui.contollers.common.base.BaseActivity: android.baoming.ui.contollers.common.base.LifeApplication android.baoming.ui.contollers.common.base.BaseActivity.j() failed to verify: android.baoming.ui.contollers.common.base.LifeApplication android.baoming.ui.contollers.common.base.BaseActivity.j(): [0x4] returning 'Reference: android.baoming.ui.contollers.common.base.BaseApplication', but expected from declaration 'Reference: android.baoming.ui.contollers.common.base.LifeApplication' (declaration of 'android.baoming.ui.contollers.common.base.BaseActivity' appears in /data/user/0/android.baoming/tinker/patch-848895a4/dex/tinker_classN.apk)
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1083) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
        08-21 13:42:51.204 31865-31865/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/android.baoming/tinker
        08-21 13:42:51.205 31865-31865/? D/Tinker.DefaultAppLike: onBaseContextAttached:
        08-21 13:42:51.209 31865-31865/? I/Tinker.TinkerPatchListener: application maxMemory:384
        08-21 13:42:51.217 31865-31865/? W/Tinker.Tinker: tinker patch directory: /data/user/0/android.baoming/tinker
        08-21 13:42:51.218 31865-31865/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
        08-21 13:42:51.221 31865-31865/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:android.baoming, main process:true, systemOTA:false, fingerPrint:honor/FRD-AL00/HWFRD:7.0/HUAWEIFRD-AL00/C00B396:user/release-keys, oatDir:null, useInterpretMode:false
        08-21 13:42:51.221 31865-31865/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
        08-21 13:42:51.222 31865-31865/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/android.baoming/tinker, code: -2, cost: 4ms
        08-21 13:42:51.223 31865-31865/? W/Tinker.Tinker: tinker load fail!
        08-21 13:42:51.296 31865-31865/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
        08-21 13:42:51.296 31865-31865/? D/Tinker.DefaultAppLike: onCreate
        08-21 13:42:51.752 31865-31865/? D/Tinker.DefaultAppLike: onTrimMemory level:5
        08-21 13:42:52.148 31865-31865/? D/Tinker.DefaultAppLike: onTrimMemory level:80
        08-21 13:42:52.324 31865-31865/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad patch file: /data/user/0/android.baoming/tinker_temp/temp.apk is not exist, just return
        08-21 13:42:53.203 32078-32078/? I/art: Failed to add image file Failed to flatten class loader hierarchy 'Unknown class loader type com.tencent.tinker.loader.AndroidNClassLoader'
        08-21 13:42:58.129 31865-31865/? D/Tinker.DefaultAppLike: onTrimMemory level:20
        08-21 13:43:01.853 32310-32310/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/android.baoming/tinker
        08-21 13:43:01.854 32310-32310/? D/Tinker.DefaultAppLike: onBaseContextAttached:
        08-21 13:43:01.857 32310-32310/? I/Tinker.TinkerPatchListener: application maxMemory:384
        08-21 13:43:01.860 32310-32310/? W/Tinker.Tinker: tinker patch directory: /data/user/0/android.baoming/tinker
        08-21 13:43:01.860 32310-32310/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.1
        08-21 13:43:01.860 32310-32310/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:android.baoming:channel, main process:false, systemOTA:false, fingerPrint:honor/FRD-AL00/HWFRD:7.0/HUAWEIFRD-AL00/C00B396:user/release-keys, oatDir:null, useInterpretMode:false
        08-21 13:43:01.861 32310-32310/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
        08-21 13:43:01.861 32310-32310/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/android.baoming/tinker, code: -2, cost: 4ms
        08-21 13:43:01.861 32310-32310/? W/Tinker.Tinker: tinker load fail!
        08-21 13:43:01.865 32310-32310/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
        08-21 13:43:01.865 32310-32310/? D/Tinker.DefaultAppLike: onCreate
        08-21 13:43:02.342 32310-32310/? D/Tinker.DefaultAppLike: onTrimMemory level:5
        08-21 13:43:02.510 32310-32310/? D/Tinker.DefaultAppLike: onTrimMemory level:80
        08-21 13:43:02.633 32310-32310/? W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry is not main process, just return
        08-21 13:43:06.459 3437-3437/? D/Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc1mnc [zh_CN_#Hans] ldltr sw360dp w598dp h336dp 480dpi nrml land finger -keyb/v/h -nav/h suim:1 s.41}
        08-21 13:43:06.470 31865-31865/? D/Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc1mnc [zh_CN_#Hans] ldltr sw360dp w598dp h336dp 480dpi nrml land finger -keyb/v/h -nav/h suim:1 s.41}
        08-21 13:43:06.532 32310-32310/? D/Tinker.DefaultAppLike: onConfigurationChanged:{1.0 460mcc1mnc [zh_CN_#Hans] ldltr sw360dp w598dp h336dp 480dpi nrml land finger -keyb/v/h -nav/h suim:1 s.41}

提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没给出任何代码截图报错的，将绝对不会有任何反馈。这种issue也是一律直接关闭的,大家可以参阅[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。

Tinker是一个开源项目，希望大家遇到问题时要学会先思考，看看sample与Tinker的源码，更鼓励大家给我们提pr.

**Comment by tomystang** [comment]
检查一下BaseActivity是不是在tinkerPatch { dex { loader [] } }配置中？
另外如果使用的是自己创建的Application，要注意在Tinker加载之前不要预先引用BaseActivity

如果这些情况都不符合的话，应该就是Application和ApplicationLike之间发生内联了，下个版本会修复。
