### ISSUE TITLE
补丁包合成成功，但加载失败

### ISSUE THREAD

**Issue by ywqian** [Tencent/tinker#912]
```
异常类型：补丁包合成成功，但加载失败

手机型号：oppo r9s

手机系统版本：Android6.0.1

tinker版本：1.9.8

gradle版本：3.0.1

是否使用热更新SDK： 否，使用tinker原生

系统：Mac

堆栈/日志：
08-24 15:07:17.264 14986-14986/? D/CustomTinkerPatch: 补丁包检查回调 onPatchReceived：/storage/emulated/0/wy_patch.zip
08-24 15:07:17.265 14986-14986/? D/CustomTinkerPatch: 补丁包检查 patchCheck：/storage/emulated/0/wy_patch.zip
08-24 15:07:17.280 14986-14986/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
08-24 15:07:17.280 14986-14986/? I/Tinker.TinkerPatchService: run patch service by intent service.

    --------- beginning of system
08-24 15:07:17.297 1559-1944/? I/ActivityManager: Start proc 19915:com.android.ywq.demo:patch/u0a971 for service com.android.ywq.demo/com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner
08-24 15:07:17.377 19915-19915/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
08-24 15:07:17.378 19915-19915/? D/Tinker.DefaultAppLike: onBaseContextAttached:
08-24 15:07:17.396 19915-19915/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.android.ywq.demo/tinker
08-24 15:07:17.397 19915-19915/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.8
08-24 15:07:17.397 19915-19915/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-1, process name:com.android.ywq.demo:patch, main process:false, systemOTA:false, fingerPrint:OPPO/R9s/R9s:6.0.1/MMB29M/1528528402:user/release-keys, oatDir:null, useInterpretMode:false
08-24 15:07:17.397 19915-19915/? W/Tinker.TinkerLoadResult: tinker is disable, just return
08-24 15:07:17.397 19915-19915/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.android.ywq.demo/tinker, code: -1, cost: 3ms
08-24 15:07:17.399 19915-19915/? D/CustomTinkerPatch: patchDirectory: /data/user/0/com.android.ywq.demo/tinker, loadCode: -1, cost: 3
08-24 15:07:17.399 19915-19915/? W/Tinker.Tinker: tinker load fail!
08-24 15:07:17.399 19915-19915/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
08-24 15:07:17.399 19915-19915/? D/Tinker.DefaultAppLike: onCreate
08-24 15:07:18.510 19915-19915/? D/Tinker.DefaultAppLike: onTrimMemory level:15
08-24 15:07:18.566 19915-19959/? I/Tinker.TinkerPatchService: try to increase patch process priority
08-24 15:07:18.573 19915-19959/? I/Tinker.DefaultPatchReporter: patchReporter onPatchServiceStart: patch service start
08-24 15:07:18.581 19915-19959/? W/Tinker.UpgradePatchRetry: try copy file: /storage/emulated/0/wy_patch.zip to /data/user/0/com.android.ywq.demo/tinker_temp/temp.apk
08-24 15:07:18.595 19915-19959/? D/CustomTinkerPatch: 开启patch进程开始合补丁包 onPatchServiceStart-----------------
08-24 15:07:18.609 19915-19959/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchMd5:cb9a5b681437088defaaceb0fd4810d2
08-24 15:07:18.612 19915-19959/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.android.ywq.demo/tinker/patch.info: open failed: ENOENT (No such file or directory)
08-24 15:07:18.613 19915-19959/? W/Tinker.PatchInfo: read property failed, e:java.io.FileNotFoundException: /data/user/0/com.android.ywq.demo/tinker/patch.info: open failed: ENOENT (No such file or directory)
08-24 15:07:18.614 19915-19959/? I/Tinker.UpgradePatch: UpgradePatch tryPatch:patchVersionDirectory:/data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68
08-24 15:07:18.617 19915-19959/? W/Tinker.UpgradePatch: UpgradePatch copy patch file, src file: /storage/emulated/0/wy_patch.zip size: 13260, dest file: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/patch-cb9a5b68.apk size:13260
08-24 15:07:23.210 19915-19959/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/classes.dex.jar, size: 3004935, use time: 4545
08-24 15:07:25.777 19915-19959/? W/Tinker.DexDiffPatchInternal: success recover dex file: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/classes2.dex.jar, size: 1623078, use time: 2566
08-24 15:07:25.778 19915-19959/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/classes3.dex.jar
08-24 15:07:27.246 19915-19959/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
08-24 15:07:27.332 19915-19959/? I/Tinker.DexDiffPatchInternal: try Extracting /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/test.dex.jar
08-24 15:07:27.334 19915-19959/? I/Tinker.DexDiffPatchInternal: isExtractionSuccessful: true
08-24 15:07:27.620 19915-19959/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/test.dex.jar
    safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/classes3.dex.jar
08-24 15:07:27.623 19915-19959/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/classes2.dex.jar
08-24 15:07:27.624 19915-19959/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/classes.dex.jar
08-24 15:07:27.627 19915-19959/? I/Tinker.DexDiffPatchInternal: merge classN dex file /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/tinker_classN.apk, result: true, size: 7271545, use: 293ms
08-24 15:07:27.628 19915-19959/? I/Tinker.DexDiffPatchInternal: legal files to do dexopt: [/data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/tinker_classN.apk]
08-24 15:07:27.629 19915-19959/? I/Tinker.DexDiffPatchInternal: patch recover, try to optimize dex file count:1, optimizeDexDirectory:/data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/odex/
08-24 15:07:27.630 19915-19959/? I/Tinker.DexDiffPatchInternal: start to parallel optimize dex /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/tinker_classN.apk, size: 7271545
08-24 15:07:27.631 19915-19959/? W/art: oat_file_name = /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/odex/tinker_classN.dex, b = 0
08-24 15:07:27.709 19980-19980/? I/dex2oat: /system/bin/dex2oat --dex-file=/data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/tinker_classN.apk --oat-file=/data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/odex/tinker_classN.dex
08-24 15:07:34.997 15008-15008/? D/Tinker.DefaultAppLike: onLowMemory
08-24 15:07:37.114 19915-19959/? I/Tinker.DexDiffPatchInternal: success to parallel optimize dex /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/tinker_classN.apk, opt file:/data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/odex/tinker_classN.dex, opt file size: 48681392, use time 9484
    recover dex result:true, cost:18497
08-24 15:07:37.114 19915-19959/? W/Tinker.BsDiffPatchInternal: patch recover, library is not contained
08-24 15:07:37.114 19915-19959/? W/Tinker.ResDiffPatchInternal: patch recover, resource is not contained
08-24 15:07:37.114 19915-19959/? I/Tinker.DexDiffPatchInternal: raw dex count: 4, dex opt dex count: 1, final wait times: 120
08-24 15:07:37.124 19915-19959/? I/Tinker.DexDiffPatchInternal: check dex optimizer file exist: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/odex/tinker_classN.dex, size 48681392
08-24 15:07:37.125 19915-19959/? I/Tinker.DexDiffPatchInternal: check dex optimizer file format: tinker_classN.dex, size 48681392
08-24 15:07:37.127 19915-19959/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.android.ywq.demo/tinker/patch.info , oldVer:, newVer:cb9a5b681437088defaaceb0fd4810d2, fingerprint:OPPO/R9s/R9s:6.0.1/MMB29M/1528528402:user/release-keys, oatDir:odex
08-24 15:07:37.129 19915-19959/? W/Tinker.UpgradePatch: UpgradePatch tryPatch: done, it is ok
08-24 15:07:37.129 19915-19959/? I/Tinker.DefaultPatchReporter: patchReporter onPatchResult: patch all result path: /storage/emulated/0/wy_patch.zip, success: true, cost: 18534
08-24 15:07:37.129 19915-19959/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker_temp/temp.apk
08-24 15:07:37.130 19915-19959/? D/CustomTinkerPatch: 合成补丁结果 onPatchResult：success=true, cost=18534
08-24 15:07:37.138 14986-20002/? I/CustomTinkerPatch.ResultService: WYResultService receive result:
    PatchResult:
    isSuccess:true
    rawPatchFilePath:/storage/emulated/0/wy_patch.zip
    costTime:18534
    patchVersion:cb9a5b681437088defaaceb0fd4810d2
08-24 15:07:37.142 19915-19915/? D/Tinker.DefaultAppLike: onTrimMemory level:80
08-24 15:07:37.143 14986-20002/? W/Tinker.DefaultTinkerResultService: deleteRawPatchFile rawFile path: /storage/emulated/0/wy_patch.zip
08-24 15:07:37.143 14986-20002/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /storage/emulated/0/wy_patch.zip
08-24 15:07:49.762 14986-14986/? D/Tinker.DefaultAppLike: onLowMemory
08-24 15:08:06.153 20031-20031/? W/Tinker.TinkerLoader: tryLoadPatchFiles:isEnabledForResource:true
08-24 15:08:06.153 20031-20031/? D/Tinker.TinkerInternals: same fingerprint:OPPO/R9s/R9s:6.0.1/MMB29M/1528528402:user/release-keys
08-24 15:08:06.154 20031-20031/? I/Tinker.PatchInfo: rewritePatchInfoFile file path:/data/user/0/com.android.ywq.demo/tinker/patch.info , oldVer:cb9a5b681437088defaaceb0fd4810d2, newVer:cb9a5b681437088defaaceb0fd4810d2, fingerprint:OPPO/R9s/R9s:6.0.1/MMB29M/1528528402:user/release-keys, oatDir:odex
08-24 15:08:06.155 20031-20031/? I/Tinker.TinkerLoader: tryLoadPatchFiles:success to rewrite patch info, kill other process.
08-24 15:08:06.158 20031-20031/? W/Tinker.TinkerLoader: tinker safe mode preferName:tinker_own_config_com.android.ywq.demo count:1
08-24 15:08:06.162 20031-20031/? I/Tinker.TinkerDexLoader: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.android.ywq.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.ywq.demo-1/lib/arm, /data/app/com.android.ywq.demo-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]]
08-24 15:08:06.163 20031-20031/? I/Tinker.TinkerDexLoader: verify dex file:/data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/tinker_classN.apk md5, use time: 1
08-24 15:08:06.163 20031-20031/? I/Tinker.ClassLoaderAdder: installDexes dexOptDir: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/odex, dex size:1
08-24 15:08:06.171 20031-20031/? I/Tinker.ClassLoaderAdder: after loaded classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/tinker_classN.apk", zip file "/data/app/com.android.ywq.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.ywq.demo-1/lib/arm, /data/app/com.android.ywq.demo-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]], dex size:1
08-24 15:08:06.172 20031-20031/? W/Tinker.ClassLoaderAdder: checkDexInstall result:false
08-24 15:08:06.173 20031-20031/? E/Tinker.TinkerDexLoader: install dexes failed
08-24 15:08:06.174 20031-20031/? W/Tinker.TinkerLoader: tryLoadPatchFiles:onPatchLoadDexesFail
08-24 15:08:06.175 20031-20031/? D/Tinker.DefaultAppLike: onBaseContextAttached:
08-24 15:08:06.183 20031-20031/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.android.ywq.demo/tinker
08-24 15:08:06.183 20031-20031/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.8
08-24 15:08:06.184 20031-20031/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-14, process name:com.android.ywq.demo, main process:true, systemOTA:false, fingerPrint:OPPO/R9s/R9s:6.0.1/MMB29M/1528528402:user/release-keys, oatDir:odex, useInterpretMode:false
    parseTinkerResult oldVersion:, newVersion:cb9a5b681437088defaaceb0fd4810d2, current:cb9a5b681437088defaaceb0fd4810d2
08-24 15:08:06.184 20031-20031/? I/Tinker.TinkerLoadResult: Tinker load have exception loadCode:-14
08-24 15:08:06.185 20031-20031/? E/Tinker.DefaultLoadReporter: patch loadReporter onLoadException: tinker dex check fail:Tinker Exception:checkDexInstall failed
08-24 15:08:06.190 20031-20031/? I/Tinker.DefaultLoadReporter: dex exception disable tinker forever with sp
08-24 15:08:06.190 20031-20031/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
08-24 15:08:06.191 20031-20031/? E/Tinker.DefaultLoadReporter: tinker load exception  com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
        at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SourceFile:84)
        at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(SourceFile:194)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(SourceFile:263)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(SourceFile:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(SourceFile:157)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:132)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:148)
        at android.app.Application.attach(Application.java:196)
        at android.app.Instrumentation.newApplication(Instrumentation.java:998)
        at android.app.Instrumentation.newApplication(Instrumentation.java:982)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:614)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4968)
        at android.app.ActivityThread.access$1800(ActivityThread.java:170)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
08-24 15:08:06.191 20031-20031/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/info.lock
08-24 15:08:06.192 20031-20031/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/patch-cb9a5b68.apk
    safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex/tinker_classN.apk
08-24 15:08:06.197 20031-20031/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/dex
    safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/odex/tinker_classN.dex
    safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68/odex
08-24 15:08:06.198 20031-20031/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch-cb9a5b68
    safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker/patch.info
08-24 15:08:06.198 20031-20031/? I/Tinker.PatchFileUtil: safeDeleteFile, try to delete path: /data/user/0/com.android.ywq.demo/tinker
08-24 15:08:06.200 20031-20031/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.android.ywq.demo/tinker, code: -14, cost: 46ms
08-24 15:08:06.201 20031-20031/? W/Tinker.Tinker: tinker load fail!
08-24 15:08:06.219 20031-20031/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
08-24 15:08:06.219 20031-20031/? D/Tinker.DefaultAppLike: onCreate
08-24 15:08:06.329 20051-20051/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.android.ywq.demo/tinker
08-24 15:08:06.330 20051-20051/? D/Tinker.DefaultAppLike: onBaseContextAttached:
08-24 15:08:06.338 20051-20051/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.android.ywq.demo/tinker
08-24 15:08:06.338 20051-20051/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.8
08-24 15:08:06.338 20051-20051/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.android.ywq.demo:push, main process:false, systemOTA:false, fingerPrint:OPPO/R9s/R9s:6.0.1/MMB29M/1528528402:user/release-keys, oatDir:null, useInterpretMode:false
08-24 15:08:06.339 20051-20051/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
08-24 15:08:06.339 20051-20051/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.android.ywq.demo/tinker, code: -2, cost: 2ms
08-24 15:08:06.340 20051-20051/? D/CustomTinkerPatch: patchDirectory: /data/user/0/com.android.ywq.demo/tinker, loadCode: -2, cost: 2
08-24 15:08:06.340 20051-20051/? W/Tinker.Tinker: tinker load fail!
08-24 15:08:06.340 20051-20051/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
08-24 15:08:06.340 20051-20051/? D/Tinker.DefaultAppLike: onCreate
08-24 15:08:06.451 20051-20051/? D/Tinker.DefaultAppLike: onTrimMemory level:15
08-24 15:08:06.986 20031-20031/? D/Tinker.DefaultAppLike: onTrimMemory level:15
08-24 15:08:07.342 20135-20135/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.android.ywq.demo/tinker
08-24 15:08:07.344 20135-20135/? D/Tinker.DefaultAppLike: onBaseContextAttached:
08-24 15:08:07.357 20135-20135/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.android.ywq.demo/tinker
08-24 15:08:07.357 20135-20135/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.8
08-24 15:08:07.358 20135-20135/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.android.ywq.demo:remote, main process:false, systemOTA:false, fingerPrint:OPPO/R9s/R9s:6.0.1/MMB29M/1528528402:user/release-keys, oatDir:null, useInterpretMode:false
08-24 15:08:07.358 20135-20135/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
08-24 15:08:07.358 20135-20135/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.android.ywq.demo/tinker, code: -2, cost: 4ms
08-24 15:08:07.359 20135-20135/? D/CustomTinkerPatch: patchDirectory: /data/user/0/com.android.ywq.demo/tinker, loadCode: -2, cost: 4
08-24 15:08:07.359 20135-20135/? W/Tinker.Tinker: tinker load fail!
08-24 15:08:07.360 20135-20135/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
08-24 15:08:07.360 20135-20135/? D/Tinker.DefaultAppLike: onCreate
08-24 15:08:07.537 20135-20135/? D/Tinker.DefaultAppLike: onTrimMemory level:15
08-24 15:08:07.605 20135-20135/? D/Tinker.DefaultAppLike: onTrimMemory level:80
08-24 15:08:11.415 20192-20192/? W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/com.android.ywq.demo/tinker
08-24 15:08:11.417 20192-20192/? D/Tinker.DefaultAppLike: onBaseContextAttached:
08-24 15:08:11.425 20192-20192/? W/Tinker.Tinker: tinker patch directory: /data/user/0/com.android.ywq.demo/tinker
08-24 15:08:11.426 20192-20192/? I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.8
08-24 15:08:11.426 20192-20192/? I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name:com.android.ywq.demo:pushservice, main process:false, systemOTA:false, fingerPrint:OPPO/R9s/R9s:6.0.1/MMB29M/1528528402:user/release-keys, oatDir:null, useInterpretMode:false
08-24 15:08:11.426 20192-20192/? W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
08-24 15:08:11.426 20192-20192/? I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/com.android.ywq.demo/tinker, code: -2, cost: 3ms
08-24 15:08:11.428 20192-20192/? D/CustomTinkerPatch: patchDirectory: /data/user/0/com.android.ywq.demo/tinker, loadCode: -2, cost: 3
08-24 15:08:11.428 20192-20192/? W/Tinker.Tinker: tinker load fail!
08-24 15:08:11.428 20192-20192/? I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
08-24 15:08:11.428 20192-20192/? D/Tinker.DefaultAppLike: onCreate
08-24 15:08:11.556 20192-20192/? D/Tinker.DefaultAppLike: onTrimMemory level:15

```

**Comment by PhantomQi** [comment]
@ywqian 请问你是怎么解决此问题的？我遇到了类似问题，求教解决办法。

**Comment by ywqian** [comment]
> @ywqian 请问你是怎么解决此问题的？我遇到了类似问题，求教解决办法。

我后面对tinkerPatch下面的dex包查看，发现tinker相关的代码并没有在主dex里面，是因为我们项目原先自己有进行dex分包，和tinker自动生成的主dex产生了冲突，后面我直接使用了tinker的dex分包规则，把项目自己的需要放入主dex的写到了loader = []这里面。
