### ISSUE TITLE
AndroidMainfest解析错误

### ISSUE THREAD

**Issue by yanunon** [Tencent/tinker#92]
AndroidManifest里面如果写了`<uses-feature android:glEsVersion="0x00020000" />`会导致生成patch错误。

> java.lang.NumberFormatException: For input string: "0x20000"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.valueOf(Unknown Source)
        at net.dongliu.apk.parser.struct.xml.Attributes.getInt(Attributes.java:40)
        at net.dongliu.apk.parser.parser.ApkMetaTranslator.onStartTag(ApkMetaTranslator.java:56)
        at net.dongliu.apk.parser.parser.CompositeXmlStreamer.onStartTag(CompositeXmlStreamer.java:19)
        at net.dongliu.apk.parser.parser.BinaryXmlParser.readXmlNodeStartTag(BinaryXmlParser.java:189)
        at net.dongliu.apk.parser.parser.BinaryXmlParser.parse(BinaryXmlParser.java:101)
        at net.dongliu.apk.parser.AbstractApkParser.transBinaryXml(AbstractApkParser.java:164)
        at net.dongliu.apk.parser.AbstractApkParser.parseManifestXml(AbstractApkParser.java:123)
        at net.dongliu.apk.parser.AbstractApkParser.parseApkMeta(AbstractApkParser.java:105)
        at net.dongliu.apk.parser.AbstractApkParser.getApkMeta(AbstractApkParser.java:56)
        at com.tencent.tinker.build.apkparser.AndroidManifest.getAndroidManifest(AndroidManifest.java:66)
        at com.tencent.tinker.build.decoder.ManifestDecoder.patch(ManifestDecoder.java:45)
        at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:109)
        at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
        at com.tencent.tinker.patch.CliMain.run(CliMain.java:103)
        at com.tencent.tinker.patch.CliMain.main(CliMain.java:54)

**Comment by shwenzhang** [comment]
#54
