### ISSUE TITLE
 # main(2)  java.lang.VerifyError

### ISSUE THREAD

**Issue by gj1990216** [Tencent/tinker#926]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：VIVO Y85A

手机系统版本：Android 8.1

tinker版本：如:1.7.7

gradle版本：如:3.3

是否使用热更新SDK： BuglySDK


系统：如

堆栈/日志：
9-14 08:27:01.092  9356  9356 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class com.zpf.workzcb.moudle.splash.SplashActivity: void com.zpf.workzcb.moudle.splash.SplashActivity.onLocationChanged(com.amap.api.location.AMapLocation) failed to verify: void com.zpf.workzcb.moudle.splash.SplashActivity.onLocationChanged(com.amap.api.location.AMapLocation): [0x53] register v0 has type Precise Reference: com.amap.api.maps.model.LatLng but expected Precise Reference: com.amap.api.maps.model.LatLng (declaration of 'com.zpf.workzcb.moudle.splash.SplashActivity' appears in /data/user/0/com.zpf.workzcb/tinker/patch-a57b0c08/dex/tinker_classN.apk!classes2.dex)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1180)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2839)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3035)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1736)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:192)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6809)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
09-14 08:27:01.092  9356  9356 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)

patch已经生效,已经合入到应用中,但是只在这款机型就不成功
提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没给出任何代码截图报错的，将绝对不会有任何反馈。这种issue也是一律直接关闭的,大家可以参阅[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)。

Tinker是一个开源项目，希望大家遇到问题时要学会先思考，看看sample与Tinker的源码，更鼓励大家给我们提pr.

**Comment by gj1990216** [comment]
其他机型没有遇到java.lang.VerifyError: Verifier rejected class

**Comment by tomystang** [comment]
看起来和proguard、ART方法内联导致的问题都有点像，试试直接在这台机器上安装完整的新包，如果没问题的话再尝试一下1.9.9版本的tinker吧。
