### ISSUE TITLE
Tinker Exception:createDelegate failed

### ISSUE THREAD

**Issue by Zerbaoo** [Tencent/tinker#944]
异常类型：app运行时异常

手机型号：oneplus 3t

手机系统版本：OxygenOS 5.0.5 

Android版本：8.0.0

tinker版本：com.tencent.bugly:tinker-support:lastest.release（最新）

gradle版本：3.0.1

是否使用热更新SDK：使用Bugly SDK

系统：Win10

问题描述：enableProxyApplication = true 开启反射Application模式
                  编译正常，启动直接报错 Tinker Exception:createDelegate failed
堆栈/日志：
java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:1011)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5997)
                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6798)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                  Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
                                                     at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:115)
                                                     at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:121)
                                                     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135)
                                                     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:152)
                                                     at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57)
                                                     at android.app.Application.attach(Application.java:218)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1106)
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1090)
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:993)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5997) 
                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6798) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                  Caused by: java.lang.ClassNotFoundException: com.tencent.bugly.beta.tinker.TinkerApplicationLike
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.Class.forName(Class.java:453)
                                                     at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109)
                                                     at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:121) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:152) 
                                                     at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
                                                     at android.app.Application.attach(Application.java:218) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1106) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1090) 
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:993) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5997) 
                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6798) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                  Caused by: java.lang.ClassNotFoundException: com.tencent.bugly.beta.tinker.TinkerApplicationLike
                                                     at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                     at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                     at java.lang.Class.classForName(Native Method) 
                                                     at java.lang.Class.forName(Class.java:453) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:121) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:152) 
                                                     at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
                                                     at android.app.Application.attach(Application.java:218) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1106) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1090) 
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:993) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5997) 
                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6798) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tinker/loader/app/DefaultApplicationLike;
                                                     at java.lang.Class.classForName(Native Method) 
                                                     at java.lang.Class.forName(Class.java:453) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:121) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:152) 
                                                     at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
                                                     at android.app.Application.attach(Application.java:218) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1106) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1090) 
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:993) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5997) 
                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6798) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.loader.app.DefaultApplicationLike" on path: DexPathList[[zip file "/data/app/cn.appoa.ospservice.servicer-D0o7QwosaAiyjPV1pFPl4w==/base.apk"],nativeLibraryDirectories=[/data/app/cn.appoa.ospservice.servicer-D0o7QwosaAiyjPV1pFPl4w==/lib/arm, /data/app/cn.appoa.ospservice.servicer-D0o7QwosaAiyjPV1pFPl4w==/base.apk!/lib/armeabi, /system/lib, /system/vendor/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                     at java.lang.Class.classForName(Native Method) 
                                                     at java.lang.Class.forName(Class.java:453) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(TinkerApplication.java:109) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(TinkerApplication.java:121) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:135) 
                                                     at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:152) 
                                                     at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57) 
                                                     at android.app.Application.attach(Application.java:218) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1106) 
                                                     at android.app.Instrumentation.newApplication(Instrumentation.java:1090) 
                                                     at android.app.LoadedApk.makeApplication(LoadedApk.java:993) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5997) 
                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6798) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by Zerbaoo** [comment]
版本换回com.tencent.bugly:tinker-support:1.1.2 可以正常运行了...

**Comment by mrldroid** [comment]
我有个测试机也报这个错

**Comment by why168** [comment]
看文档啊
https://bugly.qq.com/docs/user-guide/instruction-manual-android-hotfix/?v=20180709165613
```
// 指定tinker依赖版本（注：应用升级1.3.5版本起，不再内置tinker）
compile 'com.tencent.tinker:tinker-android-lib:1.9.9'
```

**Comment by vane002** [comment]
请问，这个问题现在有解决么？现在我遇到了一个很奇怪的问题，老版本apk要打补丁 1.9.8 就可以打出补丁，但是打出来的补丁直接崩溃，改为1.9.9补丁就打不出来了。现在不知道要怎么解决了

**Comment by lwxgit** [comment]
proguard-rules.pro文件 添加-keep class com “Didn't find class 那个类” **{*;}
