### ISSUE TITLE
Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by micck2** [Tencent/tinker#955]
## Issue/提问须知
**在提交issue之前，我们应该先查询是否已经有相关的issue以及[常见问题](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)。提交issue时，我们需要写明issue的原因，以及编译或运行过程的日志(加载进程以及Patch进程)。issue需要以下面的格式：**

```
异常类型：app运行时异常

手机型号：小米6X

手机系统版本：android8.1.0

tinker版本：1.9.8

gradle版本：4.1

是否使用热更新SDK： 

系统：Mac

堆栈/日志：
10-17 16:42:59.102 30801-30801/com.sqzx.dj.gofun_check_control E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sqzx.dj.gofun_check_control, PID: 30801
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tinker/entry/ApplicationLike;
        at com.tencent.bugly.beta.tinker.TinkerManager.installTinker(BUGLY:176)
        at com.tencent.bugly.beta.Beta.installTinker(BUGLY:981)
        at com.sqzx.dj.gofun_check_control.tinker.CarTaskManagerAppLike.onBaseContextAttached(CarTaskManagerAppLike.java:61)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:134)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
        at android.app.Application.attach(Application.java:193)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1104)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1088)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:987)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5768)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6600)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.ApplicationLike" on path: DexPathList[[zip file "/data/app/com.sqzx.dj.gofun_check_control-N2G751SE-sXX7g8_1xCUPg==/base.apk"],nativeLibraryDirectories=[/data/app/com.sqzx.dj.gofun_check_control-N2G751SE-sXX7g8_1xCUPg==/lib/arm64, /data/app/com.sqzx.dj.gofun_check_control-N2G751SE-sXX7g8_1xCUPg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.bugly.beta.tinker.TinkerManager.installTinker(BUGLY:176) 
        at com.tencent.bugly.beta.Beta.installTinker(BUGLY:981) 
        at com.sqzx.dj.gofun_check_control.tinker.CarTaskManagerAppLike.onBaseContextAttached(CarTaskManagerAppLike.java:61) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:134) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at android.app.Application.attach(Application.java:193) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1104) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1088) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:987) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5768) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6600) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821) 
10-17 16:42:59.106 2269-2390/? E/BtGatt.ContextMap: Context not found for ID 0
10-17 16:42:59.107 30801-30801/com.sqzx.dj.gofun_check_control E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/tinker/entry/ApplicationLike;
        at com.tencent.bugly.beta.tinker.TinkerManager.installTinker(BUGLY:176)
        at com.tencent.bugly.beta.Beta.installTinker(BUGLY:981)
        at com.sqzx.dj.gofun_check_control.tinker.CarTaskManagerAppLike.onBaseContextAttached(CarTaskManagerAppLike.java:61)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:134)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
        at android.app.Application.attach(Application.java:193)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1104)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1088)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:987)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5768)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6600)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.tinker.entry.ApplicationLike" on path: DexPathList[[zip file "/data/app/com.sqzx.dj.gofun_check_control-N2G751SE-sXX7g8_1xCUPg==/base.apk"],nativeLibraryDirectories=[/data/app/com.sqzx.dj.gofun_check_control-N2G751SE-sXX7g8_1xCUPg==/lib/arm64, /data/app/com.sqzx.dj.gofun_check_control-N2G751SE-sXX7g8_1xCUPg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.bugly.beta.tinker.TinkerManager.installTinker(BUGLY:176) 
        at com.tencent.bugly.beta.Beta.installTinker(BUGLY:981) 
        at com.sqzx.dj.gofun_check_control.tinker.CarTaskManagerAppLike.onBaseContextAttached(CarTaskManagerAppLike.java:61) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:134) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148) 
        at android.app.Application.attach(Application.java:193) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1104) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1088) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:987) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5768) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6600) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)

**Comment by AlwaysSum** [comment]
同样的问题。。。急。。。求大神

**Comment by dede1314** [comment]
这个不是tinker的问题，是程序本身出问题了。

**Comment by cyixlq** [comment]
之前好好的，现在突然遇到了这个问题，在线等，急！！！

**Comment by cyixlq** [comment]
我通过Bugly集成的

**Comment by AlwaysSum** [comment]
解决了这个问题，我Bugly集成的，修改了版本号 implementation 'com.tencent.tinker:tinker-android-lib:latest.release'//1.9.9  ，官方文档是1.9.3，其实版本更新了，所以lib中文件换了个包，故而找不到了

**Comment by xiongjinqiu0812** [comment]
项目是否升级了androidx？我这里升级后就出现了这个问题，也还在找原因

**Comment by yizuochengchi** [comment]
@xiongjinqiu0812 这位仁兄是否处理了这个问题 我也升到AndroidX了

**Comment by zhaoweiguo5505** [comment]
我的也是升级了androidX  也是这个问题
