### ISSUE TITLE
ava.lang.NoSuchMethodException: tryLoad 

### ISSUE THREAD

**Issue by JM0425** [Tencent/tinker#958]
10-23 11:40:28.647 30609-30609/? E/Tinker.DefaultLoadReporter: tinker load exception, welcome to submit issue to us: https://github.com/Tencent/tinker/issues
10-23 11:40:28.649 30609-30609/? E/Tinker.DefaultLoadReporter: tinker load exception  java.lang.NoSuchMethodException: tryLoad [class com.tencent.tinker.loader.app.TinkerApplication]
        at java.lang.Class.getMethod(Class.java:664)
        at java.lang.Class.getMethod(Class.java:643)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(BUGLY:159)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(BUGLY:130)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(BUGLY:146)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:996)
        at android.app.Instrumentation.newApplication(Instrumentation.java:980)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4561)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5289)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by yangyuguang** [comment]
我也遇到了这个问题 。 只要打开代码混淆就报这个错。 兄弟你解决了么？
