### ISSUE TITLE
Android9.0合成失败

### ISSUE THREAD

**Issue by LittleRoyal** [Tencent/tinker#967]
异常类型：app运行时异常

手机型号：华为P20

手机系统版本：Android9.0

tinker版本：如:1.9.9

gradle版本：如:3.0.1

是否使用热更新SDK： Bugly SDK

系统：如:Windows 

堆栈/日志：
tinker load exception  java.lang.NoSuchFieldException: Field mStringBlocks not found in class android.content.res.AssetManager
        at com.tencent.tinker.loader.shareutil.ShareReflectUtil.findField(ShareReflectUtil.java:55)
        at com.tencent.tinker.loader.TinkerResourcePatcher.isResourceCanPatch(TinkerResourcePatcher.java:101)
        at com.tencent.tinker.loader.TinkerResourceLoader.checkComplete(TinkerResourceLoader.java:122)
        at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:216)
        at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:163)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:132)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:148)
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57)
        at android.app.Application.attach(Application.java:224)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1156)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6529)
        at android.app.ActivityThread.access$1900(ActivityThread.java:267)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by spysoos** [comment]
tinker支持 9.0了？

**Comment by 401885064** [comment]
华为9.0机子合成补丁以后  容易引发崩溃  我这边测试发现偶发性第一次启动崩溃  第二次启动正常   去掉补丁一切正常

**Comment by kilo-swodh** [comment]
9.0就乖乖市场更新吧,别想太多
