### ISSUE TITLE
app检查补丁更新接口在android O系统报错

### ISSUE THREAD

**Issue by monkeycsm** [Tencent/tinker#978]
手机 小米6 系统8.0
在调用TinkerPatch.with().fetchPatchUpdate(true)检查补丁更新接口之后，日志如下，烦请告知最后的crash原因：
Tinker.UrlConnectionFetcher: loadData from url: http://stat.tinkerpatch.com/succ.php, method:POST, body:sv=1.2.9&t=1&av=10.1.0&ch=Null&pv=5&k=2a5f43bd6be859bd
2018-11-27 00:25:33.005 13847-14081/? I/Tinker.VersionInfo: updateVersionInfo file path:/data/user/0/com.yiche.autoeasy/tinker_server/2a5f43bd6be859bd_version.info, appVersion: 10.1.0, uuid:2db283cf-8695-4426-8c7a-7cdbbaf7d8fc, abi:armeabi, patchVersion:5, patchMd5:24892712b337f667771aaef360fa08f5, grayValue:9, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
2018-11-27 00:25:33.005 13847-14081/? I/Tinker.VersionInfo: updateVersionInfo file path:/data/user/0/com.yiche.autoeasy/tinker_server/2a5f43bd6be859bd_version.info, appVersion: 10.1.0, uuid:2db283cf-8695-4426-8c7a-7cdbbaf7d8fc, abi:armeabi, patchVersion:5, patchMd5:24892712b337f667771aaef360fa08f5, grayValue:9, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
2018-11-27 00:25:33.006 13847-14081/? I/Tinker.TinkerServerPatchListener: receive a patch file: /data/user/0/com.yiche.autoeasy/tinker_server/10.1.0_5.apk, file size:67351
2018-11-27 00:25:33.007 13847-14081/? W/Tinker.UpgradePatchRetry: onPatchListenerCheck retry file is not exist, just return
2018-11-27 00:25:33.007 13847-14081/? I/Tinker.TinkerPatchService: run patch service by job scheduler.
2018-11-27 00:25:33.237 13847-14081/? I/Tinker.UrlConnectionFetcher: response code 200 msg: OK
2018-11-27 00:25:33.243 13847-14081/? D/Tinker.ClientImpl: [succ] report successfully with url: http://stat.tinkerpatch.com/succ.php, body: sv=1.2.9&t=1&av=10.1.0&ch=Null&pv=5&k=2a5f43bd6be859bd reportingCount: 0, fail pool size: 0
2018-11-27 00:25:38.008 13847-13847/? I/Tinker.TinkerPatchService: check if patch service is running.
2018-11-27 00:25:38.009 13847-13847/? W/Tinker.TinkerPatchService: patch service is not running, retry with IntentService.
2018-11-27 00:25:38.010 13847-13847/? I/Tinker.TinkerPatchService: run patch service by intent service.
2018-11-27 00:25:38.032 13847-13847/? I/Tinker.TinkerPatchService: successfully start patch service with IntentService.
2018-11-27 00:25:38.089 14138-14138/? W/Tinker.TinkerLoader: tryLoadPatchFiles: we don't load patch with :patch process itself, just return
Tinker.TinkerPatchService: for system version >= Android O, we just ignore increasingPriority job to avoid crash or toasts.
com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:you must install tinker before get tinker sInstance
        at com.tencent.tinker.lib.tinker.Tinker.with(Proguard:103)
        at com.tencent.tinker.lib.service.TinkerPatchService.doApplyPatch(Proguard:176)
        at com.tencent.tinker.lib.service.TinkerPatchService.access$100(Proguard:55)
        at com.tencent.tinker.lib.service.TinkerPatchService$IntentServiceRunner.onHandleIntent(Proguard:230)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by pyc527712512** [comment]
楼主解决了吗，我的小米手机也出现了这个问题

**Comment by monkeycsm** [comment]
> 楼主解决了吗，我的小米手机也出现了这个问题

这个是Tinkerpatch的配置有问题，我设置了setFetchPatchIntervalByHours为-1禁止轮训更新导致的这个错误，改为别的就没这个问题了
