### ISSUE TITLE
编译不过 Could not get unknown property 'dependsOn

### ISSUE THREAD

**Issue by lyqaiym** [Tencent/tinker#994]
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'dependsOn' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:86)
	at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:132)
	at com.tencent.tinker.build.gradle.TinkerPatchPlugin$_apply_closure1$_closure2.doCall(TinkerPatchPlugin.groovy:187)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:154)
	at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
	at com.tencent.tinker.build.gradle.TinkerPatchPlugin$_apply_closure1.doCall(TinkerPatchPlugin.groovy:121)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy33.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:75)
	... 82 more

**Comment by wstczlt** [comment]
tinker版本？

**Comment by lyqaiym** [comment]
最新的1.9.9

**Comment by lyqaiym** [comment]
我把这段try catch了，也能成功。看日志是改的 Fix issue-866 一个bug

**Comment by lyqaiym** [comment]
tinker用的 gradle-2.14.1-all classpath 'com.android.tools.build:gradle:2.2.0'
sample 用的 gradle-4.1-all   classpath 'com.android.tools.build:gradle:3.0.1'

**Comment by lyqaiym** [comment]
applyResourceTask dependsOn这么便宜不过。改成applyResourceTask.dependsOn编译过。不知道有啥用。因为def mergeResourcesTask 这个变量提示没用

**Comment by wstczlt** [comment]
你是dev分支么，我本地demo项目没问题，我看一下tinker的sample

**Comment by wstczlt** [comment]
已确认，是我代码提交问题，提交的时候把‘’.‘’错误改成了空格，实在抱歉，我本地测试的代码是applyResourceTask.dependsOn，拷贝到tinker分支的时候写错了
